### ISSUE TITLE
Message with windows-1252 isn't parsed properly

### ISSUE THREAD

**Issue by foxinushka** [MailCore/mailcore2#1015]
Message: https://www.dropbox.com/s/z84kwhfv374h145/encoding1252.zip?dl=0

The message has encoding windows-1252. Mailcore detects Shift_JIS and doesn't decode content properly.

**Comment by dinhviethoa** [comment]
Work in progress: 97bce894f34a05378f661195c358fb18f90e3fdb

**Comment by dinhviethoa** [comment]
Fixed.

**Comment by foxinushka** [comment]
It works. Thanks.
