### ISSUE TITLE
Dsymutil warning

### ISSUE THREAD

**Issue by siberianisaev** [MailCore/mailcore2#1020]
Hi,

i've noticed a warning appears when I build my project:

```
warning: (x86_64) ...../Pods/mailcore2-ios/lib/libMailCore-ios.a(config.o) object file doesn't contain DWARF debug information
```

At the same time an option "Build Options" > "Debug Information Format" in Pod-(Project Name)-mailcore2-ios target is set to "DWARF with dSYM File".

What can be the reason?

**Comment by deltadavid** [comment]
@siberianisaev Do you have any insight after 11 days?

**Comment by siberianisaev** [comment]
@deltadavid if you don't use dSYM File, change your project settings in this way:

```
"Build Options" > "Debug Information Format" > "DWARF"
```

I still think that it's mailcore2 pod problem
