### ISSUE TITLE
DYLIB_INSTALL_NAME_BASE should be set to @rpath

### ISSUE THREAD

**Issue by jakefleksy** [MailCore/mailcore2#1023]
Example: https://github.com/fleksy/mailcore2/commit/c8d64071d61c27cea60996819b007802a758fb4e

Although most frameworks will be placed at @executable_path/../Frameworks this can't be guaranteed. It's especially wrong out of the box for iOS, since MailCore's base install name would need to be @executable_path/Frameworks, not @executable_path/../Frameworks, due to using shallow bundles.

Easiest solution: just use @rpath, which has significant overall advantages anyways.

**Comment by dinhviethoa** [comment]
Thanks for the details. About breaking platforms, I was talking about OS X vs iOS.
Could you send a pull request to fix that?
Thanks.

**Comment by jakefleksy** [comment]
Ok, check out #1027
