### ISSUE TITLE
APP STORE rejecting this library

### ISSUE THREAD

**Issue by jonasman** [MailCore/mailcore2#1037]
the other linker flags say:

Set 'Other Linker Flags': -luchardet-ios -lctemplate-ios -letpan-ios -lxml2 -lsasl2 -liconv -ltidy -lz -lc++ -stdlib=libc++ -ObjC

But I think tidy is forbidden!

When i link for release in my app i had to remove a couple of libraries to be able to link. Even removing -ltidy the submission was rejected.

Any help here?

Im using the static lib "mailcore2-ios-7.zip".

**Comment by jonasman** [comment]
![screen shot 2015-01-14 at 20 52 00](https://cloud.githubusercontent.com/assets/1762910/5745148/4538e3ec-9c2f-11e4-9c21-0ba68060a498.png)

**Comment by dinhviethoa** [comment]
Could you change -ltidy to the full path of libtidy.a?

**Comment by jonasman** [comment]
do you know the full path of libtidy.a?

**Comment by jonasman** [comment]
ok i solved it. Removing -ltidy and repackaging it. works!
