### ISSUE TITLE
Outlook slow connection and "A stable connection to the server could not be established."

### ISSUE THREAD

**Issue by jonathanff** [MailCore/mailcore2#1039]
Hi,

So im trying to fetch all mails headers from outlook, I successfully login to the account and calls like [session fetchAllFoldersOperation] and work without problems even fetching mails. 

Im requesting all the headers in batches of 50 at the time.
i'm receiving batch messages very slow and some of the request are lost. 
I receive "A stable connection to the server could not be established. error"
This is only happening with outlook, i have no problems with gmail or yahoo.

this is my session configuration.

    self.username = username;
    self.password = password;
    self.hostname = ^ NSString *(SCMMailProvider provider) {
        if (provider == SCMServiceProviderGmail) {
            return @"imap.gmail.com";
        } else if (provider == SCMServiceProviderHotmail) {
            return @"imap-mail.outlook.com";
        } else if (provider == SCMServiceProvideriCloud) {
            return @"imap.mail.me.com";
        } else if (provider == SCMServiceProviderYahoo) {
            return @"imap.mail.yahoo.com";
        }
        
        return nil;
    }(provider);
    
    if (provider == SCMServiceProvideriCloud || provider == SCMServiceProviderOther) {
        self.mailsFolder = kSCMMailFolderInbox;
        [self setAuthType:MCOAuthTypeSASLNone];
    } else {
        [self setOAuth2Token:password];
        [self setUsername:username];
        if (provider == SCMServiceProviderHotmail) {
            [self setAuthType:MCOAuthTypeXOAuth2Outlook];
            self.mailsFolder = kSCMMailFolderInbox;
        } else if (provider == SCMServiceProviderGmail) {
            [self setAuthType:MCOAuthTypeXOAuth2];
            self.mailsFolder = kSCMGmailAllMessagesFolder;
        }
    }

    MCOIMAPFetchMessagesOperation *fetchOp = [self fetchMessagesByNumberOperationWithFolder:self.mailsFolder
                                                                                requestKind:MCOIMAPMessagesRequestKindStructure | MCOIMAPMessagesRequestKindHeaders
                                                                                    numbers:uidSet];
    [fetchOp start:^(NSError *messageFetchingError, NSArray *msgs, MCOIndexSet *vanished) {
}

**Comment by dinhviethoa** [comment]
Could you ask your question on stackoverflow instead? We'll answer here. Thanks!
