### ISSUE TITLE
Error while Create/Rename/Delete folder using Gmail,Yahoo & iCloud

### ISSUE THREAD

**Issue by SreenivasiPhoneDeveloper** [MailCore/mailcore2#1041]
Hi Team, 

when i am Creating/Renaming/Deleting folder from my application i am getting below Error:

Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo=0x1a4e3f50 {NSLocalizedDescription=A stable connection to the server could not be established.}

Note:
Here self.imapSession != nil
I have internet connection(i am able to send & receive mails). 

1. MCOIMAPFolderStatus error status is  nil
2. MCOIMAPOperation error status is A stable connection to the server could not be established.

Here is the Code:
  MCOIMAPFolderStatusOperation * op = [self.imapSession folderStatusOperation:@"Test 123"];
         [op start:^(NSError *error, MCOIMAPFolderStatus * info) {
             if (info == nil) {
            MCOIMAPOperation * op1 = [self.imapSession renameFolderOperation:@"test 123" otherName:@"Test 1234"];
            [op1 start:^(NSError *error) {
                if(error == nil)
                {
                    DEBUGLOG(@"the folder name is Changed success");
                }
                else
                {
                    DEBUGLOG(@"the folder name Changed failed");
                }
            }];
        }

please let me know any solution?

**Comment by dinhviethoa** [comment]
Could you post your question on stackoverflow instead? We'll answer here.  

--  
Hoa V. Dinh
