### ISSUE TITLE
Retrieve the latest emails from one UID

### ISSUE THREAD

**Issue by gsantome** [MailCore/mailcore2#1042]
Hello guys! so this is my problem... I'm loading my latest emails and I'm saving the latest UID because later if the user reload the list of emails I want to get all the emails from that UID to now... for this, I'm using
```
UInt64 start = lUid; //this is the last UID loaded
UInt64 end = UINT64_MAX;

MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindHeaders;
MCOIndexSet *uids = [MCOIndexSet indexSetWithRange:MCORangeMake(start, end)];

MCOIMAPFetchMessagesOperation *fetchOperation = [imapSession fetchMessagesOperationWithFolder:@"INBOX"
                                                                                  requestKind:requestKind   
uids:uids];           
```

this action always return the results but I'm getting the latest email... So I tried to make

```
UInt64 start = lUid + 1;
```
but it is exactly the same.

Anyone know whats going on?

Thanks!

**Comment by gsantome** [comment]
Another comment, im looking the logger and the last UID is 34038 so when i made the call the start was 34039... so why im getting the email with id 34038?

```
2015-01-20 18:33:06.852 App[25022:730644] mailcore - IMAP: 8 UID FETCH 34039:* (UID ENVELOPE BODY.PEEK[HEADER.FIELDS (References)])
```

**Comment by dinhviethoa** [comment]
Could you ask your question on stackoverflow? We'll answer here.
Please include code sample, result from the code and connection logger. Thanks!

**Comment by gsantome** [comment]
Hi @dinhviethoa I already asked into StackOverflow... http://stackoverflow.com/questions/28055310/retrieving-the-latest-emails-with-mailcore2 

Thanks!
