### ISSUE TITLE
Man-in-the-middle Attack

### ISSUE THREAD

**Issue by ramSS** [MailCore/mailcore2#1043]
How to implement/Achieve the Server Identity in Mailcore 1, Which is in mailcore 2 ?
or 
Is there any way to fix this "man-in-the-middle" attack in mailcore ver 1 ?

Appreciate your help, Thanks.

Ram.

**Comment by dinhviethoa** [comment]
Could you ask your question on stackoverflow? We'll answer here. Thanks!  

--  
Hoa V. Dinh
