### ISSUE TITLE
image attachment content inside message body

### ISSUE THREAD

**Issue by tdquangad2** [MailCore/mailcore2#1045]
Hello,
There are 2 files in my attachments (1 text file and 1 image file).
I implemented message "MCOMessageView_templateForAttachment" in "MCOMessageViewDelegate" with Empty string to not display my attachment, but there is image in my body content.
MCOMessageView_templateForAttachment:
~~~ Objective-C
- (NSString *) MCOMessageView_templateForAttachment:(MCOMessageView *)view
{ 
    return @"";
}
~~~
<B>I don't want to display any attachments files.</B> Please help me to do that. 
Thanks

**Comment by dinhviethoa** [comment]
Could you ask you question on stackoverflow? We'll answer here. Thanks!
