### ISSUE TITLE
Resume idle operations 

### ISSUE THREAD

**Issue by gsantome** [MailCore/mailcore2#1047]
Hello, I'm using idle operations but when you have that kind of operations if I want to get the html body with an operation this is not working because the idle is listening this stuff... So I'm executing a notification to call the interrupt method inside my idle operation. But when I finish to get the html body i want to start again the idle operation but i don't want to initialize again the idle operation or the start method... 

Someone know if we could add a method like [idleOp restore]; or something like that?

Thanks!

**Comment by dinhviethoa** [comment]
Does it work if you initialize again the idle operation and restart it?

**Comment by gsantome** [comment]
So I'm using a collection view and I'm showing the html body in each collection item... so for each item im calling that method and if I start again the idle operation something weird is happening and the collection view start to re render all the item... and its not performance to start every time the idle operation... this is why I was asking if you have something to stop it and continue later... 

You think re initialize every time its a good idea? in my case if i have a lot of emails i will re initialize the operation a lot!.

Thanks!

**Comment by dinhviethoa** [comment]
I don't think the reinitializing the idle operation is going to be a performance bottleneck.
Closing the issue.
