### ISSUE TITLE
MCOIMAPSession Timeout property does not seem to be respected during MCOIMAPCopyMessagesOperation 

### ISSUE THREAD

**Issue by kgellci** [MailCore/mailcore2#1049]
If there is no internet connection, calling start on MCOIMAPCopyMessagesOperation does not call the completion block based on the MCOIMAPSession timeout property.  If the internet connection comes back on, the completion block is still not called even after waiting for a few minutes.

Does the timeout property on MCOIMAPSession determine how long Mailcore operations try before there is an error or is there some other timeout / reachability code in Mailcore which determines when operations call the completion block.

**Comment by dinhviethoa** [comment]
Could you use CPU sampler with instruments when the app is stuck and show the result here?
Thanks.

**Comment by kgellci** [comment]
Are you referring to the CPU Activity instrument or the Sampler instrument?  I can run either one of those and post the results.

**Comment by kgellci** [comment]
Let me know if this suffices for now
![screen shot 2015-01-28 at 4 47 52 pm](https://cloud.githubusercontent.com/assets/2548953/5950370/0576a412-a70e-11e4-9095-ec6b7483a974.png)

**Comment by dinhviethoa** [comment]
Could you take a look at the value for the timeout used when calling mailstream_cf_open_voip_timeout()?
Could you let me know if the delay matches what you set?

**Comment by kgellci** [comment]
It is currently using the default timeout of 30, I am not setting a timeout.  I confirmed while testing that it is in fact using 30.  After disabling the internet, performing the operation, then enabling the internet again, I waited about 10 min before it actually completed the operation.

**Comment by dinhviethoa** [comment]
Could you check what's in the loop wait_runloop() not behaving properly?
There's the following line:
```
r = CFRunLoopRunInMode(kCFRunLoopDefaultMode, delay, true);
```
and it should expire within the given delay.

**Comment by kgellci** [comment]
I actually think I have tracked the issue down, let me know if this makes any sense.

MCOIMAPSession seem to be going bad and not reusable once a network is not reachable.  Any operations added to a session, even after a network is reachable will no longer work.  My current solution is to disconnect all MCOIMAPSessions when the application is not able to reach any networks.

Do you think this is the correct solution / expected behavior on Mailcores part?

**Comment by dinhviethoa** [comment]
That's a correct solution.

**Comment by kgellci** [comment]
Will be testing for the next week, considering the issue solved for now.
