### ISSUE TITLE
Can not search messages from a date with mail core

### ISSUE THREAD

**Issue by dungnguyen2703** [MailCore/mailcore2#1051]
I try to search a message from a date in mail server and I found that we can use this 

MCOIMAPSession *_imapSession = [[MCOIMAPSession alloc] initWithMailAccount:account];
    [[_imapSession searchOperationWithFolder:folder kind:MCOIMAPSearchKindSinceReceivedDate searchString:@""] start:finishBlock];

But it through an assert. It's look like mailcore2 doesn't do that function yet.

Please help

**Comment by dinhviethoa** [comment]
Could you ask your question on stackoverflow? We'll answer here.
