### ISSUE TITLE
How to fetch headers for the mails using pop3 server

### ISSUE THREAD

**Issue by sonali19** [MailCore/mailcore2#1059]
Here is the code that I am using....

            for (int i=0; i<[message count]; i++) {
                MCOPOPFetchHeaderOperation * op = [session fetchHeaderOperationWithIndex:i];
                [op start:^(NSError * error, MCOMessageHeader * header) {
                    
                    if (header != NULL) {
                        [arry addObject:header];
                        if ([message count]-1 == i) {
                            
                            [HUD hide:YES];
                            self.title = @"Mail-Inbox";
                            [self.tableView reloadData];
                        }
                    }
                }];
            }

But I am not getting any result. Please help me to overcome this.

**Comment by dinhviethoa** [comment]
Could you ask your question on stackoverflow? We'll answer here.
Attach connection logger logs.
Thanks.
