### ISSUE TITLE
"THE CURRENT HOTMAIL ACCOUNT CANNOT CONNECT TO WEBMAIL."

### ISSUE THREAD

**Issue by jonasman** [MailCore/mailcore2#1060]
Im getting this error connecting to hotmail smtp . Error: MCOErrorNeedsConnectToWebmail

Any idea what this could be?

**Comment by jonasman** [comment]
i solved it by going to the webmail and adding my phone number to my account.

Also i used the logger to get the logs from the connection. Very useful!

**Comment by bineshpavithran** [comment]
Getting this issue even after adding phone number...any other solutions?
