### ISSUE TITLE
IOS: memory leaked when downloading header of mails.

### ISSUE THREAD

**Issue by dungnguyen2703** [MailCore/mailcore2#1061]
It look like memory leaked when i try to download header of emails using method fetchMessagesByUIDOperationWithFolder. Try to download header of more than 10000 mails, memory go up to more than 100mb and this number is not decrease after finish downloading. Please check it

**Comment by dinhviethoa** [comment]
Could you give more details? Such as some code and results from Instruments?

**Comment by dungnguyen2703** [comment]
This is the code that I use to test. (my account hold more than 8000 mails in inbox)


#import <MailCore/MailCore.h>
#import "SampleGetHeader.h"

@implementation SampleGetHeader

static MCOIMAPSession *session = nil;

+ (MCOIMAPSession *)imapSession {
    if (!session) {
        session = [[MCOIMAPSession alloc] init];
        session.hostname = @"imap.gmail.com";
        session.port = 993;
        session.connectionType = MCOConnectionTypeTLS;
        session.maximumConnections = 20;
        session.timeout = 120;
        session.username = USERNAME______;
        session.password = PASSWORD______;
    }
    return session;
}

+ (void)fetchUidMailFromDate:(NSDate *)fromDate folder:(NSString *)folder finishBlock:(void (^)(NSError *error))finishBlock {
    NSLog(@"BEGIN TEST");
    [[[self imapSession] searchExpressionOperationWithFolder:folder expression:[MCOIMAPSearchExpression searchSinceDate:fromDate]] start:^(NSError *error, MCOIndexSet *searchResult) {
        NSLog(@"COUNT = %d", searchResult.count);
        MCOIMAPMessagesRequestKind requestKind = (MCOIMAPMessagesRequestKindHeaders | MCOIMAPMessagesRequestKindInternalDate | MCOIMAPMessagesRequestKindFlags | MCOIMAPMessagesRequestKindStructure);
        [[[self imapSession] fetchMessagesOperationWithFolder:folder requestKind:requestKind uids:searchResult] start:^(NSError *error, NSArray *messages, MCOIndexSet *vanishedMessages) {
            NSLog(@"END TEST");
        }];
    }];
}


+ (void)test {
    [self fetchUidMailFromDate:[NSDate dateWithTimeIntervalSince1970:0] folder:@"INBOX" finishBlock:^(NSError *error) {
        
    }];
}
@end

**Comment by dinhviethoa** [comment]
Try to fetch messages per batch of 200 instead.
