### ISSUE TITLE
MCOAbstractMessage cannot be used as a type 

### ISSUE THREAD

**Issue by krux20** [MailCore/mailcore2#1062]
Hello, 

I'm trying to use the MCOHTMLRenderDelegate protocol, but xcode keeps giving me a strange error saying "Use of undeclared type MCOAbstractMessage". Is this because the function name is also called MCOAbstractMessage, so is this an ambiguity issue? I have attached a screenshot of the error that I'm getting. Any general help would be great thanks.  

![](http://i.gyazo.com/d73bfc33870391a5e93e7ed17b867a28.png)

**Comment by dinhviethoa** [comment]
Could you show complete project instead?

**Comment by krux20** [comment]
Thank you for the reply. Do you mean this? 

![](http://i.gyazo.com/16762ea8ea0e5d671eef5247d850bf93.png)

**Comment by dinhviethoa** [comment]
I meant an actual project on github. Not a screenshot.

**Comment by krux20** [comment]
There you go thanks. https://github.com/krux20/EmailApp

**Comment by dinhviethoa** [comment]
<unknown>:0: error: bridging header '/Users/KRU/Desktop/3rd Year Of Uni Work/ Final Year Project/Project/EmailApp/EmailApp-Bridging-Header.h' does not exist

**Comment by krux20** [comment]
Yeah, sorry. Would you be able to put the mailcore2.xcodeproj into the project that way it will work.

**Comment by dinhviethoa** [comment]
That's not the issue. Could you take a look at the code and fix your sample?

**Comment by krux20** [comment]
Hi, 
I found the issue you need to specify the library in the Build Phase section. 


![](http://i.gyazo.com/b6efa8f4e8bc7fcc5211f071a5df1339.png)

**Comment by dinhviethoa** [comment]
Do you still need help?

**Comment by krux20** [comment]
Yes, I do. It still doesn't allow me to use MCOAbstarctMessage functions for some reason

**Comment by dinhviethoa** [comment]
I downloaded the latest version of https://github.com/krux20/EmailApp.
It built successfully for me except that I had to change this:

```
    func validateEmail(email: String) -> Bool {
        // Need to fix since it allows .... com to be passed
        let emailRegex = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}"
        //return NSPredicate(format: "SELF MATCHES %@",emailRegex).evaluateWithObject(email)
        return true
        
    }
```

**Comment by dinhviethoa** [comment]
oh MCOMessageView.swift is empty...
Could you upload an accurate version of EmailApp that I can test?

**Comment by krux20** [comment]
I added some changes to it. I managed to pin-down where the issue is coming from somehow I cannot have a function name with MCOAbstractMessage and the type MCOAbstractMessage together in the same file.

**Comment by dinhviethoa** [comment]
Let's take it to stackoverflow. I'm closing that issue.
