### ISSUE TITLE
button touch is not working in cameraoverlayview

### ISSUE THREAD

**Issue by sonali19** [MailCore/mailcore2#1064]
I am using AVCaptureDevice to read the barcode and to this I am adding an overlay with a button. The button appears but the touch is not working.

Here is the sample code
    self.overlayView.frame = CGRectMake(0, 0, self.view.frame.size.width, self.view.frame.size.height);
    
    OverlayView *theOverLayView = [[OverlayView alloc] initWithFrame:self.view.bounds                                      cancelEnabled:YES oneDMode:YES];
    
    [theOverLayView setDelegate:self];
    
    self.overlayView = theOverLayView;
    
    [theOverLayView release];
    
    [self.overlayView setPoints:nil];
    
    [[self view] addSubview:self.overlayView];

**Comment by dinhviethoa** [comment]
Unrelated to mailcore2.
Closing.
