### ISSUE TITLE
Unicode char returned on message body

### ISSUE THREAD

**Issue by xdoug7** [MailCore/mailcore2#1065]
Hello!

In some specific e-mail, MailCore is returning me an strange unicode character.
This is the content that I'm getting from `-[MCOMessageParser htmlRenderingWithDelegate:]` and `-[MCOMessageParser htmlBodyRendering:]` methods:
https://gist.github.com/xdoug/5de581af4190dd3f59b3

And here is the .eml file for that e-mail:
https://www.dropbox.com/s/nr4ovsia2upz5be/NzM3NA.eml?dl=0

One more question, is there a way to remove the attachments names from the message body?

Thank You!

**Comment by dinhviethoa** [comment]
That's a character that failed to be converted.
You need to customize the template for remove attachments names.

**Comment by dinhviethoa** [comment]
I think it's fixed now.
