### ISSUE TITLE
Delete selected message when using IMAP

### ISSUE THREAD

**Issue by Mahesh-novaquad** [MailCore/mailcore2#1068]
Please suggest me how to delete selected mail from "INBOX" folder?

**Comment by ambujshukla** [comment]
Hi mahesh can u help me,I'm getting a issue as libetpan file not found.

**Comment by DrChrispoper** [comment]
There is a good example for this in the wiki.

https://github.com/MailCore/mailcore2/wiki/IMAP-Examples
