### ISSUE TITLE
problem with MCOIMAPMessageRenderingOperation

### ISSUE THREAD

**Issue by KennyVB** [MailCore/mailcore2#1071]
no matter how i make the variable it returns nil
and if i use () it's not nil but still crashes...
can anyone see what the problem is ? i'm converting from obj-c to swift from example iOS

http://stackoverflow.com/questions/28740853/custom-uitabelviewcell-variable-returns-nil-iboutlets-works-fine-mailcore2

**Comment by dinhviethoa** [comment]
The discussion is happening on stackoverflow. It's probably related to Swift more than MailCore.
