### ISSUE TITLE
Issue with MCOMessageParser / Download Part

### ISSUE THREAD

**Issue by lksnmnn** [MailCore/mailcore2#1072]
We just found a glitch in MCOMessageParser. Since we separated the message download into download by parts (body & attachments) (we're not keeping MCOMessages, and therefore can't use the designated requests), we're downloading the message mainPart and then send it through the parser.

This worked perfectly fine till now.

This message made problems: https://gist.github.com/lksnmnn/eb49e646905a43e647bf
We're able to download the part data, but after initialising the MessageParser the data (messageParser.data) is nil. It also only occurred with this specific content. Adding a "hello world" to the email made it work again.

mainPartID is 1
mainPartEncoding is 0 (7-bit)
mainPartType is text/plain

Our code:

```obj-c

NSString* mainPartID = [self.message.messageData mainPartID];
NSNumber* mainPartEncoding = [self.message.messageData mainPartEncoding];
__block NSString* mainPartType = [self.message.messageData mainPartType];

if(inFolder && session && mainPartID && mainPartEncoding && mainPartType)
{
              // this is a minor hack, the correct operation would be htmlBodyRenderingOperationWithMessage:folder:
              FetchContentOperation* fetchContentOperation = [FetchContentOperation fetchMessageContentByUIDWithFolder:inFolder.path uid:self.uid.integerValue partID:mainPartID encoding:mainPartEncoding.integerValue urgent:urgent session:session withCallback:^(NSError *error, NSData *data){
                    
                if(error)
                        callback(error, nil);
                else
                {
                        MCOMessageParser* messageParser = [[MCOMessageParser alloc] initWithData:data];

                         messageParser.mainPart.mimeType = mainPartType;
                        
                        NSString* htmlString = [messageParser htmlRenderingWithDelegate:[MCODelegate sharedInstance]];
                        
                        callback(error, htmlString);
                }
        }];
}
else
{ // Fetch complete message here }
```

**Comment by dinhviethoa** [comment]
Could you ask your question on stackoverflow instead? We'll answer here.

**Comment by lksnmnn** [comment]
Done. You’ll find it here: http://stackoverflow.com/questions/28995748/mailcore-mcomessageparser-download-and-parse-part-without-mcomessage
Thanks!

Am 11.03.2015 um 19:16 schrieb Hoà V. DINH <notifications@github.com>:
