### ISSUE TITLE
SMTP send issue Android 

### ISSUE THREAD

**Issue by alexmorris** [MailCore/mailcore2#1074]
Trying to add SMTP to the example Android project. Code crashes on builder.header().setTo(toList);

Using below code

    private void SendMessage() {

        // SMTP Server Setting
        SMTPSession smtpSession = new SMTPSession();
        smtpSession.setHostname("smtp.gmail.com");
        smtpSession.setPort(465);
        smtpSession.setUsername("yourgmail@gmail.com");
        smtpSession.setPassword("gmailpassword");
        smtpSession.setAuthType(AuthType.AuthTypeSASLPlain);
        smtpSession.setConnectionType(ConnectionType.ConnectionTypeStartTLS);

        // MessageBuilder Setting
        MessageBuilder builder = new MessageBuilder();
        Address from = new Address();
        from.setDisplayName("");
        from.setMailbox("yourgmail@gmail.com");

        Address to = new Address();
        to.setDisplayName("");
        to.setMailbox("recipientMail");
        List<Address> toList = Arrays.asList(to);

        builder.header().setFrom(from);
        builder.header().setTo(toList); // CRASHED HERE
        builder.header().setSubject("My message");
        builder.setHTMLBody("This is a test message");

        // Sending Operation
        byte[] rfc822Data = builder.data();
        SMTPOperation sendOperation = smtpSession.sendMessageOperation(rfc822Data);
        sendOperation.start(new OperationCallback() {
            @Override
            public void succeeded() {
                Log.e("SMTP", "Error");
            }

            @Override
            public void failed(MailException e) {
                Log.e("SMTP", "Success");
            }
        });
    }

**Comment by dinhviethoa** [comment]
Sure, is there an issue?
Closing.

Could your issue on stackoverflow?
Thanks.

**Comment by snehazanzane** [comment]
Only change the ConnectionType

**smtpSession.setConnectionType(ConnectionType.ConnectionTypeStartTLS);**

to

**smtpSession.setConnectionType(ConnectionType.ConnectionTypeTLS);**

Its working for me
