### ISSUE TITLE
ios how to forward/reply email

### ISSUE THREAD

**Issue by MountainHill** [MailCore/mailcore2#1078]
According to *MCOMessageBuilder.h*,we can send a message using SMTP as follows:
```
MCOMessageBuilder * builder = [[MCOMessageBuilder alloc] init];
[[builder header] setFrom:[MCOAddress addressWithDisplayName:@"Hoa V. DINH" mailbox:@"hoa@etpan.org"];
NSArray * to = [NSArray arrayWithObject:[MCOAddress addressWithDisplayName:@"Gael Roualland" mailbox:@"gael@etpan.org"]];
 [[builder header] setTo:to];
 [[builder header] setSubject:@"A nice picture!"];
 [builder setHTMLBody:@"<div>Here's the message I need to send.</div>"];
 [builder addAttachment:[MCOAttachment attachmentWithContentsOfFile:@"/Users/foo/Pictures/image.jpg"]];
 NSData * rfc822Data = [builder data];
```

But if I want to forward or reply other email,which property can I set?
I tried serval methods like set relatedAttachments,htmlInlineAttachments etc,It has no effect.
#### I wonder if I can commbine htmlBody from other email with current sending content as html, and then set setHTMLBody?  

Can anyone give some advice.
Thanks advance.

**Comment by dinhviethoa** [comment]
Could you ask your question on stackoverflow? We'll answer here.

**Comment by qq510304723** [comment]
but I`m can not find answer in stackoverflow  [forward/reply email](http://stackoverflow.com/questions/29044066/mailcore2-how-to-forward-reply-email-ios)

**Comment by qq510304723** [comment]
`MCOMessageBuilder *builder = [[MCOMessageBuilder alloc] init];    

// 设置header
builder.header = [self builderMessageHeader:newMessage];
    
// 设置文本内容
NSString *bodyHtml = originMessage.htmlBody;
NSString *body = newMessage.plainTextBody;    
NSMutableString *fullBodyHtml = [NSMutableString stringWithFormat:@"%@<br/><br/><br/>-------------原始邮件-------------<br/>%@", [body stringByReplacingOccurrencesOfString:@"\n" withString:@"<br/>"], bodyHtml];
builder.htmlBody = fullBodyHtml;

// 添加正文里的附加资源
NSArray *inattachments = originMessage.attachments;
     for (MailAttachmentObject *attachObj in inattachments) {
             MCOAttachment *attachment = [MCOAttachment attachmentWithData:attachObj.data filename:attachObj.fileName];
             [builder addRelatedAttachment:attachment]; //添加html正文里的附加资源（图片）
         }
     }
     
     
     // 添加附件
    for (MailAttachmentObject *attachObj in newMessage.attachments) {
         MCOAttachment *attachment = nil;
         if (attachObj.savePath) {
             attachment = [MCOAttachment attachmentWithContentsOfFile:attachObj.savePath];
        [builder addAttachment:attachment];
    }
    
    // 发送邮件
    MCOSMTPSendOperation *sendOperation = [_smtpSession sendOperationWithData:[builder data]];
    [sendOperation start:^(NSError *error) {
     }];
`
