### ISSUE TITLE
Could you give me a "dll" running in the win ?

### ISSUE THREAD

**Issue by sunxinfei** [MailCore/mailcore2#1079]
I  download the CTemplate\libEtPan\Cyrus SASL\LibXML 2\Tidy HTML5\zlib\ICU, OpenSSL and pthread and copy and run -----there is error  so  can you give me a dll directly running in the windows?

**Comment by dinhviethoa** [comment]
Could you ask your question on stackoverflow? We'll answer here.
Also, I don't understand what you're asking.

**Comment by sunxinfei** [comment]
I clicked "Build for Windows Read instructions for Windows."
and I did every step,when I using Visual Studio 2013, open mailcore2.sln,and make the new generation solution.it didn't work ,
