### ISSUE TITLE
On Hotmail, messageCount doesn't update unless you create a new imapSession instance

### ISSUE THREAD

**Issue by vu0tran** [MailCore/mailcore2#1081]
I'm running into something weird and I can replicate with the iOS UI Test with the library.

Repro steps:

1. Authenticate with a hotmail account 
2. Run inboxFolderInfo and look at [info messageCount]
3. Send emails to the hotmail account
4. Do step #2

messageCount between these points will always be identical, even if email has been loaded in the Outmail / Hotmail UI

In order for me to get it to work I had to do:

1. Authenticate with hotmail account
2. Run inboxFolderInfo and look at [info messageCount]
3. Send emails to the hotmail account
4. Disconnect from imapSession
5. Reinstantiate imapSession  
6. messageCount is now different

Any thoughts on the issue? I can provide logger info

**Comment by dinhviethoa** [comment]
That's a hotmail issue.
