### ISSUE TITLE
Bitmask checks in Swift

### ISSUE THREAD

**Issue by KieranMcGrady** [MailCore/mailcore2#1084]
I'm porting some Objective-C code over to Swift but having problems checking a flag status. It seems like bitmask checks are limited in Swift.

```
RawOptionSetType no longer implements BooleanType by default, so standard bitmask checks (if opt & .Option {...) only work if you add BooleanType protocol conformance manually.
```
Here is my code:
```
self.message.flags = NSNumber(int: self.message.flags.intValue & ~MCOMessageFlag.Flagged)
```
Is this something that would need to be added to MailCore or is there an alternative way for me to write that code?

NB: I already opened a [StackOverflow question](http://stackoverflow.com/questions/29120892/using-objective-c-bitmask-is-swift) on this but as it may require modifications to the framework I thought I would be useful to post here.

**Comment by dinhviethoa** [comment]
What's the modification you're suggesting in MailCore?

**Comment by DrChrispoper** [comment]
How about something like this?
```
self.message.flags = NSNumber(integer:MCOMessageFlag(self.message.flags.integerValue) & ~MCOMessageFlag.Flagged)
```

**Comment by KieranMcGrady** [comment]
@DrChrispoper Thanks for the suggestion. I now get the error:

```
Could not find an overload for '&' that accepts the supplied arguments
```

@dinhviethoa My knowledge on this isn't great but from what I've read in order to use Bitmasks in Swift ```MCOMessageFlag``` should implement BooleanType protocol conformance.

**Comment by DrChrispoper** [comment]
What version of Xcode are you using?

**Comment by DrChrispoper** [comment]
@KieranMcGrady  I get too actually. 
```
self.message.flags = NSNumber(integer:(MCOMessageFlag(self.message.flags.integerValue) & ~MCOMessageFlag.Flagged).rawValue)
```
Seems to work, but it seems more like a quick fix rather than a real solution.

**Comment by KieranMcGrady** [comment]
I'm using 6.2. That definitely seems to suppress the error. I'll report back when I'm sure it's working. Thanks for your help!

**Comment by KieranMcGrady** [comment]
@DrChrispoper How would you handle this situation? I'm trying to check if the flag is set so I can set a local Boolean. It's telling me it can't find the member 'rawValue'.

```
        if ((MCOMessageFlag(self.message.flags.integerValue) & MCOMessageFlag.Flagged).rawValue) {
            isStarred = true
        }
```

My Objective-C code looks like this:

```
    if ((self.message.flags.intValue & MCOMessageFlagFlagged)) {
        isStarred=YES;
    }
```

**Comment by DrChrispoper** [comment]
Double check but this seems to be right:
```
if (MCOMessageFlag(self.message.flags.integerValue) & MCOMessageFlag.Flagged).rawValue != 0 {
    isStarred = true
}
```

**Comment by KieranMcGrady** [comment]
Thanks, it definitely fixes the errors. Again I'll report back once I've finished porting the class and can test it. Hopefully later today or tomorrow.

**Comment by KieranMcGrady** [comment]
I've implemented starring in my app again and the code you provided works fine. Thanks for your help.
