### ISSUE TITLE
Parsing header: wrong dates

### ISSUE THREAD

**Issue by lksnmnn** [MailCore/mailcore2#1085]
We lately got a few bug requests mentioning an issue with old emails getting new received dates after the initial header fetch. Our code is (at this point) pretty straight forward:

```obj-c
// looking for header->date in the fetched MCOIMAPMessage 
if(imapMessage.header.date)
        [message setDateSent:imapMessage.header.date];
else
 {
       // no date found -> look for received date
        if(imapMessage.header.receivedDate)
            [message setDateSent:imapMessage.header.receivedDate];
        else
            // set current date (this should not happen)
            [message setDateSent:[NSDate date]];
}
```

And we fetch the following data:

```obj-c
    MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindHeaders | MCOIMAPMessagesRequestKindStructure | MCOIMAPMessagesRequestKindInternalDate | MCOIMAPMessagesRequestKindHeaderSubject | MCOIMAPMessagesRequestKindFlags | MCOIMAPMessagesRequestKindFullHeaders | MCOIMAPMessagesRequestKindExtraHeaders;
```

Do you guys have any ideas?

**Comment by lksnmnn** [comment]
I posted an example header in this gist: https://gist.github.com/lksnmnn/c5e1d1a34d194134da77
I used the header.txt unit test to check this bug with the latest mailcore version and it couldn't parse the date correctly.

The output was:
```obj-c
(lldb) po [[parser header] date]
2001-01-01 00:00:00 +0000
(lldb) po [[parser header] receivedDate]
2001-01-01 00:00:00 +0000
```
instead of 
```obj-c
2014-10-12 10:31:56 +0200
```

**Comment by dinhviethoa** [comment]
The line "From mail@example.com  Sun Oct 12 10:31:56 2014" is not part of RFC 822 format.
MailCore is not trying to parse it.
If the header does not contain a line "Date: Fri, 21 Nov 1997 09:55:06 -0600", a random date will be assigned to it.

Also, when you get a MCOIMAPMessage, the server is responsible for returning a correct receivedDate.

**Comment by lksnmnn** [comment]
Thanks. AFAIK other email clients tried and managed to parse it (somehow)...

So if its Gmail, the google imap server should return a receivedDate on not RFC conform messages... 
Where does it go wrong then?

The user also complained about in gmail imported iOS notes (from notes.app) not being sorted correctly by date. Seems to me something is broken somewhere?

I'll try to catch this in the debugger...

**Comment by dinhviethoa** [comment]
I'll let you analyze more and figure out something that works for your case.
I don't think that's an issue with MailCore.

**Comment by lksnmnn** [comment]
I'll be back ;)

**Comment by lksnmnn** [comment]
Hi,

I investigated this issue further and I got another header which failed the unit test. This time it has a date: part, which is not formatted correctly: 
```obj-c
// 114? email is to old for that stuff
Date: Sun, 13 Apr 114 16:56:26 +0200
```
The message parser returns the current timestamp for date and receivedDate.
I uploaded the new header into this gist: https://gist.github.com/lksnmnn/2236f11ed065428d7f1a

The header contains a lot "Received: " parts, which have the correct date in a correct format. Why is the receivedDate parsed wrong as well?

Seems to me, libetpan is quite strict there? We really need to fix this issue for our users, else their inbox is flooded with old mail disguised as current messages on the initial header fetch. 

Regards,
Lukas

**Comment by dinhviethoa** [comment]
The "Received" field is not meant to be parsed by an email app.

You should really read receivedDate on the MCOIMAPMessage header if you're really fetching MCOIMAPMessagesRequestKindInternalDate.
Please do so if you'd like to fix the issue for your users.

**Comment by lksnmnn** [comment]
Ok, thanks for clearing that up.

We do read the receivedDate on the MCOIMAPMessage header (as you can see in my code example above) iff the date is nil. Since you set the header date to "now" when it's not RFC conform, how should we decide which date field to trust? Should we use receivedDate as the primary source?

Regards,
Lukas

**Comment by dinhviethoa** [comment]
Could you check what the server is sending as INTERNALDATE (use connection logger)?
It's the IMAP server that is suppose to parse and send a correct date.

**Comment by lksnmnn** [comment]
It's a little bit difficult to reproduce this behavior for testing. I do not have such an email in any of my accounts. However, I once saw it myself (some time ago) but blind-sighted deleted them... 

So we only got bug reports concerning Gmail and onlime.ch

**Comment by dinhviethoa** [comment]
Ok. Let me know if you have logs related to it. Thanks.

**Comment by lksnmnn** [comment]
I'll do. 
Meanwhile, lets assume the server response is correct and receivedDate is set to the actual date the message was received and the parser couldn't parse the date: part of the header so sets the header date to the current system time.
How should we decide which date is correct? Just compare them and take the older one?

**Comment by dinhviethoa** [comment]
header->date() is the date the email was sent. It has to be parsed and parsing might fail because the email apps could generate a wrong one.
header->receivedDate() is something that's generated by the receiving email server and it's the date the email has been received by the server. Unless the implementation of the server is really wrong, it should show a correct date.

**Comment by lksnmnn** [comment]
Thank you for clearing this up. We really did expect header->date() to be nil if it couldn't be parsed.

I adjusted our code so that we do not rely on header->date() to be parsed. We now compare the two given dates and choose which ever has the older timestamp. (Or we could just use receivedDate and ignore date completely, whatever)
```obj-c
if ([imapMessage.header.date compare:imapMessage.header.receivedDate] == NSOrderedDescending)
{
    [message setDateSent:imapMessage.header.receivedDate];
}
else 
{
    [message setDateSent:imapMessage.header.date];
}
```

**Comment by Dikan** [comment]
Hello All,
I have fetched email headers, now I want to traverse through them and display them in the table view in iphone app. 
Thanks in advance

**Comment by dinhviethoa** [comment]
Please read the documentation.
