### ISSUE TITLE
Getting latest code with Cocoapods

### ISSUE THREAD

**Issue by KieranMcGrady** [MailCore/mailcore2#1087]
I switched from a direct integration of Mailcore to using Cocoapods because I thought it would be easier to stay up-to-date with the latest patches. It seems like Cocoapods is coming from the releases though which haven't been updated since December. 

1. Is there a way I can get the latest code from master via Cocoapods? 
2. Do you plan to do another release soon? 
3. Or would it be better for me to switch back to manual integration?

**Comment by dinhviethoa** [comment]
They've been updated.

**Comment by KieranMcGrady** [comment]
Thanks!
