### ISSUE TITLE
Crash in cell.messageRenderingOperation

### ISSUE THREAD

**Issue by Ramkumartr** [MailCore/mailcore2#1090]
When scrolling mail tableview continuously(with some speed),It will crash with this log  "/mailcore2/src/core/basetypes/MCObject.cc:69: assert 0"

This is the code
 cell.messageRenderingOperation = [[[Singleton sharedSingleton]getImapSession] plainTextBodyRenderingOperationWithMessage:message folder:@"INBOX" stripWhitespace:YES];

getting crash on here
[cell.messageRenderingOperation start:^(NSString *plainTextBodyString, NSError * error) {

**Comment by dinhviethoa** [comment]
I think there's an issue with your app.
Please post on stackoverflow since it's not an issue with mailcore2.
