### ISSUE TITLE
Offline HTML Rendering

### ISSUE THREAD

**Issue by KieranMcGrady** [MailCore/mailcore2#1092]
It doesn't seem possible to use ```htmlBodyRenderingOperationWithMessage:``` when offline (I get the error ```A stable connection to the server could not be established.```). Why is this? 

I already have the MCOIMAPMessage stored locally and thought it contained everything necessary to render the message. Is ```htmlBodyRenderingOperationWithMessage:``` pulling more data from the server?

**Comment by dinhviethoa** [comment]
Could you ask the question on stackoverflow instead? We'll answer here.

**Comment by KieranMcGrady** [comment]
Sure, thanks. Here's the link: http://stackoverflow.com/questions/29342382/mailcore-offline-html-rendering
