### ISSUE TITLE
Porting mailcore2 to Tizen platform

### ISSUE THREAD

**Issue by cat-cat** [MailCore/mailcore2#1093]
It's a big and good job you have done with mailcore2. We tested it on iOS and it worked perfect. But now we need a good imap library on Tizen platform https://www.tizen.org/. Could you give an overview of possible ways to port mailcore2 to Tizen. Is that possible? What should we start with? How many of dependencies we have to port along with mailcore2? Thank you.

**Comment by dinhviethoa** [comment]
Maybe see:
https://github.com/MailCore/mailcore2/blob/master/build-linux/README.md
There's a list of the dependencies to port to Tizen that might be accurate.

**Comment by cat-cat** [comment]
Could list of dependencies be reduced if use libetpan directly? I did not find any dependency descriptions for libetpan.

**Comment by dinhviethoa** [comment]
Please investigate more.
