### ISSUE TITLE
Documentation on MCOIMAPFolderInfoOperation & MCOIMAPFolderStatusOperation

### ISSUE THREAD

**Issue by Romes--** [MailCore/mailcore2#1094]
What is the difference between MCOIMAPFolderInfoOperation and MCOIMAPFolderStatusOperation? Is there a reason why recentCount is not included in MCOIMAPFolderInfo?

RFC 3501 says:
> Since any command can return a status update as untagged data, the
      NOOP command can be used as a periodic poll for new messages or
      message status updates during a period of inactivity (this is the
      preferred method to do this).

How is this achieved in MailCore? Does an MCOIMAPFolderStatusOperation suffice, or do I need to call an MCOIMAPNoopOperation first to be sure I get the latest data?

Many thanks again for such an awesome framework!

**Comment by dinhviethoa** [comment]
`MCOIMAPFolderInfoOperation` is info returned on `SELECT`.
`MCOIMAPFolderStatusOperation` is info returned on `STATUS`.

I'd avise to use a periodic `FETCH` or use `IDLE`.
