### ISSUE TITLE
cocoa pod osx platform

### ISSUE THREAD

**Issue by eahrold** [MailCore/mailcore2#1096]
We use Mailcore2 in a project that supports 10.8 and have compiled without error or warnings using that SDK. 

A while back we moved over to the mailcore2-osx cocoapod, but have had to manually modify the podspec setting the `platforms` to `10.8`. I was wondering if there was a specific reason it's currently set to 10.9 and if not whether you would consider setting it to 10.8 in future releases. 

Thank you for your consideration.

**Comment by dinhviethoa** [comment]
Done. Thanks for the feedback.

**Comment by eahrold** [comment]
That's fast!
Thank you.
