### ISSUE TITLE
Is it possible to fetch only the message id via fetchMessagesOperationWithFolder method?

### ISSUE THREAD

**Issue by kitgary** [MailCore/mailcore2#1098]
Any way to set the MCOIMAPMessagesRequestKindUid to fetch only the message id and uid?

**Comment by dinhviethoa** [comment]
Could you ask your question on stackoverflow? We'll answer here.

**Comment by kitgary** [comment]
Asked. Ths.

**Comment by kitgary** [comment]
Any update?
