### ISSUE TITLE
scripts/include.sh/build-dep.sh: line 334: cd: tidy-html5-ios-1: No such file or directory

### ISSUE THREAD

**Issue by phuc149** [MailCore/mailcore2#1103]
I did clone the project and open the example project in iOS but it show this error. I think the script cannot download the tiny library.
Please help me to fix this problems. Thank you so much!
![screen shot 2015-04-07 at 3 44 50 pm](https://cloud.githubusercontent.com/assets/1808431/7019725/3b3a5ef8-dd3d-11e4-83bd-6959d2dc7f8d.png)

**Comment by dinhviethoa** [comment]
Could you retry? Maybe there was a glitch or something.
Could you try to download this file manually if the script doesn't work?

**Comment by dinhviethoa** [comment]
I'm closing the issue. Feel free to re-open if you have any update.
