### ISSUE TITLE
Cancelling an operation is not dispatch queue safe

### ISSUE THREAD

**Issue by stevesparks** [MailCore/mailcore2#1104]
As we discussed in my previous issue, we can supply a dispatch queue for the IMAP and SMTP sessions. I have written code that creates these queues for each account and uses the appropriate queue for any operations touching the Mailcore classes. (These queues are named `IMAP-[email address]` so they can be readily identified.) Since making these changes, I have found the system to be reliable and performant.

However, I have found that when canceling currently running operations, a reliable crash occurs in `MCOperationQueue.cpp:107` when we ask the `MCObject::performMethodOnDispatchQueue` method to perform a block synchronously on the current queue.

I can work around it by changing the `waitUntilDone` value to `false`, though there may be negative side effects to that change.

Please advise.

**Comment by dinhviethoa** [comment]
Could you show me the stack trace of the crash?
It will help me find out what's going on.
Thanks.

**Comment by stevesparks** [comment]
Must be something you fixed; I was several weeks behind. A `git pull` has made the issue go away. My apologies.

**Comment by dinhviethoa** [comment]
Good news. I like problem that fix themselves without even removing or adding code :)

**Comment by stevesparks** [comment]
well... any MORE code. :D thanks as always.
