### ISSUE TITLE
Fetch message content without downloading images or attachments?

### ISSUE THREAD

**Issue by ProjectDent** [MailCore/mailcore2#1106]
I want to provide a preview of a user's messages, but I don't wish to download attachments just in order to do that. I'm using `fetchParsedMessageOperationWithFolder`, and doing:

`NSLog(@"data size: %i", [parser data].length);`

shows that the data used to parse the message with the attachment is of a much larger size, because it's reading the attachment too.

Is there a way that I can get the header information, plus the plain text body rendering of a message, without loading any images, or attachments?

**Comment by dinhviethoa** [comment]
Could you ask your question  on stackoverflow? We'll answer here.

**Comment by ProjectDent** [comment]
Posted here http://stackoverflow.com/questions/29633815/mailcore2-fetch-message-content-without-downloading-images-or-attachments
