### ISSUE TITLE
Calling fetchMessagesByNumberOperationWithFolder not returning all gmail labels.

### ISSUE THREAD

**Issue by IuliuMoga** [MailCore/mailcore2#1108]
Hey! 
I'm trying to fetch messages from Gmail INBOX and filter the messages after their labels, but when fetchMessagesByNumberOperationWithFolder returns the valid list of Gmail messages, but when i'm asking for gmailLabels only Important and Sent labels are listed the Promotions, and Social labels are missing.

Here is a chunk from code:
----------------------------------------
- (BOOL)loadAllMessages:(void (^) (EmailFolder_v2 *folder, NSArray *messages, NSError *error))completion{
    if (self.loadingMessages) {
        return NO;
    }
    self.loadingMessages = YES;
 MCOIMAPMessagesRequestKind requestKind = (MCOIMAPMessagesRequestKind)
    (MCOIMAPMessagesRequestKindHeaders | MCOIMAPMessagesRequestKindStructure |
     MCOIMAPMessagesRequestKindInternalDate | MCOIMAPMessagesRequestKindHeaderSubject |
     MCOIMAPMessagesRequestKindFlags | MCOIMAPMessagesRequestKindGmailLabels);

  MCOIMAPFolderInfoOperation *op = [self.mailBox.imapSession folderInfoOperation:self.folderName];
    [op start:^(NSError *error, MCOIMAPFolderInfo *info) {
        
        if (error) {
            self.loadingMessages = NO;
            if (completion) {
                completion(self,nil,error);
            }
            [self invokeMessagesLoadDelegate:nil error:error];
            return;
        }
       
        self.totalNumberOfFolderMessages = [info messageCount];
        if (0 == self.totalNumberOfFolderMessages ) {
            self.loadingMessages = NO;
            if (completion) {
                completion(self,nil,nil);
            }
            [self invokeMessagesLoadDelegate:nil error:nil];
            return;
        }
    
        MCORange fetchRange = MCORangeMake(1, self.totalNumberOfFolderMessages - 1);
        MCOIMAPFetchMessagesOperation *fetchOp = [self.mailBox.imapSession fetchMessagesByNumberOperationWithFolder:self.folderName
                                                                                                        requestKind:requestKind
                                                                                                            numbers:[MCOIndexSet indexSetWithRange:fetchRange]];
        
        [fetchOp start:^(NSError *fetch_error, NSArray *messages, MCOIndexSet *vanishedMessages) {
            @synchronized(self.emailCache) {
                dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
                    [self.emailCache syncFromIMAPMessages:messages];
                    NSArray *arr = [self.emailCache cacheIMAPMessages:messages sort:self.messagesSortEnabled];
                    dispatch_async(dispatch_get_main_queue(), ^{
                        self.loadingMessages = NO;
                        if (completion) {
                            completion(self,arr,fetch_error);
                        }
                        [self invokeMessagesLoadDelegate:arr error:fetch_error];
                    });
                });
            }
        }];
    }];
    return YES;
}
Thanks!

**Comment by dinhviethoa** [comment]
Yep. Gmail IMAP doesn't expose those labels.
