### ISSUE TITLE
MCOIMAPOperation storeFlagsOperationWithFolder not working

### ISSUE THREAD

**Issue by miguelgazela** [MailCore/mailcore2#1109]
I'm trying, unsuccessfully, to mark a Gmail message as read with the following code

```
MCOIMAPOperation *op = [session storeFlagsOperationWithFolder:@"INBOX"
        uids:[MCOIndexSet indexSetWithIndex:uid]
        kind:MCOIMAPStoreFlagsRequestKindAdd
        flags:MCOMessageFlagSeen];
    
    [op start:^(NSError *error) {
        if (!error) {
            NSLog(@"Updated flags");
        } else {
            NSLog(@"Error updating flags: %@", error);
        }
    }];
```

There's no error occurring, but the message is not marked as read. Should I do this in a different way? Is there anything wrong with the code?

Thanks

**Comment by dinhviethoa** [comment]
Connection logs is probably the best to help investigation.

**Comment by miguelgazela** [comment]
Apparently everything works ok. This is what I get from the logger:

```
2015-04-16 18:39:40.808 TestApp[14685:411243] data: 46 UID STORE 24061 +FLAGS.SILENT (\Seen)
2015-04-16 18:39:40.989 TestApp[14685:411243] data: 46 OK Success
```

**Comment by dinhviethoa** [comment]
Can you fetch the flag after you set it?

**Comment by WarisShams** [comment]
I want to fetch all emails of Sent Items how could i do that. Or just tell me the FolderName for Sent Items.

**Comment by dinhviethoa** [comment]
Closing that thread. Please post unrelated questions on stackoverflow.
