### ISSUE TITLE
Wait for all Mailcore2 operations to complete?

### ISSUE THREAD

**Issue by gmaletic** [MailCore/mailcore2#1114]
I want my code to wait until all Mailcore2 operations have completed. I was thinking if I could get access to the NSOperationQueue that Mailcore2 is using, I could just call -[NSOperationQueue waitUntilAllOperationsAreFinished] on it.

Is this possible, and would it work?

And if not...is there a good way to accomplish what I'm trying to do?

**Comment by dinhviethoa** [comment]
with a specific IMAPSession, you can use the following properties:
- operationQueueRunningChangeBlock: a block that will get notified when the operation queue is running or not running
- operationQueueRunning: will tell whether the operation queue is running.
As long as operationQueueRunning is YES, you can wait.

**Comment by gmaletic** [comment]
Thanks! That helps.
