### ISSUE TITLE
Set an email like Reply or Forward 

### ISSUE THREAD

**Issue by gsantome** [MailCore/mailcore2#1115]
Hello, I'm using mailcore2 to send emails and everything looks perfect, but now I'm trying to reply or forward and email but I don't understand exactly how this works... If I need to set a value into the header or something like that.

Thanks for your help.

**Comment by dinhviethoa** [comment]
Closing since it's tracked by http://stackoverflow.com/questions/30007826/mailcore2-reply-forward
