### ISSUE TITLE
Authentication failure with Gmail via c++ (windows) dll build

### ISSUE THREAD

**Issue by cuisinart** [MailCore/mailcore2#1116]
Hello, using the current windows .dll build (thank you for this!), I'm getting an authentication error when trying to send an SMTP email via gmail.  My other apps can send smtp through that address OK.  I can't find any c++ examples for mailcore, likewise to API doc for it, so I'm going by some guesswork.  Can you find the problem? Additionally, the windows dll build still has a uchardet.dll dependency, even though I see a commit from 3 months ago indicating this was removed.

Secondly, the SMTPSession (not async) doesn't appear to work, as the member function for sending mail is private.

[code]	//-------======= Sending ========-------------
	
	smtpSession.setHostname(&mailcore::String("smtp.gmail.com"));
	smtpSession.setPort(465);
	smtpSession.setUsername(&mailcore::String("myemail@gmail.com"));
	smtpSession.setPassword(&mailcore::String("password"));
	smtpSession.setAuthType(mailcore::AuthTypeSASLPlain);
	smtpSession.setConnectionType(mailcore::ConnectionTypeTLS);
	//smtpSession.setUseHeloIPEnabled(true);
	//smtpSession.setCheckCertificateEnabled(false);

	mailcore::MessageHeader header;
	header.setFrom(mailcore::Address::addressWithDisplayName(&mailcore::String("Software Support"),&mailcore::String("myemail@gmail.com")));
	mailcore::Array ary;
	ary.addObject(mailcore::Address::addressWithDisplayName(NULL,&mailcore::String("to@emaildomain")));
	header.setTo(&ary);
	
	header.setSubject(&mailcore::String("Test email subject line"));
	
	builder.setHeader(&header);
	builder.setHTMLBody(&mailcore::String("This is the Body.  Thank you for your help."));

	mailcore::Data *dat = builder.data();

	mailcore::SMTPOperation *operation = smtpSession.sendMessageOperation(dat);
	operation->setCallback(this);

	operation->start();
[/code]

**Comment by dinhviethoa** [comment]
I need to rebuild the .dll for windows to match the recent commits.
In your code, you're using stack allocation. I'd advise you to go through dynamic allocation with all objects in mailcore.

```
session = new SMTPAsyncSession();
hostname = new String("smtp.gmail.com");
hostname->autorelease();
session-> setHostname(hostname);
```

for strings, you can also use the shorthand `session-> setHostname(MCSTR("smtp.gmail.com"));`

Those methods of SMTPSession are public:

```
        virtual void sendMessage(Data * messageData, SMTPProgressCallback * callback, ErrorCode * pError);
        virtual void sendMessage(Address * from, Array * /* Address */ recipients, Data * messageData,
                                 SMTPProgressCallback * callback, ErrorCode * pError);
```

For the authentication issue, could you show the connection logger logs?

**Comment by cuisinart** [comment]
thank you for your fast reply!  I have converted the objects to use dynamic allocation, along with autorelease, however there are now memory leaks for each new.  Perhaps autorelease doesn't do what it sounds like it does?  I don't really know how to use the connection logger, but gave it a shot:

here i've added the operationFinished callback for you to see.  This is where the authent error shows up, but the log buffer is empty.

	//-------======= Sending ========-------------

	logger = new mailcore::ConnectionLogger();

	smtpSession = new mailcore::SMTPAsyncSession();
	smtpSession->autorelease();

	buffer = new mailcore::Data();
	buffer->autorelease();

	smtpSession->setConnectionLogger(logger);
	smtpSession->logConnection( //mailcore::ConnectionLogTypeErrorParse | 
								mailcore::ConnectionLogTypeErrorReceived //|
								//mailcore::ConnectionLogTypeErrorSent |
								//mailcore::ConnectionLogTypeReceived |
								//mailcore::ConnectionLogTypeSent |
								//mailcore::ConnectionLogTypeSentPrivate
							   ,buffer);
	

	smtpSession->setHostname(MCSTR("smtp.gmail.com"));
	smtpSession->setPort(465);
	smtpSession->setUsername(MCSTR("myemail"));
	smtpSession->setPassword(MCSTR("pass"));
	smtpSession->setAuthType(mailcore::AuthTypeSASLPlain);
	smtpSession->setConnectionType(mailcore::ConnectionTypeTLS);
	//smtpSession->setUseHeloIPEnabled(true);
	//smtpSession->setCheckCertificateEnabled(false);

	mailcore::MessageHeader *header = new mailcore::MessageHeader();
	header->autorelease();
	header->setFrom(mailcore::Address::addressWithDisplayName(&mailcore::String("Software Support"),&mailcore::String("email@gmail.com")));

	mailcore::Array *ary = new mailcore::Array();
	ary->autorelease();
	ary->addObject(mailcore::Address::addressWithDisplayName(NULL,&mailcore::String("email")));

	header->setTo(ary);
	header->setSubject(MCSTR("Thank you for your help"));

	
	builder = new mailcore::MessageBuilder();
	builder->autorelease();
	builder->setHeader(header);
	builder->setHTMLBody(&mailcore::String("This is the Body.  Thank you for your help"));

	mailcore::Data *dat = builder->data();


	mailcore::SMTPOperation *operation = smtpSession->sendMessageOperation(dat);
	operation->setCallback(this);

	operation->start();

}

void CMail::operationFinished(mailcore::Operation *op)
{
	mailcore::SMTPOperation* operation = (mailcore::SMTPOperation*)op;
	mailcore::ErrorCode code = operation->error();
	buffer; //<--this is empty!
}

**Comment by dinhviethoa** [comment]
You should wrap around those lines a:
```
AutoreleasePool * pool = new AutoreleasePool();
// code ...
pool->release();
```

**Comment by dinhviethoa** [comment]
`ConnectionLogger` is an interface to implement.

**Comment by cuisinart** [comment]
oh, looking at it, I thought maybe it logged to a mailcore::Data buffer.  thanks for the hint.

**Comment by cuisinart** [comment]
Here's the log it creates:

220 mx.google.com ESMTP el6sm9068010pdb.93 - gsmtp

EHLO hal

250-mx.google.com at your service, [IPADDR]

250-SIZE 35882577

250-8BITMIME

250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN XOAUTH

250-ENHANCEDSTATUSCODES

250-PIPELINING

250-CHUNKING

250 SMTPUTF8

**Comment by dinhviethoa** [comment]
Maybe libsasl2 fails to work on Windows.
I'm wondering if it's built properly.

**Comment by cuisinart** [comment]
IMAP seems to work in my testing, this uses TLS on port 993. Not sure if that helps.

**Comment by dinhviethoa** [comment]
If you can rebuild mailcore2, I can give you some guidance to workaround this issue.

**Comment by dinhviethoa** [comment]
I'm closing it. Please reopen if you'd like more help on that topic.

**Comment by cuisinart** [comment]
Hi, I built mailcore2 and libetpan under VS 2013, but it is unstable with
the latest code base, so I can't get even to the point I was before with
your older build dlls.  It's crashing on the function:
mailcore::Data *dat = builder->data();
when it tries to release the display name.  I'm not sure why.  Generally,
it's a bad idea to have one dll allocate memory and another dll free it,
and that seems to happen between mailcore and libetpan.

For the windows build of mailcore2 there were several problems:  the
include folder paths are incorrect, all of the includes use #include
<MailCore/...> but none of the include files are under a folder named
MailCore, so that has to be removed on all of the includes.  Also there is
an __attribute__ compiler specific flag used that only works with gcc, not
the MSVC compiler.  Finally, the MEMMEM function is not a standard c or c++
function and is platform specific.  you need to add an implementation, I
used this one:
http://www.overclock.net/t/1436139/fastest-memmem-in-c


If you have any suggestions I'm all ears!

**Comment by dinhviethoa** [comment]
Could you create a new issue for the crash and one for memmem()?
Could you also create a pull request for the memmem implementation on windows?
I'm locking this issue.

**Comment by dinhviethoa** [comment]
Fixed with https://github.com/dinhviethoa/cyrus-sasl/pull/1
The new prebuilt of cyrus-sasl is also available.
