### ISSUE TITLE
Move mail to another account

### ISSUE THREAD

**Issue by ngminhduong** [MailCore/mailcore2#1118]
I trying to move mail from an account to another account.
I used appendMessageOperationWithFolder to do this.
But when i moved it to new account.
These info: mailed-by, from was changed.
I want mail keep original header info when i move to another account.
How to do this.
I had a test. Apple mail can do this. Does mail support us to do this?

Thanks

**Comment by KieranMcGrady** [comment]
Try using:

```
- (MCOIMAPCopyMessagesOperation *)copyMessagesOperationWithFolder:(NSString *)folder
                                                             uids:(MCOIndexSet *)uids
                                                       destFolder:(NSString *)destFolder;
```

Then when the operation completes delete the message from it's previous location.

**Comment by ngminhduong** [comment]
i think that copyMessagesOperationWithFolder copy mail in the same account.
Is that right?
I want to copy mail from an acount to another account.

**Comment by KieranMcGrady** [comment]
Ok, currently I'm only allowing move within the current account. I'm not sure how it works with multiple accounts.

**Comment by dinhviethoa** [comment]
Could you post your question on stackoverflow? Thanks.
