### ISSUE TITLE
Assertion failure in 5.0.1

### ISSUE THREAD

**Issue by tom-mayer** [MailCore/mailcore2#1119]
Hi,

I'm using the cocoapods Version of Mailcore, to send mails over a Gmail Account. I get the following error calling `NSData * rfc822Data = [builder data];` It happens on iOS 8.3 Simulator and Device.

It happens even if I pass an empty string  to setHTMLBody. 

```
Assertion failed: (option_defs[ optId ].type == TidyInteger), function SetOptionInt, file ../../src/config.c, line 381.
Signal: 6 (signal SIGABRT)
```

The full code snippet is:
```
MCOMessageBuilder *builder = [[MCOMessageBuilder alloc] init];
MCOAddress *from = [MCOAddress addressWithDisplayName:[Properties objectForKey:@"Name"]
                                                      mailbox:[[DPOAuth2 getInstance] getEMail]];
MCOAddress *to = [MCOAddress addressWithDisplayName:nil
                                                    mailbox:[_tokenFieldView.tokenField.tokenObjects componentsJoinedByString:@", "]];
MCOAddress *cc = [MCOAddress addressWithDisplayName:nil
                                                    mailbox:[_tokenFieldViewCC.tokenField.tokenObjects componentsJoinedByString:@", "]];
[[builder header] setFrom:from];
[[builder header] setTo:@[to]];
[[builder header] setSubject:_subjectField.text];
[[builder header] setCc:@[cc]];

[builder setHTMLBody:mailhtml];
NSData * rfc822Data = [builder data];
```

Stracktrace its located in HTMLCleaner::cleanHTML

This StackOverflow post ist probably related:
http://stackoverflow.com/questions/26051052/mailcore2-mchtmlcleaner-error

**Comment by dinhviethoa** [comment]
Can you show the full stack trace?

**Comment by tom-mayer** [comment]
Here's the full stack trace:

![screen shot 2015-05-06 at 09 20 49](https://cloud.githubusercontent.com/assets/2562379/7488968/654df614-f3d1-11e4-8d93-a4d0925dc1db.png)

I'm still trying to figure this out, I simplified the code like so:

```
MCOMessageBuilder *builder = [[MCOMessageBuilder alloc] init];
    MCOAddress *from = [MCOAddress addressWithMailbox:@"test@gmail.com"];
    MCOAddress *to = [MCOAddress addressWithMailbox:@"test@gmail.com"];
    MCOAddress *cc = [MCOAddress addressWithMailbox:@"test@gmail.com"];

    [[builder header] setFrom:from];
    [[builder header] setTo:@[to]];
    [[builder header] setSubject: @"the subject"];
    [[builder header] setCc:@[cc]];

    [builder setHTMLBody:@""];
    NSData * rfc822Data = [builder data];
```

If I use this snippet in a new minimal example program it works, if I insert it into the main program it crashes with the above error.

**Comment by tom-mayer** [comment]
It seems strange I double checked all the compiler settings and flags and they are similar in both projects.

**Comment by dinhviethoa** [comment]
It sounds like it's going through libtidy.A.dylib, which means that you probably didn't link properly against libtidy.a
Did you add -ltidy in your linker flags?

**Comment by tom-mayer** [comment]
In my main project I have -ltidy in my "other linker flags"

**Comment by tom-mayer** [comment]
I'm closing this, since it is more an issue with my project than with the library,... I did get it working by removing the -ltidy flag from "other linker flags", not sure though why this worked

**Comment by dinhviethoa** [comment]
Oh sure. libtidy is already included in the cocoapods.
