### ISSUE TITLE
Get Specific Message From Server

### ISSUE THREAD

**Issue by aallard** [MailCore/mailcore2#1121]
I have an Objective-C application with an implementation of MailCore2 where I contact the server and retrieve messages.  When I iterate through the array of retrieved messages, I store selected values from each one in a local sqlite3 database.  Among the various pieces of data stored, I make sure and grab the messageID like this:
    
    NSString *messageID = messages.header.messageID;

Later in the application, I want to use the messageID from above and retrieve only that specific message from the server.  Is there a very simple, minimal example of how to do this that does NOT involve UIDs?  If not, is there a best practice example of how to retrieve one specific message from the server?

**Comment by dinhviethoa** [comment]
Searching for a message with the header "Message-ID" would work but it would have bad performance.
UID is the way to do.
If you're Gmail-specific, Gmail message ID is something you can use and you can probably search them efficiently.
