### ISSUE TITLE
Error when I search after the first result.

### ISSUE THREAD

**Issue by gsantome** [MailCore/mailcore2#1123]
Hello, I'm making a search and everything looks great.  But I'm having a problem with some kind of words. For example I'm trying to search Hello and i got all the mails who have that word in From... but if im trying to search Hello Yesterday (its an email that i have) didn't work... the result from the search is empty. the same if im trying to search by email

this is how im searching 

```
MCOIMAPSearchExpression *searchExpressionBody = [MCOIMAPSearchExpression searchBody:self.searchField.text];
MCOIMAPSearchExpression *searchExpressionFrom = [MCOIMAPSearchExpression searchFrom:self.searchField.text];
    
MCOIMAPSearchExpression *expression = [MCOIMAPSearchExpression searchAnd:searchExpressionFrom other:searchExpressionBody];
    
self.searchOperation = [[[WMEmailHelper shared] searchSession] searchExpressionOperationWithFolder:@"INBOX" expression:expression];
```

Thanks

**Comment by dinhviethoa** [comment]
It highly depends on the behavior server.
There's pretty much nothing mailcore can do about it.

I'd suggest you to tweak your query. Maybe search only from or body?

**Comment by dinhviethoa** [comment]
I close this issue since there's no update. Feel free to reopen the issue if you have more information.
