### ISSUE TITLE
Using MailCore2 problem

### ISSUE THREAD

**Issue by NewBiginner** [MailCore/mailcore2#1124]
![2015-05-18 2 57 15](https://cloud.githubusercontent.com/assets/8537734/7675707/3a9d941e-fd6e-11e4-8994-92ca17c06bba.png)

I follow the instruction of MailCore and use  the example of "Fetching message", however it is not work...
I Still can't figure out what happen... Does the code anything wrong? 

Error message:
2015-05-18 14:59:08.971 mailDemo[71572:191224] Error downloading message headers:Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo=0x7fe1f8dd21d0 {NSLocalizedDescription=A stable connection to the server could not be established.}
2015-05-18 14:59:08.972 mailDemo[71572:191224] The post man delivereth:(null)

**Comment by dinhviethoa** [comment]
Does you firewall prevent you from connecting to IMAP yahoo?

**Comment by NewBiginner** [comment]
I have turn off the firewall,and I use yahoo mail app password. I also set timeout for a long time, however the error message is "Unable to parse response from server"...

**Comment by dinhviethoa** [comment]
Could you show the connection logs? there's a property connectionLogger on the IMAP session.

**Comment by NewBiginner** [comment]
![2015-05-19 12 38 30](https://cloud.githubusercontent.com/assets/8537734/7695843/39bbb5ac-fe28-11e4-911e-9b330ad046b2.png)
![2015-05-19 12 39 31](https://cloud.githubusercontent.com/assets/8537734/7695845/3dd8aba4-fe28-11e4-8b78-b4330971f270.png)
![2015-05-19 1 08 11](https://cloud.githubusercontent.com/assets/8537734/7695846/405b82ca-fe28-11e4-92f8-9ef5454e30af.png)
![2015-05-19 1 08 25](https://cloud.githubusercontent.com/assets/8537734/7695849/44a9c8f0-fe28-11e4-985f-ff735f349bd5.png)
The first two photos are not add "connectionLogger".

**Comment by dinhviethoa** [comment]
Please use the property connectionLogger of MCOIMAPSession.

**Comment by NewBiginner** [comment]
Do you mean [session.connectionLogger]?

**Comment by dinhviethoa** [comment]
yes.

**Comment by NewBiginner** [comment]
Can I use "NSLog(@"",session.connectionLogger);".

**Comment by dinhviethoa** [comment]
Please read the documentation of connectionLogger.

**Comment by NewBiginner** [comment]
![2015-06-02 5 11 07](https://cloud.githubusercontent.com/assets/8537734/7932384/7eba5fbe-094a-11e5-962e-9e82ca69b43b.png)
![2015-06-02 5 11 27](https://cloud.githubusercontent.com/assets/8537734/7932385/82072422-094a-11e5-9157-4c51aa8aecbe.png)

![2015-06-02 5 13 05](https://cloud.githubusercontent.com/assets/8537734/7932413/af4e4406-094a-11e5-9866-80243501240b.png)

The first and second pieces of message after I using connectionLogger. The third is where I add the connectionLogger. Where is the problem? Please help me~

**Comment by dinhviethoa** [comment]
The server you're talking to has an issue.

**Comment by NewBiginner** [comment]
You means that yahoo's mail server has problem now, so we can't contact with it recently?

**Comment by dinhviethoa** [comment]
Yep. Yahoo mail server is probably having issues.

**Comment by NewBiginner** [comment]
Wow~! Is it been a long time?
