### ISSUE TITLE
Mailcore creates date of 'now' when imap message has no date header

### ISSUE THREAD

**Issue by tomandersen** [MailCore/mailcore2#1125]
There is an init call in 
MCMessageHeader.cpp
MessageHeader::MessageHeader()
{
    init(true, true);
}
 The two 'true' s mean to set the date to NOW and the messageID autogenerated. 

For autogeneration of the ID there is a warning bool, mMessageIDAutoGenerated that is set, so one can tell if the message actually had an ID coming back from the server (or however its set). Good.

The sent dates do not have this same thing, so when I download from the server some IMAP email headers (some in the draft folder from 2009) that have no date in the header, the date is returned to the api as the timestamp of when the header was built. So the Draft looks off by 5 years.

Its tricky to tell when the date is set from the header. - Can I get the original data downloaded from the IMAP server for the header from the OS X objective C api? It does not look like it. Its called env_date
![screen shot 2015-05-18 at 5 14 48 pm](https://cloud.githubusercontent.com/assets/221405/7690452/928a6eb4-fd81-11e4-9a9e-3fed07a40fb4.png)

It might be best to set up an mMessageDateAutoGenerated field so we can tell when the date is fictional.

Or can I get at that env_date from the api?

Thanks.
--Tom

**Comment by dinhviethoa** [comment]
How would your app behave if the date was auto generated?
If you think we could improve date parsing, the best would be to submit a bug to libetpan (or submit a patch would be even better).

**Comment by tomandersen** [comment]
The UI would display "unknown date" for the few files that have no known date. 

There simply are no dates in the header. So I don't think its a parsing issue. If you left the date as it really is (nil), (i.e. call init(false, true)) then likely all sorts of software that uses mailcore would fail. That's why I suggest using an auto generated flag in MCMessageHeader.cpp. 

I really don't know where the line between libetpan and mailcore is, but the file starts with 'MC'.  

Thanks for the quick reply!

**Comment by dinhviethoa** [comment]
Are you going to sort those emails by date?

**Comment by tomandersen** [comment]
I create a file for the email with the file name being the subject and the date, so when I go back to the server, I get different dates, which gives me different file names.  If there is no date I could use the message ID or similar, but users prefer dates. So they are sorted by date, but in the Finder, etc.

**Comment by dinhviethoa** [comment]
I meant: in a list of emails with some with dates and some with auto-generated dates, how will you order them if you're trying to sort them by date.

**Comment by tomandersen** [comment]
The auto generated dates are currently set to 'now' so these old mostly bad messages float to the top of the list as most recent. But I would just sort them to the bottom using my sort routine. Its just that I can't easily tell when an email is really a new email or actually an old one with partly broken headers.

**Comment by dinhviethoa** [comment]
Ok. Sounds good. Would you like to submit a pull request?  

--  
Hoa V. Dinh

**Comment by tomandersen** [comment]
I'm not familiar with the code enough to feel confident to do that. - but I can see the changes that would parallel mMessageIDAutoGenerated, but then there are questions dealing with sent and recieved date (do they need flags themselves?) Or is it simpler in the init() call to not autogenerate the dates. 

The 1970 solution is easiest for me - ie: changing the init call to (false, true) is what I would use for my purposes as its simpler for me. That may break some apps that make new emails for composing with the date at time of contstruction, though?

MCMessageHeader.cpp
MessageHeader::MessageHeader()
{
init(false, true); // leave date on constructed messages to 1970 as a flag that the date is not set.
}

**Comment by dinhviethoa** [comment]
Ok. Here's my suggestion:

If we got a parser error while trying to set the date, we could set some flags:

```
void setDateBroken(bool broken)
bool isDateBroken()
void setReceivedDateBroken(bool broken)
bool isReceivedDateBroken()
```

when setting the date manually, using setDate() or setReceivedDate(), we could clear those flags to false.

What do you think?

**Comment by tomandersen** [comment]
That sounds good. We need a way to tell if the date is broken from Objective C as the C++ header stores an integer, not a pointer. I think your way would work well for composing too, as the header date would only be broken on an IMAP header read with no date in the header, like in the screenshot.

Right now, the parser code just checks to see if the date is there and sets it,  - the call importIMAPEnvelope()  might be a good place to call setDateBroken if there is no date in the header.

**Comment by dinhviethoa** [comment]
I'll let you start. I can guide you through if you need to refine some details at some point.

**Comment by dinhviethoa** [comment]
Have you been able to make progress on it?

**Comment by tomandersen** [comment]
Sorry am on other projects right now. 

Maybe back on it soon.  

—Tom



Tom Andersen
705 888 4324
~
P/A 
Palmer Andersen
www.palmerandersen.com <http://www.palmerandersen.com/>

Access all your files anywhere with Spotdox
www.spotdox.com <http://www.spotdox.com/>
