### ISSUE TITLE
Can i fetch all pop email (including readed email)

### ISSUE THREAD

**Issue by trangtran** [MailCore/mailcore2#1126]
I am using mailcore2 to get pop email
The function I am using is: (MCOPOPFetchMessagesOperation *) fetchMessagesOperation
But this function doesn't return all email, it returns unread email
Example:
My pop email has total 718 messages (including readed and unread)
using the function (MCOPOPFetchMessagesOperation *) fetchMessagesOperation -> it returns 16 unread email, so in my email app, email list contains only 16 unread email.

I am expecting to get all 718 emails
does Mailcore2 support to get all email? and which function i should use?

Thank you!

**Comment by dinhviethoa** [comment]
You should review the settings of POP of your email account on Gmail.
