### ISSUE TITLE
Cannot connect to Hosted Exchange IMAP server.

### ISSUE THREAD

**Issue by IuliuMoga** [MailCore/mailcore2#1127]
Hey, I tried to connect to a Hosted Exchange server and no success.
I've tried to connect on all ports with all connection types and all auth types (the auth type doesn't matter right now since the session cannot connect to server ) and connection times out.
The single port that connection logger send a response is port 80 but there i get error CFNetwork SSLHandshake failed (-9847).
I've tried also with another email clients and it's working.

Here is the piece of code that tries to check the account.

+ (void) checkAccount:(void (^) (NSError* error ))completion {
    
    MCLogEnabled = 1;
    
    __block MCOIMAPSession *imapSession = [[MCOIMAPSession alloc] init];
    
    //a little tryes in here
    unsigned int ports [] = {993,143,80};
    static int  iPort = 0;
    
    MCOConnectionType connections [] = {MCOConnectionTypeClear,MCOConnectionTypeStartTLS,MCOConnectionTypeTLS};
    static int iConnection = 0;
    
    MCOAuthType authTypes [] = {MCOAuthTypeSASLPlain,MCOAuthTypeSASLNone,MCOAuthTypeSASLCRAMMD5,MCOAuthTypeSASLGSSAPI,MCOAuthTypeSASLDIGESTMD5,MCOAuthTypeSASLLogin,MCOAuthTypeSASLSRP,MCOAuthTypeSASLNTLM,MCOAuthTypeSASLKerberosV4};
    static int iAuthType = -1;
    
    static BOOL finished = NO;
    if ( (++iAuthType) >= sizeof(authTypes) / sizeof(authTypes[0])) {
        iAuthType = 0;
        if ( (++iConnection) >= sizeof(connections) / sizeof(connections[0]) ) {
            iConnection = 0;
            
            if ( (++iPort) >= sizeof(ports) / sizeof(ports[0])) {
                iPort = 0;
                finished = YES;
                NSLog(@"\t\tFINISH RESOURCES");
            }
        }
    }
    
    NSLog(@"\n------ Try on port: %d, connection: %ld, auth: %ld -------",ports[iPort], connections[iConnection], authTypes[iAuthType]);
    
    [imapSession setPort:ports[iPort]];
    [imapSession setConnectionType:connections[iConnection]];
    [imapSession setAuthType:authTypes[iAuthType]];
    [imapSession setUsername:@"the_username"];
    [imapSession setPassword:@"the_password"];
    [imapSession setHostname:@"01-ssl.midpoint.se"]; //this is the host name can be reached only on port 80, but connection is refused due a CFNetwork SSLHandshake failed (-9847) 
    [imapSession setTimeout:3];
    //[imapSession setCheckCertificateEnabled:NO];
    //[imapSession setVoIPEnabled:NO];
    
    imapSession.connectionLogger = ^(void * connectionID, MCOConnectionLogType type, NSData * data) {
        #if defined (DEBUG)
        if (data) {
            NSLog(@"%@", [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
        }
        #endif
    };
    
    //end try stuff
    
    
    MCOIMAPOperation *op = [imapSession checkAccountOperation];
    
    [op start:^(NSError *error) {
        
        if (error && !finished) {
            dispatch_async(dispatch_get_main_queue(), ^{
                [self checkAccount:completion];
            });
            return;
        }
        
        iAuthType = -1;
        iPort = 0;
        iConnection = 0;
        
        finished = NO;
        MCLogEnabled = 0;
        
        if (completion) {
            completion(error);
        }
    }];
    
}

**Comment by dinhviethoa** [comment]
It doesn't look like this server can be reached using IMAP (I tried to connect to it using IMAP port).

**Comment by IuliuMoga** [comment]
Thanks a lot for your support!
It would be great If you can tell me from your experience a solution or a work around solution for getting this to work.

Thanks,
Have a nice day!


On 26 May 2015, at 07:33, Hoà V. DINH <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1127<https://github.com/MailCore/mailcore2/issues/1127>.
