### ISSUE TITLE
Message with emoji is incorrect

### ISSUE THREAD

**Issue by baksheev** [MailCore/mailcore2#1130]
Hi,
`MCOMessageParser` parses messages with emoji wrong, so «🎉» converts to «ðŸŽ‰».
It occurs in both methods:
```
- (NSString *) htmlBodyRendering;
- (NSString *) plainTextBodyRendering
```
You can see example: http://cl.ly/image/3f2W0U0L3y0p

**Comment by dinhviethoa** [comment]
Could you attach a RFC 822 source of a message?

**Comment by baksheev** [comment]
Yeah, look here: http://cl.ly/text/3k350u1o2s2W

**Comment by dinhviethoa** [comment]
It's fixed now.
