### ISSUE TITLE
How to recognize thread email vs single email

### ISSUE THREAD

**Issue by lukelan** [MailCore/mailcore2#1131]
Dear Mailcore2 team,

I am using mailcore2 lib to build the app on iOS. I am trying to distingue between  thread email with single email on Gmail. The purpose is display thread icon for thread email and load all the email in the thread in background. 

I fetch message from gmail and have an array of object MCOIMAPMessage. I check the "references" of MCOMessageHeader from MCOIMAPMessage.header

/** References field. It's an array of message-ids.*/
@property (nonatomic, copy) NSArray * /* NSString */ references;

If thread the "references" have some info as

message.header.references = (
    "CAH-THaOHPRJ=OZMrhZmFy=7s=sK4HC8TJ+a25UZ9fCcOdcVZ6g@mail.gmail.com",
    "CABK6ehzuV18YgoGJvd4Dabch95rmYFLrHhPp_NNvCYAJS0jrmg@mail.gmail.com",
    "CAH-THaPTJAK_QPQkexLgRO92DctjTtqexfdkXxQK0_g_oPexKQ@mail.gmail.com",
    "CABK6ehyFiQ4j8PmNNyg3bKOJNWS_JsF0BBpmZtGZH35kLFZukQ@mail.gmail.com",
    "CAH-THaPv0-RH-da2F5QH7oN21+jCDCRUYBUcH3Fi0mJJyCPoGQ@mail.gmail.com"
)

if single message it will be nil. 

Please help to correct or show me the proper way to identify between thread email vs single email.

It is great if we can get the info about how many email in the thread so that we can display the number as gmail app. 

Thanks,
Trong Vu

**Comment by dinhviethoa** [comment]
Could you post to stackoverflow instead? We'll answer here. Thanks!

**Comment by lukelan** [comment]
It is here http://stackoverflow.com/questions/30572139/mailcore2-distingue-between-thread-email-with-single-email-on-gmail

Thank you
