### ISSUE TITLE
Set htmlBodyRenderingOperationWithMessage formatting delegate?

### ISSUE THREAD

**Issue by AdamNSmith** [MailCore/mailcore2#1132]
I'm trying to download the content of a message without downloading it's attachments. I found the method:

```Objective-C
- (MCOIMAPMessageRenderingOperation *)htmlBodyRenderingOperationWithMessage:(MCOIMAPMessage *)message folder:(NSString *)folder
```
and this works okay to return the HTML string. The problem is that at the bottom of the HTML, the attachments are still listed. I would like to either remove the whole section from the HTML about the attachments or format the attachments section in the HTML (like you can using the `MCOHTMLRendererDelegate` methods if working with a `MCOMessageParser` object).

Is it possible to format the attachments section of the HTML rendered using the `htmlBodyRenderingOperationWithMessage:folder:` method?

If not, consider this a request to add this feature in.

**Comment by KieranMcGrady** [comment]
See issue #813

**Comment by AdamNSmith** [comment]
Correct me if I'm understanding this incorrectly, but that solution refers to loading HTML data that is cached offline. I need to be able to download only the message contents without the section at the bottom of the email about what attachments were sent with the email.

**Comment by AdamNSmith** [comment]
I ended up just `using htmlBodyRenderingOperationWithMessage:folder:` and then parsing the HTML string with `NSXMLDocument` to remove the section about attachments. It's not a pretty solution but it works.

**Comment by arehman-powerfulpal** [comment]
@AdamNSmith can you please paste code here. How you remove attachments section info from HTML Body String using NSXMLDocument ? Thanks in advance

**Comment by dinhviethoa** [comment]
You can also implement the delegate.

```
- (NSString *) MCOAbstractMessage:(MCOAbstractMessage *)msg templateForAttachment:(MCOAbstractPart *)part
{
  return @"";
}

- (NSString *) MCOAbstractMessage_templateForAttachmentSeparator:(MCOAbstractMessage *)msg
{
  return @"";
}
```

It should remove the attachments.
