### ISSUE TITLE
Android - build for lower API

### ISSUE THREAD

**Issue by DaveInAus** [MailCore/mailcore2#1134]
Anybody out there got time to build LibMailCore2 Library for a lower API on Android? (Current API-21)

API-16 would support Jellybean/KitKat and Lollipop catering for the bulk of Android devices. See below

![chart](https://cloud.githubusercontent.com/assets/10951821/7998938/f65eaece-0b86-11e5-9870-9d16a971f4d4.png)

I've built LibMailCore for API-16 but have issues with the 3rd party libraries that Hoa has provided as part of the build as these were also built for API-21

/Users/hoa/LibEtPan/libetpan/build-android/jni/../.././src/low-level/imf/mailimf_types_helper.c:1279: error: undefined reference to 'random'
/Users/hoa/LibEtPan/libetpan/build-android/jni/../.././src/low-level/mime/mailmime_types_helper.c:518: error: undefined reference to 'random'
/Volumes/MacAirExt/Android/MailCore2/build-android/third-party/openssl-android-1/libs/x86/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'signal'
/Users/dvh/Android/libxml2/build-android/jni/../../dict.c:186: error: undefined reference to 'rand_r'
/Users/dvh/Android/libxml2/build-android/jni/../../dict.c:205: error: undefined reference to 'rand_r'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

I've tried building LibEtPan but get unstuck on the libetpan-config file not being found - symbolic link

Would be great if someone has time for a challenge

**Comment by dinhviethoa** [comment]
Could you show the logs for the build of libetpan?

**Comment by DaveInAus** [comment]
can't find the file when performing the symbolic link for libetpab-config.h 
i.e. libetpan-config.h should be in the build-android folder 
for ln -s -f ../../././libetpan-config.h  after cd ./include/libetpan/

see below

./build.sh 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-apple-darwin14.3.0
checking host system type... x86_64-apple-darwin14.3.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking for inline... inline
checking for windres... no
checking for a sed that does not truncate output... /usr/bin/sed
./configure: line 5136: : command not found
checking how to print strings... printf
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-apple-darwin14.3.0 file names to x86_64-apple-darwin14.3.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin14.3.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm output from  object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin14.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin14.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for unistd.h... (cached) yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking for inttypes.h... (cached) yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking winsock2.h usability... no
checking winsock2.h presence... no
checking for winsock2.h... no
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... yes
checking for working mmap... yes
checking for connect... yes
checking for inet_ntoa... yes
checking for setenv... yes
checking for getopt_long... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for main in -lrsaref... no
checking for main in -lcrypto... yes
checking for SSL_library_init in -lssl... yes
checking iconv.h usability... yes
checking iconv.h presence... yes
checking for iconv.h... yes
checking checking iconv() prototype... ok
checking for iconv... found
checking db.h usability... yes
checking db.h presence... yes
checking for db.h... yes
checking version of Berkeley DB... version 1.x
checking for dbopen... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for pthread_create with libc... yes
checking for lockfile_create in -llockfile... no
checking sasl/sasl.h usability... yes
checking sasl/sasl.h presence... yes
checking for sasl/sasl.h... yes
checking for sasl_client_init in -lsasl2... yes
checking whether to use IPv6... maybe
checking for IPv6 support... yes
checking for getaddrinfo... yes
checking for freeaddrinfo... yes
checking zlib version... ok (1.2.0.4 or later)
checking for library containing zlibVersion... -lz
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating libetpan-config
config.status: creating Makefile
config.status: creating build-windows/Makefile
config.status: creating include/Makefile
config.status: creating src/Makefile
config.status: creating src/bsd/Makefile
config.status: creating src/windows/Makefile
config.status: creating src/data-types/Makefile
config.status: creating src/low-level/Makefile
config.status: creating src/low-level/feed/Makefile
config.status: creating src/low-level/imap/Makefile
config.status: creating src/low-level/imf/Makefile
config.status: creating src/low-level/maildir/Makefile
config.status: creating src/low-level/mbox/Makefile
config.status: creating src/low-level/mh/Makefile
config.status: creating src/low-level/mime/Makefile
config.status: creating src/low-level/nntp/Makefile
config.status: creating src/low-level/pop3/Makefile
config.status: creating src/low-level/smtp/Makefile
config.status: creating src/driver/Makefile
config.status: creating src/driver/implementation/Makefile
config.status: creating src/driver/implementation/data-message/Makefile
config.status: creating src/driver/implementation/db/Makefile
config.status: creating src/driver/implementation/feed/Makefile
config.status: creating src/driver/implementation/hotmail/Makefile
config.status: creating src/driver/implementation/imap/Makefile
config.status: creating src/driver/implementation/maildir/Makefile
config.status: creating src/driver/implementation/mbox/Makefile
config.status: creating src/driver/implementation/mh/Makefile
config.status: creating src/driver/implementation/mime-message/Makefile
config.status: creating src/driver/implementation/nntp/Makefile
config.status: creating src/driver/implementation/pop3/Makefile
config.status: creating src/driver/interface/Makefile
config.status: creating src/driver/tools/Makefile
config.status: creating src/main/Makefile
config.status: creating src/main/libetpan_version.h
config.status: creating src/engine/Makefile
config.status: creating src/versioninfo.rc
config.status: creating doc/Makefile
config.status: creating tests/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
sed: ./ltmain.sh: No such file or directory
sed: libtoolT: No such file or directory
/bin/sh /Volumes/MacAirExt/Android/libetpan/install-sh -d ./include/libetpan/
cd ./include/libetpan/
ln -s -f ../../././libetpan-config.h .
cp: include/libetpan/libetpan-config.h: No such file or directory
cp: include/libetpan/libetpan-config.h: No such file or directory
[armeabi] Compile thumb  : etpan <= base64.c
In file included from /Volumes/MacAirExt/Android/libetpan/build-android/jni/../.././src/data-types/base64.c:36:0:
/Volumes/MacAirExt/Android/libetpan/build-android/jni/../.././src/data-types/base64.h:44:30: fatal error: libetpan-config.h: No such file or directory
 # include "libetpan-config.h"
                              ^
compilation terminated.
make: *** [/Volumes/MacAirExt/Android/libetpan/build-android/obj/local/armeabi/objs/etpan/__/__/./src/data-types/base64.o] Error 1
cp: /Volumes/MacAirExt/Android/libetpan/build-android/obj/local/armeabi/libetpan.a: No such file or directory
[armeabi-v7a] Compile thumb  : etpan <= base64.c
In file included from /Volumes/MacAirExt/Android/libetpan/build-android/jni/../.././src/data-types/base64.c:36:0:
/Volumes/MacAirExt/Android/libetpan/build-android/jni/../.././src/data-types/base64.h:44:30: fatal error: libetpan-config.h: No such file or directory
 # include "libetpan-config.h"
                              ^
compilation terminated.
make: *** [/Volumes/MacAirExt/Android/libetpan/build-android/obj/local/armeabi-v7a/objs/etpan/__/__/./src/data-types/base64.o] Error 1
cp: /Volumes/MacAirExt/Android/libetpan/build-android/obj/local/armeabi-v7a/libetpan.a: No such file or directory
[x86] Compile        : etpan <= base64.c
In file included from /Volumes/MacAirExt/Android/libetpan/build-android/jni/../.././src/data-types/base64.c:36:0:
/Volumes/MacAirExt/Android/libetpan/build-android/jni/../.././src/data-types/base64.h:44:30: fatal error: libetpan-config.h: No such file or directory
 # include "libetpan-config.h"
                              ^
compilation terminated.
make: *** [/Volumes/MacAirExt/Android/libetpan/build-android/obj/local/x86/objs/etpan/__/__/./src/data-types/base64.o] Error 1
cp: /Volumes/MacAirExt/Android/libetpan/build-android/obj/local/x86/libetpan.a: No such file or directory
[x86_64] Compile        : etpan <= base64.c
In file included from /Volumes/MacAirExt/Android/libetpan/build-android/jni/../.././src/data-types/base64.c:36:0:
/Volumes/MacAirExt/Android/libetpan/build-android/jni/../.././src/data-types/base64.h:44:30: fatal error: libetpan-config.h: No such file or directory
 # include "libetpan-config.h"
                              ^
compilation terminated.
make: *** [/Volumes/MacAirExt/Android/libetpan/build-android/obj/local/x86_64/objs/etpan/__/__/./src/data-types/base64.o] Error 1
cp: /Volumes/MacAirExt/Android/libetpan/build-android/obj/local/x86_64/libetpan.

**Comment by dinhviethoa** [comment]
Could you install libtool (for example, using homebrew) and then retry?

**Comment by DaveInAus** [comment]
yep did that i.e. libtoolize?

**Comment by dinhviethoa** [comment]
Could you let me know if autogen.sh shows any error for you?

**Comment by DaveInAus** [comment]
Yep - get the following errors

**Error**: You must have `aclocal' installed to compile libetpan-master.
Download the appropriate package for your distribution,
or get the source tarball at ftp://ftp.gnu.org/pub/gnu/

**Error**: You must have `autoconf' installed to compile libetpan-master.
Download the appropriate package for your distribution,
or get the source tarball at ftp://ftp.gnu.org/pub/gnu/

Installed automake and autoconf

Only have linking errors now on openssl and libxml2 - will give that a go
today

*/Volumes/MacAirExt/MailCore2/build-android/third-party/openssl-android-1/libs/x86/libcrypto.a(ui_openssl.o):ui_openssl.c:function
read_string_inner: error: undefined reference to 'signal'*
*/Users/dvh/Android/libxml2/build-android/jni/../../dict.c:186: error:
undefined reference to 'rand_r'*
*/Users/dvh/Android/libxml2/build-android/jni/../../dict.c:205: error:
undefined reference to 'rand_r'*

**Comment by triton3** [comment]
@DaveInAus How did you resolve "libetpan-config.h not found" error? I installed automake, autoconf and libtool but it still shows this error. Any suggestions?

**Comment by DaveInAus** [comment]
@triton3 I've been rebuilding and have the same issue - had to revert to earlier release - will provide update shortly

**Comment by dinhviethoa** [comment]
Fixed.
