### ISSUE TITLE
how to update mail box at real time?

### ISSUE THREAD

**Issue by PrabakarMP** [MailCore/mailcore2#1136]
Hi,

I have integrated Mailcore iOS in my iOS application and using it for accessing IMAP mails. I am also getting all the mail folders and showing them in slide menu. I have attached screenshot for reference. My issue now is, I need to update the mail box now based on user selection of the folder from this slide menu. For ex: By default, Inbox mails will be in the mail box. If user chooses Sent items from the slide menu, then i need to update the mail box at the real time to pull Sent item mails and display it. I know if i change folder to "Sent Item" in "loadLastNMessages()" function, it will pull sent item mails. My issue is, how can i update this on the fly from slide menu view controller ? I tried calling, "loadLastNMessages()" function or startLogin()" function from slide menu view controller, but it is crashing while loading. What is the best way to update mail box for corresponding mail folder selected?

![img_2703](https://cloud.githubusercontent.com/assets/1001894/8030082/5cee0caa-0de1-11e5-9712-2391333b9f3a.PNG)

**Comment by dinhviethoa** [comment]
Please ask on stackoverflow.
