### ISSUE TITLE
Sign Out feature MailCore 2 iOS IMAP

### ISSUE THREAD

**Issue by PrabakarMP** [MailCore/mailcore2#1138]
I am using MailCore 2 iOS IMAP source to have IMAP mail access. I added mail folder list etc. features in that. I want to provide "Sign Out" feature for any imap mail that logged-in. Could anyone advise me, how to clear the existing login session and do sign out successfully?
Here is the stackoverflow query of the same:- https://stackoverflow.com/questions/30739193/sign-out-feature-mailcore-2-ios-imap

Thanks in advance.

**Comment by KieranMcGrady** [comment]
I've answered on SO as it seems more appropriate.

**Comment by dinhviethoa** [comment]
Thanks @KieranMcGrady!

**Comment by thanhlazio** [comment]
@dinhviethoa -  "disconnectOperation" can not disconnect current session

```
let logout = imapSession.disconnectOperation()
 logout?.start({ (error) in
        if let error = error {
            log(error.localizedDescription)
             return
        }            
        _ = self.navigationController?.popToRootViewController(animated: true)
})
```

When re-login with another account, I can't get new inbox.
