### ISSUE TITLE
Error after set "deleted" flag

### ISSUE THREAD

**Issue by gsantome** [MailCore/mailcore2#1141]
Hello, When I added the new flag MCOMessageFlagDeleted to my mail everything was perfect.... but the expungeOperation execute an operation where my idle operation listen that. So my idle operation got the email but the flag of that email is Seen and not Deleted.

this is how im adding Deleted flag

````
MCOIMAPOperation *op = [self.deleteSession storeFlagsOperationWithFolder:@"INBOX"
                                                             uids:[MCOIndexSet indexSetWithIndex:uid]
                                                             kind:MCOIMAPStoreFlagsRequestKindAdd
                                                            flags:MCOMessageFlagDeleted];
    
    [op start:^(NSError * error) {
        if(!error) {
            NSLog(@"Updated flags!");
        } else {
            NSLog(@"Error updating flags:%@", error);
        }
        
        
        MCOIMAPOperation *deleteOp = [self.deleteSession expungeOperation:@"INBOX"];
        [deleteOp start:^(NSError *error) {
            if(error) {
                NSLog(@"Error expunging folder:%@", error);
            } else {
                NSLog(@"Successfully expunged folder");
            }
        }];
    }];
````

I need some help with this.

Thanks

**Comment by gsantome** [comment]
Another problem that im seeing is before change the flag and expunge I'm saving the message information like UID, SequenceNumber, ModSeqNumber, GmailMessageId, so when I execute expungeOperation my idleOperation start and I'm getting a new email. and that email have every id different of what I had before. Can you explain me how this is possible?

Thanks

**Comment by dinhviethoa** [comment]
Did you interrupt your idle operation before changing the flags?

**Comment by gsantome** [comment]
nop... the idle operation is always working... i need to interrupt the idle before the change? btw when I add the Flag "Seen" the idle operation didn't watch that change. its only with expunge operation.

**Comment by dinhviethoa** [comment]
Yes. You need to interrupt the idle operation.

**Comment by gsantome** [comment]
ok perfect I will do that... but do you know why gmail a is changing the iud of that email? 

Thanks for your help

**Comment by dinhviethoa** [comment]
Do you get a different UID in an other folder? It's an expected behavior.

**Comment by gsantome** [comment]
oh right because the message now is on Trash folder, thanks for your help!
