### ISSUE TITLE
Performance & memory issue in String::htmlMessageContent

### ISSUE THREAD

**Issue by tomandersen** [MailCore/mailcore2#1143]
String::htmlMessageContent calls str->componentsSeparatedByString(MCSTR("\n"))

On a 38 MB email, with 500,000 lines, the entire 38 MB string is duplicated 500,000 times, all in the function u_strstr() Tested on a Mac. 

The process uses about 1.2 GB of temporary memory, and takes 10 minutes to read in on my Mac.

Essentially its an N**2 problem on u_strstr.

![screen shot 2015-06-16 at 10 29 10 am](https://cloud.githubusercontent.com/assets/221405/8185452/8c957c40-1412-11e5-966d-ee969a6fd4a8.png)

One way to fix would be to create a new call on String that is optimized for the common "\n", " " calls

Array * String::componentsSeparatedByANSIString(UChar * separator) {
...
..
location = memem() or some other call that just dives through looking for 

}

The problem is that the current implantation, which uses CFStrings is nice in that it works for any strings, but it creates a full copy of the entire string for every CFStringFind(), and turns itself into an N**2 issue.

**Comment by dinhviethoa** [comment]
Would you feel comfortable sending a pull request with a new implementation of u_strstr()?
memmem() would work to implement u_strstr() and we could just check that the result is on a even index.

**Comment by dinhviethoa** [comment]
Fixed with bf9061a79c7f0ee52cc781ca356a4e273a641270.
