### ISSUE TITLE
Problem about “Undisclosed recipients:” when save draft mail without To, Cc, Bcc

### ISSUE THREAD

**Issue by JoeTotee** [MailCore/mailcore2#1144]
Hi,

I have trouble with saving draft without To, Cc, Bcc to Gmail via mailcore2. MCOMessageBuilder.data automatically adds an empty group, “Undisclosed recipients:”, to To field. When I open this draft on Gmail webmail, it shows invalid “Undisclosed recipients:” in To field.

However, when I try to save empty To, Cc ,Bcc on Gmail webmail, then open on my iOS app, it shows empty To field.

I investigated “Undisclosed recipients:” on Gmail, Outlook and Yahoo and found that when save draft, they do not add “Undisclosed recipients:” empty group into To field of draft mail. Should “Undisclosed recipients:” empty group be automatically added when sending mail only, not when saving draft?

**Comment by dinhviethoa** [comment]
Would you feel comfortable and send a pull request to implement it?
There's already a similar functionality:
dataAndFilterBccAndForEncryption()
"FilterBcc" might also not add the "undisclosed-recipient" group.
And we could rename "FilterBcc" to "ForDraft".

**Comment by dinhviethoa** [comment]
Fixed with https://github.com/MailCore/mailcore2/commit/4b3ee932f60b6dc15116127f93e3471b74876d62
