### ISSUE TITLE
mIdleEnabled and mCanIdle in MCIMAPSession.cpp

### ISSUE THREAD

**Issue by yuklai** [MailCore/mailcore2#1145]
Both seem to mean the same thing. Why are there two of them?
Also why is semaphore used while setting `mCanIdle` but not `mIdleEnabled` (or any of the other capabilities for that matter)?

See `capabilitySetWithSessionState` and `applyCapabilities`

**Comment by CodaFi** [comment]
Fixed by the merge of #1384

Thanks for reporting this!
