### ISSUE TITLE
How to set clientIdentity in MCOIMAPSession?

### ISSUE THREAD

**Issue by finian** [MailCore/mailcore2#1150]
Since `clientIdentity` is readonly in `MCOIMAPSession`, it seems that we have no way to set this property. So the default ID command (after LOGIN command) will always be `ID NIL`. Is it appropriate to change the `clientIdentity` property to writable?

**Comment by dinhviethoa** [comment]
the content of clientIdentity content can be modified.
Also, I should investigate changing the property to writable :)

**Comment by finian** [comment]
Oh you are right, the content of `clientIdentity` can be changed...I thought there was no way to change the values. My misunderstanding.

**Comment by frankobe** [comment]
Hi, just wonder whether clientIdentity is writable now?

**Comment by dinhviethoa** [comment]
The content can be changed. Does it help?

**Comment by frankobe** [comment]
I am testing it because some email providers require special clientIdentity.

**Comment by dinhviethoa** [comment]
[[session clientIdentity] setName:], etc.

**Comment by frankobe** [comment]
Hi I change clientidentity as follows, I notice that for email provider 163.com, there is a default identity in log as follows,
 
2015-09-30 14:37:11.960 MailTime[5159:1803428] XXX:  event logged:0x137b653b0 1 withData: C5 ID ("contact" "support@mailtime.com" "os-version" "8.1" "os" "iOS" "version" "2.0.0" "name" "MailTime" "vendor" "Mobile Internet Limited")

2015-09-30 14:40:10.579 MailTime[5159:1803428] XXX:  event logged:0x137b653b0 0 withData: * ID ("name" "Coremail Imap" "vendor" "Mailtech" "TransID" "Mk6XLgBHDCzcVQxW")

C5 OK ID completed

So why does "Coremail Imap" appear?

**Comment by dinhviethoa** [comment]
That's the server identity.
