### ISSUE TITLE
What exactly does session.disconnectOperation? It seems that it does not work.

### ISSUE THREAD

**Issue by av08ovur** [MailCore/mailcore2#1153]
Example Code:

    func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        let cell = mailTableView.cellForRowAtIndexPath(indexPath) as! CustomMailTableViewCell
            session.disconnectOperation().start({ (error) -> Void in
                if error != nil {
                    NSLog("%@", error!.description)
                }else {
                    NSLog("disconnect")
                
                let setDeleteFlagOP = session.storeFlagsOperationWithFolder("INBOX", uids: MCOIndexSet(index: UInt64((cell.mail.mcomessage as! MCOIMAPMessage).uid)), kind: MCOIMAPStoreFlagsRequestKind.Add, flags: MCOMessageFlag.Deleted)
                
                setDeleteFlagOP.start({ (error) -> Void in
                    if let error = error {
                        NSLog("error in deleting email: \(error.userInfo)")
                    } else {
                        NSLog("email deleted")
                        
                        let expangeFolder = session.expungeOperation("INBOX")
                        expangeFolder.start({ (error) -> Void in })
                    }
                })
            })
        }
    }

I have a normal TableView. In a cell an email is saved.
What i get when i tap a cell:
disconnected
email deleted

So the email got deleted although the session is disconnected. 
In my Opinion setDeleteFlagOP should fail because there is no session anymore.

btw: Ich need the disconnect Operation in another method to prevent the "too many simultaneous connections" error.

**Comment by dinhviethoa** [comment]
Any operation that needs an IMAP connection will reconnect on demand.
See IMAPSession.connectionLogger to check on the behavior of disconnectOperation.
