### ISSUE TITLE
MoveTo and Delete email using Mailcore2

### ISSUE THREAD

**Issue by PrabakarMP** [MailCore/mailcore2#1155]
Hi,

In my iOS project, I integrated mailcore2.
Question is, how to implement "MoveTo" and "Delete" mail from Email Account? how to implement that?

I am able to do Reply, ReplyAll and Forward features successfully using _message.header.replyTo, _message.header.to, _message.header.subject and appDelegate.mailBodyMessage.

Please help.

SO: http://stackoverflow.com/questions/31082280/moveto-and-delete-email-using-mailcore2

**Comment by KieranMcGrady** [comment]
I suggest searching closed issues and looking at the wiki as this has been asked and answered (with code samples) many times.
