### ISSUE TITLE
Attachment support in Mailcore2 iOS

### ISSUE THREAD

**Issue by PrabakarMP** [MailCore/mailcore2#1156]
In my iOS project, I integrated mailcore2. I am able to send, reply emails without any issues. I am able to do composing new email as well.

I don't know how to support multiple format attachments when forwarding an email? If an email does contain .docx, .xls files, then mailcore2 doesn't have support. I could have only images be supported and forwarded.

Can someone please suggest me how can i make support for other than image formats (video files, document, excel files..) for forwarding email using Mailcore2 iOS library?

SO:
http://stackoverflow.com/questions/31102810/attachment-support-in-mailcore2-ios

**Comment by KieranMcGrady** [comment]
You should be able to attach anything. You need to create an ```MCOAttachment``` and then add the attachment to the message builder:

```
MCOAttachment *att = [MCOAttachment attachmentWithData:[NSData dataWithContentsOfURL:url] filename:filename];
[messageBuilder addAttachment:att];
```
