### ISSUE TITLE
Reordering Mailcore2 mail folders

### ISSUE THREAD

**Issue by PrabakarMP** [MailCore/mailcore2#1157]
In my iOS project, I integrated mailcore2. I am able to get many features working viewing email, reply email, attach images etc.

I am also getting list of folders from the following code. I want to reorder the standard folders list starting from inbox, sent items, draft, Outbox, Trash and goes on to the last.

NSMutableArray *folderarray = [[NSMutableArray alloc] init];
[[self.imapSession fetchAllFoldersOperation] start:^(NSError *error, NSArray *folders) {
    NSMutableString *folderDetails = [NSMutableString new];
    for (MCOIMAPFolder *fdr in folders) {

        [folderDetails appendFormat:@"\nFolder[%@], flag : %d", fdr.path, fdr.flags];
        [folderarray addObject:fdr.path];
    }
    NSLog(@"Folder Details: %@", folderDetails);
    if (folderarray!=nil) {
        [folderList setAllFolders:folderarray];
        AppDelegate *appDelegate = [UIApplication sharedApplication].delegate;
        [appDelegate.leftMenu reloadTable];
    }
}];
I am not getting how to reorder/arrange the folders list?

**Comment by KieranMcGrady** [comment]
This doesn't seem specific to Mailcore. Unless I'm mistaken you just want reorder an NSArray. If you're having trouble with that try Stackoverflow. There are many ways to do it and it depends on your needs (specific order, alphabetical order etc.). But the gist is if you know the names of the folders and the order you want them in just create a temp array and move the folders from the folder list to that one at a time.

**Comment by dinhviethoa** [comment]
Yep. Not specific to MailCore. Closing.
