### ISSUE TITLE
fetch From: To: clean String

### ISSUE THREAD

**Issue by sundsx** [MailCore/mailcore2#1159]
I am new to mailcore and This is a challenge for me, but it's very important for my project.
 So Help Please... My problem is to representing text in tableview cell in clean way, due to "mailcore::Address:0x61000002cc00": 
How i can remove unwanted (mailcore::Address:0x61000002cc00 ) from fetch?.
 ex:

       - (NSView *)tableView:(NSTableView *)tableView viewForTableColumn:(NSTableColumn  *)tableColumn row:(NSInteger)row
         {
       NSTableCellView *result = [tableView makeViewWithIdentifier:tableColumn.identifier owner:self];
    
        MCOIMAPMessage * msg = [_msgsContainer objectAtIndex:row];
    
        if( [[tableColumn identifier] isEqual:@"MainCell"] ) {
        NSLog(@"FIND MainCell");
        
         NSLog(@"FROM %@", msg.header.sender);
         NSLog(@"TO %@", msg.header.to);
        NSLog(@"header.from TV: %@", [[_msgsContainer   valueForKeyPath:@"header.from"]objectAtIndex:row]);
        
        NSImage *iconEmail = [NSImage imageNamed:@"ol_unread_20.tiff"];
        [result.textField setTextColor:[NSColor blackColor]];
        [result.textField setStringValue:[NSString stringWithFormat:@"%@", [[msg header] subject]]];
        [result.imageView setImage:iconEmail];
        return result; 
         }
          return result;
        }
        OTPUT:
        FROM mailcore::Address:0x61000002cc00 Il team di Gmail <mail-noreply@google.com>
        2015-07-02 11:55:06.752 SciabolaDB[1439:53599] 
        TO ("mailcore::Address:0x61000002d060 sandro Pexxx <cloudsxxxx@gmail.com>"

**Comment by deltadavid** [comment]
If I understand you correctly, you just need to replace @header.from:

NSLog(@"header.from TV: %@", [[_msgsContainer   valueForKeyPath:@"header.from"]objectAtIndex:row]);

with header.from.displayName or header.from.mailbox

http://libmailcore.com/mailcore2/api/Classes/MCOAddress.html

Also: this is not an issue.

**Comment by sundsx** [comment]
Thank You!
