### ISSUE TITLE
Listing of email addresses in compose field

### ISSUE THREAD

**Issue by PrabakarMP** [MailCore/mailcore2#1162]
I am using Mailcore2 in my iOS project. I want to know how to populate the listing of email addresses when typing text in compose field ? Does Mailcore2 has any API to retrieve email addresses when typing text in compose field. I am supporting IMAP accounts like gmail and yahoo, wants to implement listing down email addresses when typing text in compose field.
 
Please advise!

**Comment by KieranMcGrady** [comment]
Look at issue #418. There is no IMAP solution for this. Integrate with specific email providers API's or use the local contacts via the iOS Address Book API.

**Comment by PrabakarMP** [comment]
Oh ok, thank you so much..Will do that.
