### ISSUE TITLE
Viewing Email in Offline is not happening

### ISSUE THREAD

**Issue by PrabakarMP** [MailCore/mailcore2#1163]
Hi,

SO:
http://stackoverflow.com/questions/31245549/mailcore2-viewing-email-content-is-empty-in-offline

I am able to store MCOIMAPMessage in persistent storage to use when device is not having internet. I am able to display the listing of emails table view. Now, When I open any email, it should open with the relevant content even when the device is in offline. But, it is not showing the email content when the iPhone is not having internet connection.  

I am setting the required properties properly in here, even when the device is offline,

Masterviewcontroller.m:

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
	
	switch (indexPath.section)
	{
		case 0:
		{
			MCOIMAPMessage *msg = self.messages[indexPath.row];
            //selectedMessage = self.messages[indexPath.row];

            // Setting email flag as READ status
            MCOIMAPOperation *op = [self.imapSession storeFlagsOperationWithFolder:folderList.selectedFolder
                                                                     uids:[MCOIndexSet indexSetWithIndex:msg.uid]
                                                                     kind:MCOIMAPStoreFlagsRequestKindAdd
                                                                    flags:MCOMessageFlagSeen];
            [op start:^(NSError *error) {
                if (!error) {
                    NSLog(@"Updated flags");
                } else {
                    NSLog(@"Error updating flags: %@", error);
                }
            }];
            
			MCTMsgViewController *vc = [[MCTMsgViewController alloc] init];
			//vc.folder = @"INBOX";
            vc.folder = folderList.selectedFolder;
			vc.message = msg;
			vc.session = self.imapSession;
			[self.navigationController pushViewController:vc animated:YES];
			
			break;
		}

and in MCOMessageView.mm, it has been using "htmlRenderingWithFolder"

- (void) _refresh
{
    NSString * content;
    
    if (_message == nil) {
        content = nil;
    }
    else {
        if ([_message isKindOfClass:[MCOIMAPMessage class]]) {
            content = [(MCOIMAPMessage *) _message htmlRenderingWithFolder:_folder delegate:self];
            
            AppDelegate *appDelegate = [UIApplication sharedApplication].delegate;
            appDelegate.mailBodyMessage = content;
        }
        else if ([_message isKindOfClass:[MCOMessageBuilder class]]) {
            content = [(MCOMessageBuilder *) _message htmlRenderingWithDelegate:self];
        }
        else if ([_message isKindOfClass:[MCOMessageParser class]]) {
            content = [(MCOMessageParser *) _message htmlRenderingWithDelegate:self];
        }
        else {
            content = nil;
            MCAssert(0);
        }
    }
	if (content == nil) {
		[_webView loadHTMLString:@"" baseURL:nil];
		return;
	}
	
	NSMutableString * html = [NSMutableString string];
    [html appendFormat:@"<html><head><script>%@</script><style>%@</style></head>"
        @"<body>%@</body><iframe src='x-mailcore-msgviewloaded:' style='width: 0px; height: 0px; border: none;'>"
        @"</iframe></html>", mainJavascript, mainStyle, content];
	[_webView loadHTMLString:html baseURL:nil];
}

But, Content of any email shows empty here when opening an email from Masterviewcontroller.m.

Please correct me what I have to do properly here for displaying Email content even when the device is in offline mode.

SO:
http://stackoverflow.com/questions/31245549/mailcore2-viewing-email-content-is-empty-in-offline

**Comment by PrabakarMP** [comment]
Finally I fixed this viewing mails in offline state. –  user1953977 just now   edit

**Comment by dinhviethoa** [comment]
Great to see that you're making progress on your app.
Please don't post here every small issues you're having with your app.
Do some investigation and if you find out that it's a bug in mailcore, post it here.
If you don't know how to do something after a week of investigation, please post on stackoverflow.

**Comment by PrabakarMP** [comment]
I understand. But for me they were being big issues, i try my best and posting it. Anyways thanks.
