### ISSUE TITLE
iPhone: Attaching a Folder does NOT zip it on the device but does on the simulator

### ISSUE THREAD

**Issue by juliangsp** [MailCore/mailcore2#1164]
iPhone 6 & 6 Plus - iOS v8.3 and 8.4; obtaining code from Cocoapod:

When trying to attach a directory/folder using:
MCOAttachment *attachFolder = [MCOAttachment attachmentWithContentsOfFile:path];

on the simulator it does compress/zip the folder (everything works fine) but on the actual iPhone device the attachmentWithContentsOfFile: method returns nil, and there for it is not able to compress the folder.

If I attach just a file (not a folder to be compressed) it works fine on both: iPhone and the simulator.

**Comment by juliangsp** [comment]
The problem seems to be that on the iPhone the method "mailcore::CreateTemporaryZipFileFromFolder" (@ MCZip.cpp) is trying to create a directory /tmp/mailcore2-XXXXXX which it's fine on the simulator (OS X) but iOS on the phone does not allow it.

**Comment by dinhviethoa** [comment]
I think we would need to create a MCZipMac.mm, create a function mailcore::String * mailcore::TemporaryDirectoryForZip(); and use NSTemporaryFolder() to implement it.
then, use this function in CreateTemporaryZipFileFromFolder() in the case of the iOS/Mac.

Let me know if you'd like to create a pull request to fix it.

**Comment by juliangsp** [comment]
Yes, sure I'll like to do a pull request for the fix. Can I create a branch instead of forking the whole repo?

**Comment by dinhviethoa** [comment]
I think you have to fork the whole repo per github rulese.

**Comment by juliangsp** [comment]
I forked and uploaded a fix, but for now it only works for the osx and ios targets since it's mixing Objective-C and C++ code. I don't have an idea on how to best have this code be separated for when compiling for other platforms.

What would you do, dinhviethoa?

You can have a look at the code at my forked repo in branch '#1164_issue_fix_iosmac ' at:
https://github.com/juliangsp/mailcore2/tree/%231164_issue_fix_iosmac

**Comment by dinhviethoa** [comment]
Added comments on your commit.

**Comment by juliangsp** [comment]
New commit after your review:
https://github.com/juliangsp/mailcore2/commit/b1b7587fe8acccbfe46fe59186ec6f383f6d91a6
