### ISSUE TITLE
Language 

### ISSUE THREAD

**Issue by aallard** [MailCore/mailcore2#1166]
When receiving an email, is there a way in MailCore to retrieve a language ID value from the email header information?  I've been reading through RFCs (such as 3282) that define things such as a "Content-language" header attribute.   This led to a couple of questions:

1. Based on your experience, do you have any idea how common the "Content-language" attributes are set in email message headers?

2. I'm assuming I would use the "extraHeaderValueForName" method in the MCOMessageHeader class to retrieve these if they exist.

**Comment by dinhviethoa** [comment]
1. This header is generally NEVER set.
2. Yep. That said, on IMAP, you have to do some extra work to fetch this header.
