### ISSUE TITLE
How can i get MCOMessageFlag when i use MCOIMAPSearchOperation ?

### ISSUE THREAD

**Issue by huapeng222** [MailCore/mailcore2#1168]
well, Now I have get  MCOMessageParser, but i don,t  know  the  attributes of MCOMessageFlag, what should I do next ?

MCOIMAPSearchOperation * op = [[RYMailLogin sharedManager].imapSession searchOperationWithFolder:selectFolder kind:MCOIMAPSearchKindFrom|MCOIMAPSearchKindTo|MCOIMAPSearchKindCc|MCOIMAPSearchKindSubject searchString:searchBar.text];
    [op start:^(NSError * error, MCOIndexSet * searchResult) {

        if (!error) {
            
            if (!searchArray) {
                searchArray=[NSMutableArray new];
            }else{
                [searchArray removeAllObjects];
            }
            
            [searchResult enumerateIndexes:^(uint64_t idx) {
                MCOIMAPFetchContentOperation *content = [[RYMailLogin sharedManager].imapSession fetchMessageOperationWithFolder:selectFolder uid:(uint32_t)idx];
                [content start:^(NSError *error, NSData *data) {
                    MCOMessageParser *message = [[MCOMessageParser alloc] initWithData:data];
                    
                    MCOIMAPMessage *newMessage=[[MCOIMAPMessage alloc] init];
                    newMessage.header=absMessage.header;
                    newMessage.uid=(uint32_t)idx;
                    newMessage.mainPart=message.mainPart;
                    

                    
                }];
            }];
            
        }
        

    }];

**Comment by dinhviethoa** [comment]
You have to get the flags through a fetchMessagesOperation.
