### ISSUE TITLE
Mailcore2 GTMOAuth2 accessToken invalid after 60 minutes and can't refresh

### ISSUE THREAD

**Issue by AdamNSmith** [MailCore/mailcore2#1170]
I'm working on an email client for Mac that uses MailCore2. I'm also supporting OAuth2 for gmail accounts using Googles GTMOAuth2 library. I can successfully authenticate using GTMOAuth2 and use the access token to validate a MCOIMAPSession like so:

    [imapSession setAuthType:MCOAuthTypeXOAuth2];
    [imapSession setOAuth2Token:utilities.OAuthToken];

the problem is that after 60 minutes the access token becomes invalid and I can't figure out how to get a new one. When my program first starts I use this code to get the access token from the keychain:

    GTMOAuth2Authentication *auth = [GTMOAuth2WindowController authForGoogleFromKeychainForName:keychainItemName clientID:kClientID clientSecret:kClientSecret];  
    if([auth canAuthorize]) [auth beginTokenFetchWithDelegate:self didFinishSelector:@selector(auth:finishedRefreshWithFetcher:error:)];

and this works fine, but after 60 minutes if I try to get a new (refreshed) access token using `authForGoogleFromKeychainForName:` I get an invalid access token that when used with an MCOIMAPSession, the session errors with "Unable to authenticate with the current session's credentials."

I'm implementing GTMOAuth2 the way the MailCore2 docs say to (https://github.com/MailCore/mailcore2/wiki/Implementing-OAuth-2.0) so I'm guessing there is a way to refresh the access token on an MCOIMAPSession although the docs don't say how to.

Using GTMOAuth2, how are you supposed to get a refreshed access token to use with a MCOIMAPSession? 

Thanks! :)

**Comment by dinhviethoa** [comment]
An issue with the token would show an authentication error, not a connection error.
The connection logger will probably help you investigate.

**Comment by AdamNSmith** [comment]
I accidently pasted the wrong error message in the original post. I have updated the original post with the correct error which is: "Unable to authenticate with the current session's credentials."

**Comment by AdamNSmith** [comment]
Ok, I figured it out. For anyone having this problem in the future just use `authorizeRequest:delegate:didFinishSelector:` and pass nil for the request parameter to force it to get a new access token. 

From the source code:

```
// Main authorization entry points
//
// These will refresh the access token, if necessary, add the access token to
// the request, then invoke the callback.
//
---------->// The request argument may be nil to just force a refresh of the access token,
// if needed.
//
// NOTE: To avoid accidental leaks of bearer tokens, the request must
// be for a URL with the scheme https unless the shouldAuthorizeAllRequests
// property is set.

// The finish selector should have a signature matching
//   - (void)authentication:(GTMOAuth2Authentication *)auth
//                  request:(NSMutableURLRequest *)request
//        finishedWithError:(NSError *)error;

- (void)authorizeRequest:(NSMutableURLRequest *)request
                delegate:(id)delegate
       didFinishSelector:(SEL)sel;

```

**Comment by dinhviethoa** [comment]
Thanks for the update! Definitively not a mailcore2 issue ;)

**Comment by manthan-desai** [comment]
Hello

I tried the same, called auth?.authorizeRequest(nil, completionHandler: { (error) in
