### ISSUE TITLE
andorid cann't find MCOIMAPNamespacePersonal

### ISSUE THREAD

**Issue by fisherdev** [MailCore/mailcore2#1173]
```
- (void)loadFolders{
     MCOIMAPFetchNamespaceOperation *namespaceOp = [_session fetchNamespaceOperation];
     [namespaceOp start:^(NSError *error, NSDictionary * namespaces) {
         MCOIMAPNamespace * namespace = [namespaces objectForKey:MCOIMAPNamespacePersonal];
         MCOIMAPFetchFoldersOperation * op = [_session fetchAllFoldersOperation];
         [_session setDefaultNamespace:namespace];
         [op start:^(NSError * error, NSArray * folders) {
             for (MCOIMAPFolder *folder in folders) {
                 NSLog(@"%@", [[_session defaultNamespace] componentsFromPath:folder.path]);
             }
         }];
     }];
 }
```

JNI DETECTED ERROR IN APPLICATION: JNI NewString called with pending exception 'java.lang.NoSuchMethodError' thrown in java.util.Map com.libmailcore.IMAPFetchNamespaceOperation.namespaces():-2
07-13 05:15:19.874  31463-31463/com.fisher.demo A/art﹕ art/runtime/check_jni.cc:65]     in call to NewString
07-13 05:15:19.874  31463-31463/com.fisher.demo A/art﹕ art/runtime/check_jni.cc:65]     from java.util.Map com.libmailcore.IMAPFetchNamespaceOperation.namespaces()

**Comment by dinhviethoa** [comment]
I don't get it. You're showing Obj-C code and you're saying that it's running on Android.

**Comment by fisherdev** [comment]
sorry, when I use   IMAPFetchNamespaceOperation.namespaces().get(MCOIMAPNamespacePersonal) has crash  on android.

 final IMAPFetchFoldersOperation fetchFoldersOperation = MessagesSyncManager.singleton().session.fetchAllFoldersOperation();

        IMAPFetchNamespaceOperation fetchNamespaceOperation = MessagesSyncManager.singleton().session.fetchNamespaceOperation();
        IMAPNamespace namespace =  fetchNamespaceOperation.namespaces().get("IMAPNamespacePersonal");
        MessagesSyncManager.singleton().session.setDefaultNamespace(namespace);

                fetchFoldersOperation.start(new OperationCallback() {
                    @Override
                    public void succeeded() {

                        List<IMAPFolder> list = fetchFoldersOperation.folders();
                        for (int i = 0; i < list.size(); i++) {
                            System.out.println("folder========" + list.get(i).path());
                        }
                    }

                    @Override
                    public void failed(MailException e) {

                    }
                });

**Comment by dinhviethoa** [comment]
Does fetchNamespaceOperation.namespaces() crash or fetchNamespaceOperation.namespaces().get() crash?

**Comment by dinhviethoa** [comment]
It's probably fixed now.
