### ISSUE TITLE
Is it possible to compile mailcore2 dll/lib use Qt for Windows or Mac osx?

### ISSUE THREAD

**Issue by elvasiu0317** [MailCore/mailcore2#1174]
I want to use mailcore2 dll/lib in my application developed by Qt on Windows and Mac OSX. But I don't know how to compile the dll/lib using QtCreator. Is it possible do that?

**Comment by dinhviethoa** [comment]
It's not an issue with MailCore2.
I don't know the answer of that question anyway. You'd better ask on stackoverflow.
