### ISSUE TITLE
How can I create/modify an imap folder with a chinese name?

### ISSUE THREAD

**Issue by skyforcc** [MailCore/mailcore2#1175]
Such as: 
MCOIMAPOperation *opCreateFolder = [_seImapSession createFolderOperation:@"测试"];

It returned nothing.

Thanks for sharing this excellent framework!

**Comment by dinhviethoa** [comment]
Does it return nil for opCreateFolder? If it doesn't return nil, did you start the returned operation?

**Comment by skyforcc** [comment]
To dinhviethoa: It doesn't, I'm sure I started the operation; I managed to show folders with chinese names by this code: 

NSArray *arFolderPathComponent = [[_seImapSession defaultNamespace] componentsFromPath:eachFolder.path];

But it seems that the create/rename/delete folder operation couldn't deal with chinese folder path, because of the encoding?

**Comment by dinhviethoa** [comment]
Could you show the connectionLogger logs?

**Comment by skyforcc** [comment]
6 SELECT INBOX

* 5 EXISTS
* 0 RECENT
* OK [UNSEEN 3]
* OK [UIDVALIDITY 1429791636] UID validity status
* OK [UIDNEXT 6] Predicted next UID
* FLAGS (\Answered \Flagged \Deleted \Draft \Seen)
* OK [PERMANENTFLAGS (\* \Answered \Flagged \Deleted \Draft \Seen)] Permanent flags
6 OK [READ-WRITE] SELECT complete

7 CREATE "测试"

 (null)

White lines devide each log.

**Comment by skyforcc** [comment]
The error notification:
Error Domain=MCOErrorDomain Code=14 "An error occurred while creating the requested folder." UserInfo=0x7fbbfbef2e00 {NSLocalizedDescription=An error occurred while creating the requested folder.}

How can I convert chinese folder name into MailCore2 style? As its opposite to this code:
NSArray *arFolderPathComponent = [[_seImapSession defaultNamespace] componentsFromPath:eachFolder.path];

**Comment by dinhviethoa** [comment]
```
NSString * path = [[imapSession defaultNamespace] pathForComponents:@[@"测试"]];
```

Then, use this path name to create the folder.
Please reopen if it doesn't work for you.

**Comment by Rain-dew** [comment]
NSString * path = [[imapSession defaultNamespace] pathForComponents:@[@"测试"]];
[[imapSession createFolderOperation:path] start:completionBlock]
It doesn't work, path is nil, and then it crashed!

For the English name, it works fine, but for the Chinese name, an error is reported
Error Domain=MCOErrorDomain Code=14 "An error occurred while creating the requested folder."

**Comment by Rain-dew** [comment]
有这个疑问应该都是懂中文的，我直接用中文回复吧
我搞明白了这个中文文件夹直接创建失败的原因
IMAP是有一个国际约定的命名空间的，[文档中有规则说明](http://www.leeon.me/upload/other/RFC3501_cn.html)
文件夹名称返回的并非是一个中文，而是一个符合命名规范的一个编码字符串，在iOS中，你可以直接使用  
`CFStringRef cfstr = CFStringCreateWithCString(NULL, [path UTF8String], kCFStringEncodingUTF7_IMAP);` 
 `NSString *decodedName = [[(__bridge NSString *)cfstr copy] lastPathComponent];`
得到转码后的中文文件夹名称；path是例如这样的字符串：~peter/mail/&U,BTFw-/&ZeVnLIqe-   （中、英、日文集合的文件夹）

那么相应的，创建文件夹也需要对中文进行编码。
`CFStringGetCString((CFStringRef)str, buffer, 1024, kCFStringEncodingUTF7_IMAP)`
当然，在mailCore2中，作者已经提供了方法。你需要先拿到命名空间进行转换再创建文件夹，具体做法如下：
```
    MCOIMAPSession *imapSession = [self getIMAPSession:mailAccount];

    MCOIMAPFetchNamespaceOperation * op = [imapSession fetchNamespaceOperation];
    [op start:^(NSError * __nullable error, NSDictionary * namespaces) {

        MCOIMAPNamespace * namespace = (imapSession.defaultNamespace != nil) ? imapSession.defaultNamespace : [namespaces objectForKey:MCOIMAPNamespacePersonal];
        NSArray *components = [namespace componentsFromPath:folderName];
        NSString *resultFolderName = [namespace pathForComponents:components];
        [[imapSession createFolderOperation:resultFolderName] start:completionBlock];

    }];
```
如果你的imapSession之前获取过namespaces，并且MCOIMAPSession对象没有被释放，可以省去fetchNamespaceOperation这个过程，直接取 imapSession.defaultNamespace
