### ISSUE TITLE
HTMLRendererTemplateCallback leads to a malformed html

### ISSUE THREAD

**Issue by tapouillo** [MailCore/mailcore2#1176]
Hi,

When using a custom callback for the html rendering, maybe the TemplateCallBack should be like this

```
mailcore::String * HTMLRendererTemplateCallback::templateForMessage(AbstractMessage * message)
{
    return MCSTR("{{BODY}}");
}
```

(same for templateForEmbeddedMessage)

instead of returning :  `div style=\"padding-bottom: 20px;\">{{HEADER}} /div> div>{{BODY}} /div>");`

Because even if we set our own call back to only returning the html body of the email, it adds a padding and header text.
Also, it leads to a bad html format, the html string looks like this: `<div style=padding...></div> <html>blabalbla</html> </div>`

**Comment by dinhviethoa** [comment]
Having the `<html>` tag is not a big issue.
If you let tidy run on it, it should clean up the `<html>` tag.

**Comment by tapouillo** [comment]
not a big issue, the html is indeed displayed correcty.
but if we use the render delegate we are not supposed to have a modified version of what is inside the email itself.
also, if you load that modified html in a webview, you can't parse the dom elements correcty, because the first element becomes the div inside which there is the html ... 
an html should start by <html>, not a <div>.

**Comment by dinhviethoa** [comment]
Could you show the input html and the output?

**Comment by tapouillo** [comment]
here is my code:
```
MCOMessageParser *messageParser = [[MCOMessageParser alloc] initWithData:data];                
NSString *msgHTMLBody = [messageParser htmlRenderingWithDelegate:self];
```

it goes correctly there where i return no template:
```
- (NSString *)MCOAbstractMessage:(MCOAbstractMessage *)msg templateForMainHeader:(MCOMessageHeader *)header
{
	return @"";
}
````

the msgHTMLBody returned is:
````
<div style="padding-bottom: 20px;"></div><div><html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link itemprop="url" href=
"https://github.com/MailCore/mailcore2/issues/1176#issuecomment-121338038" />
<meta itemprop="name" content="View Issue" />
<meta itemprop="description" content="View this Issue on GitHub" />
<title></title>
</head>
<body>
<p>Could you show the input html and the output?</p>
<p style=
"font-size:small;-webkit-text-size-adjust:none;color:#666;">—<br />
Reply to this email directly or <a href=
"https://github.com/MailCore/mailcore2/issues/1176#issuecomment-121338038">
view it on GitHub</a>.<img alt="" height="1" src=
"https://github.com/notifications/beacon/ABrOUYzX6IteftiAyYogQZC1q_APqnanks5odVA9gaJpZM4FYTpB.gif"
width="1" /></p>
<div itemscope="" itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope="" itemtype=
"http://schema.org/ViewAction"></div>
</div>
</body>
</html>
</div>
````
this is actually when I also get if i don't use delegate...

but if I change the MCHTMLRendererCallback.cpp as described above, I get what I expect:
```
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link itemprop="url" href=
"https://github.com/MailCore/mailcore2/issues/1176#issuecomment-121338038" />
<meta itemprop="name" content="View Issue" />
<meta itemprop="description" content="View this Issue on GitHub" />
<title></title>
</head>
<body>
<p>Could you show the input html and the output?</p>
<p style=
"font-size:small;-webkit-text-size-adjust:none;color:#666;">—<br />
Reply to this email directly or <a href=
"https://github.com/MailCore/mailcore2/issues/1176#issuecomment-121338038">
view it on GitHub</a>.<img alt="" height="1" src=
"https://github.com/notifications/beacon/ABrOUYzX6IteftiAyYogQZC1q_APqnanks5odVA9gaJpZM4FYTpB.gif"
width="1" /></p>
<div itemscope="" itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope="" itemtype=
"http://schema.org/ViewAction"></div>
</div>
</body>
</html>
```

**Comment by dinhviethoa** [comment]
You found the solution then. Great!

**Comment by tapouillo** [comment]
I have found why I get the div / padding code in the html, but that's not a good solution, because I need to modify the MCHTMLRendererCallback.cpp like this  ...

```
mailcore::String * HTMLRendererTemplateCallback::templateForMessage(AbstractMessage * message)
{
    return MCSTR("{{BODY}}");
    //original code was
    //return MCSTR("<div style=\"padding-bottom: 20px;\">{{HEADER}}</div><div>{{BODY}}</div>");
}
```
it should not modify the html if we don't want to, and especially if we use our own delegate for the template.

**Comment by dinhviethoa** [comment]
I advise you to use libtidy.
There's a wrapper in MailCore2: -[NSString mco_cleanedHTMLString]

**Comment by tapouillo** [comment]
it cleans the html indeed, but it is still adding that padding code inside the html
```
<div style="padding-bottom: 20px;"></div>
```
why adding this if we use our own template...

**Comment by dinhviethoa** [comment]
oh ok. I see what you are looking for.
See MCOHTMLRendererDelegate.h

Are you using on of those two methods to render the message?

```
@interface IMAPMessage
- (NSString *) htmlRenderingWithFolder:(NSString *)folder
                              delegate:(id <MCOHTMLRendererIMAPDelegate>)delegate;
```

```
@interface MCOMessageParser
- (NSString *) htmlRenderingWithDelegate:(id <MCOHTMLRendererDelegate>)delegate;
```

**Comment by tapouillo** [comment]
yes, htmlRenderingWithDelegate ,  see my code above (my third message)

**Comment by dinhviethoa** [comment]
Implement the following method in the delegate:
```
- (NSString *) MCOAbstractMessage_templateForMessage:(MCOAbstractMessage *)msg
{
  return @"{{BODY}}";
}
```

**Comment by tapouillo** [comment]
just tried, but it is still adding the padding20px  code

**Comment by dinhviethoa** [comment]
Cool to hear :+1:
