### ISSUE TITLE
Mac Example using Arc.

### ISSUE THREAD

**Issue by sundsx** [MailCore/mailcore2#1177]
Please can you provide an example using ARC?
Where you declare BOOL=YES for  boolForKey:@"FetchFullMessageEnabled"])?
i can rendering in webview only the first message clicked in tableview and i can't find where the problem reside. Where i need to relod webview in ARC?

    - (void) setMessage:(MCOIMAPMessage *)message
    {
    NSLog(@"set message : %@", message);
    NSLog(@"set attachments: %@ %@", [message attachments], [message htmlInlineAttachments]);
    for(MCOOperation * op in _ops) {
        [op cancel];
    }
    [_ops removeAllObjects];
    
    [_callbacks removeAllObjects];
    [_pending removeAllObjects];
    [_storage removeAllObjects];
    [_message release];
    _message = [message retain];
    
    if (![[NSUserDefaults standardUserDefaults] boolForKey:@"FetchFullMessageEnabled"]) {
        [_messageView setDelegate:self];
        [_messageView setFolder:_folder];
        [_messageView setMessage:message];
    }
    else {
        [_messageView setMessage:NULL];
        MCOIMAPFetchContentOperation * op = [_session fetchMessageOperationWithFolder:_folder  uid:[_message uid]];
        [_ops addObject:op];
        [op start:^(NSError * error, NSData * data) {
            if ([error code] != MCOErrorNone) {
                return;
            }
            
            NSAssert(data != nil, @"data != nil");
            
            MCOMessageParser * msg = [MCOMessageParser messageParserWithData:data];
            [_messageView setDelegate:self];
            [_messageView setFolder:_folder];
            [_messageView setMessage:msg];
        }];
        }
        }

**Comment by dinhviethoa** [comment]
Using MailCore requires to know about Objective-C.

**Comment by sundsx** [comment]
Thank you for your suggest.
But, please modernize your framework, rid off compiling warning due 64 bit conversion and add clean documentation.  
mailcore unfortunately is the only way to use imap in obj-c. the web is full of "how to" about mailcore, most of core audio.

**Comment by dinhviethoa** [comment]
Feel free to help modernizing the framework and improve documentation.
