### ISSUE TITLE
MCOConnectionLogTypeErrorParse

### ISSUE THREAD

**Issue by Simplemen** [MailCore/mailcore2#1178]
What is the cause of MCOConnectionLogTypeErrorParse ?Command to send the QUIT to return to this mistake。
![image](https://cloud.githubusercontent.com/assets/11606318/8690547/84bcefe8-2ae8-11e5-8301-b50b2fbb122d.png)
But in fact is sent successfully
stackover link:http://stackoverflow.com/questions/31421291/mcoconnectionlogtypeerrorparse

**Comment by dinhviethoa** [comment]
What's the email server you used to reproduce it?
If you can provide server info + authentication information, it would be helpful to reproduce the issue.

**Comment by qq510304723** [comment]
connectionID:     		0x15eeac5d0
	connectionLogType:		MCOConnectionLogTypeSent
	content:	{
7 UID FETCH 7428,7430:7431,7438,7440,7446:7448,7450,7455,7465:7466,7468,7470:7472,7481:7484 (UID FLAGS BODYSTRUCTURE INTERNALDATE BODY.PEEK[HEADER.FIELDS (Date Subject From Sender Reply-To To Cc Message-ID References In-Reply-To)])


* 47 FETCH (UID 7482 FLAGS (\Seen) BODYSTRUCTURE (("TEXT" "PLAIN" ("CHARSET" "GB2312") NIL NIL "8BIT" 0 0 ("BOUNDARY" "----AMDCKIKDE8DFX44Y7Z6LV5HNKHYJ7Y") NIL NIL) "MIXED" ("BOUNDARY" "----AMDCKIKDE8DFX44Y7Z6LV5HNKHYJ7Y") NIL NIL) INTERNALDATE "2-Jun-2016 16:17:55 +0800" BODY[HEADER.FIELDS (DATE SUBJECT FROM SENDER REPLY-TO TO CC MESSAGE-ID REFERENCES IN-REPLY-TO)] {196}

Date: Thu, 02 Jun 2016 16:17:11 +0800

From: huangsm@shinemo.com

To: =?UTF-8?B?5Lil5Li96Iqz?= <yanlf@shinemo.com>

Subject: aaa

Message-ID: <86007B77-8B03-4EB2-8ADC-355F8602301F@shinemo.com>

	connectionID:     		0x15eeac5d0
	connectionLogType:		MCOConnectionLogTypeErrorParse
	content:	{
47 FETCH (UID 7482 FLAGS (\Seen) BODYSTRUCTURE (("TEXT" "PLAIN" ("CHARSET" "GB2312") NIL NIL "8BIT" 0 0 ("BOUNDARY" "----AMDCKIKDE8DFX44Y7Z6LV5HNKHYJ7Y") NIL NIL) "MIXED" ("BOUNDARY" "----AMDCKIKDE8DFX44Y7Z6LV5HNKHYJ7Y") NIL NIL) INTERNALDATE "2-Jun-2016 16:17:55 +0800" BODY[HEADER.FIELDS (DATE SUBJECT FROM SENDER REPLY-TO TO CC MESSAGE-ID REFERENCES IN-REPLY-TO)] {196}

}

**Comment by qq510304723** [comment]
when i fetch uid = 7482 mail, the mailcore2 throw error parserror, then callback nil messsages and error = MCOErrorParse

**Comment by qq510304723** [comment]
how can i do to get messages

**Comment by dinhviethoa** [comment]
Maybe don't fetch bodystructure. Servers usually get it wrong.
