### ISSUE TITLE
Download attachment support

### ISSUE THREAD

**Issue by PrabakarMP** [MailCore/mailcore2#1181]
Hi,

I am developing iOS app using Mailcore2 for imap mail support, I am able to see the mail opening using MCOMessageView class. Attachments are also showing here. Attachment is not showing immediately when opening the email, it takes some time to show the attachment. This is my first issue. Next issue, there is no way I can download the attachment. How to provide download attachment support?

I saw similar question answer here -> https://github.com/MailCore/MailCore/issues/118
But i want to know, where and what action (touch or click action by user) we should give to user to download/view attachment?

Please advise.

![photo2015-07-16-23-46-07](https://cloud.githubusercontent.com/assets/1001894/8731516/7774db56-2c15-11e5-8319-70f5b985e9cc.png)

**Comment by dinhviethoa** [comment]
That's not an issue with mailcore2. It's up to you to implement it.

**Comment by HemalAsanka** [comment]
Hi @PrabakarMP,
I also want to view attachment. So if you implement it please let me know how to implement it.

**Comment by loginforvijay** [comment]
hi @PrabakarMP , @HemalAsanka if u have.. please give me some code for attachment download and display thanks in advance
