### ISSUE TITLE
API for "Delivered-to" field?

### ISSUE THREAD

**Issue by ezrasuki** [MailCore/mailcore2#1185]
Hi I'm working with BCC emails and trying to get the actual email address to which an email is delivered (involves subaddressing). 

BCC doesn't include the recipient's email in "To" field so the only way I can accurately find out which email it was delivered to is to use "Delivered-to" field from the header but it doesn't seem like the library provides that method. Am I missing something?

**Comment by dinhviethoa** [comment]
Did you try -[MCOMessageHeader extraHeaderValueForName:@"Develiered-To"] ?

**Comment by ezrasuki** [comment]
Yes I did. I looked at the entire header object and it's only returning 
Message-ID, Sender, From, To, Reply-To, and Subject.

I also tried setting the requestKind to include MCOIMAPMessagesRequestKindExtraHeaders but doesn't work. Is it supposed to work by the way? I really hope I'm doing something wrong and not the library. Thank you..

**Comment by dinhviethoa** [comment]
After the operation to request the header is returned, you need to set the extra headers you'd like to retrieve as well.

**Comment by ezrasuki** [comment]
This is what I have:

![screen](https://cloud.githubusercontent.com/assets/5409110/8840776/f64dc7e2-30b3-11e5-9c39-73d2eb4192eb.png)

**Comment by ezrasuki** [comment]
Here's what I am doing:

```
MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindHeaders | MCOIMAPMessagesRequestKindFlags | MCOIMAPMessagesRequestKindExtraHeaders;
MCOIMAPFetchMessagesOperation *fetchOperation = [self.session  fetchMessagesByUIDOperationWithFolder:folder requestKind:requestKind uids:searchResult];
[fetchOperation setExtraHeaders:@[@"Delivered-To"]];
[fetchOperation start:^(NSError * error, NSArray * fetchedMessages, MCOIndexSet * vanishedMessages) {
    for(MCOIMAPMessage *message in fetchedMessages){
        NSLog(@"Delivered-to : %@", [message.header extraHeaderValueForName:@"Delivered-To"]);
    }
}];
```

Rest of the message parts comes in fine. the `Delivered-To` field doesn't. Did I miss anything in the code?

**Comment by dinhviethoa** [comment]
Could you show connectionLogger logs?

**Comment by ezrasuki** [comment]
Hmmmm somehow it started working. I swear it's the same code as earlier, but now it's working. Sorry for the disturbance and thank you so much for helping out!
