### ISSUE TITLE
How to use static library in iOS project, not drag the project in?

### ISSUE THREAD

**Issue by gongruike** [MailCore/mailcore2#1188]
I use the static library library libMailCore-ios.a (http://d.etpan.org/mailcore2-deps/mailcore2-ios/),  not drag the mailcore2 project into my project. But it causes a lot of errors

  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::at(unsigned long) const", referenced from:
      ctemplate::ContainsFullWord(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libMailCore-ios.a(template_pathops.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(unsigned long, char)", referenced from:
      ctemplate::PrettyPrintOneModifier(ctemplate::ModifierAndValue const&) in libMailCore-ios.a(template_modifiers.o)
  "_inflate", referenced from:
      _mailstream_low_compress_read in libMailCore-ios.a(mailstream_compress.o)
  "_inflateInit2_", referenced from:
      _mailstream_low_compress_open in libMailCore-ios.a(mailstream_compress.o)

please, somebody help me.

**Comment by dinhviethoa** [comment]
Please read the instructions here: https://github.com/MailCore/mailcore2/blob/master/build-mac/README.md
