### ISSUE TITLE
android can't get chinese message .

### ISSUE THREAD

**Issue by githupfisher** [MailCore/mailcore2#1190]
I get the mail message ,but get the message's subject is null.
the message's subject is 为你推荐的热门Google+信息页

**Comment by dinhviethoa** [comment]
Can you show the RFC 822 source?

**Comment by githupfisher** [comment]
@dinhviethoa 
<mailcore::MessageHeader:0x918817e0
    Message-ID: CAGnMr6TN3W2uSPeJXTH6j7-_Bw+ZADspmu0v8Ez9tM1WEG37Ag@mail.gmail.com
    From: mailcore::Address:0x91885490 Hui Yu <fisher@mera.im>
    To: [mailcore::Address:0x91885688  <yuhui@updays.net>]
    Subject: 我的就是我的
    Return-Path: <fisher@mera.im>
    Content-Type: multipart/alternative; boundary=089e0122a69280abe3051c14bd9f
    X-Received: by 10.182.18.72 with SMTP id u8mr43848164obd.8.1438250288572;
    Thu, 30 Jul 2015 02:58:08 -0700 \(PDT\)
    Delivered-To: yuhui@updays.net
    X-Originating-IP: [106.187.103.129]
    MIME-Version: 1.0
    Authentication-Results: mx.google.com;
    spf=neutral \(google.com: 209.85.214.169 is neither permitted nor denied by best guess record for domain of fisher@mera.im\) smtp.mail=fisher@mera.im
    X-Gm-Message-State: ALoCoQmiDOXGxJywej8/s/ur0e9v82yLhwjWw5wQB0VhdkSHrN+wrwabLdmEXTTFVcoX+VpS9Kme
    Received: by 10.140.85.203 with SMTP id n69csp499638qgd;
    Thu, 30 Jul 2015 02:58:08 -0700 \(PDT\)
    Received-SPF: neutral \(google.com: 209.85.214.169 is neither permitted nor denied by best guess record for domain of fisher@mera.im\) client-ip=209.85.214.169;
    X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
    d=1e100.net; s=20130820;
    h=x-gm-message-state:mime-version:date:message-id:subject:from:to
    :content-type;
    bh=GP2NhPihIpnzg8ifuHtGEILJvhf4QyNErEhoxgTokuM=;
    b=d13VYEWLzo2tKznf03NJlz4CHjesCUTSUxJaDwYE6iSvD4lQTru1+Oi8WZdT6K8z+9
    BAqDdvn4FbVSa6WM3SKTB7NMo4Emrpmo+KRee0/2o/6h9NpKCjydxYI3xsHn+O5LSL0N
    kFJftL0SC6nY9bj8bgqlOuhfxuu16d9z61glqe9znoey9Vl9R9PlnP5CIx24gXELMptn
    +yLEt925RY4cqaJEGGXSWG1lQrcSDc221fKUeQNoeu4x+Fpn0BYNCaESnmjUCIhhWKcV
    8lsle7Yfm3ICeS5Gsb/IRdX7mSfkoUASTCVBY/S2+L1x+wTHGT0kzqkvH5qgEfiWnRhv
    iQHQ==
    >

**Comment by dinhviethoa** [comment]
It seems that you copy paste the output of mailcore2 logging, not an actual RFC 822 message source.
