### ISSUE TITLE
Cache email - solution

### ISSUE THREAD

**Issue by cuongproit** [MailCore/mailcore2#1192]
I want to cache mailitem ( array of MCOIMAPMessage object) into local device (ex: Coredata). Could you suggest me a solution? Because MCOIMAPMessage have many properties, and many properties of them are another custom objects --> very difficult to save into Database.

Thanks.

**Comment by KieranMcGrady** [comment]
Create your own message object which contains the properties you need. Save the parts of ```MCOIMAPMessage``` you need to that and save your own object to the database. You don't want to modify ```MCOIMAPMessage``` into an ```NSManagedObject``` - you create your own.

**Comment by dinhviethoa** [comment]
Thanks for your answer @KieranMcGrady
