### ISSUE TITLE
Latest mailcore-master simply explodes NS_ASSUME_NONNULL_BEGIN

### ISSUE THREAD

**Issue by sundsx** [MailCore/mailcore2#1193]
Please look this image link is more than 1000 words

http://s24.postimg.org/pmx7qhnc5/Schermata_2015_07_31_alle_10_24_14.png

A tons of error about "NS_ASSUME_NONNULL_BEGIN" n

**Comment by dinhviethoa** [comment]
If you update to latest Xcode, it will remove the error.
