### ISSUE TITLE
WKWebView support

### ISSUE THREAD

**Issue by rlaferla** [MailCore/mailcore2#1196]
Mailcore currently uses UIWebView but Apple is replacing it with WKWebView (WebKit).  Is there any code that shows how to use WKWebView with mailcore?  Any support in the mailcore API?

**Comment by dinhviethoa** [comment]
It's out of scope of mailcore. One issue though is that WKWebView doesn't allow to show downloaded resources. Then, it will be challenging to display downloaded images that you store locally.

**Comment by srinadh-k** [comment]
Hi @dinhviethoa 

The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.

So any update on WKWebview for Mailcore?

**Comment by dinhviethoa** [comment]
We could probably encode images using image URLs.
I'll take a look at it.

**Comment by srinadh-k** [comment]
Sure, Please let me know when it is done.

**Comment by dinhviethoa** [comment]
Let me know if you'd like to help reimplement the MCOMessageView with WKWebView.
I help with guidance. It might speed up the availability.

**Comment by srinadh-k** [comment]
We are using MailCore2 for the iOS app. So what is the best way to work without any issue even after apple no longer accepts UIWebView?

**Comment by haithngn** [comment]
> We are using MailCore2 for the iOS app. So what is the best way to work without any issue even after apple no longer accepts UIWebView?

You must migrate the UIWebview to WKWebView if your app still needs a DOM screen to display an email.

**Comment by srinadh-k** [comment]
Hi Thanks for getting back to me.

So is there any chance will you update framework with WKWebView your side?

If not, let me know your thoughts for replacing that and what precautions
we need to take care after updating it.

**Comment by dinhviethoa** [comment]
First of all, are you using any UI component of mailcore2? If not you could probably drop it from the framework and that would remove the dependency on UIWebView.

**Comment by rjvishnu87** [comment]
@haithngn, any progress on this ? We can't publish new iOS app if we use UIWebView, so please make this change asap. Or guide us how to remove MCOMessageView without impacting other functionality. Thanks.

**Comment by githubofyyg** [comment]
> We could probably encode images using image URLs.
> I'll take a look at it.

Do you know what to do with it，thanks

**Comment by haithngn** [comment]
UIWebView has been completely migrated to WKWebView!  - https://github.com/MailCore/mailcore2/commit/092c16bf0e67360e8410d592e86e1269b23614b4
