### ISSUE TITLE
How to get the folder details for a mail using messageID?

### ISSUE THREAD

**Issue by SaralMohan** [MailCore/mailcore2#1200]
I am using Mailcore2 to fetch mails from IMAP server. If I have a messageID of a mail using that can I get the folder in which it is for Outlook and Yahoo mails?

I am using the following code for fetching messages

      self.imapMessagesFetchOp =
     [self.imapSession fetchMessagesByNumberOperationWithFolder:inboxFolder
                                                    requestKind:requestKind
                                                        numbers:[MCOIndexSet indexSetWithRange:fetchRange]];

     [self.imapMessagesFetchOp start:
      ^(NSError *error, NSArray *messages, MCOIndexSet *vanishedMessages)
      {

        }];
Thanks for any help.

**Comment by dinhviethoa** [comment]
See https://github.com/MailCore/mailcore2/issues/1121

**Comment by SaralMohan** [comment]
I want to get the folder in which that mail is.

**Comment by dinhviethoa** [comment]
If Gmail, search in "All Mail" and retrieve the labels.
If other, perform a search in each folder.
If you're looking for efficiency, cache the list of all message-ids.

**Comment by SaralMohan** [comment]
So there is no way to get the folder in which the messageID is present

**Comment by dinhviethoa** [comment]
No. Please read IMAP spec and Gmail extension for further info:
- https://tools.ietf.org/html/rfc3501
- https://developers.google.com/gmail/imap_extensions

**Comment by SaralMohan** [comment]
Ok thank you for the help.
