### ISSUE TITLE
Save as Draft in Gmail!

### ISSUE THREAD

**Issue by cuongproit** [MailCore/mailcore2#1201]
In Yahoo mail, outlook mail.. saving email to Darft folder is worked. But, I can't save email to Draft folder in only GMAIL. The error description is: "The requested folder does not exist. Folder selection failed". See my code below:

MCOIMAPAppendMessageOperation * op = [self.currentAccount.imapSession appendMessageOperationWithFolder:self.currentAccount.draftFolder messageData:data flags:MCOMessageFlagDraft];
[op start:^(NSError *error, uint32_t createdUID) {

}];

I logged the value of draftFolder in this case is "[Gmail]/Drafts".

Please help me!

**Comment by dinhviethoa** [comment]
Please add connectionLogger to investigate what's going on.

**Comment by cuongproit** [comment]
Let me try!

**Comment by cuongproit** [comment]
I has added connectionLogger into imapsession, but i can't find more useful information. See my log below:

----------data from connectionLoger: ---------------
* OK Gimap ready for requests from 116.107.21.36 g4mb21598371iga
------------------------------

----------data from connectionLoger: ---------------
1 CAPABILITY
------------------------------

----------data from connectionLoger: ---------------
* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=XOAUTH

1 OK Thats all she wrote! g4mb21598371iga
------------------------------

----------data from connectionLoger: ---------------
2 LOGIN "username" password
------------------------------

----------data from connectionLoger: ---------------
* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS

2 OK username@gmail.com authenticated (Success)
------------------------------

----------data from connectionLoger: ---------------
 3 COMPRESS DEFLATE
------------------------------

----------data from connectionLoger: ---------------
3 OK Success
------------------------------

----------data from connectionLoger: ---------------
4 ENABLE CONDSTORE
------------------------------

----------data from connectionLoger: ---------------
* ENABLED CONDSTORE
4 OK Success
------------------------------

----------data from connectionLoger: ---------------
 5 NAMESPACE

------------------------------

----------data from connectionLoger: ---------------
* NAMESPACE (("" "/")) NIL NIL

5 OK Success
------------------------------

----------data from connectionLoger: ---------------
6 ID NIL
------------------------------

----------data from connectionLoger: ---------------
* ID ("name" "GImap" "vendor" "Google, Inc." "support-url" "http://support.google.com/mail" "version" "gmail_imap_150802.10_p0" "remote-host" "116.107.21.36")

6 OK Success
------------------------------

----------data from connectionLoger: ---------------
7 SELECT "[Gmail]/Drafts"
------------------------------

----------data from connectionLoger: ---------------
7 NO [NONEXISTENT] Unknown Mailbox: [Gmail]/Drafts (Failure)
------------------------------

Could you help me? Thanks.

**Comment by KieranMcGrady** [comment]
Could it be an access issue? If I remember correctly there are certain folders on Gmail that we don't have permission to write to. Drafts may be one of those. Just a guess though.

**Comment by dinhviethoa** [comment]
You need to enable the Draft on IMAP in the settings in the Gmail Web UI.

**Comment by cuongproit** [comment]
worked!! Many thanks @dinhviethoa  @KieranMcGrady
