### ISSUE TITLE
How to get the progress of downloading attachments and mails from imap using mailcore

### ISSUE THREAD

**Issue by SaralMohan** [MailCore/mailcore2#1204]
I am trying to get the progress of downloading mails and attachments. I have added the code that I am using to download the mails and attachments. Can I get the progress of mails and attachment. Can you please help me with this.

Code used for Mail Fetching:
self.imapMessagesFetchOp = [self.imapSession fetchMessagesByNumberOperationWithFolder:folder requestKind:requestKind numbers:[MCOIndexSet indexSetWithRange:fetchRange]];

[self.imapMessagesFetchOp start:^(NSError *err, NSArray *messages, MCOIndexSet *vanished) {
                error = err;
                emailMessages = messages;
                vanishedMessages = vanished;
                CFRunLoopStop(currentRunLoop);
            }];

Code used for download Attachment:
MCOIMAPFetchContentOperation * op =[self.imapSession fetchMessageAttachmentOperationWithFolder:self.folderName uid:self.messageUid partID:self.partId encoding:MCOEncodingBase64];
            
            [op start:^(NSError * error, NSData * messageData)
            {
                errorParam = error;
                
                attachmentData = messageData;
                
                CFRunLoopStop(currentThreadRef);
            }];

**Comment by mqmq** [comment]
there is a block call back  for  progress

    op.progress = ^(unsigned int current, unsigned int maximum){
    };

**Comment by SaralMohan** [comment]
So where should I call this method. After initialising or after starting the operation.

**Comment by mqmq** [comment]
After initialising or after starting  ， all right

**Comment by SaralMohan** [comment]
Ok I will try and let you know.

**Comment by SaralMohan** [comment]
I have tried it and it was working. Thanks for the help.
