### ISSUE TITLE
Error downloading message headers:Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo=0x7fd0da533170 {NSLocalizedDescription=A stable connection to the server could not be established.}

### ISSUE THREAD

**Issue by KiranJasvanee** [MailCore/mailcore2#1207]
I tried run below basic code to load messages from gmail, but I always gets crash error 'A stable connection to the server could not be established'.
authToken is a accessToken I got using Google Sign in. 
Is there I'm lacking of having something. Please help me so I can move further. 

```
MCOIMAPSession *session = [[MCOIMAPSession alloc] init];
    [session setHostname:@"imap.gmail.com"];
    [session setPort:993];
    [session setUsername:@"jasvanee.karan@gmail.com"];
    [session setPassword:nil];
    [session setOAuth2Token:authToken];
    [session setAuthType:MCOAuthTypeXOAuth2];
    [session setConnectionType:MCOConnectionTypeTLS];
    
    MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindHeaders;
    NSString *folder = @"INBOX";
    MCOIndexSet *uids = [MCOIndexSet indexSetWithRange:MCORangeMake(1, UINT64_MAX)];
    
    MCOIMAPFetchMessagesOperation *fetchOperation = [session fetchMessagesOperationWithFolder:folder requestKind:requestKind uids:uids];
    
    [fetchOperation start:^(NSError * error, NSArray * fetchedMessages, MCOIndexSet * vanishedMessages) {
        //We've finished downloading the messages!
        
        //Let's check if there was an error:
        if(error) {
            NSLog(@"Error downloading message headers:%@", error);
        }
        
        //And, let's print out the messages...
        NSLog(@"The post man delivereth:%@", fetchedMessages);
    }];
```

**Comment by dinhviethoa** [comment]
Does it work when you use an other email app to connect to your account?

**Comment by KiranJasvanee** [comment]
Sorry folks, I went deep on this problem and got a solution. The problem was not in my code it was on my gmail account through which I was trying to access mails. That account was having a 2-way secure authentication on privacy setting, So there is 'App password' account owner have to set to login on any app. if owner don't want to set 'App password' and want to go through regular password on apps, then he/she have to off 2-way secure notification off, then this code works fine with normal password.

**Comment by dinhviethoa** [comment]
In case of 2-factor auth, it should show an authentication error and not a connection error ("A stable connection to the server could not be established.").
With 2-factor auth, you need to implement OAuth2.
