### ISSUE TITLE
Get the attachment image thumbnail before downloading the whole attachment?

### ISSUE THREAD

**Issue by shrishaster** [MailCore/mailcore2#1208]
Using MailCore2, is it possible to get the thumbnail of an image attachment before we actually download it?

**Comment by KieranMcGrady** [comment]
AFAIK there is no IMAP property for getting previews of attachments in this way (someone else can confirm this but I'm pretty sure). The only thing I believe you can get without downloading the attachment is the file name and size. If you need to display something when the mail is opened try downloading attachments for messages in advance so they are already downloaded when the message is opened.

NB: There was a previous question regarding this #972 but the StackOverflow link in it is dead.

**Comment by shrishaster** [comment]
OK. Then any idea how outlook, etc manage to show thumbnail? It seems doubtful that they would download every attachment just because you open that mail!

**Comment by KieranMcGrady** [comment]
I haven't seen previews done where it isn't downloaded. Do you have a screenshot?

**Comment by shrishaster** [comment]
Yeah sorry. They show thumbnails after downloading attachment.
