### ISSUE TITLE
Mailcore2 on Android storeFlags operation hangs

### ISSUE THREAD

**Issue by glosterva** [MailCore/mailcore2#1209]
I'm trying to set the delete flag on a message, and when I run start() on the storeFlags operation, it hangs, and the emulator says the application has stopped running. Here's my code:
 
    IndexSet set = IndexSet.indexSetWithIndex(message.uid());
    IMAPOperation setDeleteFlagOperation = 
        MessagesSyncManager.singleton().session.storeFlagsByUIDOperation(
            "INBOX", set, IMAPStoreFlagsRequestKind.IMAPStoreFlagsRequestKindSet, 
            MessageFlag.MessageFlagDeleted);
    setDeleteFlagOperation.start(this);

I've also tried using storeFlagsByNumberOperation() to create the operation with the same result. I've made sure that I pass in a valid UID, or in the case of storeFlagsByNumberOperation(), a valid sequence number.

Maybe I'm on the wrong track, but I notice that on this bug and another one I'm about to enter, they both use array-type structures (`IndexSet` for this one, and `List<Address>` for the other one), while the parts of the API that are working well for me do not use array-type structures.  I originally posted this on StackOverflow, and Dinh Viêt Hoà suggested I file a bug here.

**Comment by dinhviethoa** [comment]
@DaveInAus have you seen that issue?

**Comment by DaveInAus** [comment]
@glosterva can you try  
IndexSet set = new IndexSet();
set.addIndex(message.uid());

**Comment by glosterva** [comment]
@DaveInAus Thanks for your help with this.  Your suggestion allows me to create the IndexSet without a problem, but the very next statement (included in my code above), the call to storeFlagsByUIDOperation()--which takes the IndexSet as an argument--hangs, and the emulator says the application has stopped running.

**Comment by DaveInAus** [comment]
can you check MessagesSyncManager.singleton().session != null

The rest of your code looks fine - Whats your target API? If its less than 21 use
https://github.com/DaveInAus/MailCore2-Android_Lib

**Comment by glosterva** [comment]
@DaveInAus I've verified that the session is not null.  It shows up in the debugger as <mailcore::ImapAsyncSession:0xb0a0a220>.  I'm also compiling with 21 as the minimum API level.  It would not link my app with the library when the minimum API level was set lower.

**Comment by DaveInAus** [comment]
@glosterva can you put the code above in a try catch block and see whether an exception is thrown
have you implemented succeeded and failed methods?

**Comment by glosterva** [comment]
@DaveInAus I put the code in a try/catch block, but no exception is thrown.  I do have succeeded and failed methods implemented, but here I'm not getting to the point where I do the start(), giving it the object with these methods.  It's failing in creating the IMAPOperation object.

**Comment by dinhviethoa** [comment]
I just checked. It looks like there are lots of missing native vs java operations converters.
I'm working on those.

**Comment by glosterva** [comment]
The StoreFlags operation works in DavInAus's recent code.

**Comment by dinhviethoa** [comment]
Fixed with 3a749d8973d67b4eab34e7502b786ab6e058c571.
