### ISSUE TITLE
Mailcore2 on Android hangs on MessageBuilder.setTo() when sending a message

### ISSUE THREAD

**Issue by glosterva** [MailCore/mailcore2#1210]
I've got the Mailcore2 demo app working well. But in trying to replicate the iOS sample code for sending an email on Android, I find that setting the list of To addresses on the `MessageBuilder` object hangs. The call to `setFrom()` works fine.  Here's my code:

    Address fromAddress = Address.addressWithDisplayName(MessagesSyncManager.singleton().displayName,
                MessagesSyncManager.singleton().user);
    String stringToAddress = mEditTo.getText().toString();
    Address toAddress = Address.addressWithMailbox(stringToAddress);
    List<Address> toList = new ArrayList<Address>();
    toList.add(toAddress);
    MessageBuilder builder = new MessageBuilder();
    builder.header().setFrom(fromAddress);
    builder.header().setTo(toList);

I've tried putting `setTo()` before `setFrom()`, but it still hangs. In the debugger I've validated that `stringToAddress` is a correctly formatted email address, and that `toAddress` and `toList` get created correctly. I've tried creating the To address using `Address.addressWithDisplayName()`, and the same thing happens. When `setTo()` hangs, the emulator shows a message box that says "Unfortunately, MailExample has stopped." I'm using Android Studio with the Nexus 5 API 21 x86 Android 5.0.2 emulator.

Maybe I'm on the wrong track, but I notice that on this bug and another one I just entered, they both use array-type structures (IndexSet for the other one, and `List<Address>` for this one), while the parts of the API that are working well for me do not use array-type structures.  I originally posted this on StackOverflow, and Dinh Viêt Hoà suggested I file a bug here.

**Comment by dinhviethoa** [comment]
@DaveInAus have you seen that issue?

**Comment by DaveInAus** [comment]
Just recreated and get the same result - will investigate further

**Comment by dinhviethoa** [comment]
Fixed with https://github.com/MailCore/mailcore2/pull/1213
