### ISSUE TITLE
MCOPOPSession timeout not respected?

### ISSUE THREAD

**Issue by lattejed** [MailCore/mailcore2#1215]
I'm trying to test a number of possible combinations of POP server configs in parallel. Regardless of the timeout set, a number of (invalid) connections will not timeout before 300 seconds. I've set a timeout of 5 seconds. I've seen it both with Microsoft servers as well as Google servers, so I haven't seen a pattern yet.

Has anyone else seen this?

**Comment by lattejed** [comment]
Wanted to add that this is for POP only, IMAP and SMTP work as expected.

**Comment by dinhviethoa** [comment]
Thanks. I'll take a look.

**Comment by lattejed** [comment]
Thank you =)

**Comment by dinhviethoa** [comment]
Fixed with 025ffced74888e54fab87db8e7d7df727a0fbfd8.

**Comment by lattejed** [comment]
Thanks for the fix & quick turnaround on this.
