### ISSUE TITLE
Lots of Linker Warnings in Xcode 7/ iOS 9 SDK — built for newer iOS version (9.0) than being linked

### ISSUE THREAD

**Issue by andrewlai87** [MailCore/mailcore2#1216]
Hi, I am building an app that uses Mailcore2 with the XCode 7 beta, and now I receive hundreds of linker warnings like the one below (all seem to be related to mailcore2):

ld: warning: object file (/*******/libMailCore-ios.a(MCOPOPFetchHeaderOperation.o)) was built for newer iOS version (9.0) than being linked (8.0)

Any insight into how to remove these warnings?  Thanks!

**Comment by dinhviethoa** [comment]
Make sure that you build MailCore using the same iOS SDK version when building MailCore and when building your app.
