### ISSUE TITLE
On Android sendMessageOperation() crashes without an exception

### ISSUE THREAD

**Issue by glosterva** [MailCore/mailcore2#1218]
@DaveInAus here's the sending bug I'm experiencing.  I am trying to send the simplest message I can send, and sendMessageOperation()  crashes without throwing an exception.  I've verified that none of the objects is null.  I've also tried using Address.addressWithDisplayName() to create the addresses with the same result.

            List<Address> toList = new ArrayList<Address>();
            toList.add(Address.addressWithMailbox("test@vancesoft.com"));
            MessageBuilder builder = new MessageBuilder();
            builder.header().setFrom(Address.addressWithMailbox("roamtst@earthlink.net"));
            builder.header().setTo(toList);
            builder.header().setSubject("Test message");
            builder.header().setDate(new Date());
            builder.setTextBody("Testing 1 2 3...");
            byte[] rfc822Data = builder.data();

            // Send the message
            try {
                SMTPOperation sendOperation = MessagesSyncManager.singleton().smtpSession.sendMessageOperation(rfc822Data);
                sendOperation.start(this);
            } catch(Exception e)
            {
                e.printStackTrace();
            }

This is how I am creating the smtpSession object:

        smtpSession = new SMTPSession();
        smtpSession.setAuthType(AuthType.AuthTypeSASLCRAMMD5);
        smtpSession.setConnectionType(ConnectionType.ConnectionTypeClear);
        smtpSession.setTimeout(15);
        smtpSession.setHostname("smtp.earthlink.net");
        smtpSession.setPort(587);
        smtpSession.setUsername(user);
        smtpSession.setPassword(password);

In the debugger I set a breakpoint at the sendMessageOperation() call, and it always gets there, but then crashes, with a message box on the emulator that the application has stopped.  I also have breakpoints set at the sendOperation.start() call and the e.printStackTrace() calls, and the program does not get there.  I'm using Android Studio, the standard Nexus emulator and your (DaveInAus's) recent build of the Mailcore2 library with the fix for Lists.

**Comment by glosterva** [comment]
P.S., I have it building for a minimum API level of 21

**Comment by dinhviethoa** [comment]
Missing native vs java operations converters.

**Comment by glosterva** [comment]
@dinhviethoa Thanks for getting this addressed!  Let me know when there is a build with a fix for this one and #1219 is available.

**Comment by dinhviethoa** [comment]
Fixed with 3a749d8973d67b4eab34e7502b786ab6e058c571.
