### ISSUE TITLE
Unable to parse response from server.  with QQ Imap server

### ISSUE THREAD

**Issue by liweiwilliam** [MailCore/mailcore2#1220]
I got this issue:
2015-09-02 13:36:23.037 SinaMail[82958:1044257] 101 FETCH (UID 3934 FLAGS (\Seen) ENVELOPE ("Mon, 31 Aug 2015 14:19:25 +0800" "=?GBK?B?dHR0dHR0dHQ=?=" (("=?GBK?B?XA==?=" NIL "power6900637" "sina.com\")) (("=?GBK?B?XA==?=" NIL "power6900637" "sina.com\")) (("=?GBK?B?XA==?=" NIL "power6900637" "sina.com\")) (("=?GBK?B?NjkwMDYzNw==?=" NIL "6900637" "qq.com")) NIL NIL NIL "<93e4584b-06af-494e-b653-9fac29003452@liweideMacBook-Pro.local>") BODY[HEADER.FIELDS (REFERENCES)] {2}
2015-09-02 13:36:23.038 SinaMail[82958:1034270] Error Domain=MCOErrorDomain Code=3 "Unable to parse response from server." 

and I read https://github.com/MailCore/mailcore2/issues/1029
still not working.

**Comment by liweiwilliam** [comment]
It seems like, QQ Imap Server will add a additional '/' in address host part. Shall we remove '/' ?

**Comment by liweiwilliam** [comment]
Wrong word. I mean '\'

**Comment by dinhviethoa** [comment]
Are you able to get QQ IMAP Server to remove the additional '\'? It's breaking the parser.

**Comment by liweiwilliam** [comment]
I can't. I am just a user. I think it has some connection with https://github.com/MailCore/mailcore2/issues/1029. QQ mail is the biggest one in China. So it's really a big trouble. not every mail has this issue. Only those mails with sender/cc/bcc/receiver has same name and email address with this trouble.

**Comment by liweiwilliam** [comment]
So, I think if it is possible that, remove any specific symbol in email host. when do parse in mailimap-parser.c file. like '\' ',' and any other specific char.

**Comment by liweiwilliam** [comment]
Please help me, If it can't be resolved, I'll be fired. :~(

**Comment by dinhviethoa** [comment]
If you request the full headers and don't request the bodystructure with QQ mail server, everything should work properly.

**Comment by liweiwilliam** [comment]
I didn't request bodystructure. 
MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindUid | MCOIMAPMessagesRequestKindHeaders | MCOIMAPMessagesRequestKindFlags;
that's all I request.

**Comment by liweiwilliam** [comment]
I already tried only request MCOIMAPMessagesRequestKindHeaders, still not work.
* 56 FETCH (UID 3917 FLAGS (\Seen) ENVELOPE ("Fri, 28 Aug 2015 15:43:09 +0800" "=?GBK?B??=" (("=?GBK?B?XA==?=" NIL "power6900637" "sina.com\")) (("=?GBK?B?XA==?=" NIL "power6900637" "sina.com\")) (("=?GBK?B?XA==?=" NIL "power6900637" "sina.com\")) (("=?GBK?B?NjkwMDYzNw==?=" NIL "6900637" "qq.com")) NIL NIL NIL "<e053e1e1-dfc0-437d-881f-ff1b75f68672@liweideMacBook-Pro.local>") BODY[HEADER.FIELDS (REFERENCES)] {2}

**Comment by dinhviethoa** [comment]
request full headers then and it will work.

**Comment by dinhviethoa** [comment]
MCOIMAPMessagesRequestKindFullHeaders

**Comment by liweiwilliam** [comment]
It works! Thank you!
