### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by sundsx** [MailCore/mailcore2#1222]
Please can you provide a fixed class?
 
    _session = [[MCOIMAPSession alloc] init];
    _session.hostname = @"mail....";
    _session.port = 993;
    _session.username = @"mail";
    _session.password = @"xxxx";
    [_session setCheckCertificateEnabled:NO];
    _session.connectionType = MCOConnectionTypeTLS;
    
    NSMutableArray *folderarray = [[NSMutableArray alloc] init];
    [[_session fetchAllFoldersOperation] start:^(NSError *error, NSArray *folders) {
        NSMutableString *folderDetails = [NSMutableString new];
        for (MCOIMAPFolder *fdr in folders) {
            
            [folderDetails appendFormat:@"\nFolder[%@], flag : %ld", fdr.path, (long)fdr.flags];
            [folderarray addObject:fdr.path];
        }
        NSLog(@"Folder Details2: %@", folderDetails);
        if (folderarray!=nil) {
            
            NSLog(@"folderarray: %@", folderarray.description);
          //...
             }
         }];
    
![schermata 2015-09-05 alle 15 51 43](https://cloud.githubusercontent.com/assets/1713528/9699532/b6a5756c-53e6-11e5-864c-c7d54f8bca67.png)

**Comment by dinhviethoa** [comment]
What happens when _session is released?

**Comment by sundsx** [comment]
Hi, nothing, still leaks memory. My project is under Automatic Reference Counting (ARC). And this probably the Problem ?

**Comment by dinhviethoa** [comment]
Could you show the Instructions Allocation screenshot showing that MCOIMAPSession has effectively been dealloc'ed?

**Comment by sundsx** [comment]
i can't explicit dealloc under ARC. so i  Just set the ivar to nil:   _session = nil;

as a documentation:
under ARC the compiler automatically inserts the necessary retain and release calls.

**Comment by dinhviethoa** [comment]
It's fixed now.
