### ISSUE TITLE
Silent Warning

### ISSUE THREAD

**Issue by sundsx** [MailCore/mailcore2#1223]
At  src/core/basetypes/ucs-det/uisstring.cpp #1000 there a warning about conversion from int to long.
i was silenced other warning by cast to (int), but this is not for mine. can you fix please?

    U_CAPI int32_t   U_EXPORT2
    u_strlen(const UChar *s) 
   {
    #if U_SIZEOF_WCHAR_T == U_SIZEOF_UCHAR
       return (int32_t)uprv_wcslen(s);
    #else
    const UChar *t = s;
    while(*t != 0) {
      ++t;
     }
    return t - s;  // --> implicit conversion loses integer precision: long to int32
    #endif
}

**Comment by dinhviethoa** [comment]
Thanks for reporting it.
That's code imported from ICU. To make easy the merge. I'd rather not fix it.

**Comment by sundsx** [comment]
ok hope i will fix. thanks
