### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS mailimap_sender.c mailimap_astring_send

### ISSUE THREAD

**Issue by gevorgk** [MailCore/mailcore2#1224]
When checking the  crashlytics reports this the most frequent crash: 
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x00000000
mailimap_sender.c line 453
mailimap_astring_send 

 I have reproduced the crash when folder path was null in IMAPFolderInfoOperation. Now I check the folder path but the crash occur again. Is there any not acceptable folder path types that can cause this issue? 

---------
mailimap_sender.c line 453
mailimap_astring_send
1
mailimap_sender.c line 1716
mailimap_select_send
2
mailimap_sender.c line 1716
mailimap_select_send
3
condstore.c line 482
mailimap_select_condstore_optional
4
mailimap.c line 2002
mailimap_select
5
mailcore::IMAPSession::select(mailcore::String*, mailcore::ErrorCode*) + 894496
6
mailcore::IMAPFolderInfoOperation::main() + 21346
7
mailcore::OperationQueue::runOperations() + 860310

**Comment by dinhviethoa** [comment]
Are you trying to work with a NULL folder?

**Comment by gevorgk** [comment]
I have added not NULL checking and pushed the code so will wait for crashlytics reports. 

I was caching the folders names and the retrial from cache could cause NULL. My question was could there be any other cases (not null as path) which can cause this issue. 

thnx for replying.

**Comment by dinhviethoa** [comment]
I don't think so. Let me know if you find out something weird.
I'll close it. Please reopen if there's something else going on.

**Comment by frankobe** [comment]
My crashlytics log the same problem. @gevorgk May I know whether your solution works?
