### ISSUE TITLE
Embedding image have typo error

### ISSUE THREAD

**Issue by gsantome** [MailCore/mailcore2#1225]
Hello, the embedding doc https://github.com/MailCore/mailcore2/wiki/Embedding-images-in-HTML-rendered-message have an error... I just found inside the javascript you are calling info.LocalPathKey to set the new src of the image... but the json object that you are creating have "InlineDataKey" so could you change the documentation to call info.InlineDataKey inside replaceImageSrc function? 

Thanks!

**Comment by KieranMcGrady** [comment]
If you want to update the docs you can just click the edit button on the top right corner of the page.
