### ISSUE TITLE
Bitcode Support

### ISSUE THREAD

**Issue by bvanosten** [MailCore/mailcore2#1226]
It would be awesome if ENABLE_BITCODE was supported for mailcore2, which is required for supporting watchOS 2.  It seems right now the external libraries: ctemplate, libetpan, etc..., would all need to be updated.

**Comment by dinhviethoa** [comment]
Have you done some research about how to build a configure/make library to bitcode format?
It would be helpful to get this done quickly.

**Comment by bvanosten** [comment]
Yea I've done it with some internal libs, mainly you need to either set ENABLE_BITCODE to YES in the xcode project, or add the flag -fembed-bitcode if its just using clang.  You need to use Xcode 7 as well.

**Comment by KieranMcGrady** [comment]
If bitcode support is added can it be easily disabled by the library user? I ask as bitcode is only supported on iOS 8 and 9.

**Comment by dinhviethoa** [comment]
@KieranMcGrady  Are you going to build using an older version of Xcode?
Do you have any recommendation testing it?
Are you supporting legacy iOS 6 / 7 in your projects?

**Comment by KieranMcGrady** [comment]
@dinhviethoa I'm building using Xcode 7 but I'm still supporting iOS 7. I'm considering dropping iOS 7 support once iOS 9 is out and based on how fast it's adopted. I think dropping older OS support in Mailcore would be fine as long as there was a fork for older OS versions at least until iOS 9 adoption is looking good.

**Comment by dinhviethoa** [comment]
Since it's supported in iOS 8 and adoption of iOS 8 is good, I'm not sure why you're still looking into iOS 7 in the transition.

**Comment by KieranMcGrady** [comment]
True I should probably consider it more. Originally the problem was iOS 8 adoption was slow due to the size but a year on I will look at it again.

**Comment by dinhviethoa** [comment]
I think bitcode support is fixed now with 9d7f7a65ff2166ff9a0330afc4a7d938a847c32d
