### ISSUE TITLE
Android dies when IMAPAppendMessageOperation is started

### ISSUE THREAD

**Issue by glosterva** [MailCore/mailcore2#1227]
When running this in the emulator, everything is fine up through getting the IMAPAppendMessageOperation object, but when the operation is started, neither the succeeded nor the failed callback is called, and the emulator shows a message box saying that the app has stopped.

                        byte[] messageData = getMessageData();
                        IMAPAppendMessageOperation appendOp = MessagesSyncManager.singleton().session.appendMessageOperation("Drafts", messageData, 0);
                        appendOp.start((OperationCallback) fragmentView);

**Comment by glosterva** [comment]
@dinhviethoa if you have a build with your recent fixes for missing Java-to-native object translation objects, I'd be glad to test whether it also fixes this problem.

**Comment by githupfisher** [comment]
when to fix it

**Comment by dinhviethoa** [comment]
I uploaded a new build for Android 16.
