### ISSUE TITLE
The requested folder does not exist. Folder selection failed

### ISSUE THREAD

**Issue by xingheng** [MailCore/mailcore2#1228]
I check the existing issues #330 , #366 , #1201 , the airmail blog site and stackover flow, there is no any useful result for me, please help to check the log, great thanks!

Currently I used mailcore2-ios with pod, version 0.5.1.

I tracked the log with connectionLogger, here is the output.

```
2015-09-17 15:42:12.019 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 0, data: * OK Coremail System IMap Server Ready(163com[726cd87d72d896a1ac393507346040fa])

2015-09-17 15:42:12.023 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 1, data: 1 CAPABILITY

2015-09-17 15:42:12.027 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 0, data: * CAPABILITY IMAP4rev1 XLIST SPECIAL-USE ID LITERAL+ STARTTLS XAPPLEPUSHSERVICE UIDPLUS X-CM-EXT-1

1 OK CAPABILITY completed

2015-09-17 15:42:12.027 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 2, data: 2 LOGIN "mymail@163.com" mypassword

2015-09-17 15:42:12.106 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 0, data: 2 OK LOGIN completed

2015-09-17 15:42:12.106 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 1, data: 3 CAPABILITY

2015-09-17 15:42:12.115 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 0, data: * CAPABILITY IMAP4rev1 XLIST SPECIAL-USE ID LITERAL+ STARTTLS XAPPLEPUSHSERVICE UIDPLUS X-CM-EXT-1

3 OK CAPABILITY completed

2015-09-17 15:42:12.115 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 1, data: 4 LIST "" ""

2015-09-17 15:42:12.118 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 0, data: * LIST (\Noselect) "/" ""

4 OK LIST Completed

2015-09-17 15:42:12.118 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 1, data: 5 ID NIL

2015-09-17 15:42:12.131 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 0, data: * ID ("name" "Coremail Imap" "vendor" "Mailtech" "TransID" "244/DQDHmNTUbvpV")

5 OK ID completed

2015-09-17 15:42:12.131 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 1, data: 6 XLIST "" "*"

2015-09-17 15:42:12.146 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 0, data: * XLIST (\Inbox) "/" "INBOX"

* XLIST (\Drafts) "/" "&g0l6P3ux-"

* XLIST (\Sent) "/" "&XfJT0ZAB-"

* XLIST (\Trash) "/" "&XfJSIJZk-"

* XLIST (\Spam) "/" "&V4NXPpCuTvY-"

* XLIST () "/" "&dcVr0mWHTvZZOQ-"

6 OK XLIST Completed

2015-09-17 15:42:12.149 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 1, data: 7 SELECT INBOX

2015-09-17 15:42:12.155 HRWNReceiver[86515:58216456] ID: 0x7fe38bd4b300, type: 0, data: 7 NO SELECT The login is not safe! Please update your mail client: http://mail.163.com/dashi

2015-09-17 15:42:12.157 HRWNReceiver[86515:58216369] Error downloading message headers:Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed" UserInfo=0x7fe38bc3f690 {NSLocalizedDescription=The requested folder does not exist.  Folder selection failed}
2015-09-17 15:42:12.157 HRWNReceiver[86515:58216369] The post man delivereth:(null)
```

Here is my code:

    MCOIMAPSession *session = [[MCOIMAPSession alloc] init];
    [session setHostname:@"imap.163.com"];
    [session setPort:993];
    [session setUsername:@"mymail@163.com"];
    [session setPassword:@"mypassword"];
    [session setConnectionType:MCOConnectionTypeTLS];
    
    session.connectionLogger = ^ (void * connectionID, MCOConnectionLogType type, NSData * data) {
        NSLog(@"ID: %p, type: %ld, data: %@", connectionID, type, [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
    };
    
    
    MCOIMAPFetchFoldersOperation *folderOperation = [session fetchAllFoldersOperation];
    [folderOperation start:^(NSError *error, NSArray *folders) {
        if (error) {
            NSLog(@"%@", error);
        }
        
        
        MCOIMAPFolder *imapFolder = folders[0];
        
        NSArray * sections = [imapFolder.path componentsSeparatedByString:[NSString stringWithFormat:@"%c",imapFolder.delimiter]];
        NSString *folderName = [sections lastObject];
        //Mailbox names are 7-bit.
        const char *stringAsChar = [folderName cStringUsingEncoding:[NSString defaultCStringEncoding]];
        folderName = [NSString stringWithCString:stringAsChar encoding:CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingUTF7_IMAP)];
        
        NSString *folder = folderName; // point to "INBOX"
        
        MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindHeaders;
        MCOIndexSet *uids = [MCOIndexSet indexSetWithRange:MCORangeMake(1, UINT64_MAX)];
        
        MCOIMAPFetchMessagesOperation *fetchOperation = [session fetchMessagesOperationWithFolder:folder requestKind:requestKind uids:uids];
        
        [fetchOperation start:^(NSError * error, NSArray * fetchedMessages, MCOIndexSet * vanishedMessages) {
            //We've finished downloading the messages!
            
            //Let's check if there was an error:
            if(error) {
                NSLog(@"Error downloading message headers:%@", error);
            }
            
            //And, let's print out the messages...
            NSLog(@"The post man delivereth:%@", fetchedMessages);
        }];
    }];

The target folder is INBOX, not the DRAFT, so I don't think there are some permission issues here like Gmail.

Any ideas are appreciate, thanks!

**Comment by dinhviethoa** [comment]
Could you build the library with the xcode project instead of using cocoapods?

**Comment by mqmq** [comment]
https://github.com/MailCore/mailcore2/pull/1086  @dinhviethoa  now 163 server，Refused again

**Comment by limaomt** [comment]
Me have this Issue too，do you solve it?

**Comment by dinhviethoa** [comment]
Use HEAD of this repository.

**Comment by frankobe** [comment]
163 mail provides request additional IMAP4 ID extension. you should contact mail provider to clarify

**Comment by youzhenyu** [comment]
For a long time...Solved?

**Comment by youzhenyu** [comment]
@frankobe  Can you tell me how to do?

**Comment by tigerZhang86** [comment]
@youzhenyu i have same issue , do you solve it?

**Comment by sachil** [comment]
Yes.I have the same problem when I use the Android version

**Comment by youzhenyu** [comment]
@tigerZhang86  163 problem.
Below is I used is no problem.
[self.imapSession.defaultNamespace pathForComponents:@[@"已发送"]];
[self.imapSession.defaultNamespace pathForComponents:@[@"已删除"]];
[self.imapSession.defaultNamespace pathForComponents:@[@"草稿夹"]];

**Comment by tigerZhang86** [comment]
@youzhenyu  thanks i will try it!

**Comment by vin-zhou** [comment]
@youzhenyu  still have the problem. It equals the value we get from MCOIMAPFolder.path. 
Could you provide more codes?  Thanks!

**Comment by vin-zhou** [comment]
@tigerZhang86 I got the same issue. Is youzhenyu's solution works for you?

**Comment by youzhenyu** [comment]
@vin-zhou  You probably want this
MCOIMAPFetchNamespaceOperation * op = [self.imapSession fetchNamespaceOperation];
    op.urgent=YES;
    [op start:^(NSError * __nullable error, NSDictionary * namespaces) {
        if (error != nil)
            return;
        MCOIMAPNamespace * ns = [namespaces objectForKey:@"IMAPNamespacePersonal"];
        if (ns!=nil) {
            self.imapSession.defaultNamespace=ns;
        }
    }];

**Comment by vin-zhou** [comment]
@youzhenyu Really great to hear your reply, thanks! However, using the codes you provide, I just get the error "Error Domain=MCOErrorDomain Code=22 "An error occurred while requesting the server's namespace." I use "imapSession.connectionType = MCOConnectionTypeTLS;" for 163 mail.  Is it caused by the connectionType?

**Comment by vin-zhou** [comment]
@youzhenyu in addition, when I use "NSString* lFolderName = [[self.imapSession defaultNamespace] componentsFromPath:folder.path][0];", it's OK to get  "已发送" as lFolderName  for  path value " &XfJT0ZAB-". And  " [self.imapSession.defaultNamespace pathForComponents:@[@"已发送"]];" will also translate "已发送“ to "&XfJT0ZAB-".   However, using this "&XfJT0ZAB-", still get the "The requested folder does not exist" error. That's really strange...

**Comment by youzhenyu** [comment]
@vin-zhou  163 A bit of trouble. 
Before 163 was a large number of hacking, if you want the third room to log in your mailbox will probably receive an e-mail, similar to the exemption agreement. You agreed to use. First solve this problem

**Comment by vin-zhou** [comment]
@youzhenyu  I did use the third-party code(授权码) to login and can successfully login and get all the folderNames. The folderNames include "&XfJT0ZAB-" ( it equals "已发送” if you use " [[self.imapSession defaultNamespace] componentsFromPath:folder.path][0];". What wired me is that use this value as folderName in " [self.imapSession folderInfoOperation:folderName];", I can just get the error "Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed",  while these codes work for QQ mail. Any suggestions?

**Comment by vin-zhou** [comment]
@youzhenyu , thanks a lot for your answer!  It did caused by the 163 server forbidden. Using this 
"On the bottom of the email, they provided a link to the configure page:
http://config.mail.163.com/settings/imap/index.jsp?uid=YOUR_EMAIL_NAME@126.com
Replace YOUR_EMAIL_NAME by yourself."
from  http://stackoverflow.com/questions/27797705/python-login-163-mail-server 

Problem solved.  Thanks again.

**Comment by youzhenyu** [comment]
@vin-zhou 
QQ does not need coding. The folder name in English online check should be used
