### ISSUE TITLE
Non-public iOS API usage

### ISSUE THREAD

**Issue by dafdafydd** [MailCore/mailcore2#1229]
Hello,

I've just submitted a binary to the App Store and it was turned down as invalid due to 'non-public API usage'. It uses the following method names: _tidyBufAppend, _tidyBufFree, _tidyBufInit, _tidyCleanAndRepair, _tidyCreate, _tidyOptSetBool, _tidyOptSetInt, _tidyParseBuffer, _tidyRelease, _tidySaveBuffer, _tidySetCharEncoding, _tidySetErrorBuffer

I spotted them in the mailcore2 code in file MCHTMLCleaner.cpp. 

I would be grateful for any help with that.

**Comment by dafdafydd** [comment]
It seems it happens only if I build the app with MailCore installed via Pods. When I added MailCore manually, there is no invalid binary problem in iTunes Connect.

I would be grateful for any help with that. Manual installation generates ~200 warnings ld: warning: object file ... was built for newer iOS version (9.0) than being linked (8.3).

**Comment by dinhviethoa** [comment]
Could you try with the new build?
I added a namespace for tidy. It will preevent such issue from happening.
The warnings have also been fixed with the new pre-built binaries.
