### ISSUE TITLE
Recently added news-groups (and articles)

### ISSUE THREAD

**Issue by CTMacUser** [MailCore/mailcore2#1231]
Looking at pull #924 (which handles issue #894), there was a comment by @CodaFi (at https://github.com/MailCore/mailcore2/pull/924#issuecomment-60173156) about the request on listing the newest newsgroups. Was he thinking about applying heroic measures on the XOVER database to do the query? Because there has been a specific command for this task since the first version of NNTP: NEWGROUPS. (There is a NEWNEWS variant for the newest articles.) Or were these the commands that have the issues preventing completion?

**Comment by dinhviethoa** [comment]
I'm not sure what you are looking for. Both commands are available through the API.

**Comment by dinhviethoa** [comment]
I'm closing it since there's no further details. Reopen if you have more details.
