### ISSUE TITLE
MCOMessageBuilder - Designated initializer invoked a non-designated initializer

### ISSUE THREAD

**Issue by hsalaheddine** [MailCore/mailcore2#1232]
Hello, with changeover to ios 9 I had this warning do you have an idea about this error   MCOMessageBuilder.mm:26:1: Designated initializer missing a 'super' call to a designated initializer of the super class  MCOMessageBuilder.mm:29:19: Designated initializer invoked a non-designated initializer

thank you in advance for any help

<img width="818" alt="capture d ecran 2015-09-19 a 13 29 39" src="https://cloud.githubusercontent.com/assets/5064624/9976152/83d53432-5ed2-11e5-9b7c-a2971a7d5c87.png">
<img width="1177" alt="capture d ecran 2015-09-19 a 13 29 22" src="https://cloud.githubusercontent.com/assets/5064624/9976153/844945f2-5ed2-11e5-9fba-6945312d31f8.png">

**Comment by dinhviethoa** [comment]
Please update to the latest commit.
It's been fixed a few days ago.
https://github.com/MailCore/mailcore2/commit/5be4a51db5a247d8a1ca25e0bc7b4782491e6425

**Comment by hsalaheddine** [comment]
it's working perfectly

Thank you
