### ISSUE TITLE
osx [_webView setResourceLoadDelegate:self]; MCOMessageView.mm

### ISSUE THREAD

**Issue by sundsx** [MailCore/mailcore2#1233]
Hi there, after udpated xcode to version 7 my app get an error. Before update It worked!
method:
    - (id)initWithFrame:(NSRect)frame
    {
    self = [super initWithFrame:frame]; 
    _webView = [[WebView alloc] initWithFrame:[self bounds]];
    [_webView setAutoresizingMask:NSViewHeightSizable | NSViewWidthSizable];
    //PROBLEM HERE
    [_webView setResourceLoadDelegate:self];
    [self addSubview:_webView];   
    return self;
    }
![schermata 2015-09-21 alle 18 34 44](https://cloud.githubusercontent.com/assets/1713528/9999412/965a45a0-6096-11e5-85dc-5f2d78526eeb.png)
i have also update at latest mailcore framework but still there. What happen?
thank you i know that you have a lot of work, I was very close to release my app...

**Comment by dinhviethoa** [comment]
Is it a class in your app or in mailcore2?
If that's in mailcore2, could you point out the file / line of code?
Thanks.

**Comment by sundsx** [comment]
Hi, the class is is MCOMessageView.mm in OS X example at line 43. I have found the way rewriting my custom class for render a message in web view.... a tons of work. Anyway if someone try to  the test example, maybe, will find this problem. i provide you a code snipped, Thank you

    #import "MCOMessageView.h"
    #import <WebKit/WebKit.h>
    #import "MCOCIDURLProtocol.h"
     @interface MCOMessageView () <MCOHTMLRendererIMAPDelegate>
     @end
     @implementation MCOMessageView {
     WebView * _webView;
     NSString * _folder;
     MCOAbstractMessage * _message;
     id<MCOMessageViewDelegate> delegate;
     BOOL _prefetchIMAPImagesEnabled;
     BOOL _prefetchIMAPAttachmentsEnabled;0
     }

     @synthesize folder = _folder;
     @synthesize delegate = _delegate;
     @synthesize prefetchIMAPImagesEnabled = _prefetchIMAPImagesEnabled;
     @synthesize prefetchIMAPAttachmentsEnabled = _prefetchIMAPAttachmentsEnabled;

     + (void) initialize
     {
     [MCOCIDURLProtocol registerProtocol];
     }

     - (id)initWithFrame:(NSRect)frame
     {
    self = [super initWithFrame:frame];
    
     if (self) {
        _webView = [[WebView alloc] initWithFrame:[self bounds]];
        [_webView setAutoresizingMask:NSViewHeightSizable | NSViewWidthSizable];      
        //[_webView setResourceLoadDelegate:self];
      }
      return self;
      }

**Comment by dinhviethoa** [comment]
Fixed.
