### ISSUE TITLE
libetpan fails linker in xcode 7

### ISSUE THREAD

**Issue by aallard** [MailCore/mailcore2#1234]
Had mailcore working perfectly in my app until I upgraded to xcode 7.  Now compile fails at linker step with the following message:

...Products/Debug-iphoneos/libetpan-ios.a(chash.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

Any ideas?

**Comment by juliangsp** [comment]
At your MAIN project settings try configuring ENABLE_BITCODE to NO. See this answer:

http://stackoverflow.com/a/30856364

**Comment by dinhviethoa** [comment]
Please update mailcore2 to HEAD to get the support for bitcode.
If you're using Cocoapods, Cocoapods don't support bitcode.
