### ISSUE TITLE
Multiple binaries share the same codesign path Error on Signing App

### ISSUE THREAD

**Issue by sundsx** [MailCore/mailcore2#1237]
Hi. after archiving app, when i try to Sign Application an error come up:
Multiple binaries share the same codesign path:

    Multiple binaries share the same codesign path:
    /Applications/FenceBase.app/Contents/Frameworks/MailCore.framework/Versions/Current

    Binaries:
    /Applications/FenceBase.app/Contents/Frameworks/MailCore.framework/MailCore
    /Applications/FenceBase.app/Contents/Frameworks/MailCore.framework/Versions/Current/MailCore

     This can happen if your build process copies frameworks by following symlinks. 

![schermata 2015-09-27 alle 12 34 14](https://cloud.githubusercontent.com/assets/1713528/10122341/7cebf882-6516-11e5-8545-805166cc958a.png)
 
After an investigation on stackoverflow my suspect fall on symbol link in mailcore2 framework. 

This in root in may app:
![schermata 2015-09-27 alle 12 52 33](https://cloud.githubusercontent.com/assets/1713528/10122373/74d6e0b6-6517-11e5-8fa5-90ea1b831c16.png)

So what i should to do: delete a directory MailCore.framework/Versions/Current/MailCore?

any suggestion?

Thank you for your great job that make every day with us.

**Comment by sundsx** [comment]
I ave found the solution: just remove "Version" Directory.
hope help

**Comment by dinhviethoa** [comment]
```
This can happen if your build process copies frameworks by following symlinks.
```

**Comment by aakrandan** [comment]
> I have found the solution: just remove "Version" Directory. hope help

This can't be the permanent fix to the problem? 
Every time before creating package should I manually delete the 'version' folder?
