### ISSUE TITLE
ios version linked fail

### ISSUE THREAD

**Issue by bulice** [MailCore/mailcore2#1238]
using the newest version, when linked, the error message:
duplicate symbol _llvm.cmdline in:
    /Users/liyang/Desktop/5.1.3.1/mxclient_ios/DerivedData/Build/Products/Debug-iphonesimulator/libctemplate-ios.a(template_namelist.o)
    /Users/liyang/Desktop/5.1.3.1/mxclient_ios/DerivedData/Build/Products/Debug-iphonesimulator/libctemplate-ios.a(jsparser.o)
duplicate symbol _llvm.embedded.module in:
    /Users/liyang/Desktop/5.1.3.1/mxclient_ios/DerivedData/Build/Products/Debug-iphonesimulator/libctemplate-ios.a(template_namelist.o)
    /Users/liyang/Desktop/5.1.3.1/mxclient_ios/DerivedData/Build/Products/Debug-iphonesimulator/libctemplate-ios.a(jsparser.o)
duplicate symbol _llvm.cmdline in:
    /Users/liyang/Desktop/5.1.3.1/mxclient_ios/DerivedData/Build/Products/Debug-iphonesimulator/libctemplate-ios.a(template_namelist.o)
    /Users/liyang/Desktop/5.1.3.1/mxclient_ios/DerivedData/Build/Products/Debug-iphonesimulator/libctemplate-ios.a(htmlparser.o)

and so on, please take a look.

**Comment by dinhviethoa** [comment]
Does it happen with Xcode 7?
Does it happen only on simulator?

**Comment by purlin07** [comment]
same problem
Xcode Version 6.3.1  IOS8.3

**Comment by purlin07** [comment]
update Xcode to 7.0.1 and It works

**Comment by dinhviethoa** [comment]
Great. Thanks.
