### ISSUE TITLE
auth type in providers.json?

### ISSUE THREAD

**Issue by rlaferla** [MailCore/mailcore2#1239]
can you specify auth type in providers.json and does it work?

**Comment by dinhviethoa** [comment]
It's usually auto detected.

**Comment by dinhviethoa** [comment]
oh... actually, it's not. We need to improve it in MCAccountValidator.

**Comment by rlaferla** [comment]
What is a reasonable default when the auth type is not known?  MCOAuthTypeSASLPlain?  Also, we need to specify it in providers.json.  There are no entries for it currently.

**Comment by dinhviethoa** [comment]
For IMAP or SMTP, that's MCOAuthTypeSASLNone.
SMTP will choose automatically what's best.
IMAP will do a simple LOGIN.

**Comment by virtru-bjost** [comment]
@dinhviethoa you stated above that SMTP is automatically detected. However, it seems that MCOAuthTypeSASLNone is being used when the server we try to connect too doesn't support it. Is there an option that needs to be enabled for this auto detection to work if the specified authType is not supported?

**Comment by dinhviethoa** [comment]
Could you create a different issue and show the server logs (using connectionLogger)?
