### ISSUE TITLE
MailCore2 not usable in waiting thread

### ISSUE THREAD

**Issue by hblockx** [MailCore/mailcore2#1240]
Hello!

For my current project i need to check success of the sendoperation synchronous. I tried different ways to wait for the completion block, but it never is called (thread sleep, dispatchgroups with wait,...). Without waiting for the operation some times the send operation is started 20seconds later. Anybody knows a way to deal with it? Using the project with ARC and setting a own queue crashes. MailCore uses release_queue which is unavailable with ARC enabled.

Thank you very much for the great project!

**Comment by hblockx** [comment]
By wrapping the MailCore and setting a linkerf-lag the arc problem is solveable. Sadly the send operation still starts/ ends after 20seconds.

**Comment by dinhviethoa** [comment]
I don't really understand the issue here. Could you show some code?

**Comment by dinhviethoa** [comment]
Since there's no update, I'm closing the issue. Reopen if you have more info.
