### ISSUE TITLE
Outlook.com oauth example?

### ISSUE THREAD

**Issue by rlaferla** [MailCore/mailcore2#1241]
Is there some example code that shows how to use Oauth and mailcore?  e.g.  with outlook.com

**Comment by guidedways** [comment]
rlaferla did you find one?

**Comment by rlaferla** [comment]
No.  If you see a good OAuth example, let me know.

**Comment by yasinbor** [comment]
Sorry to pop after a year, is there anyone who know any outlook example with mailcore? Can't pass OAuth process and Mailcore always says "Unable to authenticate with current session credentials." while i can send mail with Office365 SDK with same token.

**Comment by wengxianxun** [comment]
any news
