### ISSUE TITLE
mailcore fails to connect to outlook.com SMTP

### ISSUE THREAD

**Issue by rlaferla** [MailCore/mailcore2#1242]
Using smtp-mail.outlook.com, port 587 (also 25), TLS and Plain authType yields: “A stable connection to the server could not be established.”

1.  Is it that my client is being blocked?
2.  Does Outlook require a different authentication type?  e.g.  OAuth.
3.  If it requires OAuth, can you point me to a iOS mailcore example w/OAuth?

**Comment by dinhviethoa** [comment]
You should use startles to connect to port 587 or 25.

**Comment by rlaferla** [comment]
Thanks!
