### ISSUE TITLE
Why does MCOIMAPIdleOperation's block execute everytime when I finish an MCOIMAPFetchContentOperation?

### ISSUE THREAD

**Issue by aquaibm** [MailCore/mailcore2#1243]
Codes are as follows.
[pIdleOperation start:^(NSError *error) {----}];

And then at some point

[pIdleOperation interruptIdle];
[fetchMessagesOperation start:^(NSError *errorA, NSArray *messages, MCOIndexSet *vanishedMessages) {------}];

Ever since an fetchMessagesOperation is done, pIdleOperation's start block is excuted? Why is this happening?

**Comment by dinhviethoa** [comment]
because the block you pass to start is executed whenever the idleoperation finishes and as soon as the runloop is available.
It's probably after you started the fetchMessagesOperation.

**Comment by aquaibm** [comment]
Still doesn’t get it, so now I want idleOperation's block get excuted ONLY there are new messages coming, not after fetchMessagesOperation I started. How can I do that? Thanks.

**Comment by dinhviethoa** [comment]
When you call interruptIdle, the block is executed. That's how it works. You can probably figure out how to distinguish between being notified by IDLE or being interrupted.

**Comment by aquaibm** [comment]
Oh, got it. I thought interruptIdle means pause and do nothing, so actually it means the opposite way....
Thanks.
