### ISSUE TITLE
Dependences are build using iOS9 SDK

### ISSUE THREAD

**Issue by MrRage** [MailCore/mailcore2#1250]
Dependences are built using iOS9 SDK. The app I'm working on targets iOS8 and this generates a lot of warnings. This will probably be irrelevent in the near future but for now it's generating 400 warnings so I can't use this build and had to revert to an older checkout.

**Comment by dinhviethoa** [comment]
Hi,
You just have to set the target to iOS 9 and set the deployment target to iOS 8.

**Comment by MrRage** [comment]
I'm going to look into it a little more but according to the build logs, it's using the iOS9 SDK and has the deployment target set to iSO8.

Ld /Users/dustin/Library/Developer/Xcode/DerivedData/Chiaramail-fldhkbsrbalagsafhrkcubupiuuv/Build/Products/Debug-iphonesimulator/MailCore.framework/MailCore normal i386
    cd /Users/dustin/ChiaraMail/mailCore2/build-mac
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/dustin/Library/Developer/Xcode/DerivedData/Chiaramail-fldhkbsrbalagsafhrkcubupiuuv/Build/Products/Debug-iphonesimulator -L/Users/dustin/ChiaraMail/mailCore2/build-mac/../Externals/libetpan-ios/lib -L/Users/dustin/ChiaraMail/mailCore2/build-mac/../Externals/ctemplate-ios/lib -L/Users/dustin/ChiaraMail/mailCore2/build-mac/../Externals/libsasl-ios/lib -L/Users/dustin/ChiaraMail/mailCore2/build-mac/../Externals/tidy-html5-ios/lib -F/Users/dustin/Library/Developer/Xcode/DerivedData/Chiaramail-fldhkbsrbalagsafhrkcubupiuuv/Build/Products/Debug-iphonesimulator -filelist /Users/dustin/Library/Developer/Xcode/DerivedData/Chiaramail-fldhkbsrbalagsafhrkcubupiuuv/Build/Intermediates/mailcore2.build/Debug-iphonesimulator/mailcore\ ios.build/Objects-normal/i386/MailCore.LinkFileList -install_name @rpath/MailCore.framework/MailCore -mios-simulator-version-min=8.0 -Xlinker -objc_abi_version -Xlinker 2 -lctemplate-ios -letpan-ios -lxml2 -lsasl2 -liconv -ltidy -lz -ObjC -lresolv -stdlib=libc++ -fobjc-link-runtime -lMailCore-ios -framework CFNetwork -framework Security -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/dustin/Library/Developer/Xcode/DerivedData/Chiaramail-fldhkbsrbalagsafhrkcubupiuuv/Build/Intermediates/mailcore2.build/Debug-iphonesimulator/mailcore\ ios.build/Objects-normal/i386/MailCore_dependency_info.dat -o /Users/dustin/Library/Developer/Xcode/DerivedData/Chiaramail-fldhkbsrbalagsafhrkcubupiuuv/Build/Products/Debug-iphonesimulator/MailCore.framework/MailCore

ld: warning: object file (/Users/dustin/Library/Developer/Xcode/DerivedData/Chiaramail-fldhkbsrbalagsafhrkcubupiuuv/Build/Products/Debug-iphonesimulator/libctemplate-ios.a(template_namelist.o)) was built for newer iOS version (9.0) than being linked (8.0)

**Comment by MrRage** [comment]
IPHONEOS_DEPLOYMENT_TARGET is suppose to be set to iOS 8 because MinimumOSVersion is set to 8. It's using the iOS9 SDK though. I forget how you check this but I think the .o files are targetting iOS9 and that's why it's generating warnings.

https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html

**Comment by dinhviethoa** [comment]
Maybe I'm missing something. I'll investigate. Thanks.

**Comment by dinhviethoa** [comment]
Could you try to update to HEAD and let me know if there's still an issue?

**Comment by MrRage** [comment]
Sure I can try that out Monday or Tuesday.

-Dustin

**Comment by MrRage** [comment]
I cloned the repository again this mornign, last commit was: de7acf0.

Same issue. The dependences need to be compiled for iOS8 and linked only for iOS8 (as well as 9), or have their source so that way they can be built for what ever SDK is currently being used.

**Comment by dinhviethoa** [comment]
I think something went wrong with my previous binaries.
I uploaded new binaries. Could you try again? Thanks!

**Comment by MrRage** [comment]
Works as expected =) Thanks!
