### ISSUE TITLE
ERROR fetching attachment Error Domain=MCOErrorDomain Code=19

### ISSUE THREAD

**Issue by rlaferla** [MailCore/mailcore2#1255]
I'm trying to fetch an attachment and I'm getting this error.  I enabled connection logging and this is what it says.  The one thing that stands out is the "BAD Could not parse command" error.  What's going on?

```
 __34-[xxx]_block_invoke [Line 244] Data String :: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $Forwarded $Junk $NotJunk $NotPhishing $Phishing JunkRecorded NotJunk)
* OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $Forwarded $Junk $NotJunk $NotPhishing $Phishing JunkRecorded NotJunk \*)] Flags permitted.
* OK [UIDVALIDITY 633835109] UIDs valid.
* 38226 EXISTS
* 0 RECENT
* OK [UIDNEXT 58719] Predicted next UID.
* OK [HIGHESTMODSEQ 6516072]
8 OK [READ-WRITE] INBOX selected. (Success)
 __34-[xxx]_block_invoke [Line 242] IMAP LOG: Type 1 :: Data: <39205549 44204645 54434820 35383731 3820424f 44592e50 45454b5b 305d0d0a>
 __34-[xxx]_block_invoke [Line 244] Data String :: 9 UID FETCH 58718 BODY.PEEK[0]
 __34-[xxx]_block_invoke [Line 242] IMAP LOG: Type 0 :: Data: <39204241 4420436f 756c6420 6e6f7420 70617273 6520636f 6d6d616e 640d0a>
 __34-[xxx]_block_invoke [Line 244] Data String :: 9 BAD Could not parse command
 __69-[xxx:]_block_invoke_2 [Line 150] ERROR fetching attachment Error Domain=MCOErrorDomain Code=19 "An error occurred while fetching messages in the requested folder." UserInfo={NSLocalizedDescription=An error occurred while fetching messages in the requested folder.}
```

**Comment by dinhviethoa** [comment]
Could you show the code you use to fetch the attachment?
BODY.PEEK[0] probably means that you're trying to fetch the attachment with identifier 0.
It's an incorrect attachment identifier.

**Comment by rlaferla** [comment]
I'm using fetchMessageAttachmentOperationWithFolder and I am indeed using the incorrect identifier (0)  because I was using the uniqueID from a MCOAttachment.  Given a MCOAttachment instance, how can I get the partID?

**Comment by dinhviethoa** [comment]
If you have a MCOAttachment, it means that you already have the data. just use -[MCOAttachment data]

**Comment by rlaferla** [comment]
Is there anyway to determine if there are any attachments before downloading the whole message?  Something like hasAttachments or numAttachments?

**Comment by dinhviethoa** [comment]
If you use fetchMessages with the MCOIMAPMessagesRequestKindStructure, you'll be able to list the attachments.

```
@interface MCOIMAPSession
- (MCOIMAPFetchMessagesOperation *) fetchMessagesOperationWithFolder:(NSString *)folder
                                                         requestKind:(MCOIMAPMessagesRequestKind)requestKind
                                                                uids:(MCOIndexSet *)uids;
```

If you'd like to download only the text part, my recommendation would be to use

```
@interface MCOIMAPMessage
- (NSString *) htmlRenderingWithFolder:(NSString *)folder
                              delegate:(id <MCOHTMLRendererIMAPDelegate>)delegate;
```

**Comment by rlaferla** [comment]
Thanks.  What about for POP?

**Comment by dinhviethoa** [comment]
I don't think you have much choice. You need to download the full message with POP.

**Comment by rlaferla** [comment]
Isn't the Content-Type part of the message header?  I don't see it in MCOMessageHeader though.
