### ISSUE TITLE
uids fetched from gmail folder can be wrong occasionally

### ISSUE THREAD

**Issue by frankobe** [MailCore/mailcore2#1256]
i discover an issue when fetch uids from certain gmail folder using:
```Obj-c
MCOIndexSet *uidSet = [MCOIndexSet indexSetWithRange:MCORangeMake(localFirstUID, UINT64_MAX)]

MCOIMAPFetchMessagesOperation *fetchOperation =
    [self.imapSession fetchMessagesOperationWithFolder:folder
                                                requestKind:(MCOIMAPMessagesRequestKindFlags)
                                                       uids:uidSet];

[fetchOperation start: completionBlock];
```

Occasionally returned message uidset can miss a few uids compared with my local uid dataset. But for the next time fetching, those missed message can be found. I verify messages with missed uids belong to the folder based on gmail web.

The chance it happened can be around 1/50. I doubt it can be an error with gmail server return.

Just raise this to see who else encounter the similar issue. If it is true, double check needed when synchronizing between local and server

**Comment by dinhviethoa** [comment]
If you can reproduce, can you show connectionLogger logs? Thanks.

**Comment by frankobe** [comment]
In ConnectionLog: uid with 

* 16703 FETCH (X-GM-THRID 1515560500378804295 X-GM-MSGID 1515560500378804295 X-GM-LABELS () UID 32041 MODSEQ (2848117) INTERNALDATE "20-Oct-2015 14:25:24 +0000" FLAGS () ENVELOPE ("Tue, 20 Oct 2015 14:25:24 -0000" "This sale is sooo worth it." (("Anthropologie" NIL "Anthropologie" "email2.anthropologie.com")) (("Anthropologie" NIL "Anthropologie" "email2.anthropologie.com")) (("Anthropologie" NIL "support-b8hmpctb4xyhmuaupxg8vqc9bfgp0h" "email2.anthropologie.com")) ((NIL NIL "brownkun" "gmail.com")) NIL NIL NIL "<b8hmpctb4xyhmuaupxg8vqc9bfgp0h.14714997268.4784@mta614.email2.anthropologie.com>") BODYSTRUCTURE (("TEXT" "PLAIN" ("CHARSET" "iso-8859-1") NIL NIL "8BIT" 771 24 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "iso-8859-1") NIL NIL "QUOTED-PRINTABLE" 15832 334 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "=b8hmpctb4xyhmuaupxg8vqc9bfgp0h") NIL NIL) BODY[HEADER.FIELDS (References Message-Id)] {97}

Message-ID: <b8hmpctb4xyhmuaupxg8vqc9bfgp0h.14714997268.4784@mta614.email2.anthropologie.com>



)

* 16704 FETCH (X-GM-THRID 1515560667191600560 X-GM-MSGID 1515560667191600560 X-GM-LABELS () UID 32042 MODSEQ (2848062) INTERNALDATE "20-Oct-2015 14:28:03 +0000" FLAGS () ENVELOPE ("Tue, 20 Oct 2015 14:28:02 +0000" "Ryan Hoover just posted \"Squad\" on Product Hunt" (("Product Hunt" NIL "hello" "producthunt.com")) (("Product Hunt" NIL "hello" "producthunt.com")) (("Product Hunt" NIL "hello" "producthunt.com")) ((NIL NIL "brownkun" "gmail.com")) NIL NIL NIL "<56264f6f5ba94_33fb70ad07108960771@005ea4ac-bf26-4fbe-9244-1f5a277e07cd.mail>") BODYSTRUCTURE (("TEXT" "PLAIN" ("CHARSET" "utf-8") NIL NIL "QUOTED-PRINTABLE" 4786 80 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "utf-8") NIL NIL "QUOTED-PRINTABLE" 10075 288 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "_av-N0mugxxKZPGKX37f5SYBAg") NIL NIL) BODY[HEADER.FIELDS (References Message-Id)] {93}

Message-Id: <56264f6f5ba94_33fb70ad07108960771@005ea4ac-bf26-4fbe-9244-1f5a277e07cd.mail>



)

**Comment by dinhviethoa** [comment]
MCORangeMake(32036, UINT64_MAX) means 32036 to +infinity.
Therefore, 32041 and 32042 will be included.

**Comment by frankobe** [comment]
Yes. I see them in uid log but not in message returned. Just wonder why

**Comment by dinhviethoa** [comment]
Could you show me the full connectionLogger? Thanks!

**Comment by frankobe** [comment]
any particular line are you interested in? the full logger can be very long

**Comment by frankobe** [comment]
after digging into the log, i think there are potentially uidset inconsistency in my code. So I will close the issue and thx for the help!
