### ISSUE TITLE
Android library release 2 works fine in emulator, but crashes on phones

### ISSUE THREAD

**Issue by glosterva** [MailCore/mailcore2#1257]
My application works well in the emulator, but when I run it on a phone, either by releasing it through Google Play Store for alpha test or by debugging when the phone is connected via USB, the application immediately crashes.  

So I tried using it with the Mailcore2 example application.  I just modified the user, password, host values to connect to my test account (and had it link to the new library), and the same thing happened; it worked well in the emulator, but crashed immediately in the phone.  When I single-step through the code, it crashes on the first call to a Mailcore2 function, the call to `session.fetchMessagesByNumberOperation()`.  It never gets to the operation to call `start()`.

When I pull apart the complex call, the `new Range()` works, but the `IndexSet.indexSetWithRange()` crashes.  If I replace it with `IndexSet.indexSetWithIndex()`, that also crashes.  If I do a `new IndexSet()` and add a single index, that works, but then the call to `session.fetchMessagesByNumberOperation()`. crashes.

I appreciate you releasing the new version 2 of the library; it fixes all but one of the problems I've seen in the past in the emulator, but unlike the previous version of the library, the basic operations that work on the emulator crash on phones, and I'm finding no workaround.  I've tried compiling targeting API 21 and 22 getting the behavior I describe.  When I try compiling it for API 16, I get tons of errors.  I've tried it on both Galaxy S5 and Galaxy S6 phones, and it exhibits this behavior on both of them.

**Comment by dinhviethoa** [comment]
Could you try the following build?
http://d.etpan.org/mailcore2-deps/mailcore2-android-beta/

**Comment by glosterva** [comment]
@dinhviethoa  Thanks for the quick response!  But the same thing happens on the later build.

**Comment by glosterva** [comment]
@dinhviethoa Any chance of this getting fixed any time soon?  We are at a point where if we can't get this working quickly, we need to drop Mailcore2 from the project.

**Comment by dinhviethoa** [comment]
Did you try to rebuild mailcore2 on android? If you're able to do it, I can give some additional instructions to try.

**Comment by glosterva** [comment]
@dinhviethoa  I'll try building it and get back to you.

**Comment by dinhviethoa** [comment]
I think I figured out what's going on.
I'll update a working build soon.

**Comment by glosterva** [comment]
@dinhviethoa Thanks!  I'm having trouble building mailcore2 on Windows 7.  It complains, ld.exe: error: cannot find -lc++_shared.

**Comment by dinhviethoa** [comment]
Could you try this build?
http://d.etpan.org/mailcore2-deps/mailcore2-android-beta/mailcore2-android-3-beta-2.aar
Thanks!

**Comment by glosterva** [comment]
@dinhviethoa I'll try it and get right back to you!

**Comment by glosterva** [comment]
@dinhviethoa Thanks!

**Comment by glosterva** [comment]
@dinhviethoa It seems to be working well!  Thanks!

**Comment by dinhviethoa** [comment]
Good news!
