### ISSUE TITLE
Android release 2 cannot clear all message flags

### ISSUE THREAD

**Issue by glosterva** [MailCore/mailcore2#1258]
In my application, we want to be able to clear the SEEN flag.  Normally, a message has no other flags set, so when I read the flags from the message, the value is 1.  When I clear the SEEN flag, the flags value becomes 0.  I then call `session.storeFlagsByUIDOperation()` with a 0 flags value and call `start()` on the operation.  Instead of `success()`, `failed()` is called with this exception:

com.libmailcore.MailException: An error occurred while storing flags.

Storing all the other values of flags I've tested succeeds.

**Comment by dinhviethoa** [comment]
You need to set MessageFlag.MessageFlagSeen and use IMAPStoreFlagsRequestKind.IMAPStoreFlagsRequestKindRemove.

**Comment by glosterva** [comment]
Ah, sorry, I didn't see that.  Thanks!
