### ISSUE TITLE
Crash when instantiating MCOAbstractMultipart

### ISSUE THREAD

**Issue by sampaioroberto** [MailCore/mailcore2#1260]
When I try to instantiate an object of the class **MCOAbstractMultipart** or **MCOAbstractPart** or **MCOMultipart** or any class related with "Part", it gets me a signal SIGABRT with this message:

    /Users/hoa/MailCore-Builds/dependencies/workdir/20150325173402/src/mailcore2-ios/src/objc/abstract/MCOAbstractPart.mm:32: assert 0'

The error occurs in this line:

    MCOAbstractMultipart *multipart = [[MCOAbstractMultipart alloc] init];

Anyone knows if it is a bug? Or am I doing something wrong here?
I would appreciate any help!

**Comment by dinhviethoa** [comment]
Could you tell me what are you trying to achieve?
You should just add several attachments to a MCOMessageBuilder to build a message.
