### ISSUE TITLE
MCOIMAPFolderFlagInbox not correct

### ISSUE THREAD

**Issue by ngminhduong** [MailCore/mailcore2#1261]
I try to use MCOIMAPFolderFlag to find which folder is Inbox.
But i can not . I have debug i found that value of MCOIMAPFolderFlag is 0 which folder path: INBOX.
This is my debug value. with flag and folder paths
 flags 0 - Call log 
 flags 0 - Certificates 
 flags 0 - INBOX 
 flags 0 - Notes 
 flags 0 - SMS 
 flags 4 - [Gmail] 
 flags 128 - [Gmail]/All Mail 
 flags 512 - [Gmail]/Drafts 
 flags 2048 - [Gmail]/Important 
 flags 32 - [Gmail]/Sent Mail 
 flags 1024 - [Gmail]/Spam 
 flags 64 - [Gmail]/Starred 
 flags 256 - [Gmail]/Trash 
this is my code.
```
            MCOIMAPNamespace * namespace = [namespaces objectForKey:MCOIMAPNamespacePersonal];
            MCOIMAPFetchFoldersOperation * op = [session fetchAllFoldersOperation];
            [session setDefaultNamespace:namespace];
            [op start:^(NSError *error, NSArray *folders) {
                dispatch_async(globalQueue, ^{
                    NSMutableArray *array = [NSMutableArray array];
                    NSString *domain = [account domain];
                    for (MCOIMAPFolder *tmp in folders) {
                        NSLog(@"flags %d - %@ ", tmp.flags, tmp.path);
                        if (tmp.flags == MCOIMAPFolderFlagInbox) {
                            NSLog(@"Folder inbox");
                        }
                    }
                });
                
            }];
```

I don't know how to do it.
Please help me. Thanks.

**Comment by dinhviethoa** [comment]
You should just match against the string "INBOX" to find the inbox.

**Comment by ngminhduong** [comment]
How about with yahoo ?
With yahoo mail. I can not get correct MCOIMAPFolderFlagInbox for all folder.
Thanks.

**Comment by dinhviethoa** [comment]
Yahoo doesn't implement that feature.

**Comment by ngminhduong** [comment]
Yes. Thanks for your help.
