### ISSUE TITLE
ld: library not found for -licudata

### ISSUE THREAD

**Issue by hughesne** [MailCore/mailcore2#1263]
Followed all the install instructions for iOS, client is a swift app, so using a Bridging-Header.h to import <MailCore/MailCore.h>

Building my project with any device, real or sim, i get a linker error:

ld: library not found for -licudata
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dinhviethoa** [comment]
You don't need to link with icu any more. Therefore remove -licudata from your linker flags.
