### ISSUE TITLE
MCOIMAPFolderInfoOperation and MCOIMAPFetchMessagesOperation doesnt work anymore if there is an instance of MCOIMAPIdleOperation that was started.

### ISSUE THREAD

**Issue by IuliuMoga** [MailCore/mailcore2#1264]
After i'm fetching the newest messages list then im adding next piece of code

```
  MCOIMAPSession *imapSession = self.mailBox.imapSession;
   if (imapSession && self.messages.count) {
      self.idleOperation = [imapSession idleOperationWithFolder:self.imapFolder.path
                                       lastKnownUID:[self.newestMessage uid]];
            
            [self.idleOperation start:^(NSError *error) {
                if (!error) {
                    
                }
                
            }];
        }
  ```

and when I try to scroll down and fetch oldest first im fetching the folder info MCOIMAPFolderInfoOperation and this is doesnt work No timeout no answer, no nothing , somehow is stuck in an unknown state, and when i'm receiving a new email the idle operation is invoking the completion block without error, and the curious part is that my initial's newest emails fetch operation completion block is invoked.

From here 3 questions:
1.Isn't MCOIMAPFetchMessagesOperation to autodestroy after completion?
2.Is MCOIMAPIdleOperation blocking all MCOIMAPFolderInfoOperation and MCOIMAPFetchMessagesOperation.
3.Is  MCOIMAPIdleOperation caching refferences to all MCOIMAPFetchMessagesOperation (if the answer to first question is NO) and then invoking the fetch result?

Thanks!
Have a nice day.

**Comment by dinhviethoa** [comment]
1. I'm not sure what you mean by autodestroy.
2. MCOIMAPIdleOperation is going to potentially block all IMAP requests. You have to stop it to make sure that any other request will go through. All operations may end up in the same queue and as long as MCOIMAPIdleOperation is not finished, everything will be stuck.

**Comment by IuliuMoga** [comment]
Thanks for response, now everything is clear to me, and regarding "autodestroy" i wanted to say if an operation, once it is executed, is it removed from queue and implicitly released?

**Comment by dinhviethoa** [comment]
It is.
