### ISSUE TITLE
Error building mailcore2 for Android on Windows 7

### ISSUE THREAD

**Issue by glosterva** [MailCore/mailcore2#1267]
When building mailcore2 for Android on Windows 7 I get the following error:

[x86] SharedLibrary  : libMailCore.so
C:/cygwin64/a-ndk/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/i686-linux-android/4.9/../../../../i686-linux-android/bin/ld.exe: error: cannot find -lc++_shared

At the beginning I get this warning:

Android NDK: WARNING:/mc2/build-android/jni/Android.mk:MailCore: non-system libraries in linker flags: -lc++_shared
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module

I've been through all the Cygwin packages and can't find this library, nor can I find a reference to it on StackOverflow.

**Comment by dinhviethoa** [comment]
It's located in the Android NDK.
