### ISSUE TITLE
Mailcore2 unable to parse email date

### ISSUE THREAD

**Issue by jnseward** [MailCore/mailcore2#1270]
Mailcore2 is unable to parse some email dates, and instead substitutes the current date. Here is an example of an email date field that causes this behavior:

Date: Tue Jul 24 18:55:07 2007

**Comment by dinhviethoa** [comment]
Yes. That's an invalid date :(

**Comment by jnseward** [comment]
I have a MailSteward customer who has a lot email with dates like that.

**Comment by dinhviethoa** [comment]
You might want to investigate a patch in libetpan (https://github.com/dinhviethoa/libetpan/).
