### ISSUE TITLE
Trying to add SMTP to the Android project,but code crashes

### ISSUE THREAD

**Issue by githupfisher** [MailCore/mailcore2#1272]
List<Address> toList = new ArrayList<Address>();
        toList.add(Address.addressWithMailbox("yuhuifisher@icloud.com"));
        MessageBuilder builder = new MessageBuilder();
       builder.header().setFrom(Address.addressWithMailbox("yuhui@updays.net"));
       builder.header().setTo(toList);
        builder.header().setSubject("Test message");
        builder.header().setDate(new Date());
        builder.setTextBody("Testing 1 2 3...");
        byte[] rfc822Data = builder.data();
       SMTPSession smtpSession = new SMTPSession();
       smtpSession.setHostname("smtp.gmail.com");
       smtpSession.setPort(465);
       smtpSession.setUsername("yourgmail@gmail.com");
      smtpSession.setPassword("gmailpassword");
      smtpSession.setAuthType(AuthType.AuthTypeXOAuth2);
      smtpSession.setConnectionType(ConnectionType.ConnectionTypeTLS);

**Comment by dinhviethoa** [comment]
could you show me at which line it crashes?

**Comment by githupfisher** [comment]
have fix it

**Comment by dinhviethoa** [comment]
What was the issue?

**Comment by githupfisher** [comment]
I use it 
http://d.etpan.org/mailcore2-deps/mailcore2-android-beta/mailcore2-android-3-beta-2.aar
