### ISSUE TITLE
Latest Android version dies when loading message headers/flags/envelope for a large mailbox

### ISSUE THREAD

**Issue by glosterva** [MailCore/mailcore2#1275]
I'm using mailcore2-android-3-beta-2.aar, which is working well for me in most respects.  In the example program, I set it to point to my email account with 500 messages.  This code executes fine:

    Range myRange = new Range(1, Range.RangeMax);
    IndexSet set = IndexSet.indexSetWithRange(myRange);
    try {
            fetchMessagesOp = MessagesSyncManager.singleton().session.fetchMessagesByNumberOperation("INBOX", IMAPMessagesRequestKind.IMAPMessagesRequestKindHeaders | IMAPMessagesRequestKind.IMAPMessagesRequestKindStructure, set);
            fetchMessagesOp.start(this);
    }

The succeeded() callback method is called, but when this code executes:

    messages = fetchMessagesOp.messages();

the app crashes.  The messages listed below appear in the Android monitor, indicating the JNI code has overflowed the JNI local reference table.  I've had this happen loading as few as 100 messages.

11-10 15:57:02.089 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113] JNI ERROR (app bug): local reference table overflow (max=512)
11-10 15:57:02.089 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113] local reference table dump:
11-10 15:57:02.089 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]   Last 10 entries (of 512):
11-10 15:57:02.089 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]       511: 0x12d70d80 com.libmailcore.IMAPMessage
11-10 15:57:02.089 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]       510: 0x12c19c00 java.lang.Class<com.libmailcore.IMAPMessage>
11-10 15:57:02.089 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]       509: 0x12d70d70 com.libmailcore.IMAPMessage
11-10 15:57:02.089 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]       508: 0x12c19c00 java.lang.Class<com.libmailcore.IMAPMessage>
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]       507: 0x12d70d60 com.libmailcore.IMAPMessage
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]       506: 0x12c19c00 java.lang.Class<com.libmailcore.IMAPMessage>
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]       505: 0x12d70d50 com.libmailcore.IMAPMessage
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]       504: 0x12c19c00 java.lang.Class<com.libmailcore.IMAPMessage>
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]       503: 0x12d70d40 com.libmailcore.IMAPMessage
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]       502: 0x12c19c00 java.lang.Class<com.libmailcore.IMAPMessage>
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]   Summary:
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]       255 of java.lang.Class (4 unique instances)
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]        48 of com.libmailcore.IMAPMessage (48 unique instances)
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]         2 of java.lang.String (2 unique instances)
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]         2 of com.libmailcore.IMAPMessage (2 unique instances)
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]         1 of java.lang.String
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]        40 of com.libmailcore.IMAPMessage (40 unique instances)
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]         1 of java.lang.String[] (3 elements)
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]        52 of com.libmailcore.IMAPMessage (52 unique instances)
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]         1 of java.lang.Class
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]        10 of com.libmailcore.IMAPMessage (10 unique instances)
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]         1 of java.util.Vector
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]        99 of com.libmailcore.IMAPMessage (99 unique instances)
11-10 15:57:02.090 4906-4906/com.libmailcore.androidexample A/art: art/runtime/indirect_reference_table.cc:113]

**Comment by dinhviethoa** [comment]
Could you try this build?
http://d.etpan.org/mailcore2-deps/mailcore2-android-beta/mailcore2-android-3-beta-3.aar

**Comment by glosterva** [comment]
@dinhviethoa This is working well for me.  Thanks for the quick fix!
