### ISSUE TITLE
Can't build MailCore2 for OS X with Carthage, bitcode enabled

### ISSUE THREAD

**Issue by d370urn3ur** [MailCore/mailcore2#1278]
I try to build MailCore2 for an OS X project via Carthage, per the instructions (add this line to your Cartfile: github "MailCore/mailcore2"), I get an error in Carthage "The following build command failed: Check Dependencies".  And when I look in the log, it says this:

    Build settings from command line:
        ONLY_ACTIVE_ARCH = NO

    === BUILD TARGET static mailcore2 osx OF PROJECT mailcore2 WITH THE DEFAULT CONFIGURATION (Release) ===

    Check dependencies
    target 'static mailcore2 osx' has bitcode enabled (ENABLE_BITCODE = YES), but it is not supported for the 'macosx' platform

So I can't seem to resolve this.  There is a commit on master that looks like it should resolve this (b729a58e8adc26e50ab2a227c661f6119631a7d7) but apparently it doesn't.

**Comment by dinhviethoa** [comment]
Could you try again? I created a release 0.6.1
