### ISSUE TITLE
Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed"

### ISSUE THREAD

**Issue by NipunBilala** [MailCore/mailcore2#1280]
Using Mailcore 2 ios as pods in the project.
Application is functioning properly when using popsession but when using IMAPSession i get the following error while fetching the messages.

Following is the error
 Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed" UserInfo={NSLocalizedDescription=The requested folder does not exist.  Folder selection failed

Following is my code

imapsession = [[MCOIMAPSession alloc] init];
[imapsession setHostname:[[NSUserDefaults standardUserDefaults]valueForKey:@"PopServerName"]];
    [imapsession setPort:[[[NSUserDefaults standardUserDefaults]valueForKey:@"PopPORT"]integerValue]];
    [imapsession setUsername:[[NSUserDefaults standardUserDefaults]valueForKey:@"UserId" ]];
    [imapsession setPassword:[[NSUserDefaults standardUserDefaults]valueForKey:@"UserPaswrd"]];
    [imapsession setConnectionType:MCOConnectionTypeClear];
    imapsession.authType=MCOIMAPCapabilityAuthPlain;
    
    MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindFullHeaders|MCOIMAPMessagesRequestKindFlags;
    NSString *folder = @"INBOX";
    MCOIndexSet *uids = [MCOIndexSet indexSetWithRange:MCORangeMake(1, UINT64_MAX)];
    
    MCOIMAPFetchMessagesOperation *fetchMsgsHeadersOperation = [imapsession fetchMessagesOperationWithFolder:folder requestKind:requestKind uids:uids];
    
    [fetchMsgsHeadersOperation start:^(NSError * error, NSArray * messages, MCOIndexSet * vanishedMessages) {
    
    
     NSLog(@"the messages : %@  the error %@",messages,error);
    
    
    }];

**Comment by dinhviethoa** [comment]
Could you show the connectionLogger logs?

**Comment by NipunBilala** [comment]
ID: 0x7afd3800, type: 0, data: * OK IMAP4 Service Ready.
ID: 0x7afd3800, type: 1, data: 1 CAPABILITY
ID: 0x7afd3800, type: 0, data: * CAPABILITY IMAP4 IMAP4rev1 IDLE ID LITERAL+  1 OK Completed
ID: 0x7afd3800, type: 2, data: 2 LOGIN "*******@***.in" *****
ID: 0x7afd3800, type: 0, data: 2 OK Login Completed.
ID: 0x7afd3800, type: 1, data: 3 CAPABILITY
ID: 0x7afd3800, type: 0, data: * CAPABILITY IMAP4 IMAP4rev1 IDLE ID LITERAL+  3 OK Completed
ID: 0x7afd3800, type: 1, data: 4 LIST "" ""
ID: 0x7afd3800, type: 0, data: * LIST (\NoSelect) "/"  ""
ID: 0x7afd3800, type: 1, data: 5 ID NIL
ID: 0x7afd3800, type: 0, data: * ID ("name" "Imap" "version" "1.5" "os" "centos" "os-version" "5.5" "support-url" "mailto:admin@xgen.in")+ 5 OK Completed
ID: 0x7afd3800, type: 1, data: 6 SELECT INBOX
the folders : (null)   Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed" UserInfo={NSLocalizedDescription=The requested folder does not exist.

**Comment by NipunBilala** [comment]
@dinhviethoa : Above is the log

**Comment by dreamahui** [comment]
I have encountered this problem, I ask you how to solve this problem?
