### ISSUE TITLE
Operations in iOS while in background do not work

### ISSUE THREAD

**Issue by hughesne** [MailCore/mailcore2#1281]
When the app is in the foreground, everything works perfectly.  Im pushing remote notifications to trigger a content update.  This and all operations fail once the device backgrounds the app.

fetchOperation.start { (error, fetchedMessages, vanishedMessages) -> Void in
            DSWManager.sharedManager.unreadExist = false
            if error != nil {
                print("Error downloading message headers: \(error)")
                completionBlock(success: false)
            }
....
}

Get this error everything:
Error downloading message headers: Optional(Error Domain=MCOErrorDomain Code=3 "Unable to parse response from server." UserInfo={NSLocalizedDescription=Unable to parse response from server.})

I believe that in iOS the background content fetch MUST use NSURLSession with specific parameters.  Limited capabilities if the app must be in the foreground to update content.

**Comment by dinhviethoa** [comment]
Could you show the connection logger logs when you're in the background?
Did you create the session from scratch when you are in the background?

**Comment by hughesne** [comment]
NVM, set it like this in case anyone stumbles on this:

session.connectionLogger = {(connId, type, data) in
            if data != nil {
                    NSLog("event logged: \(type) withData:\(data)")
            }

**Comment by hughesne** [comment]
From the connectionLogger, it looks like the messages are coming down as expected, but the closure for the start method is not being called.

**Comment by dinhviethoa** [comment]
are you calling start() from the main thread? is there a main thread running properly?

**Comment by pfennema** [comment]
Hi HughesNe, 

Did you ever get this issue resolved? I have actually something similar that when trying to connect to a mail server from within the didReceiveRemoteNotification I cannot get a connection. Details not available right now.

**Comment by dinhviethoa** [comment]
Did you give me any details about the issue? I'll let you investigate.

**Comment by pfennema** [comment]
Find it out only recently when I implemented a push notification server hence I had a more reliable way of triggering in the background. Will definitely investigate and come back, thanks!
