### ISSUE TITLE
Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist. Folder selection failed"

### ISSUE THREAD

**Issue by NipunBilala** [MailCore/mailcore2#1282]
Using Mailcore 2 ios as pods in the project.
Application is functioning properly when using popsession but when using IMAPSession i get the following error while fetching the messages.

Following is the error
Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist. Folder selection failed" UserInfo={NSLocalizedDescription=The requested folder does not exist. Folder selection failed

Following is my code

imapsession = [[MCOIMAPSession alloc] init];
[imapsession setHostname:[[NSUserDefaults standardUserDefaults]valueForKey:@"PopServerName"]];
[imapsession setPort:[[[NSUserDefaults standardUserDefaults]valueForKey:@"PopPORT"]integerValue]];
[imapsession setUsername:[[NSUserDefaults standardUserDefaults]valueForKey:@"UserId" ]];
[imapsession setPassword:[[NSUserDefaults standardUserDefaults]valueForKey:@"UserPaswrd"]];
[imapsession setConnectionType:MCOConnectionTypeClear];
imapsession.authType=MCOIMAPCapabilityAuthPlain;

MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindFullHeaders|MCOIMAPMessagesRequestKindFlags;
NSString *folder = @"INBOX";
MCOIndexSet *uids = [MCOIndexSet indexSetWithRange:MCORangeMake(1, UINT64_MAX)];

MCOIMAPFetchMessagesOperation *fetchMsgsHeadersOperation = [imapsession fetchMessagesOperationWithFolder:folder requestKind:requestKind uids:uids];

[fetchMsgsHeadersOperation start:^(NSError * error, NSArray * messages, MCOIndexSet * vanishedMessages) {

 NSLog(@"the messages : %@  the error %@",messages,error);

}];

Following is the log

ID: 0x7afd3800, type: 0, data: * OK IMAP4 Service Ready.
ID: 0x7afd3800, type: 1, data: 1 CAPABILITY
ID: 0x7afd3800, type: 0, data: * CAPABILITY IMAP4 IMAP4rev1 IDLE ID LITERAL+ 1 OK Completed
ID: 0x7afd3800, type: 2, data: 2 LOGIN "****@.in" *****
ID: 0x7afd3800, type: 0, data: 2 OK Login Completed.
ID: 0x7afd3800, type: 1, data: 3 CAPABILITY
ID: 0x7afd3800, type: 0, data: * CAPABILITY IMAP4 IMAP4rev1 IDLE ID LITERAL+ 3 OK Completed
ID: 0x7afd3800, type: 1, data: 4 LIST "" ""
ID: 0x7afd3800, type: 0, data: * LIST (\NoSelect) "/" ""
ID: 0x7afd3800, type: 1, data: 5 ID NIL
ID: 0x7afd3800, type: 0, data: * ID ("name" "Imap" "version" "1.5" "os" "centos" "os-version" "5.5" "support-url" "mailto:admin@xgen.in")+ 5 OK Completed
ID: 0x7afd3800, type: 1, data: 6 SELECT INBOX
the folders : (null) Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist. Folder selection failed" UserInfo={NSLocalizedDescription=The requested folder does not exist.

**Comment by dinhviethoa** [comment]
Is there one additional log missing for the response of `SELECT INBOX`?

**Comment by NipunBilala** [comment]
following is the complete code and above is the complete log.

imapsession = [[MCOIMAPSession alloc] init];
    [imapsession setHostname:[[NSUserDefaults standardUserDefaults]valueForKey:@"PopServerName"]];
    [imapsession setPort:[[[NSUserDefaults standardUserDefaults]valueForKey:@"PopPORT"]integerValue]];
    [imapsession setUsername:[[NSUserDefaults standardUserDefaults]valueForKey:@"UserId" ]];
    [imapsession setPassword:[[NSUserDefaults standardUserDefaults]valueForKey:@"UserPaswrd"]];
    [imapsession setConnectionType:MCOConnectionTypeClear];
    imapsession.authType=MCOIMAPCapabilityAuthPlain;    
    imapsession.connectionLogger = ^ (void * connectionID, MCOConnectionLogType type, NSData * data) 
{
        NSLog(@"ID: %p, type: %d, data: %@", connectionID, type, [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
    };

    MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindFullHeaders|MCOIMAPMessagesRequestKindFlags;
    NSString *folder = @"INBOX";
    MCOIndexSet *uids = [MCOIndexSet indexSetWithRange:MCORangeMake(1, UINT64_MAX)];
    MCOIMAPFetchMessagesOperation *fetchMsgsHeadersOperation = [imapsession fetchMessagesOperationWithFolder:folder requestKind:requestKind uids:uids];
    [fetchMsgsHeadersOperation start:^(NSError * error, NSArray * messages, MCOIndexSet * vanishedMessages) {
     NSLog(@"the folders : %@   %@",messages,error);
    }];

**Comment by dinhviethoa** [comment]
is INBOX missing from the account?

**Comment by NipunBilala** [comment]
@dinhviethoa : nopes

**Comment by dinhviethoa** [comment]
It looks like the server doesn't responds after `6 SELECT INBOX`.
That's weird.

It sounds like a server issue.

**Comment by NipunBilala** [comment]
@i checked on the server also and it seems that server is properly sending the inbox mails

**Comment by dinhviethoa** [comment]
Could you try a telnet connection to the IMAP server and send the same commands and show me the result?
Thanks.

**Comment by shiwwgis** [comment]
I use mailcore2 in Swift2.0,but cannot get "inbox" folder metadata.

code:

      let imapFetchMailCountOp = imapSession.folderInfoOperation("INBOX");
        
        imapFetchMailCountOp.start()
            {
                (error:NSError?,info:MCOIMAPFolderInfo?)->Void in
                if error == nil
                {
                    print("inbox mail count=\((info?.messageCount)!)");
                }
                else
                {
                    print("get mail count of inbox fail,\(error!)")
                }
        }

debug info:

get mail count of inbox fail,Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed" UserInfo={NSLocalizedDescription=The requested folder does not exist.  Folder selection failed}

**Comment by dinhviethoa** [comment]
Can you show the connection logger logs?

**Comment by blindknight47** [comment]
I have the same issue with yahoo account.
I am able to access Inbox and Trash folder in Yahoo mail. But I can't access Drafts or Spam folder. This is my error message:

```
2016-05-27 16:42:40.962 iOS UI Test[781:73868] checking account
2016-05-27 16:42:40.963 [781:480f] MCOperationQueue.cpp:81: start thread
2016-05-27 16:42:40.997 [781:480f] MCIMAPSession.cpp:592: connect <mailcore::IMAPSession:0x12c615c50>
2016-05-27 16:42:42.715 [781:480f] MCIMAPSession.cpp:615: ssl connect imap.mail.yahoo.com 993 2
2016-05-27 16:42:42.726 [781:480f] MCIMAPSession.cpp:683: connect ok
2016-05-27 16:42:42.726 [781:480f] MCIMAPSession.cpp:723: login
2016-05-27 16:42:44.964 [781:480f] MCIMAPSession.cpp:992: login ok
2016-05-27 16:42:44.965 iOS UI Test[781:73868] finished checking account.
2016-05-27 16:42:44.967 [781:480f] MCIMAPSession.cpp:1079: select
2016-05-27 16:42:44.967 iOS UI Test[781:73930] MCOIMAPSession: [1] 5 SELECT Drafts

2016-05-27 16:42:45.561 iOS App[781:73930] MCOIMAPSession: [0] 5 BAD [TRYCREATE] SELECT error - Folder does not exist or server encountered an error

2016-05-27 16:42:45.562 [781:480f] MCIMAPSession.cpp:1083: select error : 9
2016-05-27 16:42:46.663 [781:main] MCOperationQueue.cpp:215: trying to quit 0x17015a8e0
2016-05-27 16:42:46.663 [781:480f] MCOperationQueue.cpp:102: stopping 0x17015a8e0
2016-05-27 16:42:46.664 [781:main] MCOperationQueue.cpp:230: thread stopped 0x17015a8e0
2016-05-27 16:42:46.664 [781:480f] MCOperationQueue.cpp:151: cleanup thread 0x17015a8e0
2016-05-27 16:43:19.664 [781:2017] MCOperationQueue.cpp:81: start thread
2016-05-27 16:43:20.770 [781:main] MCOperationQueue.cpp:215: trying to quit 0x17015a8e0
2016-05-27 16:43:20.770 [781:2017] MCOperationQueue.cpp:102: stopping 0x17015a8e0
2016-05-27 16:43:20.770 [781:main] MCOperationQueue.cpp:230: thread stopped 0x17015a8e0
2016-05-27 16:43:20.770 [781:2017] MCOperationQueue.cpp:151: cleanup thread 0x17015a8e0
```
I used code in iOS UI Test project. Must we special config in yahoo account?
Thanks!

**Comment by dinhviethoa** [comment]
"Drafts" doesn't exist on yahoo servers.

**Comment by blindknight47** [comment]
So, we can't get drafts messages.
