### ISSUE TITLE
Best way to get things from mail(body, subject)?

### ISSUE THREAD

**Issue by Nikiraf** [MailCore/mailcore2#1284]
Hi,
I'm working on Swift application for my final exam. It is mail client application.
I have to much problem because there are no examples and documentation for Swift.

I'm trying to get some thing from mail. For example I'm trying to get: subject, sender, time, date, body.

Should I use some other function to get emails. I tried with "fetchMessagesOperationWithFolder"

The code is below
******************
        let imapSession = MCOIMAPSession()
        imapSession.hostname = "imap.gmail.com"
        imapSession.username = "EMAIL"
        imapSession.password = "PASSWORD"
        imapSession.port = 993
        imapSession.connectionType = MCOConnectionType.TLS

        let folder = "INBOX"
        let requestKind = MCOIMAPMessagesRequestKind.Headers
        let uidSet = MCOIndexSet(range: MCORangeMake(1, UINT64_MAX))
        let message = MCOIMAPMessage()

        let fetchOperation = imapSession.fetchMessagesOperationWithFolder(folder, requestKind: requestKind, uids: uidSet)
        
        fetchOperation.start { (NSError error, NSArray msgs, MCOIndexSet vanished) -> Void in
            NSLog("Successfully recieved email!")
            print(msgs)            
        }
***********************

**Comment by dinhviethoa** [comment]
Is there an actual question here?

**Comment by Nikiraf** [comment]
Yes :-)
How to get "Sender", "Subject", "Date"...
Do I need to parse whole message or there is some function to get specific part of email?

**Comment by dinhviethoa** [comment]
`NSArray msgs` is an array of IMAPMessage. Look into IMAPMessage, there are all those informations.

**Comment by Nikiraf** [comment]
Thanks a lot for quick replay! I will try with MCOIMAPMessage. Probably I will have some more question about these topic.

**Comment by xtation** [comment]
i got the same project bro please tell me whic library you use to fetch emails i use mailcore2 to fetch mails but converted code of objectv c is not working properly do you have fetch mails code or tell me which library you used for it Thanks
