### ISSUE TITLE
android fetch message  by uid ,it crash;

### ISSUE THREAD

**Issue by githupfisher** [MailCore/mailcore2#1287]
IMAPFetchMessagesOperation op = session.fetchMessagesByUIDOperation(folder, requestKind, IndexSet.indexSetWithRange(newRange(wm_Utils.get_uint32(Long.valueOf(min_uid)),10000));
JNI ERROR (app bug): local reference table overflow (max=512)
art/runtime/indirect_reference_table.cc:98] local reference table dump:
art/runtime/indirect_reference_table.cc:98]   Last 10 entries (of 512):

how to use the indexSet

**Comment by dinhviethoa** [comment]
Could you try this build?
http://d.etpan.org/mailcore2-deps/mailcore2-android-beta/mailcore2-android-3-beta-3.aar
Thanks!
