### ISSUE TITLE
How to get X-Priority?

### ISSUE THREAD

**Issue by guidedways** [MailCore/mailcore2#1288]
I can't seem to extract X-Priority from an email. I'm using the following request kind but am not seeing it come through in any of the headers:

MCOIMAPMessagesRequestKindUid | MCOIMAPMessagesRequestKindFlags | MCOIMAPMessagesRequestKindInternalDate | MCOIMAPMessagesRequestKindFullHeaders | MCOIMAPMessagesRequestKindExtraHeaders

**Comment by dinhviethoa** [comment]
There's a extraHeaders property. You can set it to @[@"X-Priority"].
http://libmailcore.com/api/objc/Classes/MCOIMAPFetchMessagesOperation.html

**Comment by guidedways** [comment]
Perfect, thanks!

**Comment by guidedways** [comment]
Oops - just checked:

[imapMessage.header extraHeaderValueForName: @"X-Priority"]

returns nil even though I know the headers have this set.

**Comment by guidedways** [comment]
To elaborate, this is my code:

              MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindUid | MCOIMAPMessagesRequestKindFlags | MCOIMAPMessagesRequestKindInternalDate | MCOIMAPMessagesRequestKindFullHeaders | MCOIMAPMessagesRequestKindExtraHeaders;              
              
              MCOIndexSet *numbers = nil;
              MCOIMAPFetchMessagesOperation *fetchOperation = nil;
              
              if (self.lastUid == 0) {
                numbers = [MCOIndexSet indexSetWithRange:MCORangeMake(startOfMessage, numberOfMessages)];
                
                // Get the last 20 messages if it's the first time we're running this code
                fetchOperation = [self.session fetchMessagesByNumberOperationWithFolder:self.folder
                                                                            requestKind:requestKind
                                                                                numbers:numbers];
              } else {
                numbers = [MCOIndexSet indexSetWithRange:MCORangeMake(self.lastUid, UINT64_MAX)];
                
                fetchOperation = [self.session fetchMessagesOperationWithFolder:self.folder
                                                                    requestKind:requestKind
                                                                           uids:numbers];
              }

**Comment by guidedways** [comment]
Ignore me - it's working just fine.
