### ISSUE TITLE
How do we send the ENABLE extension command?

### ISSUE THREAD

**Issue by guidedways** [MailCore/mailcore2#1296]
It seems some IMAP servers that support the ENABLE extension may require the clients to explicitly enable CONDSTORE where available (https://tools.ietf.org/html/rfc5161). How can I use mailcore to send such arbitrary IMAP commands? Is there a way to do this?

**Comment by dinhviethoa** [comment]
I think mailcore already sends that command when COLDSTORE is available. Please check the connection logs.

**Comment by guidedways** [comment]
Thanks!
