### ISSUE TITLE
Outlook365 emails not reporting MCOMessageFlag correctly?

### ISSUE THREAD

**Issue by guidedways** [MailCore/mailcore2#1299]
I've got a few users complaining (all apparently Outlook 365) that when they flag an email in their normal email client, our app doesn't pick it up. I've checked the logs and it appears 'MCOMessageFlag' is always set to 'MCOMessageFlagAnswered' (if it's been replied to) but it never contains 'MCOMessageFlagFlagged'. i.e. the bitwise flags field doesn't have the 'MCOMessageFlagFlagged' bit turned ON.

Are there known issues with Outlook365? How do I tell what's causing the issue? Could it be mailcore2? Any further information I need to extract?

**Comment by guidedways** [comment]
I should add, this is how I check:

if (imapMessage.flags & MCOMessageFlagFlagged) {
   // Flagged!
}

**Comment by dinhviethoa** [comment]
Could you show the connection logger logs?
If the logs won't show the flagged flag, that's probably a Outlook 365 issue.

**Comment by guidedways** [comment]
I've quadruple checked and it seems it really is an Outlook 365 issue. However! I have found a possible work around. It seems Mail app (or other Mac clients over an Exchange email address) don't really set the Flag even if you ask it to. They set the header 'X-Message-Flag' to 'Follow up' instead. OR at times they set the 'Important' flag to 'True'.
