### ISSUE TITLE
How do I remove a header from an email such as X-Message-Flag

### ISSUE THREAD

**Issue by guidedways** [MailCore/mailcore2#1302]
I need to unflag an email that got flagged by setting the 'X-Message-Flag' header to 'Follow up'. Is there a way to remove this header from an email?

**Comment by dinhviethoa** [comment]
You can't.

**Comment by guidedways** [comment]
Sorry - is this not possible in general or just something mailcore won't be doing? I ask because Outlook seems to be able to 'toggle' this in an existing email.

**Comment by dinhviethoa** [comment]
Try to connect to outlook365 using IMAP and check.
