### ISSUE TITLE
How to get attachments file data from MCOAbstractPart?

### ISSUE THREAD

**Issue by pradnyaGaikwad** [MailCore/mailcore2#1303]
Hi,
In MCOAbstractPart we get the filename but there is not method for getting attachment data .I tried decodedStringForData which is giving only string in text file not for other files such as XLS  and even it will not be used for image attachment.
Thanks.

**Comment by dinhviethoa** [comment]
Depending on the subclass of MCOAbstractPart you're working with, there's either a data field or you have to fetch the attachment from the server.
