### ISSUE TITLE
Qt Creator link failed

### ISSUE THREAD

**Issue by jatempa** [MailCore/mailcore2#1305]
Hi,
I am trying to linking mailcore2 with Qt on Ubuntu 14.04. I can building and import the library from Qt Creator. However when I run the application returns the following message:

mailcore2/build/src//libMailCore.a(MCMainThreadGTK.cpp.o): undefined reference to symbol 'g_source_remove'

**Comment by dinhviethoa** [comment]
The Linux version was designed to work only with GTK.
Are you interested in building the support for QT?

**Comment by jatempa** [comment]
Thanks for your response. 
I am not able to support mailcore on Qt. I am novice.
