### ISSUE TITLE
Can we get libmailcore 

### ISSUE THREAD

**Issue by pradnyaGaikwad** [MailCore/mailcore2#1308]
Hi,

We are using mailcore2 library only for Pop3 mail sever for fetching mails and attachments . The mail core library is bigger in size (198.9 MB). This size is too big for IOS build .Can we get smaller size library file with required files included in it? or is there any way to make the size of the library smaller.

Thanks.

**Comment by dinhviethoa** [comment]
One you link with it, it will be smaller.
