### ISSUE TITLE
Mailcore dealloc fails

### ISSUE THREAD

**Issue by KennyVB** [MailCore/mailcore2#1310]
![skaermbillede 2015-12-12 kl 13 24 26](https://cloud.githubusercontent.com/assets/727549/11761912/ff954542-a0d3-11e5-9ad2-34e91c46475e.png)

**Comment by KennyVB** [comment]
this is what happens when i close a web view AFTER viewing a mail

**Comment by dinhviethoa** [comment]
Please, create a small project on github that reproduces the issue.
Thanks.

**Comment by KennyVB** [comment]
https://github.com/KennyVB/mailcore2test

**Comment by dinhviethoa** [comment]
If you initialize that to nil / null instead of MCOIMAPMessageRenderingOperation(), it will probably solve the crash. I'm not sure what you intent was here.
https://github.com/KennyVB/mailcore2test/blob/master/Blackmail/tableViewController.swift#L21

**Comment by KennyVB** [comment]
hmm now i tried removing it altogether... still crashes

**Comment by dinhviethoa** [comment]
Could you show the new crash log?

**Comment by CodaFi** [comment]
It's because `MCOOperation` has no designated `init` (probably should start annotating these APIs with that soon), yet your rendering view controller is calling it.  When your view gets popped, you'll destroy the instance you created and cause the operation to be over-released.  I don't know if this is a user error or if we should check for null in the destructor.

**Comment by dinhviethoa** [comment]
Could you create a pull request with those annotations?
Thanks!

**Comment by CodaFi** [comment]
I can.  But more importantly should the init() be marked unavailable?

**Comment by dinhviethoa** [comment]
what do you mean?

**Comment by CodaFi** [comment]
Well, MCOOperation doesn't look like it's setup for that call to be legal unless it's being delegated from a subclass.  So we can mark it deprecated or unavailable to prevent these kinds of things from happening in the first place, or implement -init and allow it but fix the crash.

**Comment by dinhviethoa** [comment]
Maybe a -init with a big assert would just work.
