### ISSUE TITLE
Misleading error from Outlook

### ISSUE THREAD

**Issue by guidedways** [MailCore/mailcore2#1314]
I am testing with an alias account and I see this:

Event:0x1398e61e0 0 withData: * OK Outlook.com IMAP4rev1 server version 17.4.0.0 ready (BAY451-IMAP412)
Event:0x1398e61e0 1 withData: 1 CAPABILITY
Event:0x1398e61e0 0 withData: * CAPABILITY IMAP4rev1 CHILDREN ID NAMESPACE UIDPLUS UNSELECT AUTH=PLAIN AUTH=XOAUTH2 SASL-IR
Event:0x1398e61e0 0 withData: 1 OK CAPABILITY completed
Event:0x1398e61e0 0 withData: 2 NO [AUTHORIZATIONFAILED] Account does not have a valid mailbox. Login to your account via a web browser.

Could not connect to host [imap-mail.outlook.com:993:1:2] with error: Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo={NSLocalizedDescription=Unable to authenticate with the current session's credentials.}

So the Error I get from mailcore says "Unable to authenticate with the current session's credentials" but the actual helpful error from Outlook was that the account does not have a valid mailbox. Please can Mailcore give more accurate errors?

**Comment by dinhviethoa** [comment]
Use MCOIMAPResponseKey in NSError userInfo.
It's a string you can show to the user.
