### ISSUE TITLE
Can't move a message to TrashFolder of Gmail 

### ISSUE THREAD

**Issue by cuongproit** [MailCore/mailcore2#1315]
I was using OAuth2 to authenticate with Gmail account. When I tried to move a message to TrashFolder, It didn't work. (Yahoo mail, Outlook mail that no used OAuth2 to login still worked )

This is my code:

MCOIMAPCopyMessagesOperation *opAppend = [self.currentAccount.imapSession copyMessagesOperationWithFolder:@"INBOX" uids:[MCOIndexSet indexSetWithIndex:message.uid] destFolder:@"[Gmail]/Trash"];
    self.currentAccount.imapSession.connectionLogger = ^(void * connectionID, MCOConnectionLogType type, NSData * data) {
                NSLog(@"\n----------data from connectionLoger when move to trash: ---------------\n");
                NSLog(@"%@", [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
                NSLog(@"\n------------------------------");
    };
[opAppend start:^(NSError *error1, NSDictionary *uidMapping) {

}
}

This is connectionLoger:
----------data from connectionLoger when move to trash: ---------------
2015-12-17 16:21:48.594 Mail[14821:438500] 8 UID COPY 35 "[Gmail]/Trash"
015-12-17 16:21:48.930 Mail[14821:438500] 8 NO [TRYCREATE] No folder [Gmail]/Trash (Failure)

Please help me

**Comment by dinhviethoa** [comment]
The folder doesn't exist. Maybe it's disabled in Gmail IMAP settings.

**Comment by cuongproit** [comment]
I confirm that it is still enabled in Gmail IMAP settings. Do you have any suggestion?

**Comment by dinhviethoa** [comment]
Is your trash folder really [Gmail]/Trash? Maybe it's localized. I'd recommend getting the list of folders and checking the flags.

**Comment by cuongproit** [comment]
Perfect! It's exactly localized! Thank you so much.
