### ISSUE TITLE
iOS crash in mailmessage_get_bodystructure

### ISSUE THREAD

**Issue by gc179** [MailCore/mailcore2#1317]
I'm fetching an IMAP message and checking for error or nil data then calling [MCOMessageParser messageParserWithData:data].

I've gotten a few crash reports, all seemingly from the same user and possibly the same message.

The crash appears to be in mail message_get_bodystructure in libetpan.

Unfortunately I do not have the source of the message in question since it's a crash report from Apple.

One question in particular, am I using the correct/latest version of libetpan? My project's buildetpan-ios.sh looks like this: (I haven't changed it myself)

#!/bin/sh

pushd "`dirname "$0"`" > /dev/null
scriptpath="`pwd`"
popd > /dev/null

. "$scriptpath/include.sh/build-dep.sh"

url="https://github.com/dinhviethoa/libetpan.git"
rev=9d88f56dde0eb709161814d7483af7a500ab8fac
name="libetpan-ios"
xcode_target="libetpan ios"
xcode_project="libetpan.xcodeproj"
library="libetpan-ios.a"
embedded_deps="libsasl-ios"

build_git_ios

Thanks for any help.

**Comment by dinhviethoa** [comment]
I can't help if you don't have the message or the detailed crash report.
Please reopen if you can add more details.

**Comment by gc179** [comment]
Can you confirm that the libetpan version we're using is a good one?

Thanks.

Geoff

**Comment by dinhviethoa** [comment]
This is the correct one. No crash report = no investigation.

**Comment by gc179** [comment]
OK thanks for confirming the library version. I will re-open if I get a good crash report to send.
