### ISSUE TITLE
search email starting from a specific date

### ISSUE THREAD

**Issue by arunvijay88** [MailCore/mailcore2#1320]
I've heard that mailcore2 does not have this feature, but can we achieve it by IMAPSearchOperation in Android?

**Comment by dinhviethoa** [comment]
in `IMAPSession`, look for:

```
public IMAPSearchOperation searchOperation(java.lang.String folder,
                                           IMAPSearchExpression expression)
```

and in `IMAPSearchExpression`:

```
public static IMAPSearchExpression searchSinceDate(java.util.Date date)
```

**Comment by arunvijay88** [comment]
Got it, Thanks

**Comment by ashishdevadiga** [comment]
i want to implement the IMAPSearchExpression searchSinceDate for IMAPFetchMessageOperation is this possible?

**Comment by ashishdevadiga** [comment]
Because i want indexSet as searchSinceDate is this possible to implement?
