### ISSUE TITLE
How to monitor a folder for any changes?

### ISSUE THREAD

**Issue by zhangao0086** [MailCore/mailcore2#1325]
Is there any way to monitor a folder?

**Comment by dinhviethoa** [comment]
Can you be more specific?
Does IDLE work for you?

**Comment by zhangao0086** [comment]
@dinhviethoa 
Thanks for your reply!
Yes, IDLE works for me. But when the server does not support IDLE, if I can use anyway instead?

**Comment by dinhviethoa** [comment]
You have to poll.
