### ISSUE TITLE
Can not get all email addresses of the header in MCOImapmessage ( only got one email) with Yandex Mail

### ISSUE THREAD

**Issue by cuongproit** [MailCore/mailcore2#1328]
Here is my code to get messages:
--------------------------------------------

```
MCOIMAPFetchMessagesOperation* imapMessagesFetchOp = nil;


self.imapMessagesFetchOp = [[self.currentAccount imapSession]
                                    fetchMessagesByNumberOperationWithFolder:folderName
                                    requestKind:requestKind
                                    numbers:numbers];
       
 self.currentAccount.imapSession.connectionLogger = ^(void * connectionID, MCOConnectionLogType type, NSData * data) {
                       NSLog(@"\n----------data from connectionLoger when get messages: ---------------\n");
                       NSLog(@"%@", [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
                       NSLog(@"\n------------------------------");
                   };
        
        [self.imapMessagesFetchOp start:^(NSError *error, NSArray *messages, MCOIndexSet *vanishedMessages) {
            NSSortDescriptor *sort = [NSSortDescriptor sortDescriptorWithKey:@"header.date" ascending:NO];
            block(error, [messages sortedArrayUsingDescriptors:@[sort]], vanishedMessages);
        }];

```

--------------------------------------------
It's ok for Gmail, yahoo... But with Yandex mail, in header of message, it only get one email address that it should be more ( 3 email addresses).
I logged the header of message that mailcore2 got  below:

**************
(lldb) po [(MCOIMAPMessage *)msg header]
<mailcore::MessageHeader:0x7b83bda0
Message-ID: CAHfe60WsLTRJ+Yq5BGArqCPWuUFZF+yqh8uKT9uOZ3AkjPAnPw@mail.gmail.com
Sender: mailcore::Address:0x7af95bf0 Đào Xuân Cương <cuongproit@gmail.com>
From: mailcore::Address:0x7afb4130 Đào Xuân Cương <cuongproit@gmail.com>
To: [mailcore::Address:0x7afb27a0  <tohtest1@gmail.com>]
Reply-To: [mailcore::Address:0x7afb2960 Đào Xuân Cương <cuongproit@gmail.com>]
Subject: dfdfs
>
**************
Could you help me, please?

**Comment by dinhviethoa** [comment]
Which requestKind did you use?
You probably want to try FullHeaders.
