### ISSUE TITLE
MCOAuthTypeXOAuth2 Causes Crash iOS9

### ISSUE THREAD

**Issue by johnnyshankman** [MailCore/mailcore2#1330]
Following the example outlined here:
https://github.com/MailCore/mailcore2/wiki/SMTP-Examples

I found that my app was considered not up to snuff by today's security standards according to google.

My first response was to begin declaring the authorization type for the `smtpSession` object.

I cannot seem to use `MCOAuthTypeXOAuth2` because it causes my application to crash while sending the email.

All other types seem to work just fine, but don't grant me secure access to GMail's SMTP.

I'm forced to allow the GMail address to give access to "Low Security Applications", which sounds awful.

This is on iOS9.

**Comment by johnnyshankman** [comment]
`MCOAuthTypeXOAuth2Outlook` as well.

**Comment by johnnyshankman** [comment]
<img width="909" alt="screen shot 2016-01-09 at 6 49 20 pm" src="https://cloud.githubusercontent.com/assets/6632701/12219082/bcb5cdfc-b701-11e5-9629-354b9665209f.png">

**Comment by dinhviethoa** [comment]
Could you provide a stack trace? Thanks!

**Comment by johnnyshankman** [comment]
Yes i'll get that to you asap!

**Comment by CodaFi** [comment]
I think this happens because we aren't checking for a non-NULL token before the authentication call [here](https://github.com/MailCore/mailcore2/blob/master/src/core/smtp/MCSMTPSession.cpp#L527-L542).
