### ISSUE TITLE
Custom command behaves differently on 64-bit and 32-bit platforms

### ISSUE THREAD

**Issue by libec** [MailCore/mailcore2#1334]
Hey,

I experience different behaviour for 32-bit and 64-bit platforms (iOS). When I use the custom command and send for instance:
`10 XSERVICE STATE=START`

I always receive this data back (regardless of the platform):
`10 OK Service started`

Which is okay up to this point.

However, the `CustomCommandOperation` returns error on 64-bit platforms and reponse on 32-bit platform (even thought the raw response I see in `connectionLogger` of `MCOIMAPSession` is the same)

Meaning that in the 
```objc
[customCommandOperation start:^(NSString * _Nullable response, NSError * _Nullable error) { 
}
````

For 64-bit platforms I get: `A stable connection to the server could not be established.`
For 32-bit platforms I get response with: `Service started`

Did you ever experience this behaviour? Any help and hints would be much appreciated.

**Comment by dinhviethoa** [comment]
Does any other command fail as well for you in 64bits?

**Comment by libec** [comment]
No. All other commands I use work okay for me on both platforms.

**Comment by libec** [comment]
Nope, I'm still unable to find it. I was thinking if this is not just the build issue. Or do you think this might be something to do with libetpan?

**Comment by dinhviethoa** [comment]
Fixed. Thanks for the report!

**Comment by libec** [comment]
wow, that was lightning fast :+1: Thanks a lot, you rule!
