### ISSUE TITLE
On iOS, Use reachability to drop connections faster (was SMTP timeout on airplane mode)

### ISSUE THREAD

**Issue by ekscrypto** [MailCore/mailcore2#1335]
When trying to send a message via SMTP (not tested for other protocols) if airplane mode is enabled while a session is active, the session does not report an error until timeout.  Expected behaviour would be an error reported immediately on port closed. 

Side note: Although my timeout is hard set to 60 seconds, I have on multiple occasions noticed up to 3 minutes before a callback with an error.  

Using Mailcore2 with all commits up to an including c259c2e759fe477cb70d3d45883b4dcf35b56400

**Comment by dinhviethoa** [comment]
Have you been able to get a CPU sample while the 3 sec timeout is happening?

If you want to detect when the network interface are down (airplane mode on), you can use tools such as https://github.com/tonymillion/Reachability. If you detect that situation, you can cancel the smtp commands immediately.

**Comment by ekscrypto** [comment]
@dinhviethoa The problem is this issue that is still open #775 ; I'm assuming we still can't properly cancel SMTP operations.

**Comment by ekscrypto** [comment]
We are already using Reachability and we are handling it before SMTP starts, so if the network is unreachable, we will not even attempt the SMTP process.  The problem is that once SMTP is started, we don't want to cancel the progress indicators unless the SMTP operation is really done and over with; so we are waiting on an error/completion from the API; which unfortunately can be a long time.

I do not have the proper environment to simulate bad network connections here, but I would assume that if the API cannot handle completely losing any connectivity (airplane), then we can expect a similar timeout issue on bad networks and this will affect user experience.

With a 60 seconds timeout the user experience is tolerable, but in some cases such as when images are attached to an email, we set longer timeouts and it could take minutes before the user gets an error alert.

**Comment by dinhviethoa** [comment]
I think you can just cancel the op (it will still run in the background but you can just ignore it at this point).
Don't wait for the operation to finish and you can just disconnect the session (which probably won't disconnect it immediately) and recreate a new one.

I don't think that's a big issue to have those failing TCP connection hanging around until they timeout.

**Comment by ekscrypto** [comment]
@dinhviethoa I understand the angle to which you want me to approach the issue, and given that this is unlikely to be addressed soon, I will probably have to do it this way.  That being said, if a network connection is completely dropped, the API should be able to report it immediately.

**Comment by dinhviethoa** [comment]
I agree that we could improve the situation on iOS or Mac.
For Android, I'm not sure how we could approach that issue.
For Linux and Windows, I'm not even sure that there are APIs that would help improve that behavior.

**Comment by dinhviethoa** [comment]
Could you check if the behavior is better now?

**Comment by ekscrypto** [comment]
@dinhviethoa I requested permission from the client to do additional testing, may be a while before we get authorization.
