### ISSUE TITLE
POP does not download the new email

### ISSUE THREAD

**Issue by expersisSubhash** [MailCore/mailcore2#1337]
Hi,
I am using mailCore2 and it downloads the same 18 emails that it had downloaded first time.
Do you know why?How to download all the new emails in POP

Thank you in advance.

**Comment by alexcosmin** [comment]
Could you share the code that you're using? So we can see potential mistakes.

**Comment by expersisSubhash** [comment]
// Session initialization
session = [[MCOPOPSession alloc] init];
    session.hostname = mailHost;
    session.port = [mailPort intValue];
    session.username = username;
    session.password = password;
    
    if ( [connectionType intValue] == 0 )
        session.connectionType = MCOConnectionTypeClear;
    else if ( [connectionType intValue] == 1 )
       session.connectionType = MCOConnectionTypeStartTLS;
    else if ( [connectionType intValue] == 2 )
       session.connectionType = MCOConnectionTypeTLS;

MCOPOPFetchMessagesOperation *fetchOp = [session fetchMessagesOperation];
    NSMutableArray *mailArr = [[NSMutableArray alloc] init];
    
[fetchOp start:^(NSError *err, NSArray *msgs)
     {
        if (err == nil)
        {
            for (int i=0; i<[msgs count]; i++)
            {
                NSMutableDictionary *mailDict = [NSMutableDictionary dictionary];
                //MCOPOPMessageInfo *msg = [msgs objectAtIndex:i];
                //NSLog(@"Message:%@",msg);
                
                MCOPOPFetchHeaderOperation *headerOp  = [session fetchHeaderOperationWithIndex:i];
                [headerOp start:^(NSError * __nullable error, MCOMessageHeader * headerMsg)
                {
                    if ( error == nil ){
                        // Get subject for each mail
                        NSLog(@"String:%@ Subject = %@",headerMsg.from.displayName,headerMsg.subject);
                        
                        if ( headerMsg.subject != nil )
                            [mailDict setObject:headerMsg.subject forKey:@"subject"];
                        }
                    else {
                        
                    }
                }];
                MCOPOPFetchMessageOperation * op = [session fetchMessageOperationWithIndex:i];
                [op start:^(NSError * __nullable error, NSData * messageData)
                 {
                     if ( error == nil )
                     {
                         // messageData is the RFC 822 formatted message data.
                         MCOMessageParser *parser = [[MCOMessageParser alloc] initWithData:messageData];
                         NSArray *arr = parser.attachments;
                         //NSLog(@"Attachments: %@",arr);
                         NSMutableArray *attArr = [[NSMutableArray alloc] init];
                         for ( NSInteger j = 0; j <[arr count]; j++ )
                         {
                             NSMutableDictionary *attDict = [NSMutableDictionary dictionary];
                             
                             MCOAttachment *attachment = [arr objectAtIndex:j];
                             if ( attachment.filename != nil )
                             {
                                 [attDict setObject:attachment.filename forKey:@"attachmentFileName"];
                                 
                                 // Write the file to some detination
                                 NSString *filePath = [directoryPath stringByAppendingPathComponent:attachment.filename];
                                 if ( attachment.data) {
                                     [attachment.data writeToFile:filePath atomically:YES];
                                 }
                                 [attDict setObject:filePath forKey:@"filePath"];
                                 
                                 // Add array with attachment dict
                                 [attArr addObject:attDict];
                             }
                             
                             // Write the file to some destination
                             [mailDict setObject:attArr forKey:@"attachments"];
                         }
                         
                         // Add dict to
                         [mailArr addObject:mailDict];
     
                     }
                }];
            }
        }
        else
        {
            
        }
    }]

I really appreciate the help!!

Thank You,
Subhash

**Comment by CodaFi** [comment]
A few questions because this looks fine to me:

- Are you seeing any errors output as a result of any parts of the fetch operation?  
- Can you confirm that what you're seeing is what matches the account whose credentials you're supplying to the POP session?
