### ISSUE TITLE
Latest Android version dies when loading folder on android 6.0

### ISSUE THREAD

**Issue by githupfisher** [MailCore/mailcore2#1338]
when I use IMAPFolderInfoOperation load folder,it crash

**Comment by dinhviethoa** [comment]
Have you tried this build already? http://d.etpan.org/mailcore2-deps/mailcore2-android-beta/mailcore2-android-3-beta-3.aar

**Comment by githupfisher** [comment]
I have tried ,but not work
JNI DETECTED ERROR IN APPLICATION: expected a constructor but void com.libmailcore.NativeObject.initWithNative(long): 0xa9525148
01-14 18:00:24.135 13203-13203/im.mera.mera_android A/art: art/runtime/java_vm_ext.cc:410]     in call to NewObjectV
01-14 18:00:24.135 13203-13203/im.mera.mera_android A/art: art/runtime/java_vm_ext.cc:410]     from com.libmailcore.IMAPFolderInfoOperation com.libmailcore.IMAPSession.folderInfoOperation(java.lang.String)

**Comment by dinhviethoa** [comment]
Could you show the code you're using?
You need to IMAPFolderInfoOperation from an IMAPSession.

**Comment by githupfisher** [comment]
yes,I did.it work on android 5.0
IMAPSession imapSession = new IMAPSession();
 imapSession.setHostname(imap_svr);
        imapSession.setUsername(email);
        imapSession.setPassword(password);
        imapSession.setPort(map_port);
            imapSession.setConnectionType(ConnectionType.ConnectionTypeTLS);
 IMAPFolderInfoOperation op = imapSession.folderInfoOperation("INBOX");

**Comment by dinhviethoa** [comment]
Could you check if it's fixed now?
