### ISSUE TITLE
New binary on CocoaPods?

### ISSUE THREAD

**Issue by alexanderzhigulich** [MailCore/mailcore2#1345]
Hello,

I just wondering why won't you update binary version on pods?
I see latest release was made on March'15.
From that time I see lotta commits were made :).

Thanks!

**Comment by dinhviethoa** [comment]
Updated! Let me know if everything works fine.

**Comment by alexanderzhigulich** [comment]
Thanks a lot for a quick response!
I will let you know in a couple of days, need to play with the app to cover all test cases.

**Comment by alexanderzhigulich** [comment]
Seems no issues found.
Many thanks!
