### ISSUE TITLE
Carthage installation failed (code signing is required for product type 'Framework')

### ISSUE THREAD

**Issue by pgeof** [MailCore/mailcore2#1348]
Installing the iOS framework with carthage failed : 

> $ carthage update --platform iOS
> *** Fetching mailcore2
> *** Checking out mailcore2 at "0.6.2"
> *** xcodebuild output can be found in /var/folders/0q/176vx0td2yxf5y29t_srct740000gp/T/carthage-xcodebuild.CJVyfr.log
> *** Building scheme "mailcore ios" in mailcore2.xcodeproj
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)
> CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.2'
> A shell task failed with exit code 65:
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)
> 
> 

It seems that code signing identity could no be set to 'Don't code Sign' in the project build settings.

**Comment by dinhviethoa** [comment]
Please use "static mailcore ios" or advise a fix :)

**Comment by zosocanuck** [comment]
Hi,

I'm getting the same error when building a release version to run on my device:

CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.2'

I have a code signing profile setup for release.

Any ideas?

**Comment by dinhviethoa** [comment]
Have you tried using the target "static mailcore ios"?

**Comment by zosocanuck** [comment]
Yes I ended up linking to the static mailcore2 ios library.

**Comment by Zaheer6110** [comment]
Code signning issue solved but still getting this error with device but working on simulator.
process launch failed: timed out trying to launch app

**Comment by dinhviethoa** [comment]
It's unrelated. Locking this issue now.
