### ISSUE TITLE
Crash in +[MCONNTPGroupInfo load]

### ISSUE THREAD

**Issue by alexanderzhigulich** [MailCore/mailcore2#1349]
Hello!

Have you ever met this before?
I have this crash for several times a day.
Please, have a look and share your thoughts

_Note: this is not a main thread_
Thread : Crashed: Thread
0  libsystem_kernel.dylib         0x20789c84 __pthread_kill + 8
1  libsystem_pthread.dylib        0x2082bb47 pthread_kill + 62
2  libsystem_c.dylib              0x207200c5 abort + 108
3  Applic                          0x2c62cd **+[MCONNTPGroupInfo load] (MCONNTPGroupInfo.mm:22)**
4  Applic                          0x2d69dd **mailcore::IMAPSession::login(mailcore::ErrorCode*) (MCIMAPSession.cc:689)**
5  Applic                          0x2e267d **mailcore::IMAPCheckAccountOperation::main() (MCIMAPCheckAccountOperation.cc:21)**
6  Applic                          0x2cf62b **mailcore::OperationQueue::runOperations( (MCOperationQueue.cc:113)**
7  libsystem_pthread.dylib        0x2082ac7f _pthread_body + 138
8  libsystem_pthread.dylib        0x2082abf3 _pthread_start + 110
9  libsystem_pthread.dylib        0x20828a08 thread_start + 8

Many Thanks!

**Comment by dinhviethoa** [comment]
Hey! You can only used IMAPCheckAccountOperation on a new IMAPSession, where you've run no operations on it.
