### ISSUE TITLE
assert mainPart != NULL

### ISSUE THREAD

**Issue by grandM** [MailCore/mailcore2#1356]
So I'm trying to print the body of a mail message. The messages exist as I can pull the headers. When I used the deprecated fetchMessageOperationWithFolder() method I also got results. It wasn't clear to me though how I could separate the attachments from the body. Then I saw that a message object has an array attachments and you also created a plainTextBodyByRenderingOperationWithMessage() method. My sincere thanks for those by the way. 

I looked through the documentation but it is not enlightening me. Perhaps because I'm a bit of a noob in iOS. Anyhow I'm getting this error code: /Users/grandM/GitHub/mailcore2/src/core/renderer/MCHTMLRenderer.cpp:197: assert mainPart != NULL. I found it a bit strange that it is referring to my hard drive as I dragged your xcode project in my xcode project as you showed on youtube. Once again my thanks.

The code inflicting the code I copied beneath. It happens at the level of the mainPartFetchOperation.
`session.connectionType = MCOConnectionType.StartTLS
        
        let requestKind = MCOIMAPMessagesRequestKind.Headers
        let folder = "INBOX"
        let uids = MCOIndexSet(range: MCORangeMake(1, UINT64_MAX))
        
        let fetchOperation = session.fetchMessagesByNumberOperationWithFolder(folder, requestKind: requestKind, numbers: uids)
        fetchOperation.start { (error, fetchedMessages, vanishedMessages) -> Void in
            if (error != nil) {
                print(error?.localizedDescription)
            } else {

                for message in fetchedMessages! as! [MCOIMAPMessage] {

                let mainPartFetchOperation = session.plainTextBodyRenderingOperationWithMessage(message, folder: folder)
                    
                mainPartFetchOperation.start({ (bodyText, error) -> Void in

                    if error != nil {

                        print(error?.localizedDescription)
                    } else {

                        if bodyText != nil {
                            if bodyText?.isEmpty == false {
                        print(bodyText)
                            }
                        }
                    }
                })
                    

                    
                }
            }
        }
`

**Comment by dinhviethoa** [comment]
You need to include the bodystructure in the requestKind.

**Comment by dheerajghub** [comment]
Hi dinhvh, I have a doubt that can I get a indication whether message contains an attachment or not with help of mainpart.isAttachment ?? Cauz it always returning false even if message contains attachments!
