### ISSUE TITLE
synchronously download unread count for folders messages...

### ISSUE THREAD

**Issue by eduardolomb** [MailCore/mailcore2#1362]
Is there a way to synchronously download unread count for folders messages? 

The method / block:
MCOIMAPFolderStatusOperation * op = [session folderStatusOperation:encodedName];
                        [op start:^(NSError *error, MCOIMAPFolderStatus * info) {
                        newFolder.unreadMessageCount = [info unseenCount];
                        }];
is taking too long and i'm having trouble with my UI...by the way I tried to implement it when downloading folders so I have the name of all of them and the possibility to add all the folders and info. appropriately to an NSArray.

**Comment by dinhviethoa** [comment]
Even if it was synchronous, it would be too long.
I hope using session.connectionLogger will help.
