### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by shrishaster** [MailCore/mailcore2#1365]
While my app is fetching mail headers, their body and saving it, Mailcore2 has a lot of leaks.
<img width="1012" alt="screen shot 2016-02-18 at 1 11 35 am" src="https://cloud.githubusercontent.com/assets/3250858/13123117/a57329de-d5e0-11e5-847f-5151a59ccb63.png">
Above is an image from Instruments.

Let me know if you need anymore details.

**Comment by dinhviethoa** [comment]
Do you have a simple example to reproduce the memory leaks?
Thanks!

**Comment by shrishaster** [comment]
I don't think I can reproduce with a simple project and the project I am working I can't share.
Can you understand anything from the screenshot I have posted?
Will it help if I give their stack trace for each of the leaks?

**Comment by dinhviethoa** [comment]
It's likely that the memory leaks are on your end, because of the memory management in your app.

**Comment by shrishaster** [comment]
I am using mailcore2 as a framework built using Carthage. Can that cause some of sort of memory clean issues?

**Comment by dinhviethoa** [comment]
If you can't share a simple code to reproduce the issue, I can't help you.

**Comment by shrishaster** [comment]
Following is a screenshot of the stacktrace of one of the leaks:
<img width="1130" alt="screen shot 2016-02-18 at 12 38 25 pm" src="https://cloud.githubusercontent.com/assets/3250858/13136097/ac3bb036-d63c-11e5-9660-9916679e2706.png">

Does this help?
The reason I can't share my code is it's my company's property.

**Comment by shrishaster** [comment]
@dinhviethoa 
So I went through old issues and found this:
https://github.com/MailCore/mailcore2/issues/156

I can't see the attached screenshots due to some GitHub issue, but I think its the same issues I am facing. You closed the issue saying you fixed it in the commit:
https://github.com/MailCore/mailcore2/commit/f63f85b2bc62053ff7a8646c3c8d99966bbd8680

But that code fix is not there in 'master'. Did you forget to merge it?

**Comment by dinhviethoa** [comment]
I confirm: that fix is in master.

**Comment by shrishaster** [comment]
Hey
So I did some more profiling and zeroed in on the memory leaks. It's basically the following lines that leak memory:
- `emailMessage.uid`
- `emailMessage.gmailThreadID`
- `ccAddress.mailbox`
etc...

So all these leaks are when I use a Mailcore object and access some property of it. This mainly happens in a loop during the initial header sync of mails.

@dinhviethoa  Any solution to fix these leaks?

**Comment by dinhviethoa** [comment]
Please send pull request to fix the leaks. Obviously, I can't investigate the issue you're having.
I'm not experiencing it.
