### ISSUE TITLE
mailcore gives me a wrong date

### ISSUE THREAD

**Issue by zhangao0086** [MailCore/mailcore2#1366]
Here is logs:
```
* 3324 FETCH (UID 4821 BODYSTRUCTURE (("TEXT" "PLAIN" ("CHARSET" "utf-8") NIL NIL "QUOTED-PRINTABLE" 2020 34 NIL NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "utf-8") NIL NIL "QUOTED-PRINTABLE" 5720 86 NIL NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "----sinikael-?=_1-14556146145080.7677746945992112") NIL NIL NIL) ENVELOPE ({123}
Tue Feb 16 2016 17:23:34 GMT+0800
 =?UTF-8?Q?=28=E4=B8=AD=E5=9B=BD=E6=A0=87=E5=87=86?=
 =?UTF-8?Q?=E6=97=B6=E9=97=B4=29?= "=?utf-8?B?UmU6IOOAkOmHjeimgeOAkeWFs+S6juWFrOWPuOS6uuWRmOWPmOWKqOivtOaYjg==?=" ((NIL NIL "chendihai" "258.com")) ((NIL NIL "chendihai" "258.com")) ((NIL NIL "chendihai" "258.com")) (("=?utf-8?B?56iL5pWP?=" NIL "chengmin" "258.com")) (("12all" NIL "12all" "258.com")("=?utf-8?B?6a2P5aaC5p2w?=" NIL "weirujie" "258.com")("gongzuo" NIL "gongzuo" "shusheng.com")) NIL NIL "<1455614614700-b031b5b6-1d9ef452-1e5dbc22@258.com>") BODY[HEADER.FIELDS (DATE SUBJECT FROM SENDER REPLY-TO TO CC MESSAGE-ID REFERENCES IN-REPLY-TO REFERENCES)] {627}
From: chendihai@258.com
Sender: chendihai@258.com
To: "=?UTF-8?Q?=E7=A8=8B=E6=95=8F?=" <chengmin@258.com>
Cc: 12all <12all@258.com>, "=?UTF-8?Q?=E9=AD=8F=E5=A6=82=E6=9D=B0?="
 <weirujie@258.com>, gongzuo <gongzuo@shusheng.com>
Subject: Re: =?UTF-8?Q?=E3=80=90=E9=87=8D=E8=A6=81=E3=80=91?=
 =?UTF-8?Q?=E5=85=B3=E4=BA=8E=E5=85=AC=E5=8F=B8?=
 =?UTF-8?Q?=E4=BA=BA=E5=91=98=E5=8F=98=E5=8A=A8?=
 =?UTF-8?Q?=E8=AF=B4=E6=98=8E?=
Date: Tue Feb 16 2016 17:23:34 GMT+0800
 =?UTF-8?Q?=28=E4=B8=AD=E5=9B=BD=E6=A0=87=E5=87=86?=
 =?UTF-8?Q?=E6=97=B6=E9=97=B4=29?=
Message-Id: <1455614614700-b031b5b6-1d9ef452-1e5dbc22@258.com>

 FLAGS (\Seen))
```

Here is my used requestKind:
```
MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindUid | MCOIMAPMessagesRequestKindFullHeaders | MCOIMAPMessagesRequestKindFlags | MCOIMAPMessagesRequestKindStructure;
```

![0a7b7aa1-0692-4d0d-a719-fedbae0e7afd](https://cloud.githubusercontent.com/assets/7742344/13168438/9e6b131c-d717-11e5-9e87-f60832e78894.png)
(_the date is always the machine time_)

I've seen https://github.com/MailCore/mailcore2/issues/1085 and https://github.com/MailCore/mailcore2/issues/233 already. If I want the date to be `Tue Feb 16 2016 17:23:36 GMT+0800 (中国标准时间)`, how should I do?

Thanks in advance :)

**Comment by dinhviethoa** [comment]
Yeah. The date is in the wrong format.
Please take a look at MessageHeader::importIMAPEnvelope().
If you can provide a patch, that would be great!

**Comment by zhangao0086** [comment]
Hi @dinhviethoa  Thanks for your reply!
The `single_fields.fld_orig_date` always is NULL in the `MessageHeader::importIMFields`...
Maybe the problem is in the `mailimf_envelope_and_optional_fields_parse` of the libetpan?

**Comment by zhangao0086** [comment]
Why the `Subject` is able to process the encoding, but `Date` not?

**Comment by dinhviethoa** [comment]
The format of the date is broken. It doesn't conform to RFC 822.
There's some workaround in libetpan for other broken formats.
The format you have is not handled.
Pull requests are welcome.
Thanks.

**Comment by zhangao0086** [comment]
Thanks again!
One more question. If I want to handling the format which function is best to handling the broken format?

**Comment by zhangao0086** [comment]
@dinhviethoa Please review this:https://github.com/dinhviethoa/libetpan/pull/225
