### ISSUE TITLE
library not found for -licudata

### ISSUE THREAD

**Issue by raj-android-ios** [MailCore/mailcore2#1369]
Error : ld: library not found for -licudata
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dinhviethoa** [comment]
what platform? how did you set it up?

**Comment by raj-android-ios** [comment]
I am Working on an email Client iOS Project . i am using Thatinbox , ThatInbox is a free and open-source email client. In that project , MailCore is used  for receiving, viewing, and sending emails.

**Comment by dinhviethoa** [comment]
Mailcore has updated the dependencies.
Thatinbox did not update the dependencies.
