### ISSUE TITLE
add mailcore2,but project don't built.

### ISSUE THREAD

**Issue by maqihan** [MailCore/mailcore2#1372]
the Xcode build progress bar does not move ？？？

**Comment by maqihan** [comment]
[http://a3.qpic.cn/psb?/V14WlxO73PAitH/kJBqTY1IGVAioH37l94tR5GeCLYhWuRtDtF9*1bnUg0!/b/dAIBAAAAAAAA&ek=1&kp=1&pt=0&bo=QgeIAQAAAAADB.4!&sce=0-12-12&rf=viewer_4](url)

**Comment by lksnmnn** [comment]
Could you be more specific? It may be a good idea to add MailCore via CocoaPods.
