### ISSUE TITLE
mailcore2 in Swift2.0 cannot get "inbox" folder metadata.

### ISSUE THREAD

**Issue by shiwwgis** [MailCore/mailcore2#1373]
I use mailcore2 in Swift2.0,but cannot get "inbox" folder metadata.

code:

  let imapFetchMailCountOp = imapSession.folderInfoOperation("INBOX");

    imapFetchMailCountOp.start()
        {
            (error:NSError?,info:MCOIMAPFolderInfo?)->Void in
            if error == nil
            {
                print("inbox mail count=\((info?.messageCount)!)");
            }
            else
            {
                print("get mail count of inbox fail,\(error!)")
            }
    }
debug info:

get mail count of inbox fail,Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist. Folder selection failed" UserInfo={NSLocalizedDescription=The requested folder does not exist. Folder selection failed}

**Comment by shiwwgis** [comment]
I have solved it,because email provider has blocked my request,you should check you account's secure configaration.

**Comment by lksnmnn** [comment]
So the issue was with your email provider? This can be closed?
