### ISSUE TITLE
Fetch folders operation does not return

### ISSUE THREAD

**Issue by lksnmnn** [MailCore/mailcore2#1374]
Hi there,

I stumbled upon a rather strange issue:

On startup we loop through our IMAP accounts and start a ```MCOIMAPFetchFoldersOperation``` for each account. Each operation uses its own session and a central dispatch queue.

While all operations are starting and listing the account's folders (checked with a connection logger), not all come back and run their completion block.

I testet it with 3 accounts: at most 0 to 2 operations are calling their callback. Never all 3.

Calling ```[operation operationCompleted] ``` manually after some time, completes the operations as expected and they start running their completion blocks.

It seems to me like a problem within MailCore. Any ideas?

Cheers,
Lukas

Ps. Using latest version 0.6.3 via CocoaPods

**Comment by shiwwgis** [comment]
you can check error info and print it ,maybe you request is refused by you mail provider

**Comment by dinhviethoa** [comment]
Are you performing your calls to mailcore from a dispatch_queue?

**Comment by lksnmnn** [comment]
@shiwwgis No, the request is fine. I used the connection logger to check this.

@dinhviethoa Yes, we use the following code:

```obj-c

dispatch_async([SessionsHelper mailcoreDispatchQueue], ^{

        MCOIMAPFetchFoldersOperation* operation = [self.session fetchAllFoldersOperation];
        [operation setCallbackDispatchQueue:[SessionsHelper mailcoreDispatchQueue]];

        [operation start:^(NSError *error, NSArray *fetchedFolders)
         {
             [self handleConnectionError:error];

             dispatch_async([SessionsHelper mailcoreDispatchQueue], ^{
                   if(self.callback)
                        self.callback(error, fetchedFolders);
                   [self nowDone];
             });
         }];
    });

    [self waitUntilDone];
```

**Comment by lksnmnn** [comment]
Closing this...
