### ISSUE TITLE
Sporadic Crash on MCONNTPGroupInfo.mm

### ISSUE THREAD

**Issue by dsanghan** [MailCore/mailcore2#1383]
We're seeing this crash about 0.2% of sessions:

<pre><code>
Crashed: Thread
SIGABRT ABORT 0x00007fff8dc45002

Thread : Crashed: Thread
0  libsystem_kernel.dylib         0x7fff8dc45002 __pthread_kill + 10
1  libsystem_pthread.dylib        0x7fff887b95c5 pthread_kill + 90
2  libsystem_c.dylib              0x7fff931646e7 abort + 129
3  Canary                         0x109cacd1d +[MCONNTPGroupInfo load] (MCONNTPGroupInfo.mm:22)
4  Canary                         0x109cbe3d6 mailcore::IMAPSession::login(mailcore::ErrorCode*) (MCIMAPSession.cpp:695)
5  Canary                         0x109cce945 mailcore::IMAPCheckAccountOperation::main() (MCIMAPCheckAccountOperation.cpp:21)
6  Canary                         0x109cb6ae2 mailcore::OperationQueue::runOperations() (MCOperationQueue.cpp:120)
7  libsystem_pthread.dylib        0x7fff887b7c13 _pthread_body + 131
8  libsystem_pthread.dylib        0x7fff887b7b90 _pthread_body + 166
9  libsystem_pthread.dylib        0x7fff887b5375 thread_start + 13
</code></pre>

We don't have a lot of debugging information apart from this nor does anything seem obviously out there - any suggestions?

**Comment by dinhviethoa** [comment]
I think you're using IMAPCheckAccountOperation twice within the same session (or when the session is already connected), which is not allowed with this operation.

**Comment by dsanghan** [comment]
Ah I see. Thanks! I'll look into it.
