### ISSUE TITLE
how can I delete the attachment info in HTMLBody returned by htmlBodyRendering

### ISSUE THREAD

**Issue by shiwwgis** [MailCore/mailcore2#1387]
attachments info are showed like red rect in following picture,how can I hide or delete it?

![Uploading mail.png…]()

**Comment by dinhviethoa** [comment]
I can't see the picture here.

Anyway, you might want to use one of the following.
- MCOHTMLRendererIMAPDelegate
- MCOHTMLRendererDelegate

**Comment by shiwwgis** [comment]
I don't know why I cannot upload jpg. I used this code:

 content=[(MCOMessageParser *) _message  htmlBodyRendering].

I don't want to fetch full message

**Comment by shiwwgis** [comment]
I have solver this problem just by modifing MCOHTMLRendererIMAPDelegate.
