### ISSUE TITLE
may i use gcd such as     dispatch_sync when an operation start?

### ISSUE THREAD

**Issue by shiwwgis** [MailCore/mailcore2#1389]
i want to check account,hope to wait and get result until check operation is over. i have try dispatch_sync. i also try dispatch_semaphore_create+dispatch_semaphore_signal+dispatch_semaphore_wait,but all tasks are blocked

**Comment by dinhviethoa** [comment]
Maybe the best way to achieve it would be to wait by running a run loop.
See CFRunLoop APIs.
