### ISSUE TITLE
Trying to use carthage/xcode 7.3/from Swift "include of non-modular header inside framework module 'MailCore.MCIndexSet"

### ISSUE THREAD

**Issue by jonnolen** [MailCore/mailcore2#1390]
Steps:

* added mailcore2 to Cartfile
* `carthage update --use-submodules --platform iOS`
* dragged framework to project from `Carthage/Build` and added carthage copy-framework run script step, per carthage install instructions.
* added bridging header with `#import <MailCore/MailCore.h>`

I have also tried adding the `Other linker flags` from manual setup, as well as linking the CFNetwork and SecurityFrameworks and setting the c++ std lib version.

The offending line is the import of inttypes.h
```
//
//  MCIndexSet.h
//  mailcore2
//
//  Created by DINH Viêt Hoà on 3/4/13.
//  Copyright (c) 2013 MailCore. All rights reserved.
//

#ifndef MAILCORE_MCINDEXSET_H

#define MAILCORE_MCINDEXSET_H

#include <MailCore/MCObject.h>
#include <MailCore/MCRange.h>
#include <inttypes.h>
```

Setting `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES` also had no effect.

**Comment by dinhviethoa** [comment]
Did you update mailcore2 to the latest commit? A workaround has been applied on march 14th.

**Comment by jonnolen** [comment]
Derp.  Thanks.

**Comment by Isuru-Nanayakkara** [comment]
Hi guys,

I'm also having this issue. Is the fix included in the master branch? My current one is this.
```
github "MailCore/mailcore2" "master"
```

**Comment by dinhviethoa** [comment]
The fix is in the master branch.
Could you check if MCIndexSet.h matches the master version?

**Comment by Isuru-Nanayakkara** [comment]
The version Carthage checked out has this.
```
#ifndef MAILCORE_MCINDEXSET_H

#define MAILCORE_MCINDEXSET_H

#include <MailCore/MCObject.h>
#include <MailCore/MCRange.h>
#include <inttypes.h>

#ifdef __cplusplus

namespace mailcore {
```

In the source that exists in Github, it's [this](https://github.com/MailCore/mailcore2/blob/master/src/core/basetypes/MCIndexSet.h).

That is strange. Not sure why Carthage doesn't get the correct version.

**Comment by dinhviethoa** [comment]
Could you post an issue in Carthage about it? I'd need to add a release version of MailCore2 at some point that fixes it.

**Comment by Isuru-Nanayakkara** [comment]
I opened an issue [here](https://github.com/Carthage/Carthage/issues/1233).

**Comment by Isuru-Nanayakkara** [comment]
By the way, in the `Cartfile.resolved` file created by Carthage, I saw this.
```
github "MailCore/mailcore2" "0.6.2"
```
Is this the correct latest version?
