### ISSUE TITLE
Creating multipart/alternative messages

### ISSUE THREAD

**Issue by MichaelMcGuire** [MailCore/mailcore2#1391]
I've searched through the issues and documentation, but have not been able to find an answer to this seemingly simple question: Can I create a message using the `MCOMessageBuilder` with a `Content-Type` of `multipart/alternative`?  Using the `addAttachment` method, I always end up getting a `multipart/mixed` type instead.

Thanks for any help in advance!

**Comment by dinhviethoa** [comment]
You should be able to achieve that by using the properties htmlBody and textBody.
