### ISSUE TITLE
convertBlockQuoteToDIV() wrong when reply email more than 2 time with Apple mail

### ISSUE THREAD

**Issue by viettrungphan** [MailCore/mailcore2#1394]
More detail, our mail contents have many level of block quote tags, the javascript function convertblockquotetodiv() will make content of email mess-up.
![screen_shot_2016-04-05_at_9_19_58_am](https://cloud.githubusercontent.com/assets/16550689/14269560/f532f4d2-fb0f-11e5-96f6-a44f7f135bc1.png)

This is my fixed code using jquery.
function convertBlockQuotesToDivs() {
    var colorStep = 0;
    var blockquotes = document.getElementsByTagName('blockquote');
    for (var i = blockquotes.length - 1; i >= 0; i--) {
        var blockquote = blockquotes[i];
        var parent = blockquote.parentNode;
        var newElement = document.createElement('div');
        while(blockquote.firstChild){
            var color = incrementColor('#008000', colorStep);
            colorStep = colorStep + 100;
            var divElm = document.createElement('div');
            divElm.style['border-left'] = '1px solid ' + color;
            divElm.style['color'] = color;
            divElm.style['padding-left'] = '5px';
            $(divElm).prepend(blockquote.firstChild);
            newElement.appendChild(divElm);
        }
        $(blockquote).replaceWith(newElement);
    }
}

**Comment by dinhviethoa** [comment]
There's no javascript code in mailcore. It's probably not a mailcore isssue. I'm closing the issue.
