### ISSUE TITLE
Crash in `importIMFFields`

### ISSUE THREAD

**Issue by zhangao0086** [MailCore/mailcore2#1397]
I've received an extra header named `Cc`. It cannot be decoded:
![5593c85e-467d-4ec2-9b6d-ba7a73e1e7a4](https://cloud.githubusercontent.com/assets/7742344/14427266/866d85c8-0026-11e6-8fe2-57c9abc4a997.png)

The fieldValue contains some `\r\n ` in encoded value:
![7a50d8e1-2601-4799-b35c-27f0ce40e3ea](https://cloud.githubusercontent.com/assets/7742344/14427484/9d264682-0027-11e6-8bb3-8ff5c1c7a571.png)

I found two solutions:

**Solution 1** In `mailmime_encoded_word_parse`:
```c
  ...
  r = mailimf_char_parse(message, length, &cur_token, '?');
  if (r != MAILIMF_NO_ERROR) {
    res = r;
    goto free_charset;
  }
  
  r = mailimf_fws_parse(message, length, &cur_token); // This line should be added.
  r = mailmime_encoding_parse(message, length, &cur_token, &encoding);
  if (r != MAILIMF_NO_ERROR) {
    res = r;
    goto free_charset;
  }

  r = mailimf_char_parse(message, length, &cur_token, '?');
  if (r != MAILIMF_NO_ERROR) {
    res = r;
    goto free_charset;
  }
  ...
```

**Solution 2** Remove all `\r\n` in `fieldValue`:
```c
char *removeAllLineBreaks(char *message)
{
	char *toRemove = (char *)"\r\n";
	char *s = NULL;
	size_t toRemoveLength;
	while( (s = strstr(message, toRemove)) ) {
		toRemoveLength = strlen(toRemove);
		
		if (s[2] == ' ') {
			++toRemoveLength;
		}
		
		memmove(s, s + toRemoveLength, 1 + strlen(s + toRemoveLength));
	}
	
	return message;
}
```

then change 
`fieldValue = field->fld_data.fld_optional_field->fld_value;` 
to 
`fieldValue = removeAllLineBreaks(field->fld_data.fld_optional_field->fld_value);`

**Comment by zhangao0086** [comment]
Let me know your thoughts

**Comment by dinhviethoa** [comment]
Could you show the header of the message you received?
I'm wondering why it doesn't get caught in single_fields.fld_cc in the first place.

**Comment by dinhviethoa** [comment]
Actually, the following address failed to be parsed:

```
"=?gb18030?
 B?zfXA8c/O?=" <wanglixian@258.com> -> (null)
```

**Comment by zhangao0086** [comment]
You're right. There are only two problems:

1. The address does fail to parse.
1. I cannot access it via `header.cc`, but `extraHeaderValueForName:@"Cc"` can.

**Comment by dinhviethoa** [comment]
The problem 2/ is due to 1/.

**Comment by zhangao0086** [comment]
Could you please fix the problem?

**Comment by dinhviethoa** [comment]
You you're able to provide a pull request (probably on libetpan side) before me, I'll be happy to merge it.
But yeah, I'll fix it eventually.

**Comment by dinhviethoa** [comment]
I fixed at least the crash.
and filed this issue: https://github.com/dinhviethoa/libetpan/issues/239

**Comment by zhangao0086** [comment]
Thanks!

**Comment by dinhvh** [comment]
Fixed with:
https://github.com/dinhvh/libetpan/commit/e5db7e7ae73986e4efc92a97914930c00f74e21e
