### ISSUE TITLE
How can I get Chinese filename correctly instead of "" ___________________20160414.docx"

### ISSUE THREAD

**Issue by shiwwgis** [MailCore/mailcore2#1398]
I use attactment.filename to get filename,but Chinese filename is converted into "" ___________________20160414.docx"

**Comment by dinhviethoa** [comment]
If you had the source of the message, it would actually be helpful to investigate.

**Comment by shiwwgis** [comment]
message source:
(lldb) po self.message

<mailcore::IMAPMessage:0x7fd9617621a0 1276752484 110
<mailcore::MessageHeader:0x7fd963660b20
Message-ID: 6E9B8126-16FC-4BF3-814C-44F2D084EB6C@126.com
Sender: mailcore::Address:0x7fd9637f56e0 工作邮箱 <chinagis001@126.com>
From: mailcore::Address:0x7fd9637f1940 工作邮箱 <chinagis001@126.com>
To: [mailcore::Address:0x7fd9637f0450 wangning <wangning1@supermap.com>,mailcore::Address:0x7fd9637ef110  <huangqian@supermap.com>,mailcore::Address:0x7fd9637f1840 张丽 <zhangli@supermap.com>]
Reply-To: [mailcore::Address:0x7fd9637ef640 工作邮箱 <chinagis001@126.com>]
Subject: from 石伟伟 郑州文档修改意见
><mailcore::IMAPMultipart:0x7fd9637ee5a0 alternative [<mailcore::IMAPPart:0x7fd9637f3050
mime type: text/plain
charset: utf-8
inline: 0
attachment: 0
>,<mailcore::IMAPMultipart:0x7fd9637ee830 mixed [<mailcore::IMAPPart:0x7fd9637ed050
mime type: text/html
charset: gb2312
inline: 0
attachment: 0
>,<mailcore::IMAPPart:0x7fd9637f1ff0
filename: ___________________20160414.docx
mime type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
inline: 0
attachment: 1
x-apple-part-url: EADA6871-3A80-4DFE-9093-FEDACDA4DAE9
>,<mailcore::IMAPPart:0x7fd9637ce3c0
mime type: text/html
charset: utf-8
inline: 0
attachment: 0
>]>]>
>


attatchment source:

<mailcore::IMAPPart:0x7fd9637f1ff0
filename: ___________________20160414.docx
mime type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
inline: 0
attachment: 1
x-apple-part-url: EADA6871-3A80-4DFE-9093-FEDACDA4DAE9
>

**Comment by dinhviethoa** [comment]
Could you show the RFC 822 message source instead? Thanks!
