### ISSUE TITLE
Incorrect html rendering

### ISSUE THREAD

**Issue by dsanghan** [MailCore/mailcore2#1401]
Visually:

<img width="600" alt="renderingbug" src="https://cloud.githubusercontent.com/assets/6698354/14640169/efe37232-065d-11e6-8325-b329bedd4d39.png">

In HTML, the `<dfn>` tags are being converted to `<div>` incorrectly.

I'm using:
`- (NSString *) htmlRenderingWithFolder:(NSString *)folder delegate:(id <MCOHTMLRendererIMAPDelegate>)delegate;` with a vanilla rendering delegate.

Here's the full [message](https://github.com/MailCore/mailcore2/files/225919/message.txt)

**Comment by dinhviethoa** [comment]
`<dfn>` doesn't seem to be a valid HTML tag anyway.
Maybe the CSS is doing something with that tag.

**Comment by dinhviethoa** [comment]
The full message you sent renders properly for me.
![screen shot 2016-05-11 at 11 26 30 pm](https://cloud.githubusercontent.com/assets/332168/15205880/ce293f90-17cf-11e6-8404-3bda4adba191.png)

**Comment by dsanghan** [comment]
Here's an example project. Still the same issue using an eml with MCOMessageParser and htmlRenderingWithDelegate:nil

[EML Debug](https://github.com/dsanghan/mailcoreDebug)

**Comment by dsanghan** [comment]
Ok, seems like `html->cleanedHTMLString();` is at fault for the table rows. There's still some css substitution going on for tables.

**Comment by dsanghan** [comment]
Yeah figured it out. The` <!DOCTYPE ...>` was being mangled. That resolved the remaining issues.
