### ISSUE TITLE
MCOErrorGmailIMAPNotEnabled ignored

### ISSUE THREAD

**Issue by alexanderzhigulich** [MailCore/mailcore2#1403]
Hello!

I just noticed that mailcore ignores MCOErrorGmailIMAPNotEnabled erro code.
If user turned off IMAP support on hist account mailcore returns simple MCOErrorAuthentication with the message inside "Unable to authenticate with the current session's credentials.".

Is that true? Or I missed smth?

Thank you!

**Comment by dinhviethoa** [comment]
Could you show the connection loggers from the Gmail server?
Maybe I need to update the code to match the error string returned by Gmail.
Thanks!

**Comment by alexanderzhigulich** [comment]
Sorry Just saw your answer...
Will provide logs soon.

**Comment by dinhviethoa** [comment]
ping?

**Comment by alexanderzhigulich** [comment]
Hi,
Sorry, for the delay, was really busy.
We managed this in a bit another way.
We use our backend for internal needs and it uses JavaMail which detects this error properly and returns to the client app the internal code.

So... returning to the issue:
Here is the error:
Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo={NSLocalizedDescription=Unable to authenticate with the current session's credentials.}

Here is the connection logs:

IMAP session[0] * OK Gimap ready for requests from 134.17.26.21 u139mb305548432lfd
IMAP session[1] 1 CAPABILITY
IMAP session[0] * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
1 OK Thats all she wrote! u139mb305548432lfd
IMAP session[2] 2 AUTHENTICATE XOAUTH2 dXNlcj10ZXN0QHRpbXlvLmNvAWF1dGg9QmVhcmVyIHlhMjkuQ2pIa0Ftc2dVamdpOTlPUDNvcEo3aUNNdXpzbDRBS1VscnZHbmRqRS1sLUFQSmNCRG1tWFd6X0dnQVBsTDJFbll6V2MBAQ==
IMAP session[0] + eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==
IMAP session[1] 
IMAP session[0] 2 NO [ALERT] IMAP access is disabled for your domain. Please contact your domain

**Comment by dinhviethoa** [comment]
See the error message at protocol level: "IMAP access is disabled for your domain. Please contact your domain"
