### ISSUE TITLE
Outlook Trash Folder Path

### ISSUE THREAD

**Issue by andrewlai87** [MailCore/mailcore2#1408]
Right now, providers.json has for the trash folder path of Outlook as "Deleted Messages".  However, I just created a new Outlook account, and the IMAP folder path for trash is "Deleted".  

Not sure if this is the case for all outlook and hotmail accounts, so I'm posting this issue since it might make sense to get a more general consolidation on this.

**Comment by dinhviethoa** [comment]
Could you send a pull request to fix it? Thanks!
It highly depends on each provider.

**Comment by andrewlai87** [comment]
Just submitted a pull request
