### ISSUE TITLE
MCOMessageParser partForContentID returns always nil

### ISSUE THREAD

**Issue by malavsoni** [MailCore/mailcore2#1412]
Hello 
I am using the MailCore2 and fetching the emails.
Now I want to get embedded images from the HTML String. 
I have posted question in StackOverFlow also : http://stackoverflow.com/questions/36944721/mailcore-2-partforcontentid-returns-always-nil
I follow the same code from here : https://github.com/MailCore/mailcore2/wiki/Embedding-images-in-HTML-rendered-message

When I call below method it always return nil attachment. 

   `-(MCOAttachment*)partForContentID:(NSString*)partUniqueID{    
        MCOMessageParser *parser = [MCOMessageParser messageParserWithData:mailBodyData];
        NSLog(@"Render :: %@",[parser htmlBodyRendering]);
        MCOAttachment * attachment = (MCOAttachment *) [parser partForContentID:partUniqueID];
        return attachment;
   }`

You can check whole code in stackoverflow link.

And what should I pass in mailBodyData ?

**Comment by dinhviethoa** [comment]
It sounds like you removed your stackoverflow question. Closing here as well.
