### ISSUE TITLE
dependencies library version 

### ISSUE THREAD

**Issue by naderi4** [MailCore/mailcore2#1413]
![snip_20160429224250](https://cloud.githubusercontent.com/assets/10121766/14925488/2f83db80-0e37-11e6-8ad9-dedd4f78ea44.png)
i want build mailcore2 in visual studio 2012 for windows
and run it in user computer without Visual C++ Redistributable Packages instillation
what is version of below library that use in mailcore2
CTemplate
Cyrus SASL 
LibXML 2 
Tidy HTML5 
zlib 
icu4c 
OpenSSL 
pthread 
where is source code of library
thanks

**Comment by dinhviethoa** [comment]
They were built using visual studio 2013.

ctemplate: https://github.com/dinhviethoa/ctemplate
cyrus sasl: https://github.com/dinhviethoa/cyrus-sasl
libxml2: https://github.com/dinhviethoa/libxml2
tidy: https://github.com/dinhviethoa/tidy-html5
zlib: https://github.com/dinhviethoa/zlib
icu4c: http://apps.icu-project.org/icu-jsp/downloadPage.jsp?ver=54.1&base=c&svn=release-54-1
openssl: http://www.npcglib.org/~stathis/blog/precompiled-openssl/
pthread: https://sourceforge.net/projects/pthreads4w/
