### ISSUE TITLE
Static library symbols not found

### ISSUE THREAD

**Issue by dmholmes** [MailCore/mailcore2#1414]
Using the binary download I'm having trouble with undefined symbols using the static library. I've tried setting header search paths to no avail. How do you get the static library to find the header files?

**Comment by dinhviethoa** [comment]
Could you show the specific issue with the symbols, like build logs?
Thanks!

**Comment by dmholmes** [comment]
Absolutely.

Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      lepMixedConv(char const*, char const*, char const*, unsigned long, char*, unsigned long*) in libMailCore-ios.a(MCData.o)
      _mail_iconv in libMailCore-ios.a(charconv.o)
  "_iconv_close", referenced from:
      lepMixedConv(char const*, char const*, char const*, unsigned long, char*, unsigned long*) in libMailCore-ios.a(MCData.o)
      _charconv in libMailCore-ios.a(charconv.o)
      _charconv_buffer in libMailCore-ios.a(charconv.o)
  "_iconv_open", referenced from:
      lepMixedConv(char const*, char const*, char const*, unsigned long, char*, unsigned long*) in libMailCore-ios.a(MCData.o)
      _charconv in libMailCore-ios.a(charconv.o)
      _charconv_buffer in libMailCore-ios.a(charconv.o)
  "_res_9_dn_expand", referenced from:
      mailcore::MXRecordResolverOperation::main() in libMailCore-ios.a(MCMXRecordResolverOperation.o)
  "_res_9_ns_initparse", referenced from:
      mailcore::MXRecordResolverOperation::main() in libMailCore-ios.a(MCMXRecordResolverOperation.o)
  "_res_9_ns_parserr", referenced from:
      mailcore::MXRecordResolverOperation::main() in libMailCore-ios.a(MCMXRecordResolverOperation.o)
  "_res_9_ns_sprintrr", referenced from:
      mailcore::MXRecordResolverOperation::main() in libMailCore-ios.a(MCMXRecordResolverOperation.o)
  "_res_9_search", referenced from:
      mailcore::MXRecordResolverOperation::main() in libMailCore-ios.a(MCMXRecordResolverOperation.o)

**Comment by dinhviethoa** [comment]
link with -liconv and -lresolv.

**Comment by dmholmes** [comment]
Thank you!
