### ISSUE TITLE
Get oldest uid in a folder (was Fetch <next N> messages)

### ISSUE THREAD

**Issue by malcommac** [MailCore/mailcore2#1415]
Hi guys,
I'm using `MCOIMAPSession's` `fetchMessagesByNumberOperationWithFolder` to get a list of messages inside a folder.
How can I say "download from 50th message for 100 messages?"

**Comment by malcommac** [comment]
Okay I suppose I should get them by uid, but how can I get the range of uid inside a folder?

**Comment by malcommac** [comment]
Okay it should be:

```
let index = MCOIndexSet(range: MCORangeMake(LOCATION_IDX, COUNT))
let type = MCOIMAPMessagesRequestKind.HeaderSubject
let op = session.fetchMessagesOperationWithFolder(folderName, requestKind: type, uids: index)
```

And I could use MCOIMAPFolderInfo's messageCount to get the max LOCATION_IDX value, right?

**Comment by dinhviethoa** [comment]
Sure!
Make sure the MCOIndexSet you created matches the range you expect by showing.
It might be off by 1.
