### ISSUE TITLE
Can we link with the internal libEtPan?

### ISSUE THREAD

**Issue by CTMacUser** [MailCore/mailcore2#1425]
If we link to MailCore2, can we access the headers (and described types & functions) to its internal LibEtPan? Or do we have to separately download and link to LibEtPan if we want to use functions from both libraries?

(I guess you guys should add labels for "question" and "libEtPan".)

**Comment by dinhviethoa** [comment]
Questions should ideally go on stackoverflow. There's already a libetpan label.
To answer quickly, what functionality would you need from libetpan that's not available on mailcore?
