### ISSUE TITLE
windows IMAP Save message Attachment in file

### ISSUE THREAD

**Issue by naderi4** [MailCore/mailcore2#1430]
i try to save IMAP message attachment in file 
but return error file 35
![capture](https://cloud.githubusercontent.com/assets/10121766/15266831/61b2b7ee-195d-11e6-8df5-1e693d82483b.PNG)

**Comment by dinhviethoa** [comment]
You're using:
```
data->writeToFile([path])
```
And the path you're providing is probably not valid.

**Comment by naderi4** [comment]
problem resolved 

FILE * mailcore::win32_fopen(const char * filename, const char * mode)
{
    FILE * f = NULL;
    int r = fopen_s(&f, filename, "rb");
    if (r != 0) {
        return NULL;
    }
    return f;
}

MCwin32.cpp
to

FILE * mailcore::win32_fopen(const char * filename, const char * mode)
{
    FILE * f = NULL;
    int r = fopen_s(&f, filename, mode);
    if (r != 0) {
        return NULL;
    }
    return f;
}
