### ISSUE TITLE
ld: library not found for -lctemplate-ios

### ISSUE THREAD

**Issue by keyjacky** [MailCore/mailcore2#1431]
I want to use mailcore2 in my iOS project  , if I drag the mailcore2 project into my project ,everything work    well . But if I use static library , an error turn up when I bulid the project . Here is the error , please help to solve it

ld: library not found for -lctemplate-ios
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm not using Cocoapods

**Comment by dinhviethoa** [comment]
You need to remove the linker flags.
All the dependencies are included in the static library.

**Comment by keyjacky** [comment]
Is all linker flags should be remoed or just some of them ?

**Comment by dinhviethoa** [comment]
Try it and remove the ones that fail.

**Comment by keyjacky** [comment]
It's not work ! if I remove the ones tha fail

**Comment by dinhviethoa** [comment]
Please show more logs.

**Comment by keyjacky** [comment]
I add these(-lctemplate-ios -letpan-ios -lxml2 -lsasl2 -liconv -ltidy -lz -lc++ -lresolv -stdlib=libc++ -ObjC) linker flags in project , build error appear : 

ld: library not found for -lctemplate-ios
clang: error: linker command failed with exit code 1 (use -v to see invocation)




then I remove the linker flag -lctemplate-ios,  build error appear : 

ld: library not found for -letpan-ios
clang: error: linker command failed with exit code 1 (use -v to see invocation)






so I remove the linker flag  -letpan-ios,  build error appear : 

ld: library not found for -lsasl2
clang: error: linker command failed with exit code 1 (use -v to see invocation)




I continute remove the linker flag  -lsasl2,  about 200 build error appear like :

Undefined symbols for architecture armv7:
  "_mailstream_get_certificate_chain", referenced from:
      mailcore::checkCertificate(_mailstream*, mailcore::String*)
