### ISSUE TITLE
Error while trying to embed MailCore2 in a framework

### ISSUE THREAD

**Issue by klefevre** [MailCore/mailcore2#1432]
I'm trying to embed MailCore2 in our own framework but I'm stuck on an error compilation. 

We use Carthage to checkout our dependencies as following:
`carthage update --use-submodules --no-use-binaries --no-build`
and we build them in a workspace "manually" with Xcode.

I properly linked MailCore2 in own framework and it builds properly if we don't use it =/

But if we import the module we have this issue:
<img width="378" alt="capture d ecran 2016-05-16 a 19 14 34" src="https://cloud.githubusercontent.com/assets/1300874/15297449/763af39a-1b9a-11e6-96ac-95f4bcb926f4.png">
<img width="476" alt="capture d ecran 2016-05-16 a 19 15 08" src="https://cloud.githubusercontent.com/assets/1300874/15297476/a6ce9656-1b9a-11e6-83b2-32b621e86da7.png">
<img width="409" alt="capture d ecran 2016-05-16 a 18 55 09" src="https://cloud.githubusercontent.com/assets/1300874/15297480/ad0bbd1e-1b9a-11e6-852b-92e601c050d5.png">

> MailCore.h
> <img width="548" alt="capture d ecran 2016-05-16 a 18 55 32" src="https://cloud.githubusercontent.com/assets/1300874/15296975/21993646-1b98-11e6-9f87-0d66aa751395.png">

Any idea how to fix that ?

**Comment by coryoso** [comment]
I had the same problem and found the issue: The releases are more than 600 commits behind the master.
As Carthage always uses the last release, the fix is to simply force the use of the latest version by replacing `github "MailCore/mailcore2"` with `github "MailCore/mailcore2" "master"` in the cartfile

**Comment by atljeremy** [comment]
> the fix is to simply force the use of the latest version by replacing github "MailCore/mailcore2" with github "MailCore/mailcore2" "master" in the cart file

That's not a fix, it's a dangerous alternative. Just blindly relying on the latest from `master` could lead to all sorts of issues in your app. The real fix would be for those maintaining this project to create regular, smaller, releases. The fact that the last release was created in Feb. 2016 and is now 141 commits behind master tells me there is no clear cut off for each releasable chunk of code. I would suggest the maintainers start utilizing the issues and milestones features Github provides to better track what they'd like to release in each version. This will also give everyone else an idea of what to expect in the next release. Right now, we have absolutely no idea what to expect in the next release, nor when to expect it to be released.

For the time being, I would highly recommend you **not** just blindly target the master branch and instead, target a specific sha. Once you find a sha that works well, lock it down and do not accept anything else until the next release is out. Example...

```
github "MailCore/mailcore2" "7eeb60a8b42cddcd4e61d299c8037cbb22eb63ba"
```
