### ISSUE TITLE
MCAssertInternal : assert mState == STATE_CONNECTED

### ISSUE THREAD

**Issue by malavsoni** [MailCore/mailcore2#1434]
Hello 
I am using mailcore in my app and I am facing some assert issue with it.

In my app 2 things happening concurrently.
- Downloading mails in background
- Download mail with specific uids

I have attached the error screenshot which I am facing and another screenshot where I init the session object.

scenario is like when i fetched email in background (imapSession init successfully) now I use same reference to fetch email with specific uids and crashed.

I don't understand why it failed.

![mailcore satup](https://cloud.githubusercontent.com/assets/11372923/15333953/8ecea6b4-1c89-11e6-9800-3498a6087de3.png)
![error](https://cloud.githubusercontent.com/assets/11372923/15333955/8f26f422-1c89-11e6-995a-4b79e4ba6b82.png)

**Comment by dinhviethoa** [comment]
Once you used checkAccount on a session. You should get rid of that session.

**Comment by malavsoni** [comment]
So we need to write checkAccount only once in app life time?

**Comment by malavsoni** [comment]
I wrote like below

    // Mailcore setup
    if (!self.imapSession) {
        self.imapSession = [[MCOIMAPSession alloc] init];
        self.imapSession.hostname = kHostName;
        self.imapSession.port = 993;
        self.imapSession.username = [EventBinUser sharedDelegate].email;
        [self.imapSession setCheckCertificateEnabled:NO];
        self.imapSession.password = nil;
        if (auth.accessToken != nil) {
            self.imapSession.OAuth2Token = auth.accessToken;
            self.imapSession.authType = MCOAuthTypeXOAuth2;
        }
        self.imapSession.connectionType = MCOConnectionTypeTLS;
        self.imapCheckOp = [self.imapSession checkAccountOperation];
    }
    // resetting inbox
    messageContainer = nil;
    // account vlaidation
    [self.imapCheckOp start:^(NSError *error) {
        if (error == nil){
            // My Operation
        }
    }];

is this the correct way to create it?

and how should I reuse it?

**Comment by dinhviethoa** [comment]
`-checkAccountOperation` is meant to be used only when checking credentials of the account: when adding the account to the app.
After that you don't need to use it.
If you need to "ping" the connection, use IDLE or NOOP.

**Comment by malavsoni** [comment]
Got it....
Solved Issue... Thnx for the Help.
