### ISSUE TITLE
Storing MCOIMAPMessage in Core Data

### ISSUE THREAD

**Issue by asjesset** [MailCore/mailcore2#1437]
I am trying to store MCOIMAPMessage in core data to avoid requerying the imap server as much as possible.

I see it implements NSCoding. There are some mentions to mainPart needing to be handled differently in issue 461.

@dinhviethoa indicates that mainPart (MCOAbstractPart) implements NSCoding, but I am not seeing that in the source. Does it implement NSCoding? Why doesn't it encode/decode cleanly with MCOIMAPMessage? Is there another way I can do this?

Thanks for the help! I have enjoyed using mailcore2.

**Comment by dinhviethoa** [comment]
Just give it a try. If something doesn't work expectedly, let me know.

**Comment by asjesset** [comment]
I had forgotten to add MCOIMAPMessagesRequestKindStructure to my requestKind.

Still now sure how it implements coding, but everything works now. Closing!

**Comment by kapil0408** [comment]
@asjesset Can you please share code of storing MCOIMapMessage in core data or some clue for it.
I have used Transformable attribute for MCOIMapMessage. it is working fine on saving but when I am fetching from local DB then it showing error:

/Users/tejendramac/Desktop/MYPROJECTS/trunk/mailcore2/src/objc/utils/NSObject+MCO.mm:104: assert aClass != nil

Please help.
Thanks

**Comment by kapil0408** [comment]
Solved.
