### ISSUE TITLE
Secure Sockets Layer 3.0 (SSLv3) protocol and the RC4 cipher suites for TLS Wrapper

### ISSUE THREAD

**Issue by dafdafydd** [MailCore/mailcore2#1440]
Hello,

I use MailCore to send e-mails from my app via Amazon SES. A few days ago I received this e-mail:

"As part of our continuing efforts to help you protect your data, Amazon SES is discontinuing support of the Secure Sockets Layer 3.0 (SSLv3) protocol and the RC4 cipher suites for TLS Wrapper connections to the Amazon SES SMTP endpoints. This change is scheduled for June 29th, 2016.

You are receiving this email because our logs indicate that your client software might connect to Amazon SES SMTP endpoints through a TLS wrapper that uses RC4 or SSLv3. To avoid interrupted access to Amazon SES, you must update your client SMTP software to use Transport Layer Security 1.0 (instead of SSLv3) as the minimum protocol version, and strong cryptographic ciphers instead of RC4 cipher suites. Details on how to do this are specific to your client software, so please refer to that software's documentation."

To be honest, I am a bit ignorant as far as server connections are concerned and thus I need to ask you for help.

Would you be able to point me to the right direction about what I should do with my MailCore implementation?

**Comment by dinhviethoa** [comment]
Are you using MailCore on iOS?
Did you update to the latest master? It should use an updated version of libetpan.

**Comment by dafdafydd** [comment]
Hello,
Thank you for your response and sorry for a late reply.

Yes, I am using MailCore on iOS and I use the latest master installed via CocoaPods.

I read more about the thing and found this part which directly applies to the issue:

"Once you have updated your SMTP client, you can verify that it no longer uses SSLv3 or RC4 cipher suites by pointing it to port 3465 of the Amazon SES SMTP endpoint and sending a test email. The SMTP endpoint is configured to refuse SSLv3 and RC4 connections to port 3465, so a successfully sent test email means that your SMTP client is using TLS and strong cryptographic ciphers. Please note that the Amazon SES SMTP endpoints only accept connections on port 3465 until June 29th, 2016 for testing SMTP clients without SSLv3 and RC4; in other words, port 3465 shouldn't be used on production systems. For a list of Amazon SES SMTP endpoints, please see the developer guide: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html."

So I tried it and sent an e-mail with the following settings:

MCOSMTPSession *smtpSession = [[MCOSMTPSession alloc] init];
        smtpSession.hostname = @"email-smtp.us-east-1.amazonaws.com";
        smtpSession.port = 3465;
        smtpSession.username = @"<someusername>";
        smtpSession.connectionType = MCOConnectionTypeTLS;

And it worked fine - the e-mail got sent and received with an attachment.

Do you believe I can assume the issue to be resolved?

**Comment by dinhviethoa** [comment]
Cocoapods might be behind.
Could you try to the use the master on the repo and check that it's fixed fo you?

**Comment by dafdafydd** [comment]
Thank you very much for your response. I tried both - results are the same - everything works fine.

Actually, I wonder if there is any issue at all - as I mentioned before, I would be grateful if you could review my attempt to send the e-mail via the 3465 port. All worked fine so I wonder if their algorithms are not oversensitive.

**Comment by dinhviethoa** [comment]
Well, the code looks fine. If you're up to date with libetpan and mailcore, everything should be good and you should not receive warnings. Reopen if you can still see warnings.
