### ISSUE TITLE
Podspec needs to be in repo root

### ISSUE THREAD

**Issue by virtru-bjost** [MailCore/mailcore2#1451]
According to https://guides.cocoapods.org/using/the-podfile.html the podspec file needs to be in the repo root. Without it in the root, we are unable to specify specific commits that fix any issues we have until a new cocoapod build is created and uploaded.

**Comment by dinhviethoa** [comment]
The issue is that Cocoapods doesn't support well MailCore. Therefore, I had to create binaries for the cocoapods. Then, the fix won't be available until I create a new cocoapods.

**Comment by virtru-bjost** [comment]
I see. Any idea when 0.6.5 will be released?

**Comment by virtru-bjost** [comment]
@dinhviethoa any update on when a new version will be out with the latest changes? Or possibly an updated podspec script that can create the binaries locally?

**Comment by dinhviethoa** [comment]
Hey Brian, could you investigate if we can create the binaries locally with a podspec? build-mailcore2-ios.sh / build-mailcore2-osx.sh is how the binaries are created.

**Comment by virtru-bjost** [comment]
@dinhviethoa I have done this and have successfully built them locally via https://github.com/virtru/mailcore2

However, now I am getting the same errors as https://github.com/MailCore/mailcore2/issues/1431 and https://github.com/MailCore/mailcore2/issues/584

If you want to try for iOS (haven't updated the mac os x) build script yet, you can set the cocoapod to

`pod 'mailcore2-ios', :git => 'http://github.com/virtru/mailcore2.git'`

let me know if you have any thoughts on the errors. Once I get this solved I can combine the 2 spec files and have a single one at the root.

**Comment by dinhviethoa** [comment]
Could you show the specific errors you got?

**Comment by dinhviethoa** [comment]
What would be the instructions for people to install the Cocoapods in their app?

**Comment by virtru-bjost** [comment]
They would just add

`pod 'mailcore2-ios', :git => 'http://github.com/MailCore/mailcore2.git'`

to their pod file and run `pod install` to get the latest master branch

**Comment by dinhviethoa** [comment]
It's great! Could you start sending a pull request? I'll comment on the patch over here.

**Comment by virtru-bjost** [comment]
Closing as this was done in PR https://github.com/MailCore/mailcore2/pull/1460

**Comment by dinhviethoa** [comment]
Hey Brian, could you check the pod lint on the new podspec? Thanks!
