### ISSUE TITLE
How to use CustomCommandOperation

### ISSUE THREAD

**Issue by yann-developer** [MailCore/mailcore2#1455]
I need to be performed according to the message - id query uid, How to use CustomCommandOperation

Instruction："UID SEARCH HEADER Message-Id fa240531-6d94-4a1c-9617-f9b64099e712@yangzhende-iPhone"

**Comment by dinhviethoa** [comment]
You can use the regular searchOperation for that.

**Comment by yann-developer** [comment]
Can give me an example？

**Comment by yann-developer** [comment]
thanks
    MCOIMAPSearchOperation * op = [self.imapSession searchExpressionOperationWithFolder:@"INBOX" expression:[MCOIMAPSearchExpression searchHeader:@"Message-ID" value:@"2afa5767db1622a-0000c.Richmail.00039042141391592520@139.com"]];
    [op start:^(NSError * _Nullable error, MCOIndexSet * _Nullable searchResult) {
        
    }];
