### ISSUE TITLE
Swift: Include of non-modular header inside framework

### ISSUE THREAD

**Issue by marbetschar** [MailCore/mailcore2#1456]
I'm trying to use MailCore in a Swift project and have installed it using Carthage.

Unfortunately, I'm unable to use the preferred `import MailCore` as this lends to a `Could not build Objective-C module "MailCore"` error.

Even worse, if I add a BridgingHeader as suggested, Xcode 7.3.1 claims `Include of a non-modular header inside framework module "MailCore.MCIndexSet"`.

How to fix this?

**Comment by tesserakt** [comment]
👍

**Comment by marbetschar** [comment]
I've just read #1432 and installing MailCore with Carthage using `master` seems to fix this problem:
`github "MailCore/mailcore2" "master"`

So my next question is: How safe is it to use `master` in a production app?

**Comment by hailcl** [comment]
same problem with @marbetschar
