### ISSUE TITLE
How to remove the padding-bottom: 20px?

### ISSUE THREAD

**Issue by zhangao0086** [MailCore/mailcore2#1459]
I just want to get the html body(not include any attachments). I'm using `htmlBodyRenderingOperationWithMessage`, but I've noticed is that the HTMLString contains a `<div style="padding-bottom: 20px;">`.

I have been trying to fix it via `MCOHTMLRendererIMAPDelegate` but no success. I can't use the `fetchMessageOperationWithFolder` and the `fetchParsedMessageOperationWithFolder` APIs, it's will get whole message content(include all attachments).

I was wondering if you can help me.... thank you.. ^^

**Comment by dinhviethoa** [comment]
Use
```
@interface MCOIMAPMessage
- (NSString *) htmlRenderingWithFolder:(NSString *)folder
                              delegate:(id <MCOHTMLRendererIMAPDelegate>)delegate;
```

or 

```
@interface MCOMessageParser
- (NSString *) htmlRenderingWithDelegate:(id <MCOHTMLRendererDelegate>)delegate;
```

And use MCOHTMLRendererDelegate methods.

Those two methods are accurate:
```
- (NSString *) abstractMessage_templateForMessage:(MCOAbstractMessage *)msg;
- (NSString *) abstractMessage:(MCOAbstractMessage *)msg templateForEmbeddedMessage:(MCOAbstractMessagePart *)part;
```

**Comment by zhangao0086** [comment]
Hi @dinhviethoa Thanks for your help! I've tried the following methods:
```objective-c
// 1.
NSString *HTMLString = [rawMessage htmlRenderingWithFolder:folder delegate:[WBMailHTMLRenderer new]];
// The HTMLString is nil.

// 2.
[[self.IMAPSession fetchMessageOperationWithFolder:folder uid:mail.rawMailId] start:^(NSError * _Nullable error, NSData * _Nullable data) {
	MCOMessageParser *messageParser = [[MCOMessageParser alloc] initWithData:data];
	NSString *HTMLString = [messageParser htmlRenderingWithDelegate:[WBMailHTMLRenderer new]];
	// Correct. But so slow while the message contains some attachments.
}];

// 3.
[[self.IMAPSession fetchParsedMessageOperationWithFolder:folder uid:mail.rawMailId] start:^(NSError * _Nullable error, MCOMessageParser * _Nullable parser) {
	NSString *HTMLString = [parser htmlRenderingWithDelegate:[WBMailHTMLRenderer new]];
	// Correct. But so slow while the message contains some attachments.
}];

// 4.
MCOIMAPMessageRenderingOperation *renderingOperation = [self.IMAPSession htmlBodyRenderingOperationWithMessage:rawMessage
																										folder:folder];
[renderingOperation start:^(NSString *HTMLString, NSError *error) {
	// The HTMLString contains <div style="padding-bottom: 20px;">.
}];
```

I get the `rawMessage` using this:`MCOIMAPMessagesRequestKindUid | MCOIMAPMessagesRequestKindFullHeaders | MCOIMAPMessagesRequestKindFlags | MCOIMAPMessagesRequestKindStructure`.

Any ideas?

**Comment by dinhviethoa** [comment]
What is your question exactly?

**Comment by zhangao0086** [comment]
I want to quickly get an html body like ``htmlBodyRenderingOperationWithMessage:folder:`, and not contains `<div style="padding-bottom: 20px;">`.

**Comment by zhangao0086** [comment]
Hi @dinhviethoa I hope that you can help me...

**Comment by zhangao0086** [comment]
Hi @dinhviethoa  Is that any way to do it?

**Comment by zhangao0086** [comment]
Please help me with my problem.. what should I do so the div will be removed..
Thanks in advance..

**Comment by dinhviethoa** [comment]
You can reach out to me by email hoa at dinhvh dot me.
