### ISSUE TITLE
library not found for -lctemplate-ios

### ISSUE THREAD

**Issue by luckychat** [MailCore/mailcore2#1463]
I have follow and search many issue that relevant to that issue above but no luck with mailcore2.It's my step to setup:
1- I install mailcore2 via pod. then I got this in my project.
![screen shot 2016-06-30 at 10 31 53 am](https://cloud.githubusercontent.com/assets/20177110/16476273/f1e2dd68-3eaf-11e6-8564-bc8471cfa3f3.png)
2- I have added many other linker flags:
![screen shot 2016-06-30 at 10 32 52 am](https://cloud.githubusercontent.com/assets/20177110/16476281/0a1a0280-3eb0-11e6-858e-758e4fbeb4fe.png)
3- When I build project, I got error above. (iOS platform)
I don't know what's wrong that cause this problem.

**Comment by dinhviethoa** [comment]
You can remove -lctemplate-ios from the linker flags.

**Comment by luckychat** [comment]
After remove -lctemplate-ios, I got this issue "library not found for -letpan-ios".
- remove "-letpan-ios" -> "library not found for -lsasl2"
- remove "-lsasl2" -> 
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MCOAddress", referenced from:
      objc-class-ref in ContactAHViewController.o
  "_OBJC_CLASS_$_MCOMessageBuilder", referenced from:
      objc-class-ref in ContactAHViewController.o
  "_OBJC_CLASS_$_MCOSMTPSession", referenced from:
      objc-class-ref in ContactAHViewController.o
ld: symbol(s) not found for architecture x86_64

**Comment by luckychat** [comment]
1- I resolve this by adding  "libMailCore-ios.a" to Link brinary  with Library at Build phrase.
2- Solving crash by remove "-ltidy" at Other linker flags in Build Settings.
