### ISSUE TITLE
Email image Attachment in swift code

### ISSUE THREAD

**Issue by tuzzo77** [MailCore/mailcore2#1468]
Is there the possibility to convert this object c code into swift? It's impossible to me. ThanksNSString *attachmentPath = allAttachments[x];
    MCOAttachment *attachment = [MCOAttachment attachmentWithContentsOfFile:attachmentPath];
    [msgBuilder addAttachment:attachment];

**Comment by yasinbor** [comment]
https://objectivec2swift.com/#/home/converter/

**Comment by tuzzo77** [comment]
MCOAttachment.attachmentWithContentsOfFile doesn't exist in swift mode.....sorry I've already try to convert with online tool, but with no luck

**Comment by yasinbor** [comment]
Let me show you how i download attachments, xcode complains that method is deprecated but it works.

First you download email, in email you have attachments array and there are parts in that array. Each one of them attachments so you loop through download session for each part.

`     if parts.count > 0 {
            for k in 0 ..< parts.count {
                let part: MCOIMAPPart = parts[k]
                let mcop: MCOIMAPFetchContentOperation = self.session.fetchMessageAttachmentByUIDOperationWithFolder("INBOX", uid: email.uid, partID: part.partID, encoding: part.encoding)
                mcop.start({(error: NSError?, data: NSData?) -> Void in
                    if error != nil {
                        //You get error while downloading
                       print(error)
                    }
                    else
                    {
                      //You downloaded attachment go write that file or show it to user
                     print(data)
                    }
                })
            }
        }`

**Comment by dinhviethoa** [comment]
Try that instead `fetchMessageAttachmentOperationWithFolder("INBOX", uid: email.uid, partID: part.partID, encoding: part.encoding)`.
