### ISSUE TITLE
Android: Old openSSL

### ISSUE THREAD

**Issue by ganeshkarthick4** [MailCore/mailcore2#1469]
openSSL lib used in the mailcore2 is very old and when I try to upload my app to playstore its giving warning.
As per Google, we have to at least use Open SSL 1.02 f / 1.01r.
Please update

**Comment by dinhviethoa** [comment]
Which platform is it?

**Comment by ganeshkarthick4** [comment]
Its in android

**Comment by fonixland** [comment]
Any chance OpenSSL can be updated for the mailcore2 binaries? My app was just rejected for not using OpenSSL 1.02f/1.01r or higher. From the rejection email:

The vulnerabilities were addressed in OpenSSL 1.02f/1.01r. To confirm your OpenSSL version, you can do a grep search for:

$ unzip -p YourApp.apk | strings | grep "OpenSSL"

I'm seeing OpenSSL 1.02d listed.

**Comment by christianlanz** [comment]
My app update also got rejected from the Google Play store due vulnerabilities in OpenSSL. Please fix this and upload a new library version!

**Comment by fonixland** [comment]
I wound up having to give up on MailCore for now, and reimplemented my background email using JavaMail. Took about 5 hours to get everything working, but it sailed through Google Play.

**Comment by christianlanz** [comment]
It's me again. I figured out how to fix the OpenSSL issue.

1. Download the latest openssl version (I used 1.0.2j) from: https://www.openssl.org/source/
2. Use this script to compile the openssl library against the target ABIs (armeabi-v7a, x86, ...) you need: https://github.com/VoiSmart/pjsip-android-builder/blob/master/openssl-build
3. After compiling openssl use this build script to re-build the .aar: https://github.com/MailCore/mailcore2/tree/master/build-android
4. Embed your new .aar into your project and upload a new .apk to Google Play.
5. No more Google Play OpenSSL error ;)

PS: Here is the precompiled .aar: [mailcore2-17df6ae-openssl_1.0.2j-no_armeabi.zip](https://github.com/MailCore/mailcore2/files/585864/mailcore2-17df6ae-openssl_1.0.2j-no_armeabi.zip)

Cheers
Chris

**Comment by dinhviethoa** [comment]
It's fixed now.
It's using 1.0.2j.
