### ISSUE TITLE
Server's Namespace Error

### ISSUE THREAD

**Issue by lxypeter** [MailCore/mailcore2#1471]
When I try to connect to the mail service of '189'(imap.189.com:143), the console print the error of namespace as below:
```
2016-07-08 11:37:16.404 Test[809:9461] Error Domain=MCOErrorDomain Code=22 "An error occurred while requesting the server's namespace." UserInfo={NSLocalizedDescription=An error occurred while requesting the server's namespace.}
```
I have not faced this problem before in other mail services, could you give me some advice? Many thanks!

**Comment by lxypeter** [comment]
MCOIMAPOperation *operation = [session checkAccountOperation];
 [operation start:^(NSError * _Nullable error) {
...
 }]; 

connectionLogger as below:
```
* OK Hermes (ver-1.0.0-2016-06-06) Wed,20 Jul 2016 03:26:41 +0000 
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 ID XAPPLEPUSHSERVICE
1 OK CAPABILITY completed
2 LOGIN "test@189.cn" 123
2 OK LOGIN completed
3 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 ID NAMESPACE XAPPLEPUSHSERVICE
3 OK CAPABILITY completed
4 NAMESPACE
4 BAD command syntax error
```

**Comment by dinhviethoa** [comment]
What's the server? It seems to advertise incorrectly the `NAMESPACE` capability.
