### ISSUE TITLE
Android: the searchFrom expression gives the same result as searchAll 

### ISSUE THREAD

**Issue by gevorgk** [MailCore/mailcore2#1475]
When I use searchFrom expression as result get all UIDs of folder: 

IMAPSearchExpression searchExpression = IMAPSearchExpression.searchFrom("test8765@gmail.com");
                IMAPSearchOperation op = imapSession.searchOperation(folder.getPath(),searchExpression);

**Comment by mixaz** [comment]
it's a misprint in IMAPSearchExpression JNI wrapper, there's another one there too:

`
diff --git a/src/java/native/com_libmailcore_IMAPSearchExpression.cpp b/src/java/native/com_libmailcore_IMAPSearchExpression.cpp
index 6324041..0a67fde 100644
--- a/src/java/native/com_libmailcore_IMAPSearchExpression.cpp
+++ b/src/java/native/com_libmailcore_IMAPSearchExpression.cpp
@@ -20,10 +20,10 @@ JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchAll
 }
 
 JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchFrom
-  (JNIEnv * env, jclass cls, jstring)
+  (JNIEnv * env, jclass cls, jstring value)
 {
     MC_POOL_BEGIN;
-    jobject result = MC_TO_JAVA(IMAPSearchExpression::searchAll());
+    jobject result = MC_TO_JAVA(IMAPSearchExpression::searchFrom(MC_FROM_JAVA(String, value)));
     MC_POOL_END;
     return result;
 }
@@ -284,7 +284,7 @@ JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchGmailM
   (JNIEnv * env, jclass cls, jlong messageID)
 {
     MC_POOL_BEGIN;
-    jobject result = MC_TO_JAVA(IMAPSearchExpression::searchGmailThreadID((uint64_t) messageID));
+    jobject result = MC_TO_JAVA(IMAPSearchExpression::searchGmailMessageID((uint64_t) messageID));
     MC_POOL_END;
     return result;
 }
`
