### ISSUE TITLE
Android: get crash when I set ProgressListener on operation which has ProgressListener

### ISSUE THREAD

**Issue by gevorgk** [MailCore/mailcore2#1477]
When I call
MAPFetchContentOperation setProgressListener

get the crash: 

JNI GetObjectField called with pending exception 'java.lang.NoSuchFieldError' thrown in void com.libmailcore.IMAPFetchContentOperation.setupNativeOperationProgressListener():-2
07-04 17:25:51.959 3883-3883/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65]     in call to GetObjectField
07-04 17:25:51.960 3883-3883/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65]     from void com.libmailcore.IMAPFetchContentOperation.setupNativeOperationProgressListener()

one more:
when I call

IMAPFetchMessagesOperation setProgressListener

get the crash:

07-12 14:44:27.782 17974-17974/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI GetObjectField called with pending exception 'java.lang.NoSuchFieldError' thrown in void com.libmailcore.IMAPFetchMessagesOperation.setupNativeOperationProgressListener():-2

07-12 14:44:27.782 17974-17974/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65]     in call to GetObjectField

07-12 14:44:27.782 17974-17974/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65]     from void com.libmailcore.IMAPFetchMessagesOperation.setupNativeOperationProgressListener()

07-12 14:44:27.782 17974-17974/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65] "main" prio=5 tid=1 Runnable

07-12 14:44:27.782 17974-17974/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x72fe32e0 self=0xb5007800

07-12 14:44:27.782 17974-17974/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65]   | sysTid=17974 nice=0 cgrp=apps sched=0/0 handle=0xb6f34ec8

07-12 14:44:27.782 17974-17974/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=127 stm=18 core=0 HZ=100

07-12 14:44:27.782 17974-17974/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65]   | stack=0xbe1f8000-0xbe1fa000 stackSize=8MB

07-12 14:44:27.782 17974-17974/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)

07-12 14:44:27.782 17974-17974/com.libmailcore.androidexample A/art: art/runtime/check_jni.cc:65]   native: #00 pc 0

**Comment by dinhviethoa** [comment]
There are further investigation of this issue here: #1482
