### ISSUE TITLE
Missing moveMessageWithUID:toPath: from MailCore

### ISSUE THREAD

**Issue by jaragones** [MailCore/mailcore2#148]
Checking methods to migrate from Mailcore to Mailcore2, I realized that the moveMessageWithUID:toPath:  method is not in MailCore2. I think that this method is really useful to move one email to another folder in one action. Otherwise the process to move an email should be copy to folder + mark as delete + expunge folder, shouldn't be?

I checked IMAP and I couldn't see a command MOVE, does it means that the moveMessageWithUID:toPath: in Mailcore was somehow emulating/implementing this behavior?

**Comment by deltadavid** [comment]
@Ramkumartr Ram can you please share briefly how you resolved it?

**Comment by Ramkumartr** [comment]
You can edit  setList = splitSet(set, 100); in MCIMAPSession.cc file.

**Comment by deltadavid** [comment]
@Ramkumartr thank you for the prompt reply.
I had been using cocoapods prior to this.

so instead, i have to -> step1. download master, -> step2. edit said line in the cpp file -> step3. build into static library -> step 4 integrate into my project.

correct? :)

**Comment by dinhviethoa** [comment]
MOVE has been added now.
Closing.

**Comment by Unihilator** [comment]
@dinhviethoa  
How can I use MOVE command? Is there some specific method for this? I cant find any move operation for imap session

**Comment by dinhviethoa** [comment]
```
- (MCOIMAPMoveMessagesOperation *)moveMessagesOperationWithFolder:(NSString *)folder
                                                             uids:(MCOIndexSet *)uids
                                                       destFolder:(NSString *)destFolder NS_RETURNS_NOT_RETAINED;
```

**Comment by Unihilator** [comment]
cant find it in mailcore Ios @dinhviethoa

**Comment by dinhviethoa** [comment]
Update to master.

**Comment by Unihilator** [comment]
tryed to use Carthage with master branch - still cant see this method.

**Comment by mixtly87** [comment]
What am I missing? I'm using mailcore2 via cocoapods:
```
pod 'mailcore2-ios'
```
and I'm not seeing the `MCOIMAPMoveMessagesOperation` class.
