### ISSUE TITLE
HTML message won't render correct when it contain inline attachment

### ISSUE THREAD

**Issue by Unihilator** [MailCore/mailcore2#1481]
I have a message on server that contain only inline images. In message they are represented as array of parts(htmlInlineAttachments). And when I render message with **htmlBodyRenderingOperationWithMessage:folder**: method it returns html without any image. What I need to do?

**Comment by dinhviethoa** [comment]
See the example to see how to handle the inline attachments.
https://github.com/MailCore/mailcore2/tree/master/example

**Comment by Unihilator** [comment]
Thanks a lot)



Отправлено из мобильной Почты Mail.Ru


воскресенье, 24 июля 2016 г., 1:21 +0300 от notifications@github.com  <notifications@github.com>:
