### ISSUE TITLE
arm64-v8a support for android

### ISSUE THREAD

**Issue by ganeshkarthick4** [MailCore/mailcore2#1483]
In the build options for android I don't see arm64-v8a in the arch list.
If I add 'arm64-v8a' to arch list, build is failing. 

TestBed/mailcore2-master/build-android/jni/Android.mk:etpan: LOCAL_SRC_FILES points to a missing file  
Android NDK: Check that /TestBed/mailcore2-master/build-android/third-party/libetpan-android-4/libs/arm64-v8a/libetpan.a exists  or that its path is correct

**Comment by dinhviethoa** [comment]
What's the missing file?

**Comment by ganeshkarthick4** [comment]
libetpan.a does not exists in arm64-v8a path.
This will be same for all third party libraries used in mailcore2

**Comment by dinhviethoa** [comment]
Could you show the content of  /TestBed/mailcore2-master/build-android/third-party/libetpan-android-4/libs?

**Comment by vonox7** [comment]
does libetpan support arm64-v8a? It seems [it doesn't](https://github.com/dinhviethoa/libetpan/blob/master/build-android/build.sh). As all modern android phones are 64bit, this is a real blocker for the whole mailcore library.

**Comment by CotunaAurelian** [comment]
Any updates on this one? Is arm64 supported? How about MIPS?

**Comment by dinhviethoa** [comment]
Can anyone help with supporting those additional platforms?

**Comment by sasvarizoli** [comment]
Any updates???

**Comment by dinhviethoa** [comment]
@sasvarizoli  can you try to get it to work and send a pull request?

**Comment by dinhviethoa** [comment]
Fixed now.
