### ISSUE TITLE
Folder Flags

### ISSUE THREAD

**Issue by yasinbor** [MailCore/mailcore2#1484]
Hey everyone,
I have been looking around for a week for this but couldn't understand the process and had to open this issue.

I am fetching all mail headers and messages without any problems but i can't understand how folderflags work. I want to show Archive, Junk, Deleted, Sent folders to user. 

For this i tried 3 possible ways;
-  headers.flags.intersect(.Read) -> This one and other types are returning states of message (for example: flagged, answered, ext.) and these types are MCOMessageFlag types.
Also this method returns me Deleted, Junk, Achieve types too. But these are MCOIMAPFolderFlag type results and i cant use them within this method.

- headers.customFlags i think this array is the answer but it always returns nil. i can't even check if it's empty or not.

- headers.gmailLabels i thought maybe for gmail this one is where the folder flags are stored but no result.

My problem is i don't know that should i download any additional info to access folderflags like i did it for "Inbox". I have been looking to mailcore examples and many mailcore based apps but no-one uses folderflags, all i see is .seen flag.

I know you are going to answer with this but i have tried to read this ugly document and looked its examples but also no results [https://tools.ietf.org/html/rfc3501](url)

I know this is not stackoverflow and i am not asking for direct answers. Just need someone to show me the way.

Thanks.

**Comment by shrishaster** [comment]
You need to use `MCOIMAPFetchFoldersOperation` this operation to fetch the folders of an account.

**Comment by yasinbor** [comment]
Thank you for your reply i would like to ask another question if you don't mind; gmailLabels returns array of labels and in that array there are \\Inbox, \\Important, \\Sent, \\Draft but there is no \\Spam and \\Trash flags.

 In my mailbox there are mails in Trash and Spam folder. How do i find \\Spam and \\Trash flags. Should i filter mails that doesn't have \\Important flags as spams? what about \\Trash?

Thank you.

**Comment by shrishaster** [comment]
\Trash and \Spam are not there because they are IMAP folders and not labels.
IMAP has 3 main folders - All Mail, Trash and Spam. So if you want mails specific to Trash or Spam, you have to fetch from those folders.

BTW were you able to get labels from IMAP headers for non gmail labels?

**Comment by yasinbor** [comment]
Hey shrishaster thank you so much for your help, you are life saver.
Yes i did got labels from headers thanks to you and i have been trying to find Trash and Spam labels in gmailLabels.
Now i will just fetch those folders too.
Cheers mate!

**Comment by yasinbor** [comment]
Hey @shrishaster i have to ask you another question but its not about flags. I want to download mail body with only inlineAttachments.  For this i was using  "session.fetchMessageOperationWithFolder".
But i realised that this fetch type, downloads not only inlineAttachments but all other attachments too.

To get inlineAttachments i tried "session.htmlBodyRenderingOperationWithMessage" but this one only downloads html content without any inline and normal attachments.


What i want is when user opens the inbox page, i want to download mail content with inlineAttachments. 
And when the user taps the mail for details, s/he will see mail content with inlineAttachments directly and if s/he wants to download other attachments, s/he will be able to download them separately.


So is there any way to download only mail body text content and inline attachments without downloading other attachments?

Thanks, mate.

**Comment by shrishaster** [comment]
I think you should have opened a new thread for this  but here is the solution.

First you need the body part id for the body text or html you want to fetch like this:

- This is how you check the mime type (text or html) `emailMessage.mainPart.mimeType`

- This is how you get the partID `MCOIMAPPart *part = (MCOIMAPPart *)emailMessage.mainPart;` then `part.partID`

Next, you use these partIDs to in the following function to get the respective content:
`[imapSession fetchMessageAttachmentOperationWithFolder:folderName uid:uid partID:partId encoding:bodyPartEncoding];`

**Comment by yasinbor** [comment]
Thanks for the reply @shrishaster.

This block `MCOIMAPPart *part = (MCOIMAPPart *)emailMessage.mainPart;` gives error that says "Could not cast value of type 'MCOIMAPMultipart' to 'MCOIMAPPart'"

What i understand from your reply is; first i should download html content part. Then fetch every inlineAttachment separately.

But with this i have to merge body html with inline attachments, is it possible get all content with inlineAttachments without other attachments?

`[imapSession fetchMessageAttachmentOperationWithFolder:folderName uid:uid partID:partId encoding:bodyPartEncoding];`

Is it possible to give this method array of partID's that i want to download? And get response with single NSData?

**Comment by shrishaster** [comment]
The error you got is clear. Basically `emailMessage.mainPart` can be `MCOPartTypeSingle` or something else. Check the header file `MCOAbstractPart.h` for more details. Before you cast `emailMessage.mainPart` into `MCOIMAPPart` you need to make sure it is `MCOPartTypeSingle`.

As far as inline attachments are concerned, they are part of the attachments. Their details can be found like this `emailMessage.attachments` which is an array of `MCOAttachment`. From each `MCOAttachment` you can check if that attachment is an inline attachment as well get their `partID`. Check the header file `MCOAttachment.h` for more details. On a side note, I think inline attachments are also included when you download the body html of a mail.

Also I suggest you spend some time going through these documentations here http://libmailcore.com/api/objc/index.html
