### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by ad0ma** [MailCore/mailcore2#1485]
/Users/adoma/Library/Developer/Xcode/DerivedData/mail3-hjmszgmmflwksnazrzndcxwxfpxz/Build/Intermediates/mailcore2.build/Debug-iphonesimulator/static mailcore2 ios.build/Script-C6BA2B0A1705F4E6003F0E9E.sh: line 2: /Users/adoma/Documents/test/mail3/mail3/../scripts/get-ios.sh: No such file or directory

when i don't use cocoapods but drag mailCore2 to my xcode project and do other config like add framework 、target 、other linker flags 、c++ support .

**Comment by dinhviethoa** [comment]
Could you recheckout mailcore2? It looks like some files are missing.
