### ISSUE TITLE
Problem to fetch email by receivedDate in ios swift

### ISSUE THREAD

**Issue by razzaghi** [MailCore/mailcore2#1486]
I write a method to fetch email by date but i got null this is my code:
func startFetch() {

```
    let session = MCOIMAPSession()
    session.hostname = "imap.oosllc.com"
    session.username = "saeed@oosllc.com"
    session.password = "12345679"
    session.port = 143
    session.authType = MCOAuthType.SASLPlain
    session.connectionType = MCOConnectionType.Clear
    session.connectionLogger = {(connectionID, type, data) in
        if data != nil {

            if let string = NSString(data: data, encoding: NSUTF8StringEncoding){
                //NSLog("Connectionlogger: \(string)")
                print("Salam")
            }
        }
    }

    let yesterday: NSDate = NSDate(timeIntervalSinceNow: -(((3600 * 24) * 24 ) * 24))

    let expr: MCOIMAPSearchExpression = MCOIMAPSearchExpression.searchSinceDate(yesterday)

    let fetchOp: MCOIMAPSearchOperation = session.searchExpressionOperationWithFolder("INBOX", expression: expr)


    fetchOp.start { (err, uiSet) in
        print(uiSet) // return null
    }

}
```

**Comment by dinhviethoa** [comment]
Could you print the error out?
and could you show the connection logger logs?

**Comment by trangtran** [comment]
Dear,
I also get the error with parse date and receivedDate in header with POP3 mail.
The field header.date and header.receivedDate are always the current date.
In this case it should be Wed, 24 Aug 2016 20:07:48 +0900.
Some information with the email error parsing date:
- Email sender: from Naver mail, or from POP3 mail.
- Email received: POP3 mail

Here is the log i printed out message header field and header.date, header.receivedDate fields:
//=======================
(lldb) po parser.header;
<mailcore::MessageHeader:0x16a1cb70
Message-ID: 985519079.11472036874167.JavaMail.jason@jason-PC
From: mailcore::Address:0x16a1c3b0  <sagarmata76@naver.com>
To: [mailcore::Address:0x16a1c290  <jason@soosan.co.kr>]
Subject: test subject from Naver
X-TERRACE-DUMMYSUBJECT: Terrace Spam system                                  *
Return-Path: <sagarmata76@naver.com>
Content-Type: text/html; charset=utf-8
Delivered-To: soosan.co.kr\jason
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Received: from sf.sukwon.co.kr (61.74.201.69)
	by naver.com (0.0.0.0) with [CrewMAIL (c)2012 by DaZone]
	for <jason@soosan.co.kr> from <sagarmata76@naver.com>;
	Wed, 24 Aug 2016 20:07:48 +0900
X-TERRACE-SPAMMARK: NO       (SR:3.55)                     
  (by Terrace)                                                   
>

(lldb) po parser.header.date;
2016-09-05 00:34:21 +0000

(lldb) po parser.header.receivedDate;
2016-09-05 00:34:21 +0000
//=======================
