### ISSUE TITLE
Mac OS X: Yahoo OAuth2 SMTP send failure ("unstable connection")

### ISSUE THREAD

**Issue by triton3** [MailCore/mailcore2#1488]
Hi,

I am trying to use OAuth2 with Yahoo mail. It works when fetching messages from IMAP server. However it fails to submit messages to SMTP server with the following error:
    
    Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established."

**Yahoo Session Parameters:**

    Hostname = smtp.mail.yahoo.com
    Port = 465
    User name = ****@yahoo.com
    Auth Type = MCOAuthType.XOAuth2
    OAuth2Token = VM5L***     // <-- truncated
    ConnectionType = MCOConnectionType.TLS

**Yahoo Connection logs:**

    220 smtp.mail.yahoo.com ESMTP ready            
    EHLO MacBook-Pro.local            
    250-smtp.mail.yahoo.com            
    250-PIPELINING            
    250-SIZE 41697280            
    250-8 BITMIME            
    250 AUTH PLAIN LOGIN XOAUTH2 XYMCOOKIE            
    AUTH XOAUTH2            
    +             
    
    QUIT

Now it does look like Yahoo SMTP supports OAuth2 from the connection dialog. It looks to me like the authentication token is not being submitted (see empty space between AUTH XOAUTH2 and the line where it shows QUIT)? Or is there something else happening here?

For comparison, I checked against connection logs when using OAuth2 with Google (see below):
**Gmail Session Parameters:**

    Hostname = smtp.gmail.com
    Port = 465
    User name = ****@gmail.com
    Auth Type = MCOAuthType.XOAuth2
    OAuth2Token = ya29***     // <-- truncated
    ConnectionType = MCOConnectionType.TLS

**Gmail Connection logs:**

    220 smtp.gmail.com ESMTP 55sm18366190qtm.36 - gsmtp
    EHLO MacBook-Pro.local
    250-smtp.gmail.com at your service, [**.**.***.***]
    250-SIZE 35882577
    250-8BITMIME
    250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
    250-ENHANCEDSTATUSCODES
    250-PIPELINING
    250-CHUNKING
    250 SMTPUTF8
    AUTH XOAUTH2
    
    334 

    dXNlcj1za2hhc2Fud**** // <-- truncated

    235 2.7.0 Accepted
    ...

As you can see, it looks like the auth token is being submitted to google correctly and is being accepted.

Is there any suggestion on how to fix this? Any help will be greatly appreciated!

**Comment by triton3** [comment]
Just wanted to add that I also tried with SMTP port 587 and STARTTLS. It shows the same behavior and fails to send message to SMTP server.

**Error:**

    Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." 

**Yahoo Session Parameters:**

    Hostname = smtp.mail.yahoo.com
    Port = 587
    User name = ****@yahoo.com
    Auth Type = MCOAuthType.XOAuth2
    OAuth2Token = l3C8gp7***     // <-- truncated
    ConnectionType = MCOConnectionType.StartTLS
    
**Yahoo Connection logs:**

    220 smtp.mail.yahoo.com ESMTP ready
    EHLO MacBook-Pro.local
    250-smtp.mail.yahoo.com
    250-PIPELINING
    250-SIZE 41697280
    250-8 BITMIME
    250 STARTTLS

    STARTTLS
    220 2.0.0 Start TLS

    EHLO MacBook-Pro.local
    250-smtp.mail.yahoo.com
    250-PIPELINING
    250-SIZE 41697280
    250-8 BITMIME
    250 AUTH PLAIN LOGIN XOAUTH2 XYMCOOKIE
    AUTH XOAUTH2
    + 
    
    QUIT

**Comment by dinhviethoa** [comment]
Could you put a full example of XOAuth2 authentication with Yahoo somewhere so I can take a look? (including opening the auth webpage in a webview)

**Comment by triton3** [comment]
@dinhviethoa I built a test app today with the latest Mailcore2 commit, and it seems to have fixed the issue. Yahoo Oauth2 works for both send and receive emails. You can close this issue.

If you still want to take a look at the example app, let me know. I can share the test project. By the way, I am just using GTMOAuth2 for this. I followed steps [here](http://stackoverflow.com/questions/36058534/how-can-yahoo-mail-be-accessed-by-imap-using-oauth-or-oauth2-authentication) to register app with Yahoo for Oauth2 client credentials.
