### ISSUE TITLE
Run androidExample ,My LogCat

### ISSUE THREAD

**Issue by tracy891110** [MailCore/mailcore2#1489]
08-05 09:09:44.117 24210-24210/com.libmailcore.androidexample D/dalvikvm: Trying to load lib /data/app-lib/com.libmailcore.androidexample-1/libMailCore.so 0x41951b58
08-05 09:09:44.137 24210-24210/com.libmailcore.androidexample D/dalvikvm: Added shared lib /data/app-lib/com.libmailcore.androidexample-1/libMailCore.so 0x41951b58
08-05 09:09:44.137 24210-24210/com.libmailcore.androidexample D/dalvikvm: No JNI_OnLoad found in /data/app-lib/com.libmailcore.androidexample-1/libMailCore.so 0x41951b58, skipping init
08-05 09:09:44.207 24210-24210/com.libmailcore.androidexample D/dalvikvm: Trying to load lib /data/app-lib/com.libmailcore.androidexample-1/libMailCore.so 0x41951b58
08-05 09:09:44.207 24210-24210/com.libmailcore.androidexample D/dalvikvm: Shared lib '/data/app-lib/com.libmailcore.androidexample-1/libMailCore.so' already loaded in same CL 0x41951b58
08-05 09:09:44.207 24210-24210/com.libmailcore.androidexample D/dalvikvm: Trying to load lib /data/app-lib/com.libmailcore.androidexample-1/libc++_shared.so 0x41951b58
08-05 09:09:44.207 24210-24210/com.libmailcore.androidexample D/dalvikvm: Added shared lib /data/app-lib/com.libmailcore.androidexample-1/libc++_shared.so 0x41951b58
08-05 09:09:44.207 24210-24210/com.libmailcore.androidexample D/dalvikvm: No JNI_OnLoad found in /data/app-lib/com.libmailcore.androidexample-1/libc++_shared.so 0x41951b58, skipping init

**Comment by dinhviethoa** [comment]
What's the question here?
