### ISSUE TITLE
SMTP Objective-C Code Example

### ISSUE THREAD

**Issue by ghr1234** [MailCore/mailcore2#1491]
Hi,
Is it possible the Obj-C SMTP code example is missing a line at the end of the example:

`[[NSRunLoop currentRunLoop] run];`

Nothing happened when trying to send an email in Mac OSX until I finally found this line in the obj-c tests and added it. And then attempts were made to send the email.

If so, can you please add the line to help the next person.

Thank you for this framework.

**Comment by dinhviethoa** [comment]
Done.
