### ISSUE TITLE
Android: libetpan seems outdated

### ISSUE THREAD

**Issue by alexanderzhigulich** [MailCore/mailcore2#1492]
Hello!

Did you forget to upload new libetpan here http://d.etpan.org/mailcore2-deps/libetpan-android/?
I'm encountering issues when build for android.

`
/Users/sharky/Downloads/mailcore2/build-android/jni/../../src/core/imap/MCIMAPSession.cpp: In member function 'virtual void mailcore::IMAPSession::fetchMessageAttachmentToFileByUID(mailcore::String*, uint32_t, mailcore::String*, mailcore::Encoding, mailcore::String*, mailcore::IMAPProgressCallback*, mailcore::ErrorCode*)':
/Users/sharky/Downloads/mailcore2/build-android/jni/../../src/core/imap/MCIMAPSession.cpp:3084:67: error: 'mailimap_set_msg_body_handler' was not declared in this scope
     mailimap_set_msg_body_handler(mImap, msg_body_handler, decoder);
                                                                   ^
/Users/sharky/Downloads/mailcore2/build-android/jni/../../src/core/imap/MCIMAPSession.cpp: In member function 'bool mailcore::IMAPSession::enableFeature(mailcore::String*)':
`

Thank you!

**Comment by dinhviethoa** [comment]
Yep. It's not up to date yet :(

**Comment by alexanderzhigulich** [comment]
Thank you for such a quick response!

Do you plan to update it soon?

**Comment by dinhviethoa** [comment]
I'll try to do it soon.

**Comment by mixaz** [comment]
Same issue here, waiting for the update...

**Comment by dinhviethoa** [comment]
It's fixed.
