### ISSUE TITLE
New binary on CocoaPods?

### ISSUE THREAD

**Issue by alexanderzhigulich** [MailCore/mailcore2#1493]
Hello!

Can you please update binary on CocaPods?
I see some important changes since Apr'16.
Some related to flattening html.
I tried to build locally, seems stable for me.

Thank you very much!

**Comment by alexanderzhigulich** [comment]
Hello!

Please, update mailcore2 on cocoapods.
Or do you have any concerns?

Thanks!

**Comment by dinhviethoa** [comment]
Meanwhile, could you use Carthage instead?
