### ISSUE TITLE
How to display the progress of an operation right now?

### ISSUE THREAD

**Issue by clooth** [MailCore/mailcore2#1494]
I'm trying to use MailCore from Swift, and I can't seem to find a way to properly show progress for any operation. I tried subclassing and swizzling but I can't seem to get reasonable output for the operations' progress anywhere.

Could you show an example on how you planned the subclassing would work? Since there's no `progress` property anymore, as far as I could see.

**Comment by clooth** [comment]
I actually think not all methods support tracking progress. Will look into this again later on.

**Comment by dinhviethoa** [comment]
Yep. Some operation have progress. Some don't.
Which operation did you need progress for?

**Comment by houssem-yahiaoui** [comment]
@dinhviethoa  what operation does support the progress ???

**Comment by dinhviethoa** [comment]
You need to look at the APIs.
