### ISSUE TITLE
Why In Mailcore2 Sample the 'MCOMessageView' file is a c++ file instead of objective c one?

### ISSUE THREAD

**Issue by fans3210** [MailCore/mailcore2#1496]
I'm checking the source code from mailcore 2. The IOS project has a class 'MCOMessageView.mm'. It's a very good helper class with a webview and a few delegates for html rendering. So why use 'mm' as its file extension since it doesn't contain any c++ code.

I've already post this question in stackoverflow too.

http://stackoverflow.com/questions/38951997/why-in-mailcore2-sample-the-mcomessageview-file-is-a-c-file-instead-of-objec

**Comment by fburel** [comment]
see answer in so.

**Comment by fans3210** [comment]
Thanks a lot!

**Comment by dinhviethoa** [comment]
Answered on stackoverflow.
