### ISSUE TITLE
strange MCOMessageFlag returned from an reply email from gmail

### ISSUE THREAD

**Issue by fans3210** [MailCore/mailcore2#1499]
I've send and reply a thread using my email client with anther user with gmail. When I fetched the email list today and found that there is a MCOIMAPMessage with '3' as the MCOMessageFlag. The other emails are fine, either 'MCOMessageFlagNone' or 'MCOMessageFlagSeen' etc. Is this issue related to gmail? Does gmail set some custom flags sometimes?

**Comment by dinhviethoa** [comment]
It's MCOMessageFlagAnswered + MCOMessageFlagSeen
