### ISSUE TITLE
In the use of share extension will crash!!!!!!

### ISSUE THREAD

**Issue by yellowzhou-person** [MailCore/mailcore2#1500]
In the use of share extension, send more than 20M attachments when [builder data] will appear memory Warning and quit, I would like to ask how to solve

---
- (MCOMessageBuilder *)createMessageBuilder:(PMMailModel *)mail withUser:(PMUserModel *)user
  {
  MCOMessageBuilder *builder = [[MCOMessageBuilder alloc] init];
  if (user.disp_account && user.disp_account.length>0) {
      MCOAddress *address = [MCOAddress addressWithDisplayName:user.nickname mailbox:user.disp_account];
      [[builder header] setFrom:address];
      address = [MCOAddress addressWithDisplayName:user.nickname mailbox:user.account];
      [[builder header]setSender:address];
  }else{
      [[builder header] setFrom:[MCOAddress addressWithDisplayName:user.nickname mailbox:user.account]];
  }
  
  NSArray \* to =[PMShareUtil formatMailAddrs:mail.receivers];
  [[builder header] setTo:to];
  if (mail.ccs.count>0) {
      NSArray \* cc =[PMShareUtil formatMailAddrs:mail.ccs];
      [[builder header] setCc:cc];
  }
  if (mail.bccs.count>0) {
      NSArray \* bcc =[PMShareUtil formatMailAddrs:mail.bccs];
      [[builder header] setBcc:bcc];
  }
  [[builder header] setSubject:mail.subject];
  
  for (PMAttachmentModel _m_att in mail.attachments) {
      MCOAttachment_ att = [MCOAttachment attachmentWithData:m_att.data filename:m_att.filename];
      [builder addAttachment:att];
  }
  [builder setHTMLBody:mail.htmlText];
  return builder;
  }
  
  MCOMessageBuilder *builder = [self createMessageBuilder:mail withUser:user];
  /// unable to find offset 0x83af1da8 in shared cache for arch 'arm64'  
  /// memory limit ...
  NSData \* rfc822Data = [builder data]; ///////// crash

**Comment by dinhviethoa** [comment]
You can now write the message to a file and use an operation that refers to the file.
