### ISSUE TITLE
how to find MCOIMAPMessage object belongs to which folder?

### ISSUE THREAD

**Issue by Shehryaar** [MailCore/mailcore2#1502]
I have a list that contains MCOIMAPMessage objects which i have fetched from **[Gmail]/All Mail** folder. Now my question is "How can i filter this list in a way that distinguish every single message of list on basis of sent, inbox or draft message etc?" thanks

**Comment by asjesset** [comment]
Keep track of the folder when you fetch it. I don't think there's an identifier in the MCOIMAPMessage itself.
