### ISSUE TITLE
Unable to authenticate with the current session's credentials.

### ISSUE THREAD

**Issue by luhaikong** [MailCore/mailcore2#1503]
Unable to authenticate with the current session's credentials.

**Comment by luhaikong** [comment]
Unable to authenticate with the current session's credentials.

**Comment by CotunaAurelian** [comment]
What email provider are you hitting?
If you're trying to connect to a Gmail account, note that Google have a [blocking mechanism ](https://www.google.com/settings/u/1/security/lesssecureapps) that interact with your requests.
Otherwise, it might be a problem related to your credentials
