### ISSUE TITLE
POP3 email problem with parse header.date and header.receivedDate fields

### ISSUE THREAD

**Issue by trangtran** [MailCore/mailcore2#1505]
Dear,
I also get the error with parse date and receivedDate in header with POP3 mail.
The field header.date and header.receivedDate are always the current date.
In this case it should be Wed, 24 Aug 2016 20:07:48 +0900.
Some information with the email error parsing date:

Email sender: from Naver mail, or from POP3 mail.
Email received: POP3 mail
Here is the log i printed out message header field and header.date, header.receivedDate fields:
//=======================
(lldb) po parser.header;
Message-ID: 985519079.11472036874167.JavaMail.jason@jason-PC
From: mailcore::Address:0x16a1c3b0 
To: [mailcore::Address:0x16a1c290 jason@soosan.co.kr]
Subject: test subject from Naver
X-TERRACE-DUMMYSUBJECT: Terrace Spam system *
Return-Path: sagarmata76@naver.com
Content-Type: text/html; charset=utf-8
Delivered-To: soosan.co.kr\jason
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Received: from sf.sukwon.co.kr (61.74.201.69)
by naver.com (0.0.0.0) with [CrewMAIL (c)2012 by DaZone]
for jason@soosan.co.kr from sagarmata76@naver.com;
Wed, 24 Aug 2016 20:07:48 +0900
X-TERRACE-SPAMMARK: NO (SR:3.55)

(by Terrace)

(lldb) po parser.header.date;
2016-09-05 00:34:21 +0000

(lldb) po parser.header.receivedDate;
2016-09-05 00:34:21 +0000
//=======================

**Comment by dinhviethoa** [comment]
for header.data, I think the format of the mail is incorrect, that's why mailcore fails parsing it.
for header.receivedData, it's not really supported for POP. It's only an IMAP feature.
