### ISSUE TITLE
could not build Objective -c module 'MailCore'

### ISSUE THREAD

**Issue by Ehsanwww** [MailCore/mailcore2#1507]
I am developing iOS app which I want to use MailCore 2 ,I used Carthage dependancy manager, and Installed MailCore.framework [which installed in path of Carthage/Build/iOS/MailCore.framework
] I also go to  project setting  in Link Framework  and libraries  add  MailCore.framework,I import MailCore  in my ViewController.swift  but when I compiled it, I got this error:
"Couldn't  build Objective-c  module 'MailCore' ", how can i solve this issue??

Thanks for your help

**Comment by dinhviethoa** [comment]
Could you ask on stackoverflow? It's rather a swift question, not mailcore2.

**Comment by Ehsanwww** [comment]
that was Solved.

**Comment by Ehsanwww** [comment]
OK,Thanks  for your answer

**Comment by jamit2-ford** [comment]
@Ehsanwww How did you solve it?
