### ISSUE TITLE
iOS:how to fetch messages in different folder when use POP ?

### ISSUE THREAD

**Issue by zhengyatian** [MailCore/mailcore2#1508]
"MCOPOPFetchMessagesOperation *messagesOperatiopn = [[MCOPOPTool getPOPSession] fetchMessagesOperation];
    [messagesOperatiopn start:^(NSError *error, NSArray *messages) {.....
"
All messages are "INBOX". How to get other folders ' message?

**Comment by dinhviethoa** [comment]
There are no folders with POP.
