### ISSUE TITLE
iOS 10: private API usage

### ISSUE THREAD

**Issue by gdeman** [MailCore/mailcore2#1510]
With iOS 10, submitting an app with mailcore included is giving me this problem

```
2. 5 PERFORMANCE: SOFTWARE REQUIREMENTS
```

Performance - 2.5.1

Your app uses or references the following non-public APIs:

setTo:, setFrom:

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Next Steps

Please revise your app to remove any non-public APIs. If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your application being flagged in future submissions.

Additionally, if you are using third party libraries, please update to the most recent version of those libraries. If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These tools can help you narrow down where the problematic code resides. You could also use the "nm" tool to verify if any third-party libraries are calling these APIs.

**Comment by Palleas** [comment]
Hello! Did you manage to submit your app?

**Comment by gdeman** [comment]
Yes, but not with mailcore included - fortunately our app has several different targets and the one we were submitting did not require the mailcore2 functionality, so we disabled it for now.  We do need mailcore functionality for other targets that may eventually need to be submitted though, so we are still looking for a fix for this.

**Comment by dinhviethoa** [comment]
Have you tried to resolve the issue with Apple? Obviously, mailcore doesn't use any private API.

**Comment by gdeman** [comment]
correct, mailcore doesn't use any private API, but Apple now has a private API that has the same method name as an API mailcore uses and according to Apple
**If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your application being flagged in future submissions.**

**Comment by dinhviethoa** [comment]
Have you tried to resolve the issue with Apple?

I can't forecast what Apple will use in the future as methods names.
setFrom: is a too common names.
Apple probably needs to improve their submission process here.
