### ISSUE TITLE
Encryption/export compliance?

### ISSUE THREAD

**Issue by rlaferla** [MailCore/mailcore2#1516]
Not sure where to ask this but it would be nice to have something basic in the README that says it probably does or probably doesn't but go check with an attorney or look at these blog articles.  But even if you consult with an attorney, you would need to know which parts may need to be reviewed.

Do mailcore2 apps use any encryption that require US export compliance?  ie.  Is the SSL authentication exempt?

**Comment by dinhviethoa** [comment]
It's using the SSL implementation of iOS then, theoretically, no need for encryption/export compliance.
