### ISSUE TITLE
What is the best way to fetch new mail from background in iOS?

### ISSUE THREAD

**Issue by sohels** [MailCore/mailcore2#1522]
Hello Hoa,

Apple [recommends using NSURLSession](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW1) for this.

However, I believe MailCore2 does not support this (?), so we are currently triggering MCOIMAPFolderStatusOperation in response to a remote notification. But this sometimes does not complete within the few seconds that iOS appears to grant for this activity. If we find new emails, we fetch them using MCOIMAPFetchMessagesOperation in the subsequent remote notification window. This generally fails even with urgent on. 

Is there a better way to fetch new emails in response to a remote notification when the app is in the background?

Thanks!

**Comment by houssem-yahiaoui** [comment]
In fact i do believe that mailcore 2 already work on background, this answers the non-blocking functionalities and trying to put it in the background will cause some crashing, also like you said the NSURLSession won't fit in such scenario. using of a custom login is needed.
