### ISSUE TITLE
Receving Multiple mailid's from server but Library only parsing 1

### ISSUE THREAD

**Issue by NipunBilala** [MailCore/mailcore2#1524]
This is the log

BODYSTRUCTURE 
2016-10-04 12:25:09.662 DataMail[8998:86111] Logger Received: (("TEXT" "PLAIN" ("charset" "UTF-8") NIL NIL "7BIT" 52 6 NIL NIL NIL)("TEXT" "HTML" ("charset" "UTF-8") NIL NIL "7BIT" 243 4 NIL NIL NIL) "ALTERNATIVE" ("boundary" "----=_Part_870_876433156.1475563962036") NIL NIL))
7 OK UID FETCH Completed
2016-10-04 12:25:09.725 DataMail[8998:86111] Logger Received: \* 42 FETCH (UID 61978214 BODY[] {2924}
2016-10-04 12:25:09.726 DataMail[8998:86111] Logger Received: Received: From[856a035bc4b07f9f3840e67d84bff8b5]  [202.157.83.51] with SMTP id 53754.68435367985(1475563991008); Tue, 4 Oct 2016 06:53:11 +0000
X_SpamJadoo_Score: -8.7/4.0
X_SpamJadoo_ALL_TRUSTED:[-10] Passed through trusted hosts only via SMTP
X_SpamJadoo_MIME_8BIT_HEADER:[0.3] Message header contains 8-bit character
X_SpamJadoo_XPRIO_SHORT_SUBJ:[1.0] Has X-Priority header + short subject
X_SpamJadoo_XPRIO_SHORT_SUBJ:[1.0]
SJ_BAYESIAN_SKIPPED: MOVE FROM QUARANTINE OR SETTING NOT APPLIED 
Received: From[4e54d591576d297aa9b4281a42777882] [202.157.95.39] [निपुण@डाटामेल.भारत] by [202.157.81.51] [mx2.datainfosys.com] [antispam1.7] with SMTP id 11685.520490113022(1475563991007) For <निपुण@डाटामेल.भारत>; Tue, 4 Oct 2016 06:53:11 +0000
X_SpamJadoo_Status: Ip is friend in whitelist
X_SpamJadoo_Reason: Friend
X_SpamJadoo_Jmail: No
X_SpamJadoo_From: nipun.b@dil.in
X_SpamJadoo_To: &#2344;&#2367;&#2346;&#2369;&#2339;@&#2337;&#2366;&#2335;&#2366;&#2350;&#2375;&#2354;.&#2349;&#2366;&#2352;&#2340;
Received: From 202.157.83.50[202.157.83.50] by [202.157.83.51] [mx2.datainfosys.com] [mta] with SMTP id ../InBoxS/20161004/12/77546.74582839503(1475563990163); Tue, 4 Oct 2016 06:53:10 +0000
Received: From power0.dil.in[202.157.83.50] by [202.157.83.50] [power0.dil.in] [mta] with SMTP id 52498.15967905482(1475563962040); Tue, 4 Oct 2016 06:52:42 +0000
Return-path: nipun.b@dil.in
Date: Tue, 4 Oct 2016 12:22:42 +0530 (IST)
From: nipun.b@dil.in
To: <निपुण@डाटामेल.भारत>,
    <सचिन@डाटामेल.भारत>,
    <राम@डाटा.भारत>,sachin.s@dil.in
Message-ID: 621718119.8701475563962037.JavaMail.root@power0.dil.in
Subject: Test
MIME-Version: 1.0

but library is just showing 
 <निपुण@डाटामेल.भारत> rest are not getting displayed

**Comment by houssem-yahiaoui** [comment]
It might be a problem of your logic, can you show me the code behind it ? it might be the cause.

**Comment by dinhviethoa** [comment]
The message is malformed. <निपुण@डाटामेल.भारत> is an invalid email address.
