### ISSUE TITLE
Would you please let the search function support chinese?

### ISSUE THREAD

**Issue by skyforcc** [MailCore/mailcore2#1532]
When I use this framework to perform a search task with a chinese keyword in any mailbox, such as this issue: https://github.com/MailCore/mailcore2/issues/1526

or perform a search task in any chinese mailbox, I got this error:
Error Domain=MCOErrorDomain Code=19 "An error occurred while fetching messages in the requested folder."

Then I converted the chinese keyword by this method:
NSString \* path = [[imapSession defaultNamespace] pathForComponents:@[@"测试"]];
which I got from this issue last year: https://github.com/MailCore/mailcore2/issues/1175

the error disappeared but the search result was empty (which should have sth.)
Is there anyway to search a chinese keyword or searching in chinese mailbox?

Thanks for sharing this excellent framework, which help us a lot.

**Comment by dinhviethoa** [comment]
The search function is theoretically working for chinese too. It depends highly on the server.
If the server doesn't support it, maybe take a look at the connection logger logs to figure out what's going on.
