### ISSUE TITLE
Request Kind in Swift

### ISSUE THREAD

**Issue by houssem-yahiaoui** [MailCore/mailcore2#1533]
Hello,
I'm having this issue when i work with two or many request kinds, in ObjC we used it use "|" to bind between the different wanted requests, but now in swift it's not the case, so my quest is how i can add more than one request kind in Swift

**Comment by dinhviethoa** [comment]
Could create a pull request that implements the following?
http://stackoverflow.com/questions/16166895/declaring-and-checking-comparing-bitmask-enums-in-objective-c

**Comment by houssem-yahiaoui** [comment]
@dinhviethoa after some digging into the MCOMessageRequestKind methods, i found the union one and the code i'm writing look like this : 

``` swift
/////// Geeting everything
        let kind = MCOIMAPMessagesRequestKind()
        let fk = kind.union(MCOIMAPMessagesRequestKind.structure)
        let sk = fk.union(MCOIMAPMessagesRequestKind.headers)
        let ak = sk.union(MCOIMAPMessagesRequestKind.flags)
```

then simply using it over my operation 

```swift
let fetchOperation : MCOIMAPFetchMessagesOperation = imapsession.fetchMessagesOperation(withFolder: folder, requestKind: ak, uids: uids)
```

And now i can get everything i'm looking for, so it's fix for me and possibly the simple way to use multiple **MCOIMAPMessageRequestKind** types.

**Comment by rlaferla** [comment]
Swift 3:

`let kind:MCOIMAPMessagesRequestKind = [.flags, .headers, .structure]`
