### ISSUE TITLE
msg.attachment().count always return 0

### ISSUE THREAD

**Issue by houssem-yahiaoui** [MailCore/mailcore2#1534]
Hello, 

While implementing my app using swift and mailcore 2 I wanted to know the messages that have attachments and the one that don't, so I used the msg.attachment().count to figure out the attachments number so I can add a small icon in front of each email that indicates the presence of attachments ( in-line and attached). 

But the issue here is that evertime I loop over my emails I find 0 as count even when there's attachments I got 0 from the count. 

I'm using : MCOIMAPMessageRequestKind.headers as my request kind. Does it have any relationship?  And what's the problem and is there any fix? 

Thankx in advance.

**Comment by dinhviethoa** [comment]
You need to request the bodystructure to be able to query attachments.

**Comment by houssem-yahiaoui** [comment]
Didn't get how's that is done. Can you please show it.

**Comment by dinhviethoa** [comment]
MCOIMAPMessageRequestKind.bodystructure
