### ISSUE TITLE
Mailcore trying to open connection with bad OAuth2 token

### ISSUE THREAD

**Issue by tuzonghua** [MailCore/mailcore2#1536]
When using OAuth2, Mailcore sometimes tries to open connections using expired access tokens. What is the right way to keep a current MCOIMAPSession open and update the credentials for new connections (since current open connection might still work)? Or should I discard the MCOIMAPSession and start a new one?

**Comment by dinhviethoa** [comment]
You need to discard the MCOIMAPSession.
