### ISSUE TITLE
Unable to authenticate with the current session's credentials.

### ISSUE THREAD

**Issue by yhy999** [MailCore/mailcore2#1539]
```
    String username = "***********";
    String password = "******";

    SMTPSession session = new SMTPSession();
    session.setHostname("pop3.newchinalife.com");
    session.setPort(587);
    session.setUsername(username);
    session.setPassword(password);
    session.setAuthType(AuthType.AuthTypeSASLLogin);
    session.setConnectionType(ConnectionType.ConnectionTypeStartTLS);
    session.setCheckCertificateEnabled(false);

    SMTPOperation operation = session.loginOperation();
    operation.start(new OperationCallback() {
        @Override
        public void succeeded() {
           Log.d(TAG, "succeeded: ");
        }

        @Override
        public void failed(MailException e) {
            e.printStackTrace();
            Log.d(TAG, e.getMessage());

        }
    });
```

why？

10-21 17:53:32.287 1322-4343/com.zhangxun.ncl I/MCOperationQueue.cpp: start thread
10-21 17:53:32.298 1322-4343/com.zhangxun.ncl I/MCSMTPSession.cpp: connect pop3.newchinalife.com 587
10-21 17:53:32.317 1322-4343/com.zhangxun.ncl I/MCSMTPSession.cpp: init
10-21 17:53:32.324 1322-4343/com.zhangxun.ncl I/MCSMTPSession.cpp: start TLS
10-21 17:53:33.259 1322-4343/com.zhangxun.ncl I/MCSMTPSession.cpp: done
10-21 17:53:33.259 1322-4343/com.zhangxun.ncl I/MCSMTPSession.cpp: init after starttls
10-21 17:53:33.270 1322-4343/com.zhangxun.ncl I/com.zhangxun.ncl: No worthy mechs found
10-21 17:53:33.271 1322-1322/com.zhangxun.ncl I/TypesUtils.cpp: converter to java: Unable to authenticate with the current session's credentials.
10-21 17:53:33.271 1322-1322/com.zhangxun.ncl I/TypesUtils.cpp: converter to java: -1835360976
10-21 17:53:33.271 1322-1322/com.zhangxun.ncl W/System.err: com.libmailcore.MailException: Unable to authenticate with the current session's credentials.
10-21 17:53:33.271 1322-1322/com.zhangxun.ncl W/System.err:     at com.libmailcore.SMTPOperation.exception(SMTPOperation.java:12)
10-21 17:53:33.271 1322-1322/com.zhangxun.ncl W/System.err:     at com.libmailcore.SMTPOperation.callCallback(SMTPOperation.java:29)
10-21 17:53:33.271 1322-1322/com.zhangxun.ncl W/System.err:     at com.libmailcore.MainThreadUtils.runIdentifierAndNotify(Native Method)
10-21 17:53:33.271 1322-1322/com.zhangxun.ncl W/System.err:     at com.libmailcore.MainThreadUtils.access$100(MainThreadUtils.java:8)
10-21 17:53:33.271 1322-1322/com.zhangxun.ncl W/System.err:     at com.libmailcore.MainThreadUtils$2.run(MainThreadUtils.java:43)
10-21 17:53:33.271 1322-1322/com.zhangxun.ncl W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
10-21 17:53:33.271 1322-1322/com.zhangxun.ncl W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-21 17:53:33.272 1322-1322/com.zhangxun.ncl W/System.err:     at android.os.Looper.loop(Looper.java:148)
10-21 17:53:33.272 1322-1322/com.zhangxun.ncl W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5438)
10-21 17:53:33.272 1322-1322/com.zhangxun.ncl W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-21 17:53:33.272 1322-1322/com.zhangxun.ncl W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
10-21 17:53:33.272 1322-1322/com.zhangxun.ncl W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
10-21 17:53:34.283 1322-1322/com.zhangxun.ncl I/MCOperationQueue.cpp: trying to quit 0x9c9f8cc0
10-21 17:53:34.283 1322-4343/com.zhangxun.ncl I/MCOperationQueue.cpp: stopping 0x9c9f8cc0
10-21 17:53:34.284 1322-1322/com.zhangxun.ncl I/MCOperationQueue.cpp: thread stopped 0x9c9f8cc0
10-21 17:53:34.284 1322-4343/com.zhangxun.ncl I/MCOperationQueue.cpp: cleanup thread 0x9c9f8cc0

**Comment by reyansh811** [comment]
any update on this?
I am facing same issue in android

**Comment by yhy999** [comment]
> any update on this?
> I am facing same issue in android

sorry ，I have not paid attention to this issue anymore.
