### ISSUE TITLE
mailcore does not support arm64-v8a architecture.

### ISSUE THREAD

**Issue by yuanlida** [MailCore/mailcore2#1540]
I have compiled android in x86 arm and armv7a in android, but now I find that this project can not run in arm64-v8a android architecture.It depends too many library to be recompiled.

**Comment by dinhviethoa** [comment]
Could you work on getting the dependencies to compile properly with arm64-v8a?

**Comment by yuanlida** [comment]
I have forked the dependencies on your github and have compiled them successful. I feel sorry that I did not find the exactly project earlier times。

**Comment by dinhviethoa** [comment]
I'm working on it.

**Comment by dinhviethoa** [comment]
It supports it now.
