### ISSUE TITLE
#include <unicode/ucsdet.h> fails when compiling for watchOS

### ISSUE THREAD

**Issue by briansuda** [MailCore/mailcore2#1543]
I made a copy of the mailcore lib for iOS schema and changed the values to compile for watchOS. I am trying to get MailCore2 to run on an Apple Watch.

At the moment it is erroring in MCData.cpp on:
# if USE_UCHARDET
# include <uchardet/uchardet.h>
# else
# include <unicode/ucsdet.h>
# endif

I see that icu4c dependancies were removed for macOS and iOS, but it looks like watchOS does not have the files (or they are not compiled for that architecture) by default.

**Comment by dinhviethoa** [comment]
This file is located in src/core/basetypes/icu-ucsdet/include/unicode/ucsdet.h
