### ISSUE TITLE
How do I fix "Use of undeclared identifier 'message'?

### ISSUE THREAD

**Issue by bootsie123** [MailCore/mailcore2#1549]
Hi, I keep getting this error.

> Use of undeclared identifier 'message'

How do I fix this? Here;s my code.

`- (void)viewDidLoad {
    MCOIMAPSession *session = [[MCOIMAPSession alloc] init];
    [session setHostname:@"imap.gmail.com"];
    [session setPort:993];
    [session setUsername:[UICKeyChainStore stringForKey:@"bootsie227@gmail.com"]];
    [session setPassword:[UICKeyChainStore stringForKey:@"password"]];
    [session setConnectionType:MCOConnectionTypeTLS];
    MCOIMAPFetchContentOperation *operation = [session fetchMessageByUIDOperationWithFolder:@"INBOX" uid:message.uid];
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
}`

**Comment by dinhviethoa** [comment]
Please ask on stackoverflow.

**Comment by sikosis** [comment]
How rude ... you could at least put it in the documentation.

**Comment by dinhviethoa** [comment]
That's build errors unrelated to MailCore.
It's not the place to get help with general iOS skills.

**Comment by sikosis** [comment]
Well, it's related to using MailCore, implementing the headers are required to using the code. Without them, you get this error.
