### ISSUE TITLE
Code In Basic IMAP Usage Is Deprecated?

### ISSUE THREAD

**Issue by bootsie123** [MailCore/mailcore2#1550]
Hi. I'm trying to follow along with the code in the Base IMAP Usage page which can be found [here](https://github.com/MailCore/mailcore2#basic-imap-usage), and I'm getting this warning from Xcode.

> 'fetchMessagesByUIDOperationWithFolder:requestKind:uids:' is deprecated

What do I use for an alternative?

**Comment by houssem-yahiaoui** [comment]
Hello @bootsie123,
It might seems weird but I've used some func's that mentioned in the XCODE as deprecated and it worked normally.

**Comment by bootsie123** [comment]
Hmm. Okay. I'll see if it works then.
