### ISSUE TITLE
UTF-7 IMAP folder names

### ISSUE THREAD

**Issue by rlaferla** [MailCore/mailcore2#1554]
How do I convert a UTF-7 IMAP folder name to UTF-8?  Is there a method somewhere?  If not, how can I do it?

e.g.  [Gmail]/&MLkwvzD8TtgwTQ-

**Comment by dinhviethoa** [comment]
You can use mUTF7DecodedString.
The best would be to use:
`-[MCOIMAPNamespace componentsFromPath:]`

**Comment by otaviolima** [comment]
If you don't want to deal with the `MCOImapNamespace` object/operation consider this other solution that can be found here: http://stackoverflow.com/a/21724286/3927536

Code to avoid deadlink: 
```
const char *stringAsChar = [folder.path cStringUsingEncoding:[NSString defaultCStringEncoding]];
NSString *str = [NSString stringWithCString:stringAsChar encoding:CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingUTF7_IMAP)];
```
Where `folder` is instance of `MCOIMAPFolder`
