### ISSUE TITLE
I found that icu did not support ascii charset when call ucnv_open method  in android.

### ISSUE THREAD

**Issue by yuanlida** [MailCore/mailcore2#1555]
Could I use 
 return data->stringWithCharset("us-ascii");
instead of     return data->stringWithCharset("ascii");
in 
String * String::mUTF7EncodedString().
My code is like that:
String * String::mUTF7EncodedString()
{
    Data * data = mUTF7EncodedData();
    #if __APPLE__
    return data->stringWithCharset("ascii");
    #else
    return data->stringWithCharset("us-ascii");
    #endif
}

**Comment by dinhviethoa** [comment]
Can you create a pull request?
I'd love to check if "us-ascii" would just work on Apple platforms.
