### ISSUE TITLE
how to release Operation object and Callback object in those async methods?

### ISSUE THREAD

**Issue by gavinwa** [MailCore/mailcore2#1558]
i found the objects in async methods was not release correctly. for example:

`
static void testAsyncIMAP()
{
    mailcore::IMAPAsyncSession * session;
    TestIMAPCallback * callback = new TestIMAPCallback(); // NOT RELEASE
    session = new mailcore::IMAPAsyncSession(); // NOT RELEASE
    session->setHostname(MCSTR("imap.gmail.com"));
    session->setPort(993);
    session->setUsername(email);
    session->setPassword(password);
    session->setConnectionType(mailcore::ConnectionTypeTLS);
    mailcore::IMAPMessagesRequestKind requestKind = (mailcore::IMAPMessagesRequestKind)
        (mailcore::IMAPMessagesRequestKindHeaders | mailcore::IMAPMessagesRequestKindStructure |
        mailcore::IMAPMessagesRequestKindInternalDate | mailcore::IMAPMessagesRequestKindHeaderSubject |
        mailcore::IMAPMessagesRequestKindFlags);
    mailcore::IMAPFetchMessagesOperation * op = session->fetchMessagesByUIDOperation(MCSTR("INBOX"), requestKind, mailcore::IndexSet::indexSetWithRange(mailcore::RangeMake(1, UINT64_MAX))); // NOT RELEASE
    op->setCallback(callback);
    op->setImapCallback(callback);
    op->start();
    //MCLog("%s", MCUTF8DESC(messages));
    mainLoop();
    //session->release();
}

`

Could you please provide a proper way to release above session obj, Callback obj and Operation obj?

**Comment by dinhviethoa** [comment]
You can release the session, callback and operation in the callback instead.

**Comment by wyyt** [comment]
Is there a perfect example?
