### ISSUE TITLE
Operations on Java Main Thread

### ISSUE THREAD

**Issue by christianlanz** [MailCore/mailcore2#1561]
What's the exact reason why you execute operations on the main thread?

The functionality seems to come from: MainThreadUtils.java
https://github.com/MailCore/mailcore2/blob/master/src/java/com/libmailcore/MainThreadUtils.java

Because you execute operations on the main thread, the callbacks must be invoked on the main thread (otherwise it crashes), but I don't get the point of this. The only thing that does is making the application laggy when refreshing the mails, because the callbacks **must** be invoked on the main thread.

Can you move that off the main thread? That would be awesome.

Cheers
Chris

**Comment by dinhviethoa** [comment]
Is it because your callback have some heavy work?
Could you spawn the content of your callback in a thread instead?
