### ISSUE TITLE
Cant compile current master for Android

### ISSUE THREAD

**Issue by 2h4u** [MailCore/mailcore2#1562]
Since the commit "1e77049" the "build.sh" script in the "build-android" directory fails with the following error:

/mailcore2/build-android/jni/../../src/core/imap/MCIMAPSession.cpp: In member function 'virtual void mailcore::IMAPSession::fetchMessageAttachmentToFileByUID(mailcore::String*, uint32_t, mailcore::String*, mailcore::Encoding, mailcore::String*, mailcore::IMAPProgressCallback*, mailcore::ErrorCode*)':
/mailcore2/build-android/jni/../../src/core/imap/MCIMAPSession.cpp:3088:67: error: 'mailimap_set_msg_body_handler' was not declared in this scope
     mailimap_set_msg_body_handler(mImap, msg_body_handler, decoder);
                                                                   ^

My setup is correct because the previous commit "17df6ae" compiles fine.

Please fix this.

**Comment by dinhviethoa** [comment]
Should be fixed now.
Could you check?

**Comment by 2h4u** [comment]
yeah it compiles now, thank you!
