### ISSUE TITLE
how to receive mail instantly when a new mail arrived?

### ISSUE THREAD

**Issue by tigerZhang86** [MailCore/mailcore2#1564]
I'm building an iOS mail client for receiving mails via mailcore2, with IMAP protocol, I've fetched the mail messages successfully. But, how to implement the remote notification push when the target mail account received a new mail in client? I checked the mailcore2 project and some google search results, no luck there.

Please help, thanks!

**Comment by dinhviethoa** [comment]
Use IDLE operation.

**Comment by duanLH** [comment]
@dinhviethoa what's IDLE operation？ thanks
