### ISSUE TITLE
MCOIMAPFolderInfo 's six properties ,just two of them are useful ?

### ISSUE THREAD

**Issue by zhengyatian** [MailCore/mailcore2#1565]
`Printing description of info->_nativeInfo->mUidNext:
<nil>
Printing description of info->_nativeInfo->mUidValidity:
(uint32_t) mUidValidity = 1
Printing description of info->_nativeInfo->mModSequenceValue:
<nil>
Printing description of info->_nativeInfo->mFirstUnseenUid:
<nil>
`
Why always  is nil or '1' ?

**Comment by dinhviethoa** [comment]
Lots of them are useful when using MODSEQ.
