### ISSUE TITLE
Message body can't parse correct, how can I change the parse data charset?

### ISSUE THREAD

**Issue by Ryan0520** [MailCore/mailcore2#1566]
I have a trouble when I use mailCore2-iOS, When I get an e-mail, parse text distortion. I guess it should be a charset, because this message is not standardized, and the message content is Chinese. MailCore2 did not do this, I would like to know how to add Charset to make the message body appear correctly.It should be ‘gbk'.

**Comment by Ryan0520** [comment]
![7ee7f6e24dabc853eb6770105ea2cd32](https://cloud.githubusercontent.com/assets/11271005/20300849/f4698f82-ab5b-11e6-8e11-e874827f0d18.png)

**Comment by bootsie123** [comment]
Not sure if this will help you or not, but here's an issue I found which as code for a good way to parser a message successfully. You could probably take a look at the code and see what you're doing differently.

[Here's The Link](https://github.com/MailCore/mailcore2/issues/86)
