### ISSUE TITLE
Crash on IMAPSession.idleOperation - Android

### ISSUE THREAD

**Issue by patwam** [MailCore/mailcore2#1569]
Hi,
I am trying to use IMAPSession.idleOperation on Android.
I use the mailcore2-android-3 library.

What I am trying to do is that:

 `class MyThread extends Thread implements OperationCallback {`
 `   IMAPSession imapSession;`
 `   IMAPIdleOperation idleOperation;`

    MyThread() {
        imapSession = new IMAPSession();
        imapSession.setUsername(...
        imapSession.setPassword(...
        imapSession.setHostname(...
        imapSession.setPort(...
    }

    public void run() {
       idleOperation = imapSession.idleOperation("INBOX", 0);
       idleOperation.start(this);
    }

    @Override
    public void succeeded() {
    //notify new message, do nothing for now
    }

`    @Override`
`     public void failed(MailException e) {`
`     }`
`}`

But when I start this thread, first it blocks the UI, then after a few seconds the app crashes, without anything in logcat.

Is this not the right way to use the API?

Best

**Comment by dinhviethoa** [comment]
You need to call mailcore2 APIs on the main thread.

**Comment by yuanlida** [comment]
You can create a threadhandler and parse it to JNI and then the operation does not run in main thread.

**Comment by dinhviethoa** [comment]
Could you show some code?

**Comment by yuanlida** [comment]
1.In MainThreadUtils.java
public static synchronized MainThreadUtils mSingleton(Handler mHandler) {
        if (mInstance == null) {
            mInstance = new MainThreadUtils(mHandler);
        }
        return mInstance;
    }

    private MainThreadUtils(Handler mHandler){
        System.loadLibrary("MailCore");
        System.loadLibrary("gnustl_shared");

        handler = mHandler;
        setupNative();
    }

2.In application :
public static Handler mHandlerInBgThread;
HandlerThread handlerThread = new HandlerThread("Mail-Handler-Thread");
handlerThread.start();
mHandlerInBgThread = new Handler(handlerThread.getLooper());

3.call this fucntion to init it.
        MainThreadUtils.mSingleton(mHandlerInBgThread);

4.when call the method.
mHandlerInBgThread..post(new Runnable() {
                    @Override
                    public void run() {
                        try {
//execute() is the method in mailcore.
                            execute();
                        } catch (Exception ex) {
                            ex.printStackTrace();                        }
                    }
                });

now the thread is executing in mHandlerInBgThread from handlerThread.

**Comment by yuanlida** [comment]
The mHandlerInBgThread parameter can ensure that jni function and application funcion can work in the same thread.
I feel that it is not a good method but it can work.
