### ISSUE TITLE
(Objective-C) How do I get the UID for the newest email?

### ISSUE THREAD

**Issue by bootsie123** [MailCore/mailcore2#1570]
Hi, I've been looking around at the documentation and I have been a little confused on how to incorporate what it says into my project. I'm trying to find the UID of the newest email that the user has and then display the HTML Rendering for the body of that message. Could I have an example of code which could accomplish this so I can learn from the code?

**Comment by dinhviethoa** [comment]
You can get the number of messages (you can get it through the operation to get folder info). Then, you can get the messages by number, then get the UID from the result.

**Comment by bootsie123** [comment]
Thanks for the response. Could you explain this a bit more?
