### ISSUE TITLE
icu - charset conversion issue (?)

### ISSUE THREAD

**Issue by yuanlida** [MailCore/mailcore2#1573]
I compiled icu myself in the libxml2 project from your github(https://github.com/dinhviethoa/libxml2.git).I wrote test code like this:
    UErrorCode err;
    err = U_ZERO_ERROR;
    UConverter * converter = ucnv_open("utf-8", &err); 
    if (converter == NULL) {
        MCLog("invalid charset INITIALIZE %s %i", "utf-8", err);
    }
    converter = ucnv_open("us-ascii", &err); 
    if (converter == NULL) {
        MCLog("invalid charset INITIALIZE %s %i", "us-ascii", err);
    }
    converter = ucnv_open("gbk", &err); 
    if (converter == NULL) {
        MCLog("invalid charset INITIALIZE %s %i", "gbk", err);
    }
    converter = ucnv_open("gb18030", &err); 
    if (converter == NULL) {
        MCLog("invalid charset INITIALIZE %s %i", "gb18030", err);
    }
    converter = ucnv_open("IMAP-mailbox-name", &err); 
    if (converter == NULL) {
        MCLog("invalid charset INITIALIZE %s %i", "IMAP-mailbox-name", err);
    }
    converter = ucnv_open("utf-16", &err); 
    if (converter == NULL) {
        MCLog("invalid charset INITIALIZE %s %i", "utf-16", err);
    }
    converter = ucnv_open("HZ-GB-2312", &err); 
    if (converter == NULL) {
        MCLog("invalid charset INITIALIZE %s %i", "HZ-GB-2312", err);
    }
    converter = ucnv_open("Big5", &err); 
    if (converter == NULL) {
        MCLog("invalid charset INITIALIZE %s %i", "Big5", err);
    }
    converter = ucnv_open("ISO-8859-2", &err); 
    if (converter == NULL) {
        MCLog("invalid charset INITIALIZE %s %i", "ISO-8859-2", err);
    }
Only utf-8 and us-ascii could work normally, other's coverter returned null.

**Comment by yuanlida** [comment]
I feel sorry that I can not find a way to resolve this problem.Thanks for your help.
In android I have import the icudetect library and #define USE_UCHARDET 1, but it can not find the exact encode method.

**Comment by dinhviethoa** [comment]
Is it related to mailcore2 at all?

**Comment by yuanlida** [comment]
YES，This is test code in java.
The program report error in appendbytes method and I set some log in mailcore2.
I found that the error is caused by ucnv_open("gbk",&error).
Thanks.

String rfc822 =
                "From: =?gbk?b?zfjS19PKz+S088qm?= <masteruser@service.netease.com>\n" +
                "Sender: masteruser@service.netease.com\n" +
                "To: =?gbk?b?zfjS19PKz+TTw7un?= <user@netease.com>\n" +
                "Subject: =?gbk?b?1tiw9dDCxrehqrS419OhsE0xobHK1rv6w+vHwLmlwtSjoQ==?=\n\n" +
                "body";
        MessageParser parser = MessageParser.messageParserWithData(rfc822.getBytes());

**Comment by yuanlida** [comment]
thanks.

**Comment by yuanlida** [comment]
I recompiled mailcore2 and meet the same question.android did not support gbk,gb18030 eg. charset.

**Comment by yuanlida** [comment]
I think the project must call setICUDataDirectory(String * directory) to init icu4c enviroment in android.But I do not sure where to add the method.Then I will write a test.If you give me a little advice, I will be very grateful.
thanks.

**Comment by yuanlida** [comment]
I have resolved this problem. u_setDataDirectory must be called and icudt54l.dat must be copyed into the project.

**Comment by yuanlida** [comment]
1.copy icudt54l.dat to assets folder.
2.When application start copy this file to an absolute path.
3.pass this absolute path to u_setDataDirectory.
4.ok.

**Comment by dinhviethoa** [comment]
Could you show some code sample too? It would be helpful.
Thanks!

**Comment by yuanlida** [comment]
It would only effect in android application, I have not found a method to work in JNI envoriment.

1.Get icudata for our icu4c edition.in this website http://apps.icu-project.org/datacustom/ICUData54.html  choose icu54 data and click Get Data Library.then download a file named icudt54l.dat automatically.
2.Copy icudt54l.dat file to android application assets path.
3.Because assets path have no absolute path,so I copy icudt54l.dat file to an abusolute path and return the folder path.my code like that:
	public static final File getAttachmentsFolder () {
		Context context = EmailApplication.getContext();
		File cacheFolder = new File(context.getCacheDir(), "attachments");
		return cacheFolder;
	}

public static String copyIcu4cDat() {
        String datPath = getAttachmentsFolder().getAbsolutePath();
        String datFile = datPath + "/icudt54l.dat";

        File icuDatFile = new File(datFile);
        if (!icuDatFile.exists()){
            byte[] buffer = new byte[1024];
            int byteCount=0;
            try {
                InputStream is = EmailApplication.getContext().getAssets().open("icudt54l.dat");
                FileOutputStream fos = new FileOutputStream(new File(datFile));

                while((byteCount=is.read(buffer))!=-1) {
                    fos.write(buffer, 0, byteCount);
                }
                fos.flush();
                is.close();
                fos.close();


            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return datPath;
    }
when application init invoke this method copyIcu4cDat. then icudt54l.dat file is in an absolute path that JNI can read.
4.Before call icu4c method take for example ucnv_open. invoke this method:void mailcore::setICUDataDirectory(String * directory)
{
#if !DISABLE_ICU
    u_setDataDirectory(directory->fileSystemRepresentation());
#endif
}
the directory parameter is returned by copyIcu4cDat.
u_setDataDirectory would set icu4c environment in global. It would be called only one time.
5.Then converter = ucnv_open("gb18030", &err) can work.

Thank you for your open source projects. They are amazing.
