### ISSUE TITLE
How To set a SOCKS proxy for MailCore2?

### ISSUE THREAD

**Issue by PeaceWanghp** [MailCore/mailcore2#1576]

**Comment by dinhviethoa** [comment]
If the OS sets the socks proxy, it will be set automatically by libetpan.
See https://github.com/dinhviethoa/libetpan/blob/d9977879a11a0e848c3e8b0a8462e478bb845d30/src/data-types/mailstream_cfstream.c#L504

**Comment by PeaceWanghp** [comment]
I need set socket socks. what can I do？

**Comment by PeaceWanghp** [comment]
mailstream_low * mailstream_low_cfstream_open_voip_timeout(const char * hostname, int16_t port,
  int voip_enabled, time_t timeout, const char * proxy_port)
{
#if HAVE_CFNETWORK
  mailstream_low * s;
  struct mailstream_cfstream_data * cfstream_data;
  CFReadStreamRef readStream;
  CFWriteStreamRef writeStream;
  CFStringRef hostString;
  CFOptionFlags readFlags;
  CFOptionFlags writeFlags;
  int r;
  
  hostString = CFStringCreateWithCString(NULL, hostname, kCFStringEncodingUTF8);
  CFStreamCreatePairWithSocketToHost(NULL, hostString, port, &readStream, &writeStream);
  CFRelease(hostString);

#if TARGET_OS_IPHONE && !TARGET_IPHONE_SIMULATOR  
  if (voip_enabled) {
    CFReadStreamSetProperty(readStream, kCFStreamNetworkServiceType, kCFStreamNetworkServiceTypeVoIP);
    CFWriteStreamSetProperty(writeStream, kCFStreamNetworkServiceType, kCFStreamNetworkServiceTypeVoIP);
  }
#endif

//#if !TARGET_OS_IPHONE && !TARGET_IPHONE_SIMULATOR
//#if TARGET_OS_IPHONE
  fprintf(stderr,"--------------- proxy_port = %s \n", proxy_port);
  size_t port_size = proxy_port ? strlen(proxy_port):0;
  if (port_size > 0) {
    fprintf(stderr,"--------------- proxy_port = %s \n", proxy_port);

    CFDictionaryRef proxySettings = CFNetworkCopySystemProxySettings();
    CFMutableDictionaryRef socksConfig = CFDictionaryCreateMutableCopy(NULL, 0, proxySettings);
  
    CFStringRef proxyHostString = CFStringCreateWithCString(NULL, "127.0.0.1", kCFStringEncodingUTF8);
    CFStringRef proxyPortString = CFStringCreateWithCString(NULL, proxy_port, kCFStringEncodingUTF8);;
    
    CFDictionarySetValue(socksConfig, kCFStreamPropertySOCKSProxyHost, proxyHostString);
    CFDictionarySetValue(socksConfig, kCFStreamPropertySOCKSProxyPort, proxyPortString);
    CFDictionarySetValue(socksConfig, kCFStreamPropertySOCKSVersion, kCFStreamSocketSOCKSVersion5);
    
    CFRelease(proxyHostString);
    CFRelease(proxyPortString);
    
    CFReadStreamSetProperty(readStream, kCFStreamPropertySOCKSProxy, socksConfig);
    CFWriteStreamSetProperty(writeStream, kCFStreamPropertySOCKSProxy, socksConfig);

    CFRelease(proxySettings);
    CFRelease(socksConfig);
  }
  
//#endif

  cfstream_data = cfstream_data_new(readStream, writeStream);
  s = mailstream_low_new(cfstream_data, mailstream_cfstream_driver);
	mailstream_low_set_timeout(s, timeout);  

  //fprintf(stderr, "open %s %i -> %p\n", hostname, port, s);
  
  /* setup streams */
  cfstream_data->streamContext.info = s;
  
  readFlags = kCFStreamEventOpenCompleted |
  kCFStreamEventHasBytesAvailable |
  kCFStreamEventErrorOccurred |
  kCFStreamEventEndEncountered;
  
  writeFlags = kCFStreamEventOpenCompleted |
  kCFStreamEventCanAcceptBytes |
  kCFStreamEventErrorOccurred |
  kCFStreamEventEndEncountered;
  
  CFReadStreamSetClient(cfstream_data->readStream, readFlags, readStreamCallback, &cfstream_data->streamContext);
  CFWriteStreamSetClient(cfstream_data->writeStream, writeFlags, writeStreamCallback, &cfstream_data->streamContext);
  
  CFRelease(readStream);
  CFRelease(writeStream);
  readStream = NULL;
  writeStream = NULL;
  
  /* setup cancel */
  cfstream_data->cancelContext.info = s;
  cfstream_data->cancelContext.perform = cancelPerform;
  cfstream_data->cancelSource = CFRunLoopSourceCreate(NULL, 0, &cfstream_data->cancelContext);
  
  r = low_open(s);
  if (r < 0) {
    mailstream_low_cfstream_close(s);
    return NULL;
  }
  
  return s;
#else
  return NULL;
#endif
}

-----------------------------------------------------------------------------
Run project crash! Can you help review it?
-----------------------------------------------------------------------------
crash log : -[NSTaggedPointerString _getValue:forType:]: unrecognized selector sent to instance 0xa000038323037355
2016-12-14 10:40:24.710398 SMail[6964:2983717] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString _getValue:forType:]: unrecognized selector sent to instance 0xa000038323037355'

**Comment by PeaceWanghp** [comment]
int proxyPort = atoi(proxy_port);
    CFNumberRef nbProxyPort = CFNumberCreate(NULL, kCFNumberIntType, &proxyPort);
    CFDictionarySetValue(socksConfig, kCFStreamPropertySOCKSProxyPort, nbProxyPort);

It's OK!
