### ISSUE TITLE
What's an easy way to parser just the body of a message?

### ISSUE THREAD

**Issue by bootsie123** [MailCore/mailcore2#1578]
Hi, I'm trying to just parse the body of a message to display. Here's the code I have so far. It gives you who sent it, who received it, etc, but I just want the body of the message.

`MCOIMAPFetchContentOperation *op123 = [session fetchMessageOperationWithFolder:@"INBOX" number:UIDNumber];
        
        [op123 start:^(NSError *error, NSData *messageData123) {
            MCOMessageParser *parser123 = [MCOMessageParser messageParserWithData:messageData123];
            NSString *FirstMessage = [parser123 htmlRenderingWithDelegate:self];
            FirstMessage = [[FirstMessage mco_flattenHTML]stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];

            [_TextLabel setText:FirstMessage];`

**Comment by haithngn** [comment]
You can implement *htmlRenderingWithDelegate* methods to just render the body of message by ignore the message header
