### ISSUE TITLE
IOS Swift - icloud not working

### ISSUE THREAD

**Issue by phucnd0604** [MailCore/mailcore2#1579]
got the error when use icloud account but work with gmail: 
Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established.

this is my code to setup SMTPSession
        smtpSession.hostname = "smtp.mail.me.com"
        smtpSession.username = icloud account
        smtpSession.password = "password"
        smtpSession.port = 587
        smtpSession.authType = MCOAuthType.saslPlain
        smtpSession.connectionType = MCOConnectionType.TLS
        smtpSession.isCheckCertificateEnabled = true

**Comment by haithngn** [comment]
@phucnd0604 
You must check iCloud account security, try with generated password that will be generated from Apple ID Page

check https://github.com/MailCore/mailcore2/issues/1651

:)
