### ISSUE TITLE
GTMAppAuth support since GTM OAuth 2 is deprecated

### ISSUE THREAD

**Issue by sagarpshah** [MailCore/mailcore2#1593]
Google has deprecated the use of embedded web-views for OAuth. As instructed in [deprecated notice](https://github.com/google/gtm-oauth2), when making OAuth requests to Google, use the replacement GTMAppAuth library.
Can you please upgrade mailcore2 from [GTM OAuth 2](https://github.com/google/gtm-oauth2) to [GTMAppAuth](https://github.com/google/GTMAppAuth)?

**Comment by xaphod** [comment]
@sagarpshah As I understand it, there's no work to be done on mailcore2 for this. You need to do the GTMAppAuth work yourself, grab the token from GTMAppAuth (see line 199 of the iOS Example project in GTMAppAuth, file GTMAppAuthExampleViewController.m), and feed it into mailcore2 the same way as you did with GTMOAuth2.

I'm trying this today, if i'm successful i'll make a pull request to update the tutorial/README.md in mailcore2

**Comment by sagarpshah** [comment]
Hey @xaphod, thanks for your message. Were you able to achieve this? I have tried to integrate this. After getting accessToken from OIDTokenResponse, I passed it to mailcore as described in https://github.com/MailCore/mailcore2/wiki/Implementing-OAuth-2.0.

However it's unable establish IMAP session and throws an error with errorCoe = 5 along with message "Unable to authenticate with the current session's credentials."

**Comment by xaphod** [comment]
Yes I got it working. Hopefully I can make a pull request to the OAuth readme with some code, not sure if I have time.
One thing that snarled me up, you need to add the gmail scope to the OAuth request, or your token won't have access to gmail. Which you probably need. Here is the important line (look how the gmail URL has to be in there) -- maybe this helps you?

`        [[OIDAuthorizationRequest alloc] initWithConfiguration:configuration
                                                      clientId:kClientID
                                                        scopes:@[OIDScopeOpenID, OIDScopeProfile, @"https://mail.google.com/"]
                                                   redirectURL:redirectURI
                                                  responseType:OIDResponseTypeCode
                                          additionalParameters:nil];
`

**Comment by xaphod** [comment]
... and, I did have time: I just updated the wiki with my code. Hope it helps. https://github.com/MailCore/mailcore2/wiki/Implementing-OAuth-2.0

**Comment by sagarpshah** [comment]
Thanks a lot @xaphod. You made my day. @"https://mail.google.com/" scope was a real catch which I missed. It has been mentioned in the official docs as well -- https://developers.google.com/gmail/xoauth2_protocol.

**Comment by yogi41** [comment]
@xaphod can you explain the migration steps that you followed to implement GTMAppAuth to access gmail.
