### ISSUE TITLE
Set realtime notification ios

### ISSUE THREAD

**Issue by JigarPatel1234** [MailCore/mailcore2#1598]
I am using this framework to create my mail app, Is there any way to set realtime notification with mailcore2? Please let me know if there is a solution for this.

Thanks 
Jigar Patel

**Comment by hainguyen86** [comment]
@JigarPatel1234 ,
There are two types of notifications (I'm talking on iOS Topic)
#1. Remote Notification
#2. Local Notification

In case #1 you must implement both sides client and server side.
In case #2 you can register background fetch on iOS system then make Mailcore fetch the message every 10 minutes so you can schedule notification for the incoming emails

Hai,
