### ISSUE TITLE
Please help - can't build

### ISSUE THREAD

**Issue by ghost** [MailCore/mailcore2#16]
I have a Macbook pro from mid 2010 running Mountain Lion. I am trying to build the mailcore2 library to use in a project that I am working on in Xcode 4.6. Sorry that I am a newb when it comes to working with terminal, but I really need help.

When I try to build mailcore2.xcodeproj I get the error:

'libetpan/libetpan.h' file not found

I then try to run the script prepare.sh hoping that it will fix the issue. I get the following:

line 2: ./prepare-icu4c-macos.sh: No such file or directory
line 3: ./prepare-libetpan-macos.sh: No such file or directory
line 4: ./prepare-ctemplate-macos.sh: No such file or directory

I don't understand why it doesn't find the files. So I tried to run the scripts individually beginning with prepare-icu4c-macos.sh

I get the following

install from cache
mkdir: ../Externals/tmp: Permission denied
checkdir:  cannot create extraction directory: ../Externals/tmp
mv: rename ../Externals/tmp/icu4c-50_1_1/icu4c to ../Externals: No such file or directory

I have tried changing the permissions but I have had no luck. Any help would be greatly appreciated.

**Comment by neowinston** [comment]
I'm having the same problem with 

`line 3: ./prepare-ios.sh: Permission denied`

Any suggestions to solve this problem?
