### ISSUE TITLE
Send and Receive Email using MailCore2

### ISSUE THREAD

**Issue by CleverMobile2811** [MailCore/mailcore2#1608]
Hi, 
I would like to use mailcore2 library in windows desktop application.
I want to know how to send and receive emails using this library.
Thanks & Best Regards.

**Comment by Sophrinix** [comment]
Read the documentation. there is even a windows example.

**Comment by haithngn** [comment]
First plz follow the instruction to integrate MailCore2 https://github.com/MailCore/mailcore2/blob/master/build-windows/README.md
