### ISSUE TITLE
How to fetch the content of a message without attachments downloaded

### ISSUE THREAD

**Issue by Meloda** [MailCore/mailcore2#1610]
As the title says

**Comment by dinhviethoa** [comment]
The examples show how to do that.

**Comment by Meloda** [comment]
@dinhviethoa Thanks for your answer.Now,i store fetched message to local DB use NSKeyedArchiver,and this time my question is how can i get the information of all messages in local DB when changed.Such as,some message seen or deleted

**Comment by Meloda** [comment]
@haithngn 
Thanks!
Actually my question is like this:
  i want to show htmlInlineAttachments use UIWebView with javascript,and i used is a MCOIMAPMessage object,then use function "partForContentID" to find a MCOAbstractPart object ,but retuns nil;
  i have tried to change to get  a class of MCOMessageParser to solve,and it can get a MCOAbstractPart object,then show htmlInlineAttachments good.
but as i know, all functions to get the content of a message with a class of MCOMessageParser as return,also download attachments,but it is not i want

**Comment by haithngn** [comment]
@Meloda, 
You could implement html parse delegate to skip which message parts you want.
Please let's me know if you are still facing with this.
