### ISSUE TITLE
How to load multiple accounts

### ISSUE THREAD

**Issue by DChristopher** [MailCore/mailcore2#1613]
@dinhviethoa @tokyovigilante 

I am trying to load multiple accounts on iOS. All accounts
are gmail (IMAP).

I assumed that the way to do this was to essentially call startLogin (then
loadAccountWithUsername) as in the iOS example, but looping over the accounts.
This required synchronizing the loading so that the first load finished,
prior to starting the next load.

The issue I see is that the messages, after merging, appear to be damaged
somehow - the message view (MCOMessageView) is blank. Loading any of the accounts one
at a time works fine. The merging is simple array addition in swift.

I know this leaves a lot of detail out, but it seems I am missing something
in my approach and would appreciate greatly some advice on that.

Dennis Christopher

**Comment by haithngn** [comment]
Depend on the strategy you implemented to retrieve message from multiple account. 
Let's me know if you still there.
Tks
