### ISSUE TITLE
GTM OAuth fails to connect

### ISSUE THREAD

**Issue by DChristopher** [MailCore/mailcore2#1615]
under iOS using GMTAuth to access gmail. The test code follows below. The account is accessible with MailCore, essentially similar code, but user/pw no oAuth. Any clues would be appreciated.

I get this log output:

__nw_connection_get_connected_socket_block_invoke 3 Connection has no connected handler
2017-02-24 17:20:02.977 Example-iOS[38329:24679819] finished checking account.
2017-02-24 17:20:10.526 Example-iOS[38329:24679819] error loading account: Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." 

*************code********************************
    self.imapSession  = [[MCOIMAPSession alloc] init];
    self.imapSession.hostname = @"imap.google.com";
    self.imapSession.port = 993;
    self.imapSession.username = [_authorization userEmail];
    GTMAppAuthFetcherAuthorization* authorization =
    [GTMAppAuthFetcherAuthorization authorizationFromKeychainForName:kExampleAuthorizerKey];
    self.imapSession.OAuth2Token = authorization.authState.lastTokenResponse.accessToken;
    self.imapSession.authType = MCOAuthTypeXOAuth2;
    self.imapSession.connectionType = MCOConnectionTypeTLS;
    GTMAppAuthExampleViewController * __weak weakSelf = self;
    self.imapSession.connectionLogger = ^(void * connectionID, MCOConnectionLogType type, NSData * data) {
        @synchronized(weakSelf) {
            if (type != MCOConnectionLogTypeSentPrivate) {
                NSLog(@"event logged:%p %li withData: %@", connectionID, (long)type, [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
            }
        }
    };
    
    // Reset the inbox
    self.messages = nil;
    
    NSLog(@"checking account");
    self.imapCheckOp = [self.imapSession checkAccountOperation];
    [self.imapCheckOp start:^(NSError *error) {
        GTMAppAuthExampleViewController *strongSelf = weakSelf;
        NSLog(@"finished checking account.");
        if (error == nil) {
            // TBD: [strongSelf loadLastNMessages:NUMBER_OF_MESSAGES_TO_LOAD];
        } else {
            NSLog(@"error loading account: %@", error);
        }
        strongSelf.imapCheckOp = nil;
    }];
}

**Comment by srcreigh** [comment]
I got it to work (i was working on @DChristopher's old code) here's an SO question + answer: http://stackoverflow.com/questions/43237397/gtmappauth-mailcore-a-stable-connection-to-the-server-could-not-be-establish/43237588#43237588

**Comment by DChristopher** [comment]
Shane,

Congrats to you.

I had implemented a test project with Email Helper but it seemed to fail with the same connection error.
Perhaps there was a difference with the connection type you mention.

Dennis

**Comment by srcreigh** [comment]
Yeah, I got really lucky, I think it just came down to setting `.TLS` as the connection type. One small tweak compared to all the code you wrote. Thanks.
