### ISSUE TITLE
Connecting to Exchange

### ISSUE THREAD

**Issue by bunkerbilly** [MailCore/mailcore2#1623]
IOS
Swift 3.0
Microsoft Exchange 2010

I'm trying to connect to our hosted Exchange server, every time i try and send an email i get "A stable connection to the server could not be established." i have tried different ports, connection types and also auth types but i can't seem to get any where. Does anyone know any default connection types or know where i can find these details within my Exchange Server. 

I'm not sure if this is a connection issue or authentication issues. 

any advice would be helpful.

Regards,

**Comment by wwwang89** [comment]
mailcore2 doesn't support exchange right now.
you can refer
https://github.com/MailCore/mailcore2/issues/1634
