### ISSUE TITLE
Crash - MCObject.cpp:75: release too much 0x6100000360c0 mailcore::IMAPIdentity

### ISSUE THREAD

**Issue by rlaferla** [MailCore/mailcore2#1630]
I'm having a hard time trying to track down this crash bug during an IMAP folder info operation.  It looks like a IMAPIdentity object is being released too many times.  I think the solution is to retain that object but I don't know where it needs to be retained.  I'm looking for insight into where to look and how to go about debugging this.  My app is written in Swift so it can get complicated using mailcore (Swift->Objc->C++->C)

Note: My code is complex and proprietary so I can't just share my project.  However, I will try to share any relevant parts when possible.

```
2017-04-18 14:54:39.598 [61880:11617] MCOperationQueue.cpp:81: start thread
2017-04-18 14:54:39.598 [61880:11617] MCIMAPSession.cpp:648: connect <mailcore::IMAPSession:0x7fff0dc57e50>
2017-04-18 14:54:39.721 [61880:9947] MCIMAPSession.cpp:676: ssl connect imap.gmail.com 993 2
2017-04-18 14:54:39.754 [61880:9947] MCIMAPSession.cpp:746: connect ok
2017-04-18 14:54:39.754 [61880:9947] MCIMAPSession.cpp:786: login
2017-04-18 14:54:39.766 [61880:11617] MCIMAPSession.cpp:676: ssl connect imap.gmail.com 993 2
2017-04-18 14:54:39.800 [61880:11617] MCIMAPSession.cpp:746: connect ok
2017-04-18 14:54:39.800 [61880:11617] MCIMAPSession.cpp:786: login
2017-04-18 14:54:40.500 [61880:9947] MCIMAPSession.cpp:1055: login ok
2017-04-18 14:54:40.500 [61880:9947] MCIMAPSession.cpp:1142: select
2017-04-18 14:54:40.594 [61880:11617] MCIMAPSession.cpp:1055: login ok
2017-04-18 14:54:40.594 [61880:11617] MCIMAPSession.cpp:1142: select
2017-04-18 14:54:41.113 [61880:9947] MCIMAPSession.cpp:1146: select error : 0
2017-04-18 14:54:41.113 [61880:11617] MCIMAPSession.cpp:1146: select error : 0
2017-04-18 14:54:41.113 2017-04-18 14:54:41.113 [61880:9947] MCIMAPSession.cpp:1201: [61880:11617] MCIMAPSession.cpp:1201: select okselect ok

2017-04-18 14:54:41.113 [61880:11617] MCObject.cpp:75: release too much 0x6100000360c0 mailcore::IMAPIdentity
MCObject.cpp:76: assert 0
```
![image](https://cloud.githubusercontent.com/assets/1135694/25147979/5984e6f0-2447-11e7-90f6-99ba2c116944.png)

![image](https://cloud.githubusercontent.com/assets/1135694/25148019/7c88f75e-2447-11e7-974e-0072e3809330.png)

**Comment by rlaferla** [comment]
This occurs during a IMAP folder info operation.  Can anyone give me some insight?  Mailcore has been rather inactive.

**Comment by dinhviethoa** [comment]
I'm wondering if this one should be done on the main thread.

https://github.com/MailCore/mailcore2/blob/f708ce74e23b61ec6e5ae958eba0b8bcd8831a1e/src/async/imap/MCIMAPOperation.cpp#L181

Could you try to make that change and see if it helps?

**Comment by rlaferla** [comment]
Thanks.  Which change?  The link shows this which I don't see any difference in.

```
void IMAPOperation::afterMain()
{
    if (mSession->session()->isAutomaticConfigurationDone()) {
        mSession->owner()->automaticConfigurationDone(mSession->session());
        mSession->session()->resetAutomaticConfigurationDone();
    }
}
```

**Comment by dinhviethoa** [comment]
Something like that:

```
void IMAPOperation::afterMain()
{
   performSelectorOnMainThread(afterMainOnMainThread);
}

void IMAPOperation::afterMainOnMainThread()
{
    if (mSession->session()->isAutomaticConfigurationDone()) {
        mSession->owner()->automaticConfigurationDone(mSession->session());
        mSession->session()->resetAutomaticConfigurationDone();
    }
}
```

(the code is highly syntaxically incorrect)

**Comment by rlaferla** [comment]
I'm trying this:

```
void IMAPOperation::afterMain()
{
//    if (mSession->session()->isAutomaticConfigurationDone()) {
//        mSession->owner()->automaticConfigurationDone(mSession->session());
//        mSession->session()->resetAutomaticConfigurationDone();
//    }
    performMethodOnMainThread((Object::Method) &IMAPOperation::afterMainOnMainThread, NULL);
}

void IMAPOperation::afterMainOnMainThread()
{
    if (mSession->session()->isAutomaticConfigurationDone()) {
        mSession->owner()->automaticConfigurationDone(mSession->session());
        mSession->session()->resetAutomaticConfigurationDone();
    }
}

```

**Comment by rlaferla** [comment]
It still crashes but now in a new place:

![image](https://cloud.githubusercontent.com/assets/1135694/25541680/98f87710-2c1d-11e7-8547-a9bb0921813e.png)

**Comment by dinhviethoa** [comment]
2 options:

```
performMethodOnMainThread((Object::Method) &IMAPOperation::afterMainOnMainThread, true /* wait until done */);
```

or

void IMAPOperation::afterMain()
{
    retain();
    performMethodOnMainThread((Object::Method) &IMAPOperation::afterMainOnMainThread, false);
}

void IMAPOperation::afterMainOnMainThread()
{
    if (mSession->session()->isAutomaticConfigurationDone()) {
        mSession->owner()->automaticConfigurationDone(mSession->session());
        mSession->session()->resetAutomaticConfigurationDone();
    }
    release();
}

**Comment by rlaferla** [comment]
I am trying the latter but with NULL instead of false.  So far so good but time will tell as the bug doesn't always show up right away.  I'll continue testing over the next couple of days and if it works, I will let you know so you can commit the patch.  I like the retain/release version.

```
void IMAPOperation::afterMain()
{
    retain();
    performMethodOnMainThread((Object::Method) &IMAPOperation::afterMainOnMainThread, NULL);
}

void IMAPOperation::afterMainOnMainThread()
{
    if (mSession->session()->isAutomaticConfigurationDone()) {
        mSession->owner()->automaticConfigurationDone(mSession->session());
        mSession->session()->resetAutomaticConfigurationDone();
    }
    release();
}

```

**Comment by dinhviethoa** [comment]
> I am trying the latter but with NULL instead of false.

Ah yeah. The first option is rather:

```
performMethodOnMainThread((Object::Method) &IMAPOperation::afterMainOnMainThread, NULL, true /* wait until done */);
```

Anyway, let me know how it works out.
And please send a pull request if everything works out!

**Comment by rlaferla** [comment]
Yes, that worked!  Thank you thank you thank you!
