### ISSUE TITLE
Imported with CocoaPods but imports don't work

### ISSUE THREAD

**Issue by MaikoHermans** [MailCore/mailcore2#1631]
I'm working on a project which needs to use mailcore2.
I used cocoa pods to install the library as follows

```
pod "mailcore2-ios"
```

However when I try to import certain classes it will tell me that they cannot be found

```
#import "MCOSMTPSession.h"
#import "MCOMessageBuilder.h"
#import "MCOMessageHeader.h"
#import "MCOAddress.h"
#import "MCOSMTPSendOperation.h"
```

Am I missing something that is causing it to throw these errors?

**Comment by montan3ro** [comment]
This might be a bit late for the OP, but for anyone else that encounters this, you probably need to use angled brackets i.e #import <MailCore/MCOSMTPSession.h>
