### ISSUE TITLE
I just want to get the contents of the mail and attachments to the basic information

### ISSUE THREAD

**Issue by Oil-Knight** [MailCore/mailcore2#1635]
I just want to get the contents of the mail and attachments to the basic information, because the attachment may be great, the phone will be very slow to download the message, and a waste of the user's cost
Note: Attachment basic information: only the attachment name, size, type

How to achieve

**Comment by tomfriwel** [comment]
@Oil-Knight You can get attachments filename and mimeType from the `attachments` property in `MCOAbstractMessage`. If the attachment class is `MCOIMAPPart`, you can get the size of the attachment.

**Comment by Oil-Knight** [comment]
`MCOIMAPFetchContentOperation * op = [ImapSession fetchMessageOperationWithFolder:@"INBOX" uid:456 urgent:NO];
[op start:^(NSError * __nullable error, NSData * messageData) {
	MCOMessageParser * parser = [MCOMessageParser messageParserWithData:messageData];
	NSArray *abstractParts = ((MCOMultipart *)parser.mainPart).parts;
	for (id object in abstractParts) {
		if([object isMemberOfClass:[MCOAttachment class]]){
			MCOAttachment *attachment = object;
			NSLog(@"type:%@ size:%lu", attachment.mimeType, (unsigned long)attachment.data.length);
		}
	}
}];`
so “NSData * messageData”  already contains the attachment.data, But I don't want to get the attachment.data。
I just want to get attachment.filename、  attachment.size 、attachment.mineType  to show,
Download the attachment.data when the user clicks on the attachment。

**Comment by Oil-Knight** [comment]
@dinhviethoa 
MCOIMAPFetchContentOperation * op = [ImapSession fetchMessageOperationWithFolder:@"INBOX" uid:456 urgent:NO];
[op start:^(NSError * __nullable error, NSData * messageData) {
	MCOMessageParser * parser = [MCOMessageParser messageParserWithData:messageData];
	NSArray *abstractParts = ((MCOMultipart *)parser.mainPart).parts;
	for (id object in abstractParts) {
		if([object isMemberOfClass:[MCOAttachment class]]){
			MCOAttachment *attachment = object;
			NSLog(@"type:%@ size:%lu", attachment.mimeType, (unsigned long)attachment.data.length);
		}
	}
}];

so “messageData”  already contains the attachment.data, But I don't want to get the attachment.data。
I just want to get attachment.filename、  attachment.size 、attachment.mineType  to show,
Download the attachment.data when the user clicks on the attachment。

**Comment by muwan** [comment]
I have the same problem.And the html body contans inline css ,when I render the HTML body of a message,I can always get "<![CDATA[" in the HTML body ,but there is no attachment.

**Comment by NSDeveloper** [comment]
Seems similar as #1106 .
