### ISSUE TITLE
Crash in +[MCONNTPGroupInfo load]

### ISSUE THREAD

**Issue by mqmq** [MailCore/mailcore2#1636]
hello!
some time i got crash in +[MCONNTPGroupInfo load].

NPushMail	+[MCONNTPGroupInfo load]
4 NPushMail	mailcore::Object::release() + 180
5 NPushMail	mailcore::IMAPAsyncSession::automaticConfigurationDone(mailcore::IMAPSession*) + 44
6 NPushMail	mailcore::IMAPOperation::afterMain() + 108
7 NPushMail	mailcore::OperationQueue::callbackOnMainThread(mailcore::Operation*) + 32
8 libdispatch.dylib	__dispatch_client_callout + 16
9 libdispatch.dylib	__dispatch_sync_function_invoke + 72
10 NPushMail	mailcore::Object::performMethodOnDispatchQueue(void (mailcore::Object::*)(void*), void*, void*, bool) + 116
11 NPushMail	mailcore::OperationQueue::runOperations() + 440
12 libsystem_pthread.dylib	__pthread_body + 240
13 libsystem_pthread.dylib	__pthread_body

**Comment by srinadh-k** [comment]
@mqmq, Even i am also facing same issue. do you know any solution for this?
Without solution they are closing ticket.
