### ISSUE TITLE
 providerForEmail: method has no result

### ISSUE THREAD

**Issue by wwwang89** [MailCore/mailcore2#1640]
MCOMailProvider *accountProvider = [MCOMailProvidersManager.sharedManager providerForEmail:myGmail]

when  I called  the method like above use my gmail  ,but I got the result, "accountProvider" = nil, and I changed my other emails,there always the same results, is there any wrong ? thanks

**Comment by haithngn** [comment]
Make sure you provide correct providers file in JSON, the parameter name is quite confuse.
If you still facing with it plz let us know.
