### ISSUE TITLE
compile error:build-android/libs/arm64-v8a/libMailCore.so: No such file or directory

### ISSUE THREAD

**Issue by Sean66** [MailCore/mailcore2#1643]
I execute the command in mac computer:
$ ./build.sh
and my console show errors:
mailcore2/build-android/libs/arm64-v8a/libMailCore.so: No such file or directory
警告: [options] 未与 -source 1.6 一起设置引导类路径
com/libmailcore/MainThreadUtils.java:3: 错误: 程序包android.os不存在
import android.os.Handler;
                 ^
com/libmailcore/MainThreadUtils.java:4: 错误: 程序包android.os不存在
import android.os.Looper;
                 ^
com/libmailcore/MainThreadUtils.java:5: 错误: 程序包android.util不存在
import android.util.Log;
                   ^
com/libmailcore/MainThreadUtils.java:10: 错误: 找不到符号
    private Handler handler;
            ^
  符号:   类 Handler
  位置: 类 MainThreadUtils
com/libmailcore/MainThreadUtils.java:21: 错误: 找不到符号
        handler = new Handler(Looper.getMainLooper());
                      ^
  符号:   类 Handler
  位置: 类 MainThreadUtils
com/libmailcore/MainThreadUtils.java:21: 错误: 找不到符号
        handler = new Handler(Looper.getMainLooper());
                              ^
  符号:   变量 Looper
  位置: 类 MainThreadUtils

**Comment by vonox7** [comment]
Fyi: https://github.com/MailCore/mailcore2/pull/1912 explains the build pipeline on Android that works also in 2021

**Comment by haithngn** [comment]
thank @vonox7 ,
closed https://github.com/MailCore/mailcore2/pull/1912
