### ISSUE TITLE
How to use GTMAppAuth with Mail Core 2

### ISSUE THREAD

**Issue by hanming223** [MailCore/mailcore2#1661]
I saw the wiki of this project for GTMAppAuth.
So I tried to do it. but I have an issue
 
Bellow is the code of wiki
- (void)doInitialAuthorizationWithVC:(UIViewController*)vc completionBlock:(dispatch_block_t)completionBlock {
    NSURL *issuer = [NSURL URLWithString:kIssuer];
    NSURL *redirectURI = [NSURL URLWithString:kRedirectURI];
    
    NSLog(@"EmailHelper: Fetching configuration for issuer: %@", issuer);
    
    // discovers endpoints
    [OIDAuthorizationService discoverServiceConfigurationForIssuer:issuer completion:^(OIDServiceConfiguration *_Nullable configuration, NSError *_Nullable error) {
        if (!configuration) {
            NSLog(@"EmailHelper: Error retrieving discovery document: %@", [error localizedDescription]);
            self.authorization = nil;
            return;
        }
        
        NSLog(@"EmailHelper: Got configuration: %@", configuration);
        
        // builds authentication request
        OIDAuthorizationRequest *request =
        [[OIDAuthorizationRequest alloc] initWithConfiguration:configuration
                                                      clientId:kClientID
                                                        scopes:@[OIDScopeOpenID, OIDScopeProfile, OIDScopeEmail, OIDScopeAddress, OIDScopePhone]
                                                   redirectURL:redirectURI
                                                  responseType:OIDResponseTypeCode
                                          additionalParameters:nil];
        // performs authentication request
        NSLog(@"EmailHelper: Initiating authorization request with scope: %@", request.scope);
        self.currentAuthorizationFlow = [OIDAuthState authStateByPresentingAuthorizationRequest:request
                                                                       presentingViewController:vc
                                                                                       callback:^(OIDAuthState *_Nullable authState, NSError *_Nullable error) {
            if (authState) {
                self.authorization = [[GTMAppAuthFetcherAuthorization alloc] initWithAuthState:authState];
                NSLog(@"EmailHelper: Got authorization tokens. Access token: %@", authState.lastTokenResponse.accessToken);
                NSLog(@"EmailHelper: Got authorization tokens. refresh token: %@", authState.lastTokenResponse.refreshToken);
                [self saveState];
            } else {
                self.authorization = nil;
                NSLog(@"EmailHelper: Authorization error: %@", [error localizedDescription]);
            }
        }];
    }];
}

By to do this, I can get user's email address and access token.
Then I tried to use it in mail core.

	self.imapSession = [[MCOIMAPSession alloc] init];
	self.imapSession.hostname = hostname; // imap.gmail.com
	self.imapSession.port = 993;
	self.imapSession.username = username; //user email address
    
    if (oauth2Token != nil) {
        BOOL can = _mail.authorization.canAuthorize; // can authorize
        self.imapSession.authType = MCOAuthTypeXOAuth2;
        self.imapSession.OAuth2Token =  _mail.authorization.authState.lastTokenResponse.accessToken; // access token
    }
	self.imapSession.connectionType = MCOConnectionTypeTLS;
    NSLog(@"%ld", (long)_imapSession.authType);
    MasterViewController * __weak weakSelf = self;
	self.imapSession.connectionLogger = ^(void * connectionID, MCOConnectionLogType type, NSData * data) {
        @synchronized(weakSelf) {
            if (type != MCOConnectionLogTypeSentPrivate) {
                NSLog(@"event logged:%p %i withData: %@", connectionID, type, [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
            }
        }
    };
	
	// Reset the inbox
	self.messages = nil;
	self.totalNumberOfInboxMessages = -1;
	self.isLoading = NO;
	self.messagePreviews = [NSMutableDictionary dictionary];
	[self.tableView reloadData];
    
	NSLog(@"checking account");
	self.imapCheckOp = [self.imapSession checkAccountOperation];
	[self.imapCheckOp start:^(NSError *error) {
		MasterViewController *strongSelf = weakSelf;
		NSLog(@"finished checking account.");
		if (error == nil) {
			[strongSelf loadLastNMessages:NUMBER_OF_MESSAGES_TO_LOAD];
		} else {
			NSLog(@"error loading account: %@", error);
		}
		
		strongSelf.imapCheckOp = nil;
	}];

But I get an issue "Unable to authenticate with current session's cridentials"

How can I fix this issue?

Please help me

**Comment by hanming223** [comment]
One thing more, I can authenticate with user's password, but not working with token

**Comment by haithngn** [comment]
https://github.com/MailCore/mailcore2/issues/1672
