### ISSUE TITLE
Outlook SMTP not sending correct oauth2 response

### ISSUE THREAD

**Issue by dsanghan** [MailCore/mailcore2#1663]
The outlook specification says that for OAuth2 we're supposed to send:
`Auth XOAuth2 [Base64Encoded: 'user=%s\1auth=Bearer %s\1\1']`.

In libetpan, we're sending:

```
case XOAUTH2_TYPE_OUTLOOK_COM:
      snprintf(command, SMTP_STRING_SIZE, "AUTH XOAUTH2\r\n");
      r = mailsmtp_send_command_private(session, command);
      if (r == -1) {
        res = MAILSMTP_ERROR_STREAM;
        goto free;
      }
      break;
  }
```

Which on some servers returns `[504] 5.7.4 Unrecognized authentication type [SG2PR0401CA0012.apcprd04.prod.outlook.com]`.

If instead we send `AUTH XOAUTH2 base64`, we get an authentication successful. This only happens on some specific outlook servers, and works on others, but I think the libetpan flow should change to send with the base64.

**Comment by dsanghan** [comment]
Using the `XOAUTH2_TYPE_GMAIL` flow instead works for Outlook.

**Comment by dinhviethoa** [comment]
Good to know. Something probably changed on outlook servers.
