### ISSUE TITLE
Get messages based on MODSEQ?

### ISSUE THREAD

**Issue by atomicbird** [MailCore/mailcore2#1671]
Is it possible to get messages based on the last known highest MODSEQ value with MailCore2? I'd like to get all updates since the last check, including metadata changes. RFC 4551 indicates that it should be possible to search based on MODSEQ, but `MCOIMAPSearchExpression` doesn't have a MODSEQ option. Any means to get this would be useful-- whether a search or a fetch or something else I'm not aware of.

**Comment by atomicbird** [comment]
It looks like what I need is `-syncMessagesWithFolder:requestKind:uids:modSeq:`. At least that does what I was hoping for. I'm not sure I understand why it's a "sync" call instead of a fetch or search, but I have something that works

**Comment by dinhviethoa** [comment]
It's definitely it :)

It's called "sync" like synchronization: it's trying to get only the diff with what you have locally.

**Comment by atomicbird** [comment]
Thanks! On a somewhat-related note then, what's a good way to find out which messages have been deleted since the last time I checked in with the server? The server I'm working with right now doesn't support the `vanishedMessages` argument I get with this message.

**Comment by dinhviethoa** [comment]
when QRESYNC is available on the server, that's the way to do it.
If QRESYNC is not available (vanishedMessages), the best way is to list all the UID of a folder and remove locally the one that are not available remotely any more.
One trick to speed it up is to get UID only of the last x messages frequently (every couple of minutes or one IDLE notifications) and then do a full list of UIDs infrequently.

**Comment by kapil0408** [comment]
Can you please tell me what is MODSEQ and how to get it?

**Comment by haithngn** [comment]
@kapil0408 
https://tools.ietf.org/html/rfc5162
https://tools.ietf.org/html/rfc4551

**Comment by kapil0408** [comment]
@dinhviethoa  
Can you please tell me how to configure server for "Conditional store" and "QRESYNC" or give me some link for this

Thanks

**Comment by haithngn** [comment]
@kapil0408 , it depend on which IMAP server software your running on the remote size
eg. Postfix

p/s: solution already provided
