### ISSUE TITLE
Demo app OAuth2 no longer works

### ISSUE THREAD

**Issue by atomicbird** [MailCore/mailcore2#1672]
I am trying to use the iOS demo app's OAuth2 code. However, the web view that appears reports an HTTP 403 from Google with an error reading

> This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.

I believe this may be related to issue #1625. It looks like the OAuth SDK in the demo app isn't supported for authorization by Google anymore.

I'm using what I think is a newer scheme from the [GTMAppAuth](https://github.com/google/GTMAppAuth) project (which uses `SFSafariViewController` to resolve the user agent error), but I'm having trouble getting OAuth to work. I was hoping that the demo app would help resolve this but I'm not having any luck at the moment.

**Comment by haithngn** [comment]
Google release a new OAuth flow, I will create another demo for that.
Hope it will help you.

**Comment by wengxianxun** [comment]
What about the new demo?
