### ISSUE TITLE
how to get a list of the snippet of the mails

### ISSUE THREAD

**Issue by AttackOnDobby** [MailCore/mailcore2#1676]
I am trying to fetch a list of mails, with title, date, display name and one or two lines of the mail body shown on the screen, I could get them with MCOIMAPMessage, except the snippet of mail body, but I don't want to parse every mail with MCOMessageParser in a loop, so how to solve this problem

**Comment by dinhviethoa** [comment]
You can take a look at https://github.com/MailCore/mailcore2/tree/master/example
