### ISSUE TITLE
I cannot find any document with examples

### ISSUE THREAD

**Issue by hanming223** [MailCore/mailcore2#1677]
I tried to develop iOS email client. But I cannot find documentation with examples. 
I can find only class references here.  http://libmailcore.com/api/objc/index.html
But I don't know how to use them.  Please help me to find documentation I can reference for email client app.

**Comment by dinhviethoa** [comment]
See https://github.com/MailCore/mailcore2/tree/master/example

**Comment by hanming223** [comment]
This is very basic example.  It has only authentication and fetching inbox.
Could you please provide more complicated example or document of usage for all classes?
