### ISSUE TITLE
[Android] - MessageBuilder.header().messageID() returns '@localhost'

### ISSUE THREAD

**Issue by BigNateBombBomb** [MailCore/mailcore2#1687]
If I use 'MessageBuilder builder = new MessageBuilder();' and then try to grab the 'messageID' it always returns '@localhost'. I was under the impression that the MessageBuilder should generate the messageID automatically (at least on iOS it does). Am I missing something here?

**Comment by dinhviethoa** [comment]
It uses:
https://github.com/MailCore/mailcore2/blob/master/src/core/rfc822/MCMessageBuilder.cpp#L549
or https://github.com/MailCore/mailcore2/blob/master/src/core/abstract/MCMessageHeader.cpp#L87

`gethostname(name, MAX_MESSAGE_ID);`

You can always use builder.getHeader().setMessageID(messageID) to override it.

**Comment by BigNateBombBomb** [comment]
Awesome, thanks for the links!

**Comment by MohsinaJavaid** [comment]
I have been facing the same issue for android. Can you please elaborate the solution
