### ISSUE TITLE
how can i remove attachment info from plainTextBodyRenderingOperation results

### ISSUE THREAD

**Issue by bupojung** [MailCore/mailcore2#1688]
I use the plainTextBodyRenderingOperation to fetch summary of an email. but i return string included the attachments like this
`<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<title></title>\n</head>\n<body>\n<div style=\"padding-bottom: 20px;\"></div>\n<div>\n<div>- xx.txt, 14 KB</div>\n</div>\n</body>\n</html>\n`
and the plain text is "- xx.txt, 14KB"
how can i remove the attachments info "- xx.txt, 14KB"

**Comment by haithngn** [comment]
you could implement htmlParserDelegate to handle what it will be render

**Comment by bupojung** [comment]
I have find out how to make it,  thanks.

**Comment by MohsinaJavaid** [comment]
@bupojung please share the way how you did it

**Comment by bupojung** [comment]
@MohsinaJavaid 
I solved it by remove 
`
<div>- {{FILENAME}}, {{SIZE}}</div>\
`
in MCHTMLRendererCallback.cpp 
mailcore::String * HTMLRendererTemplateCallback::templateForAttachment(AbstractPart * part)
{
    return MCSTR("{{#HASSIZE}}\
                 {{#HASFILENAME}}\
                 <div>- {{FILENAME}}, {{SIZE}}</div>\
                 {{/HASFILENAME}}\
                 {{#NOFILENAME}}\
                 <div>- Untitled, {{SIZE}}</div>\
                 {{/NOFILENAME}}\
                 {{/HASSIZE}}\
                 {{#NOSIZE}}\
                 {{#HASFILENAME}}\
                 <div>- {{FILENAME}}</div>\
                 {{/HASFILENAME}}\
                 {{#NOFILENAME}}\
                 <div>- Untitled</div>\
                 {{/NOFILENAME}}\
                 {{/NOSIZE}}\
                 ");
}`

**Comment by MohsinaJavaid** [comment]
@bupojung thanks:)

**Comment by zhangylios** [comment]
hello,
I remove this line ,
<div>- {{FILENAME}}, {{SIZE}}</div>\

from MCHTMLRendererCallback.cpp
mailcore::String * HTMLRendererTemplateCallback::templateForAttachment(AbstractPart * part) { return MCSTR("{{#HASSIZE}}\ {{#HASFILENAME}}\ {{/HASFILENAME}}\ {{#NOFILENAME}}\ <div>- Untitled, {{SIZE}}</div>\ {{/NOFILENAME}}\ {{/HASSIZE}}\ {{#NOSIZE}}\ {{#HASFILENAME}}\ <div>- {{FILENAME}}</div>\ {{/HASFILENAME}}\ {{#NOFILENAME}}\ <div>- Untitled</div>\ {{/NOFILENAME}}\ {{/NOSIZE}}\ "); }
but,don't solved it,please share the way how you did it.
