### ISSUE TITLE
How to move emails to the "Trash" or "Archive" folder in gmail through mailcore + imap?

### ISSUE THREAD

**Issue by philip511** [MailCore/mailcore2#1700]
Ive been struggling with this for a few days now, I can successfully delete folders and move emails to folders that I myself have created but for some reason it doesnt seem to work when I try to move an email to an already built in folder such as "Trash" and "Archive". Here is my code for moving emails to a folder that I have created. If anyone can write or show me some code somewhere that would be really appreciated, its been a frustrating few days

    MCOIMAPSession *session = [[MCOIMAPSession alloc] init];
    MCOIndexSet *uidSet = [MCOIndexSet indexSetWithRange:MCORangeMake(1,UINT64_MAX)];

    MCOIMAPMoveMessagesOperation *moveOp = [session moveMessagesOperationWithFolder:@"Inbox" uids:uidSet destFolder:@"MyEmails"];

    [moveOp start:^(NSError * _Nullable error, NSDictionary * _Nullable uidMapping) {
        if (uidMapping.count > 0){
            for (MCOIMAPMessage *m in uidMapping){
                MCOIMAPFetchContentOperation *operation =  [session fetchMessagesByUIDOperationWithFolder:@"Drafts" requestKind:MCOIMAPMessagesRequestKindHeaders uids:uidSet];
                [operation start:^(NSError * _Nullable error, NSData * _Nullable data) {
                    NSLog(@"The m %@", m);
                    NSLog(@"The set %@", uidSet);
                } ];
            }
        } else {
            NSLog(@"ITS EMPTY");
        }
    }];

**Comment by dinhviethoa** [comment]
MOVE is not supported by Gmail.
Use COPY.

**Comment by philip511** [comment]
If your referring to this, I have tried this too with no luck

 MCOIMAPCopyMessagesOperation * op = [session copyMessagesOperationWithFolder:@"INBOX"
                                                                         uids:[MCIndexSet indexSetWithIndex:456]
                                                                   destFolder:@"Cocoa"];
 [op start:^(NSError * error, NSDictionary * uidMapping) {
      NSLog(@"copied to folder with UID mapping %@", uidMapping);
 }];

**Comment by dinhviethoa** [comment]
Could you enable connection logs and can you show which error you're getting?

**Comment by philip511** [comment]
Im sorry Im a little new to this what are connection logs and where can I enable them. 
For the second part of your question, my code isnt showing any errors it just simply doesnt work. To be more specific, take a look at these lines of code
    
MCOIMAPMoveMessagesOperation *moveOp = [session moveMessagesOperationWithFolder:@"Inbox" uids:uidSet destFolder:@"Spam"];

    [moveOp start:^(NSError * _Nullable error, NSDictionary * _Nullable uidMapping) {
        if (uidMapping.count > 0){

uidMapping.count is actually returning 0 results because my else statement for that if statement printing

    } else {
        NSLog(@"ITS EMPTY");
    }

**Comment by philip511** [comment]
Would you also be able to help me with deleting gmail emails through imap

**Comment by dinhviethoa** [comment]
Did you try using `NSLog(@"%@", error)`?

**Comment by xtation** [comment]
move and copy both is enabled in gmail i have used it and its successfully moving and copying mail 
  let imapSession = MCOIMAPSession()
        imapSession.hostname = "imap.gmail.com"
        imapSession.username = "*********"
        imapSession.password = "********"
        imapSession.port = 993
        imapSession.connectionType = MCOConnectionType.TLS
        let folder =  "INBOX"
        let copy = imapSession.copyMessagesOperation(withFolder: folder, uids:MCOIndexSet(index: UInt64((8))), destFolder: "[Gmail]/Trash")
        copy?.start({ (error, msgs) -> Void in
            if error == nil{print("copy")
             //     imapSession.cancelAllOperations()
            }
            else{print(error.debugDescription)}
            
        })
