### ISSUE TITLE
Library file size almost 200MB Xcode 9 Swift 4

### ISSUE THREAD

**Issue by 10686142** [MailCore/mailcore2#1706]
Hi there,

I am using mailcore2 for a while now, but I am running into the problem that the library file size is way too big at the extend that can't even commit my code to Github. Does somebody know a workarround or a way to reduce this library in size?

I installed mailcore2 through my podfile with "use_frameworks!", and I went through all the steps of the bridging header file.

Thanks in advance

**Comment by xaphod** [comment]
Why are you checking in a compiled/binary lib into source control?
If you really want to do this, use Git LFS... but ... why?
