### ISSUE TITLE
Cocoapods warning

### ISSUE THREAD

**Issue by siberianisaev** [MailCore/mailcore2#1710]
```[!] 'mailcore2-ios' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.```

**mailcore2-ios (0.6.4)**

**Comment by lehrblogger** [comment]
@siberianisaev I got the same error, but it appears to be fixed in `master`, perhaps by https://github.com/MailCore/mailcore2/commit/b99e4eab5cc02bda9a723cd38b0a3a2393dd1e15. You can use it in your Podfile like this:
```
pod 'mailcore2-ios', :git => 'https://github.com/MailCore/mailcore2.git', :commit => 'e6b4597d3b'
```

**Comment by Jigar360** [comment]
I got the same error for :
**'mailcore2-osx' (0.6.4)**
Any help is appreciated..!
