### ISSUE TITLE
fetching more than 40K mails .. app memory getting increased by using mailcore2

### ISSUE THREAD

**Issue by aravind4321** [MailCore/mailcore2#1712]
.............App getting crash because of memory increase...................
is this correct way to fetch more than 40 thousand mails.. i need "Structure of mails and headers"..
in request kind [.hearder,.structure].... i need some suggestion regarding this mailcore2 fetching....

let request : MCOIMAPMessagesRequestKind = [ .headers,.structure]
let indexSet = MCOIndexSet(range: MCORangeMake(1, UINT64_MAX))
let fetchOperation = session.fetchMessagesByNumberOperation(withFolder: path, requestKind: request, numbers: indexSet)
 fetchOperation?.start({ (error, messages, vanishedMessages) ->Void in
if let error = error {
}else
{

//Saving fetched mails
savingArray = messages

}

**Comment by haithngn** [comment]
To reduce limitation of the query you should chunk the request size base on the next uid of the IMAP folder or the oldest message's uid.
