### ISSUE TITLE
Send email to specific folder

### ISSUE THREAD

**Issue by Pades9** [MailCore/mailcore2#1721]
Hello guys,

so my goal is, that user send email and recipient would have this email in specific folder. It is possible in case that I have access to recipient's IMAP credentials? Another solution is add filter to IMAP server but I don't know if IMAP supports it.

**Comment by haithngn** [comment]
Absolutely NO: Send email to specific folder
It is possible in case that I have access to recipient's IMAP credentials?: YES, you can use the append message operation.
