### ISSUE TITLE
Please use HTTPS for source URL in podspec file

### ISSUE THREAD

**Issue by MarshalGeazipp** [MailCore/mailcore2#1722]
Hi,

when I install the pod "mailcore2-ios" by running pod install, there is a warning saying:
"mailcore2-ios' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue."

Can you please fix this security issue by changing the URL in the mailcore2-ios.podspec file from http://d.etpan.org/... to https://d.etpan.org/...?

Thank you for this great library!

**Comment by haithngn** [comment]
to avoid CocoaPod warning now you could use this cmd
```
pod 'mailcore2-ios', :git => 'https://github.com/MailCore/mailcore2.git', :commit => '58473736aa31e57ed94c7ab6221af8def5839ca1'
```

we’ll fix this warning in the next release

Thank you for your contributions @MarshalGeazipp

**Comment by dhipin** [comment]
Still having the issue on the latest version. Will this issue be fixed on the main branch anytime soon?

**Comment by Poreis** [comment]
Im still having this problem , this is so unreliable and shitty content.
