### ISSUE TITLE
Hey. Can someone please share the way to unflagged number of mails at a time?

### ISSUE THREAD

**Issue by MohsinaJavaid** [MailCore/mailcore2#1728]
Can someone please share the way to unflagged number of mails at a time?

**Comment by haithngn** [comment]
You have to provide:
- The uids of messages list which are a same folder.
- What's kind of adding flag action ? (add, remove, set)
- Flags

Then use one of these operation to make a change in only one action at a time

> – storeFlagsOperationWithFolder:uids:kind:flags:
> – storeFlagsOperationWithFolder:numbers:kind:flags:
> – storeFlagsOperationWithFolder:uids:kind:flags:customFlags:
> – storeFlagsOperationWithFolder:numbers:kind:flags:customFlags:

**Comment by MohsinaJavaid** [comment]
Thanks @haithngn
