### ISSUE TITLE
MCOIMAPIdleOperation example?

### ISSUE THREAD

**Issue by waynehartman** [MailCore/mailcore2#173]
I've been able to get MailCore2 up and running and really like the blocks-based API, but I'm a bit confused on how the MCOIMAPIdleOperation is supposed to work.  I am trying to build a very simple client that listens for mail to arrive in an IMAP account, but I only get the callback as soon as it is started.  Am I supposed to create a new idle operation as soon as my existing handler is finished?  A simple example would be appreciated.

**Comment by gsantome** [comment]
@mronge if we are contacting directly gmail with oath2 how we will send a notification from another server when i just receive the email? 

Do you have an idea?
Thanks!
