### ISSUE TITLE
I am using mailcore2 in swift 3 project after adding libraries on other linker flags, i got these errors.

### ISSUE THREAD

**Issue by arslanzafar9313** [MailCore/mailcore2#1731]
Ld /Users/admin/Library/Developer/Xcode/DerivedData/email-brzyxdbsxxjjawfqbevvjglsjcwn/Build/Products/Debug-iphonesimulator/email.app/email normal x86_64
    cd /Users/admin/Desktop/Arslanproject
    export IPHONEOS_DEPLOYMENT_TARGET=10.2
    export PATH="/Users/admin/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Users/admin/Desktop/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Users/admin/Desktop/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Users/admin/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk -L/Users/admin/Library/Developer/Xcode/DerivedData/email-brzyxdbsxxjjawfqbevvjglsjcwn/Build/Products/Debug-iphonesimulator -F/Users/admin/Library/Developer/Xcode/DerivedData/email-brzyxdbsxxjjawfqbevvjglsjcwn/Build/Products/Debug-iphonesimulator -filelist /Users/admin/Library/Developer/Xcode/DerivedData/email-brzyxdbsxxjjawfqbevvjglsjcwn/Build/Intermediates/email.build/Debug-iphonesimulator/email.build/Objects-normal/x86_64/email.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=10.2 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/admin/Library/Developer/Xcode/DerivedData/email-brzyxdbsxxjjawfqbevvjglsjcwn/Build/Intermediates/email.build/Debug-iphonesimulator/email.build/Objects-normal/x86_64/email_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Users/admin/Desktop/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/admin/Library/Developer/Xcode/DerivedData/email-brzyxdbsxxjjawfqbevvjglsjcwn/Build/Intermediates/email.build/Debug-iphonesimulator/email.build/Objects-normal/x86_64/email.swiftmodule -lc++ -lz -ltidy -liconv -lsasl2 -lxml2 -letpan-ios -lctemplate-ios -lstdc++ -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/admin/Library/Developer/Xcode/DerivedData/email-brzyxdbsxxjjawfqbevvjglsjcwn/Build/Intermediates/email.build/Debug-iphonesimulator/email.build/email.app.xcent /Users/admin/Library/Developer/Xcode/DerivedData/email-brzyxdbsxxjjawfqbevvjglsjcwn/Build/Products/Debug-iphonesimulator/libMailCore-ios.a -framework CFNetwork -Xlinker -dependency_info -Xlinker /Users/admin/Library/Developer/Xcode/DerivedData/email-brzyxdbsxxjjawfqbevvjglsjcwn/Build/Intermediates/email.build/Debug-iphonesimulator/email.build/Objects-normal/x86_64/email_dependency_info.dat -o /Users/admin/Library/Developer/Xcode/DerivedData/email-brzyxdbsxxjjawfqbevvjglsjcwn/Build/Products/Debug-iphonesimulator/email.app/email

Undefined symbols for architecture x86_64:
  "std::string::append(char const*, unsigned long)", referenced from:
      ctemplate::StringEmitter::Emit(char const*, unsigned long) in libMailCore-ios.a(MCHTMLRenderer.o)
  "std::string::c_str() const", referenced from:
      renderTemplate(mailcore::String*, mailcore::HashMap*) in libMailCore-ios.a(MCHTMLRenderer.o)
  "std::string::operator+=(std::string const&)", referenced from:
      ctemplate::StringEmitter::Emit(std::string const&) in libMailCore-ios.a(MCHTMLRenderer.o)
  "std::string::operator+=(char)", referenced from:
      ctemplate::StringEmitter::Emit(char) in libMailCore-ios.a(MCHTMLRenderer.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()", referenced from:
      renderTemplate(mailcore::String*, mailcore::HashMap*) in libMailCore-ios.a(MCHTMLRenderer.o)
  "std::string::operator+=(char const*)", referenced from:
      ctemplate::StringEmitter::Emit(char const*) in libMailCore-ios.a(MCHTMLRenderer.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()", referenced from:
      renderTemplate(mailcore::String*, mailcore::HashMap*) in libMailCore-ios.a(MCHTMLRenderer.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by haithngn** [comment]
Which method did you use to add Mailcore to your project ?
- CocoaPods
- Carthage
- Manual

**Comment by arslanzafar9313** [comment]
CocoaPods

**Comment by arslanzafar9313** [comment]
My issue is resolved now thanks.

**Comment by haithngn** [comment]
we can close this issue ?

**Comment by arslanzafar9313** [comment]
yes

**Comment by arslanzafar9313** [comment]
Tell me 1 more thing how to fetch all emails from gmail server and show it on table view using swift 3??

**Comment by haithngn** [comment]
@arslanzafar9313 you should read the document first, it now available at http://libmailcore.com/api/objc/index.html

bonus : IMAPSession
Happy coding :)
