### ISSUE TITLE
how to add a "RelatedAttachment" or "inlineAttachment" when forward  email ?

### ISSUE THREAD

**Issue by zhengyatian** [MailCore/mailcore2#1733]
I received an email on phone,  like this :
The image is in content. <img> src scheme is "cid:" or "x-mailcore-image:".

![image](https://user-images.githubusercontent.com/16497789/39977253-344dd25e-576b-11e8-8292-3d55c526d770.png)

When i forward this email , whether i "addAttachment" or "addRelatedAttachment",  the attachment is always in "attachment-area", not in content. As shown in figure.

`        for (MCOAttachment *attach in inAttach) {
            NSString * path = [NSTemporaryDirectory() stringByAppendingPathComponent:[NSString stringWithFormat:@"%@_%@",msgParser.header.messageID,attach.filename]];
            NSData *data = [NSData dataWithContentsOfFile:path];
            MCOAttachment *temp = [MCOAttachment attachmentWithData:data filename:attach.filename];
            temp.inlineAttachment = YES;
//            [msgBuilder addAttachment:temp];
            [msgBuilder addRelatedAttachment:temp];
        }`

![image](https://user-images.githubusercontent.com/16497789/39977265-4c566a14-576b-11e8-8039-a6ad9c252cae.png)
![image](https://user-images.githubusercontent.com/16497789/39977268-500580c8-576b-11e8-8783-9ea0086ebe75.png)

How to show it in the content?

**Comment by haithngn** [comment]
You must handle like send new message via SMTP. 
Refefer MessageBuilder :)

**Comment by zhengyatian** [comment]
As I said above, i did use SMTP protocol  and MessageBuilder

`MCOMessageBuilder *msgBuilder = [[MCOMessageBuilder alloc] init];`
`[msgBuilder addRelatedAttachment:temp];`
`NSData *rfc822 = [msgBuilder data];`
` MCOSMTPSendOperation *send = [[MMSMTPTool getSMTPSession] sendOperationWithData:rfc822];`

**Comment by zhengyatian** [comment]
Anyone knows????? How to solve this problem ?
