### ISSUE TITLE
Gmail messageId type

### ISSUE THREAD

**Issue by tereks** [MailCore/mailcore2#1737]
Hello
I have a problem with settings labelIds for gmail messages. StoreLabelsOperation seems not working for GMAIL. But mainly I have a question about MCOIMAPMessage class. 

Why MCOIMAPMessage.gmailMessageID is of uint type? Gmail API documentation says that messageId and threadID are strings.

**Comment by dinhviethoa** [comment]
On this page, it says that it's a 64-bits unsigned integer:
https://developers.google.com/gmail/imap/imap-extensions
