### ISSUE TITLE
How to delete multiple message from mailcore2 

### ISSUE THREAD

**Issue by kapil0408** [MailCore/mailcore2#1741]
Hi, 
I am using below code but it is deleting single message. could you please tell me how to pass multiple uids.

MCOIMAPOperation *deleteOperation = [objSeesion storeFlagsOperationWithFolder:strFolderName uids:uids kind:MCOIMAPStoreFlagsRequestKindAdd flags:MCOMessageFlagDeleted];
        [deleteOperation start:^(NSError * _Nullable error)
         {
             if(error)
			{
                   NSLog(@"error 1=%@",[error description]);
             }
             else
             {
                 MCOIMAPOperation *exPungOperation = [objSeesion expungeOperation:strFolderName];
                 [exPungOperation start:^(NSError * _Nullable error) {
                     //[[CMSessionController sharedInstance] disconnectSession:session];
                     if(error){
                         NSLog(@"error 1=%@",[error description]);
                     }else{
                         NSLog(@“Success”);
                     }
                 }];
             }
         }];

Thanks

**Comment by haithngn** [comment]
mark deleted flag for these messages.
then call expunge on their folder

good luck

**Comment by kapil0408** [comment]
Thanks haithngn . I check and get back to you. :)
