### ISSUE TITLE
Outlook authentication problems

### ISSUE THREAD

**Issue by atomicbird** [MailCore/mailcore2#1743]
I'm trying to use MailCore with Outlook. I've been using Microsoft's [guide to connecting with OAuth 2.](https://msdn.microsoft.com/en-us/library/dn440163.aspx) as a reference, and so far I can:

1. Initiate the OAuth process, using the scopes described at that page-- `wl.imap` and `wl.offline_access`.
2. Go through the OAuth process for an outlook.com email address
3. Get an OAuth token in my app.

However when I try to connect to the IMAP server, the `AUTHENTICATE XOAUTH2` call gets a reply of `NO AUTHENTICATE failed`. I'm using the token endpoint and IMAP server info as described in the page linked above, and OAuth succeeds, but then the IMAP server doesn't like the result. I also decoded the base64 data that MailCore sends to the IMAP server to ensure that it's following the right format, and that looks good too.

Does anyone have suggestions for what could be going wrong?

**Comment by atomicbird** [comment]
It turns out that Outlook is kind of picky about the OAuth scopes. I used the scopes described at that page but also included other scopes defined elsewhere, like `Mail.ReadWrite`. I wasn't completely certain which ones I needed so I added several and planned to shorten the list once I had something working. But if you ask for both `Mail.ReadWrite` and `wl.imap`, you get `Mail.ReadWrite` access but not `wl.imap`. So even though OAuth seemed to work, it doesn't cover the scope you need for IMAP. Fixing the requested scopes fixed this problem.

**Comment by Be-Maps** [comment]
Hi Tom, would you have time to copy paste your code for IMAP with OAuth, as I am getting :
2024-08-29 09:32:23 : imapConnect - IMAP Connect Error: Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo={NSLocalizedDescription=Unable to authenticate with the current session's credentials.}

I am getting token, and this part might be fine.
I try to read folders, create folders, delete messages, append messages.
my scopes are:
    let kScopes:[String] = [//"ExternalItem.Read.All",
                            "IMAP.AccessAsUser.All",
                            "Mail.Read",
                            "Mail.ReadBasic",
                            //"Mail.ReadBasic.All",
                            "Mail.ReadWrite",
                            "Mail.Send",
                            //"MailboxFolder.Read.All",
                            //"MailboxFolder.ReadWrite.All",
                            //"MailboxItem.ImportExport.All",
                            //"MailboxItem.Read.All",
                            //"MailboxSettings.Read",
                            //"MailboxSettings.ReadWrite",
                            "SMTP.Send",
                            //"User-Mail.ReadWrite.All",
                            "User.Read"
    ]

I try to use IMAP like the below variations (my testing code):
    public static func imapOAuthOutlook() async {
        let session =  MCOIMAPSession()
        session.hostname = "imap-mail.outlook.com"
        //session.username = "<****example>@<outlook.com>"
        session.username = "****example@outlook.com"
        //session.password = nil
        session.oAuth2Token  = OAuthDetails.getToken()
        session.port = 143//993//143
        session.allowsFolderConcurrentAccessEnabled = true
        session.connectionType              = MCOConnectionType.startTLS
        session.authType                    = MCOAuthType.xoAuth2Outlook//xoAuth2//xoAuth2Outlook
        session.isCheckCertificateEnabled   = false
        session.isVoIPEnabled               = false
        session.maximumConnections          = 2
        session.timeout                     = App.connectionTimeout
        
        if let loginOperation = session.checkAccountOperation() {
            do { try await loginOperation.start(); logd("imapConnect - Successful IMAP connection") }
            catch { logd("imapConnect - IMAP Connect Error: \(error)"); return }
        }
        
        // list folders
        var folderList:[Any]? = nil
        if let folderListOperation = session.fetchAllFoldersOperation() {
            do { folderList = try await folderListOperation.start(); logd("All IMAP Folders loaded") }
            catch { logd("Error listing folders: \(error)") }
        }
        
        for value in folderList! { // MARK: folderlist was null
            switch value {
            case is MCOIMAPFolder:
                let folder:MCOIMAPFolder = value as! MCOIMAPFolder
                //folder.path
                logd("\(folder.path.description) is a folder")
                //folder.
            default:
                logd("Skip ... possibly null value!")
            }
        }
    }

**Comment by atomicbird** [comment]
Hi @Be-Maps. I'm afraid I can't help. I left the company where I worked on this five years ago and don't have access to the source code.

**Comment by Be-Maps** [comment]
Thank You.
