### ISSUE TITLE
Get latest messages from last known mail Id. 

### ISSUE THREAD

**Issue by aqsa-arshad08** [MailCore/mailcore2#1746]
Is it possible to get messages based on the last known Email UID. I am able to fetch newest emails using "fetchMessagesByNumberOperation" method. But somehow i need to implement a way to fetch newest emails from one email id. 

Let say i have fetched x emails latest emails. And after 5 minutes i got three more emails. Now i want to fetch the latest emails from the last saved UID. 

Is it possible to do?

**Comment by haithngn** [comment]
@aqsa-arshad08 ,
Unfortunately, no one can make sure the UIDs are serialize because the message maybe removed by another mail client during that 5 minutes.
So you can increase your latest UID to find some new message on server side but you may miss some message.

**Comment by aqsa-arshad08** [comment]
So how do people usually sync the new emails ?

**Comment by dinhviethoa** [comment]
You need to use UIDVALIDITY on folder to make sure that the UIDs were the same.
If UIDVALIDITY is the same, you can assume that UIDs are the same. Then, get the latests UIDs.

Then, as @haithngn mentioned, UIDs could be removed by another email client. In this case, you need to get the list of messages anyway to update the list of messages that disappeared.

QRESYNC, only implemented on a small amount of servers would solve proper syncing.
