### ISSUE TITLE
Windows Source won't compile with VS2017 (#n)

### ISSUE THREAD

**Issue by ga2k** [MailCore/mailcore2#1755]
Compiling for Windows using VS2017 produces the following errors...

MCIMAPSession.cpp

d:\dev\mailcore2\src\core\imap\mcimapsession.cpp(1122): error C3861: 'mailimap_custom_command': identifier not found

d:\dev\mailcore2\src\core\imap\mcimapsession.cpp(1920): error C3861: 'mailimap_uidplus_uid_move': identifier not found

d:\dev\mailcore2\src\core\imap\mcimapsession.cpp(3097): error C3861: 'mailimap_set_msg_body_handler': identifier not found

d:\dev\mailcore2\src\core\imap\mcimapsession.cpp(3101): error C3861: 'mailimap_set_msg_body_handler': identifier not found

MCSMTPSession.cpp
d:\dev\mailcore2\src\core\smtp\mcsmtpsession.cpp(754): error C3861: 'mailesmtp_send_quit_no_disconnect': identifier not found

**Comment by haithngn** [comment]
duplicate #1752
