### ISSUE TITLE
Problem in Store whole MCOIMapMessage in core data using Transformable attribute

### ISSUE THREAD

**Issue by kapil0408** [MailCore/mailcore2#1756]
I am storing MCOIMapMessage in Local DB when I fetch this message from local DB than app crashes and show following error.

NSObject+MCO.mm:104: assert aClass != nil

Please help me to solve this problem. I am facing this since last two days.

**Comment by haithngn** [comment]
never depend on framework's model :D
you should transform these model to your local db and just interact with your models.

**Comment by kapil0408** [comment]
Yes, I created my model (EmailModel class) with property MCOIMAPMessage object then pass MCOIMapMessage(which is coming from server) to MCOIMapMessage of EmailModel. I saved MCOIMapMessage of EmailModel like below

-(instancetype)initWithImapMessage:(MCOIMAPMessage *)message strEmailId:(NSString*)strEmailId
{
    if(self = [super init])
    {
        self.emailUID = message.uid;
        self.date = message.header.date;
        **self.message = message;**
        self.strEmailId = strEmailId;
        self.strFoldername = nil;
        self.isDeleteStatus = @"0";
        self.isEmailLoaded = @"0";
        self.isReadStatus = @"0";
        self.strEmailContentHTMLBody = nil;
        self.strEmailContentTextBody = nil;
    }
    return self;
}


+ (void)saveEmailInTable:(NSString*)strTblName withFolderName:(NSString*)folderName withMessage:(NSMutableArray*)arrMessage
{
    NSManagedObjectContext* privateContext = [[NSManagedObjectContext alloc] initWithConcurrencyType:NSPrivateQueueConcurrencyType];
    [privateContext setPersistentStoreCoordinator:[[[AppDelegate sharedDelegate] managedObjectContext] persistentStoreCoordinator]];
    [privateContext performBlock:^{
        
        NSEntityDescription* descp = [NSEntityDescription entityForName:strTblName inManagedObjectContext:privateContext];
        for (EmailModel *objModel in arrMessage)
        {
            
            NSManagedObject* obj = [[NSManagedObject alloc]initWithEntity:descp insertIntoManagedObjectContext:privateContext];
//            NSData *arrayData = [NSKeyedArchiver archivedDataWithRootObject:objModel.message];
            NSLog(@"objModel.message=%@",objModel.message);
            [obj setValue:objModel.message forKey:@"imapMessage"];
            [obj setValue:[AppDelegate sharedDelegate].currentEmailId forKey:@"emailId"];
            [obj setValue:[NSNumber numberWithInt:objModel.message.uid] forKey:@"emailUID"];
            [obj setValue:@"sdsd" forKey:@"emailContentHTMLBody"];
            [obj setValue:@"sdsd" forKey:@"emailContentTextBody"];
            [obj setValue:objModel.message.header.date forKey:@"date"];
            [obj setValue:folderName forKey:@"foldername"];
            if (objModel.message.flags==MCOMessageFlagNone)
                [obj setValue:@"0" forKey:@"isReadStatus"];
            else
                [obj setValue:@"1" forKey:@"isReadStatus"];
            
            [obj setValue:@"0" forKey:@"isDeleteStatus"];
            
            
            [obj setValue:@"0" forKey:@"isEmailLoaded"];
            
           
            NSError *error = nil;
            @try {
                [privateContext save:&error];
                if (!error) {
                    NSLog(@"Successfully email added");
                } else {
                    NSLog(@"Error while adding new email:- %@",error.localizedDescription);
                }
            } @catch (NSException *exception) {
                NSLog(@"Exception while adding new email:- %@",exception);
            } @finally {
            }
        }
    }];
}

I also used archived way to fetch MCOIMapMessage. it is showing same error as I mentioned last comments. please see below code

+ (NSMutableArray*)getEmailFromTable:(NSString*)strTblName withFolderName:(NSString*)strFolderName withEmailId:(NSString*)strEmailId deleteStatus:(NSString*)isDeleteStatus
{
    NSError* error = nil;
    NSMutableArray* arrEmails;
    NSManagedObjectContext *mainContext = [AppDelegate sharedDelegate].managedObjectContext;
    NSFetchRequest *request = [NSFetchRequest fetchRequestWithEntityName:strTblName];//[NSString stringWithFormat:@"%@",strTblName]];
    request.predicate = [NSPredicate predicateWithFormat:@"emailId == %@ AND foldername == %@ AND isDeleteStatus == %@", [AppDelegate sharedDelegate].currentEmailId, strFolderName,isDeleteStatus];
    NSArray *arrResult = [mainContext executeFetchRequest:request error:&error];
    if (error)
    {
        NSLog(@"error Description=%@",[error description]);
        return nil;
    }
    else
    {
        if ([arrResult count]>0)
        {
            arrEmails = [[NSMutableArray alloc]initWithCapacity:arrResult.count];
            for (NSManagedObject* objModel in arrResult)
            {
                NSLog(@"objModel valueForKey=%@",[objModel valueForKey:@"imapMessage"]);
//                id msg  = [NSKeyedUnarchiver unarchiveObjectWithData: [objModel valueForKey:@"imapMessage"]];
                EmailModel *model = [[EmailModel alloc] initWithDataBaseObject:objModel];
                [arrEmails addObject:model];
            }
        }
    }
    return  arrEmails;
}

Thanks. :)

**Comment by kapil0408** [comment]
I also used "NSValueTransformer" approach  but give same error when fetching. it is working fine on saving

**Comment by kapil0408** [comment]
Solved.

**Comment by qqq1010440810** [comment]
@kapil0408 I also encountered this problem， May I ask how this problem was solved，
