### ISSUE TITLE
How to get notification when app is suspended when sent new email.

### ISSUE THREAD

**Issue by jhon786** [MailCore/mailcore2#1763]
Hi,

I am new with mailcore. I need to implement Push notification when app terminated/suspended. How i go with the same. Can you please help? 

Thanks in advance.

**Comment by dinhviethoa** [comment]
People usually run their servers, poll the imap account from the servers and send push notifications.

**Comment by starman-karthik** [comment]
Does MailCore 2 support Push IMAP ? to enable push notifications for new emails ?
