### ISSUE TITLE
Soooo.... Windows users can go fxxk themselves, then?

### ISSUE THREAD

**Issue by ga2k** [MailCore/mailcore2#1764]
No responses or views in weeks for my issues in building the library? 

Fine. I'll use the pre-built libraries.

Oh, wait, there aren't ANY examples and documentation on how to use this library with windows. I've googled this s..t for hours now. 

Soooo... Windows users can go fxxk themselves, then?

**Comment by dinhviethoa** [comment]
Can you refer to the headers?

For example:
https://github.com/MailCore/mailcore2/blob/master/src/async/imap/MCIMAPAsyncSession.h
https://github.com/MailCore/mailcore2/blob/master/src/async/smtp/MCSMTPAsyncSession.h
Let me know if you have specific questions.
