### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [MailCore/mailcore2#1771]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex") ⇒ [IMAPIdleOperation constructor](https://github.com/MailCore/mailcore2/blob/f708ce74e23b61ec6e5ae958eba0b8bcd8831a1e/src/async/imap/MCIMAPIdleOperation.cpp#L16)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string") ⇒ [NNTPSession::fetchArticleByMessageID](https://github.com/MailCore/mailcore2/blob/096c8665b5d7c6851395a46bd09d33e3fa6e2d52/src/core/nntp/MCNNTPSession.cpp#L490)

**Comment by dinhviethoa** [comment]
It would be indeed nice to add more error handling.
Could you add assert() at those locations in a pull request?
Thanks!

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by dinhviethoa** [comment]
> How do you think about to improve static source code analysis also for this software?
There's clang static analysis in Xcode. That said, I'm unsure if I already ran it on the codebase.
But sure, I'm interested in static analysis to catch issues that are around.

> Are you interested to apply aspect-oriented software development?
Does it work with Xcode in a simple way?
Does it disrupt the C++ you write? (ie: would contributors have to learn aspect to be able to write it?)

> Would you like to encapsulate error detection and corresponding exception handling as a reusable aspect in this software?
Could you show what it would look like?

**Comment by diejmon** [comment]
This man just trolling every repository he can find and always ask another question instead of continuing conversation.

**Comment by elfring** [comment]
How do you think about to replace calls of POSIX thread API functions by [the use of the C++ thread support library](https://en.cppreference.com/w/cpp/thread "Description for the thread support library")?

-----

>Could you show what it would look like?

Do you find information sources like the following useful?
- Article "[A Reusable Aspect for Memory Allocation Checking](https://web.archive.org/web/20120120194035/http://research.msrg.utoronto.ca/ACC/Tutorial#A_Reusable_Aspect_for_Memory_All)"
- Document "[Aspect-Oriented Software Development - An Introduction](https://web.archive.org/web/20130512025224/http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf)" by Johan Brichau and Theo D'Hondt
- Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164)" by Daniel Lohmann and Olaf Spinczyk

**Comment by dinhviethoa** [comment]
> Do you find information sources like the following useful?

Nope. I'd like to see how it applies to this specific codebase.

@elfring is it likely that this conversation will lead to contributions?
You didn't answer the questions that I have.

**Comment by elfring** [comment]
* I suggest to take another look at the linked information sources.
* The referenced tools can find update candidates generally and show possible fixes if you would be willing to use higher level development tools at all.

**Comment by dinhviethoa** [comment]
It doesn't seem actionable. Closing.

**Comment by elfring** [comment]
:crystal_ball: Would you ever like to extend your software tool box?

**Comment by elfring** [comment]
>Could you show what it would look like?

Do you get further ideas from the following example for a small AspectC++ script?

```
…
aspect string_duplication_check
{
 advice execution("% * strdup(...)"): after()
 {
  if (*tjp->result() == NULL)
     abort();
 }
};
…
```

**Comment by elfring** [comment]
Is the aspect specification easily extensible for more use cases?
