### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [MailCore/mailcore2#1772]
Would you like to [wrap any pointer data members](https://github.com/MailCore/mailcore2/blob/f708ce74e23b61ec6e5ae958eba0b8bcd8831a1e/src/async/pop/MCPOPAsyncSession.cpp#L71 "Update candidate: POPAsyncSession class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by dinhviethoa** [comment]
For now, I was trying to follow a model with manual reference counting.
I'm undecided about adding smart pointers since it adds a lot of syntax sugar.

**Comment by elfring** [comment]
Do you care for [C++ guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ core guideline “R.11: Avoid calling new and delete explicitly”")?

**Comment by dinhviethoa** [comment]
I prefer the rule of "always use new" rather than "try to avoid new and sometimes you have to use it where it applies".

**Comment by elfring** [comment]
This programming approach is unsafe. How are the chances to reconsider it?

**Comment by dinhviethoa** [comment]
> This programming approach is unsafe. How are the chances to reconsider it?

Could you show me how you would handle the bridging between C++ and Objective-C?
If there's a route that's not too complex for it and if you'd like to make it happen, I would be open to it.
Let me know!

**Comment by elfring** [comment]
Which software components are responsible for [the lifetime management of the involved objects](https://en.cppreference.com/w/cpp/language/lifetime "Description for lifetime management")?

**Comment by dinhviethoa** [comment]
Alright, this discussion doesn't seem to be constructive. I'm closing it.

**Comment by elfring** [comment]
It might be harder to achieve consensus about desirable software design directions and possible improvements.
