### ISSUE TITLE
How to set the AuthType to none

### ISSUE THREAD

**Issue by dphidden** [MailCore/mailcore2#1775]
I am trying to connect to an SMTP server that I have setup and it doesn't require AuthType, by default it uses plain. How do I set  smtpSession.authType = MCOAuthType to none.

I am using Swift

**Comment by dphidden** [comment]
cc: @haithngn @dinhviethoa

**Comment by haithngn** [comment]
@dphidden 
Ref: http://libmailcore.com/api/objc/Constants/MCOAuthType.html
Try this:
smtpSession.authType = MCOAuthType(rawValue:0)
