### ISSUE TITLE
How to get MCOMessageParser for several IMAP messages with one operation only?

### ISSUE THREAD

**Issue by ikemuc** [MailCore/mailcore2#1781]
Hi,

I'm using 

`
let requestKind = MCOIMAPMessagesRequestKind().union(MCOIMAPMessagesRequestKind.structure)
let operationIndexSet = ImapHandlerMailcore2.convertIndexSet(indexSet: indexSet)
let operation = imapSession.fetchMessagesOperation(withFolder: folder, requestKind: requestKind, uids: operationIndexSet)
            
operation?.start( { error, messages, vanishedMessages in
[...]
`

to get a number of IMAP messages from the server. I want to get the message text (BODY, mainPart) of all messages, but it seems that I don't get the message RFC 822 data out of the result of imapSession.fetchMessagesOperation (or similar) to feed it into the MCOMessageParser?

One possibility would be to to use fetchMessageOperation* or fetchParsedMessageOperation*, but they all only take one uid as argument, so it looks like I have to call one operation per message, which produces possibly a higher load onto the IMAP server than only one operation.

Any hints for me how to get a MCOMessageParser for several messages with one operation?
A pointer to more (beginners) example code (Swift) would be great :-)
Is there a Swift 3 open source project on github using mailcore2 to have a look at?

**Comment by haithngn** [comment]
You may you fetchParsedMessage operation but it just for a specific message.
You have to implement other strategy to fetch multiple messages (one by one).

**Comment by ikemuc** [comment]
OK, then I can stop searching for a way to solve this with my strategy. I thought I didn't look good enough ;-)

Thanks for the quick answer!

**Comment by haithngn** [comment]
welcome :)
