### ISSUE TITLE
iOS, no moveMessagesOperationWithFolder method

### ISSUE THREAD

**Issue by zhouzhongguang** [MailCore/mailcore2#1792]
iOS platform, have no moveMessagesOperationWithFolder method in MCOIMAPSession.h file after installed the code use CocoaPods.(code version 0.6.4).
![2018-11-19 11 08 44](https://user-images.githubusercontent.com/10241716/48684188-879f3500-ebeb-11e8-9e0a-4a631a3d1f2e.png)
![2018-11-19 11 06 27](https://user-images.githubusercontent.com/10241716/48684192-8e2dac80-ebeb-11e8-8f06-2bb4f5bef432.png)

**Comment by haithngn** [comment]
MailCore2 0.6.4 on CocoaPods is out update (Apr 2016), you should adjust Pod file to tell podspec must pull the latest commit.

**Comment by zhouzhongguang** [comment]
I add the below line to podfile, to specify the lastest commit. And pod install
`pod 'mailcore2-ios', :git => 'https://github.com/MailCore/mailcore2.git', :commit => '1e889f7e441d8540bc55c131b891a338199ad207'`

it goes to "Failed to download 'mailcore2-ios'".

![2018-11-19 2 52 29](https://user-images.githubusercontent.com/10241716/48690836-18393d80-ec0b-11e8-862d-be01b176b698.png)

**Comment by zhouzhongguang** [comment]
I want to integrate Mailcore2 by link against MailCore2 as a static library. But i found the the time of lastest [build for iOS](http://d.etpan.org/mailcore2-deps/mailcore2-ios/) is 2016-04-07 06:05. 

![2018-11-28 9 37 04](https://user-images.githubusercontent.com/10241716/49122951-a55a5180-f2f1-11e8-8093-41ea799b1bfa.png)

So i want to build MailCore2 static library myself. Is the build-mailcore2-ios.sh file in scripts directory lastest? Can i build the lastest mailcore2 commit code to a static library by run this sh file?

**Comment by haithngn** [comment]
```github "MailCore/mailcore2" "master"```

incase you are using Carthage

**Comment by zhouzhongguang** [comment]
resolve this isssue by use Carthage😄

**Comment by yiyuan-liaoqiang** [comment]
pod 'mailcore2-ios', :git => 'https://github.com/MailCore/mailcore2.git', :commit => '1e889f7e441d8540bc55c131b891a338199ad207'
it works
