### ISSUE TITLE
Unable to refresh expired token without a refresh token

### ISSUE THREAD

**Issue by manthan-desai** [MailCore/mailcore2#1795]
While trying to Fetch New Messages, it returns error: "Unable to authenticate with the current session\'s credentials."

As per Issue listed in MailCore 2 
link : https://github.com/MailCore/mailcore2/issues/1170

tried to call authorizeRequest with nil as request but it didn't help me, It returns error : "Unable to refresh expired token without a refresh token."

Please help me on the same.

Thank You in Advance.

**Comment by haithngn** [comment]
You have to request to refresh access token.
