### ISSUE TITLE
Is there a way to fetch messages in batches - MCOIMAPFetchMessagesOperation

### ISSUE THREAD

**Issue by palaniraja** [MailCore/mailcore2#180]
I'm following the example given in [IMAP Examples](https://github.com/MailCore/mailcore2/wiki/IMAP-Examples) and [MasterViewController.m](https://github.com/MailCore/mailcore2/blob/master/example/ios/iOS%20UI%20Test/iOS%20UI%20Test/MasterViewController.m#L80)

The [start block at Line 85](https://github.com/MailCore/mailcore2/blob/master/example/ios/iOS%20UI%20Test/iOS%20UI%20Test/MasterViewController.m#L85) is called when the array of messages of the given folder. Should I be worried if I tried with a mailbox of considerable mails? 

I had to download each messages and save it in local sqlitedb for offline access, and I'm looking for a way to download each mails instead of having an array of large set.

I also noticed the progress block returns an integer _current progress_ but no reference to the mail/uniqid?

Sorry to raise this as issue here, I tried mailing list but github seems to be more active.

**Comment by vymallesh** [comment]
@dinhviethoa 

I am trying to sync mails which were already downloaded in my local DB.I was using below things, but it was not working...

My server is supporting below things,
This is only for servers that support Conditional Store. See RFC4551
vanishedMessages will be set only for servers that support QRESYNC. See RFC5162.

But still i am not getting any modified mails / Deleted mails.Below is the code,

int start = 1;
int lastUID = [[[NSUserDefaults standardUserDefaults]valueForKey:@"lastUID"]intValue];

MCOIMAPFolderStatusOperation * op = [session folderStatusOperation:@"INBOX"];
[op start:^(NSError *error, MCOIMAPFolderStatus * info) {

NSLog(@"UIDNEXT: %lu", (unsigned long) [info uidNext]);
NSLog(@"UIDVALIDITY: %lu", (unsigned long) [info uidValidity]);
NSLog(@"UIDVALIDITY: %lu", (unsigned long) [info highestModSeqValue]);

MCOIndexSet *UIDS = [MCOIndexSet indexSetWithRange:MCORangeMake(start, UINT64_MAX)];

MCOIMAPFetchMessagesOperation * op1 = [session syncMessagesByUIDWithFolder:@"INBOX"
                                                               requestKind:MCOIMAPMessagesRequestKindUid
                                                                      uids:UIDS
                                                                    modSeq:[info highestModSeqValue]];
[op1 start:^(NSError * __nullable error, NSArray * messages, MCOIndexSet * vanishedMessages) {
    NSLog(@"added or modified messages: %@", messages);
    NSLog(@"deleted messages: %@", vanishedMessages);
}];
}];

Still i am not getting any modified mails in the log.

Any help would be appreciated..
