### ISSUE TITLE
Issue with the Message Flags

### ISSUE THREAD

**Issue by vymallesh** [MailCore/mailcore2#1807]
Hi,

I was wondering, why i am getting different message flag values. If i delete an email in Mail server, i am supposed to get MessageDeletedFlag as '3'(int).But i am getting '8'(int),and even i am getting deleted messages too in my mobile application.Why it was happening like that, really i don't understand..

**Comment by haithngn** [comment]
@vymallesh,

The raw value in Integer of the MessageDeletedFlag is 8 not 3.
http://libmailcore.com/api/java/com/libmailcore/MessageFlag.html#MessageFlagDeleted
http://libmailcore.com/api/objc/Constants/MCOMessageFlag.html

1 << 3 is a bitwise expresion and the the result is 8 :D

**Comment by vymallesh** [comment]
@haithngn 

Thank you for your response. But still i am getting few deleted messages in my Mail server.Why it was happening like that.And i have few more queries.

1. I am using Webmail Client for my emails, as we knew that, there will be two kinds of mails,
Roundcube and horde.
 If i delete the emails in Horde, again i am getting those emails in my mobile app, Where as with roundcube , if i do the same , i am not getting that issue.

2.Will the Message Flag differs from message type to type.
I meant, will MessageDelete /MessageRead/ MessageImportant flag differs for Reply Message , Forward Message, New Message.

**Comment by haithngn** [comment]
When you alter a message flag to delete that message will still exist on the remote until the folder that contains the message was invoke cmd expunge.
https://www.cyrusimap.org/imap/reference/faqs/o-deleted-expired-expunged-purged.html

This is not a MailCore2 issue.
