### ISSUE TITLE
Unable to Sync the mail

### ISSUE THREAD

**Issue by vymallesh** [MailCore/mailcore2#1811]
I am trying to sync mails which were already downloaded in my local DB.I was using below things, but it was not working...

My server is supporting below things,
This is only for servers that support Conditional Store. See RFC4551
vanishedMessages will be set only for servers that support QRESYNC. See RFC5162.

But still i am not getting any modified mails / Deleted mails.Below is the code,

int start =  1;
int lastUID = [[[NSUserDefaults standardUserDefaults]valueForKey:@"lastUID"]intValue];

MCOIMAPFolderStatusOperation * op = [session folderStatusOperation:@"INBOX"];
[op start:^(NSError *error, MCOIMAPFolderStatus * info) {
    
    NSLog(@"UIDNEXT: %lu", (unsigned long) [info uidNext]);
    NSLog(@"UIDVALIDITY: %lu", (unsigned long) [info uidValidity]);
    NSLog(@"UIDVALIDITY: %lu", (unsigned long) [info highestModSeqValue]);
    
    MCOIndexSet *UIDS = [MCOIndexSet indexSetWithRange:MCORangeMake(start, UINT64_MAX)];
    
    MCOIMAPFetchMessagesOperation * op1 = [session syncMessagesByUIDWithFolder:@"INBOX"
                                                                   requestKind:MCOIMAPMessagesRequestKindUid
                                                                          uids:UIDS
                                                                        modSeq:[info highestModSeqValue]];
    [op1 start:^(NSError * __nullable error, NSArray * messages, MCOIndexSet * vanishedMessages) {
        NSLog(@"added or modified messages: %@", messages);
        NSLog(@"deleted messages: %@", vanishedMessages);
    }];
}];

Still i am not getting any modified mails in the log.

**Comment by haithngn** [comment]
The result of MCOIMAPFetchMessagesOperation just tell you which messages was modified  on the remote side, it does not help you sync.
You have to adjust you local messages base on that result.
