### ISSUE TITLE
Not able to login Outlook

### ISSUE THREAD

**Issue by vymallesh** [MailCore/mailcore2#1813]
If i try to login Outlook , it ends up with the below error.

Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo={NSLocalizedDescription=A stable connection to the server could not be established.}

I am using below code,

    session = [[MCOIMAPSession alloc]init];
    session.hostname = @"mail.outlook.com";
    session.username = userName;
    session.password = pwd;
    session.port = 993;
    session.authType = MCOAuthTypeSASLPlain;
    session.connectionType = MCOConnectionTypeTLS;

Any help would be appreciated..

**Comment by haithngn** [comment]
you do wrong Outlook IMAP configuration, you should read:

https://github.com/MailCore/mailcore2/wiki/Providers-Syntax
http://libmailcore.com/api/objc/Classes/MCOMailProvider.html
http://libmailcore.com/api/objc/Classes/MCOMailProvidersManager.html

**Comment by vymallesh** [comment]
Can i login through respective SDK's (Microsoft/Google/Yahoo) and send/receive mails through Mailcore2.

**Comment by haithngn** [comment]
@vymallesh MailCore can work for POP, IMAP and SMTP support
We do not care Microsoft or Google or Yahoo or whatever.

**Comment by vymallesh** [comment]
Still getting the error,

Error Logion Email : Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo={NSLocalizedDescription=A stable connection to the server could not be established.}

Below is the configuration, which i am doing

 session = [[MCOIMAPSession alloc]init];
    session.hostname = @"imap-mail.outlook.com";
    session.username = userName;
    session.password = pwd;
    session.port = 993;
    session.authType = MCOAuthTypeSASLPlain;
    session.connectionType = MCOConnectionTypeTLS;
    NSString *valueToSave = session.username;

**Comment by haithngn** [comment]
SMTP config:
host: smtp-mail.outlook.com
port: 25
connection type: starttls
authentication type: saslNone
isCheckCertificateEnabled: false

**Comment by vymallesh** [comment]
![Screenshot 2019-05-23 at 11 38 03 AM](https://user-images.githubusercontent.com/19487513/58229392-3f560080-7d4f-11e9-8dab-e4f55afe1dde.png)

Still getting the same issue for me, what was the issue, i am not getting..

**Comment by haithngn** [comment]
![Screen Shot 2019-05-23 at 1 28 59 PM](https://user-images.githubusercontent.com/22902671/58230548-d5ddee00-7d5e-11e9-9415-614fbc31cfaa.png)

Can you show me the console logs ?

**Comment by vymallesh** [comment]
![Screenshot 2019-05-23 at 12 07 10 PM](https://user-images.githubusercontent.com/19487513/58230951-57c81a00-7d53-11e9-93a9-10ff3c32103d.png)

Here is that ..

**Comment by haithngn** [comment]
I mean the xcode debug console
you could try this

```
//
//  ViewController.m
//  SMTPTest
//
//  Created by Hai Nguyen Thanh on 5/23/19.
//  Copyright © 2019 MailCore. All rights reserved.
//

#import "ViewController.h"
#import <MailCore/MailCore.h>

@interface ViewController ()

@property (nonatomic) MCOSMTPSession * outlookSession;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    _outlookSession = [[MCOSMTPSession alloc] init];
    _outlookSession.username = @"mailbox";
    _outlookSession.password = @"pwd";
    _outlookSession.hostname = @"smtp-mail.outlook.com";
    _outlookSession.connectionType = MCOConnectionTypeStartTLS;
    _outlookSession.authType = MCOAuthTypeSASLNone;
    _outlookSession.port = 25;
    _outlookSession.checkCertificateEnabled = false;
    
    [_outlookSession setConnectionLogger:^(void *connectionID, MCOConnectionLogType type, NSData *data) {
        NSString *myString = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
        NSLog(@"Log: %@", myString);
    }];
    
    MCOSMTPOperation * op = _outlookSession.loginOperation;
    [op start:^(NSError * _Nullable error) {
        NSLog(@"Error : %@", error);
    }];
}


- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}


@end
```

**Comment by vymallesh** [comment]
![Screenshot 2019-05-23 at 12 18 00 PM](https://user-images.githubusercontent.com/19487513/58231536-e5f0d000-7d54-11e9-9235-4095f946d004.png)

Above screenshot was my Model Class, where i will be having my Connection Logger method and Login SMTP method.



![Screenshot 2019-05-23 at 12 18 23 PM](https://user-images.githubusercontent.com/19487513/58231586-015bdb00-7d55-11e9-83ef-34a07c81c48b.png)

Above screenshot was my View class, where i will be having my button action, on that button action i will be calling the Model class to execute.

I am following the same thing which you mentioned, kindly let me know what was the issue i am doing...

Thanks,

**Comment by haithngn** [comment]
Did you try login with my code and your account ?

**Comment by vymallesh** [comment]
yeah..but still same issue continues...

![Screenshot 2019-05-23 at 1 00 08 PM](https://user-images.githubusercontent.com/19487513/58233866-cd83b400-7d5a-11e9-83ee-e241a28a36ba.png)

In above screenshot, you could see the same code which you provided.

![Screenshot 2019-05-23 at 1 00 19 PM](https://user-images.githubusercontent.com/19487513/58233898-e3917480-7d5a-11e9-810d-5558a3fe1827.png)

In above screenshot, you could see the Log message.

Let me the issue what was the issue i am getting/ committing, or it is something related to any any network issue.I am not able to figure out the exact issue...

**Comment by haithngn** [comment]
@vymallesh could you set timeout to 60 seconds ?

**Comment by vymallesh** [comment]
Nope...

**Comment by haithngn** [comment]
I mean
```
_outlookSession.timeout = 60.0;
```

**Comment by vymallesh** [comment]
Nope, i didn't set any timeout variables.

**Comment by vymallesh** [comment]
![Screenshot 2019-05-23 at 3 22 41 PM](https://user-images.githubusercontent.com/19487513/58243643-a33bf180-7d6e-11e9-87d6-3881554dec1e.png)

@haithngn , i had setted the timeout variable too.But, still i am getting the same issue.

**Comment by vymallesh** [comment]
Not Working Still

**Comment by haithngn** [comment]
@vymallesh can I have your account ?

**Comment by vymallesh** [comment]
@haithngn ,
I had changed   _outlookSession.authType = MCOAuthTypeSASLNone to _outlookSession.authType = MCOAuthTypeSASLLogin...surprisingly it started working..

**Comment by vymallesh** [comment]
@haithngn , will the same works for Gmail and Yahoo too.

**Comment by vymallesh** [comment]
![Screenshot 2019-05-23 at 3 46 36 PM](https://user-images.githubusercontent.com/19487513/58245781-31b27200-7d73-11e9-8747-a52e7f8ec8b4.png)

In the above screenshot, you could see that it was not working for Gmail.

**Comment by vymallesh** [comment]
![Screenshot 2019-05-23 at 3 55 18 PM](https://user-images.githubusercontent.com/19487513/58245835-4f7fd700-7d73-11e9-8a2e-291851da18ea.png)

In the above screenshot, you could see that it was not working for Gmail..

**Comment by vymallesh** [comment]
@haithngn , Do we need to implement Auth type , if we would like to access Gmail through Mailcore.

**Comment by vymallesh** [comment]
Yeah that's fine, i will maintain...But i just wanted to know whether we need to implement Auth type or not ?

**Comment by haithngn** [comment]
No, you don’t.
You can implement whatever you want to get the access token then set it to the session.

**Comment by haithngn** [comment]
@vymallesh should we close this ?

**Comment by vymallesh** [comment]
Nope ..How can I get the access token without implementing the Auth...Are
there such apis to get the access token..

**Comment by haithngn** [comment]
You have to implement the Auth with any framework you wan.
MailCore2 does not support to get any access token.

**Comment by vymallesh** [comment]
Yeah..That I understood , but I just wanted to know , do we have any apis
in gmail to get the access token without implementing the Auth.

**Comment by haithngn** [comment]
No

**Comment by vymallesh** [comment]
Can be able to login successfully through Mailcore in Outlook, but not getting messages from Imap. Below is my code,

//Imap Session

    session = [[MCOIMAPSession alloc]init];
    session.hostname = @"imap-mail.outlook.com";
    session.username = @"dummy@outlook.com";
    session.password  = @"dummy14";
    session.port = 993;
    session.authType = MCOAuthTypeSASLLogin;
    session.connectionType = MCOConnectionTypeStartTLS;
    session.checkCertificateEnabled = false;

//Fetch messages

-(void)fetchMessages{

    NSString *folder = @"INBOX";
    MCOIMAPMessagesRequestKind *requestKind = MCOIMAPMessagesRequestKindUid | MCOIMAPMessagesRequestKindHeaders|
    MCOIMAPMessagesRequestKindHeaderSubject;

    MCOIMAPFolderInfoOperation *folderInfo = [session folderInfoOperation:folder];

    [folderInfo start:^(NSError *error, MCOIMAPFolderInfo *info) {
        int numberOfMessages = 1;
        numberOfMessages -= 1;
        MCOIndexSet *numbers = [MCOIndexSet indexSetWithRange:MCORangeMake([info messageCount] - numberOfMessages, numberOfMessages)];

        MCOIMAPFetchMessagesOperation *fetchOperation = [self->session fetchMessagesByNumberOperationWithFolder:folder
                                                                                                    requestKind:MCOIMAPMessagesRequestKindUid | MCOIMAPMessagesRequestKindHeaders|         MCOIMAPMessagesRequestKindHeaderSubject|MCOIMAPMessagesRequestKindFlags|MCOIMAPMessagesRequestKindStructure|MCOIMAPMessagesRequestKindInternalDate                                            numbers:numbers];

        [fetchOperation start:^(NSError *error, NSArray *messages, MCOIndexSet *vanishedMessages) {
            for (MCOIMAPMessage * message in messages) {
                MCOMessageHeader *header = [message header];
                NSLog(@"fromMail: %@",[[[message header] from] mailbox]);
                NSLog(@"to first : %@",[[[header to] firstObject] mailbox]);
                NSLog(@"message Id: %u", [message uid]);
                NSString * subject = message.header.subject;
                NSLog(@"Subject %@",subject);

                if(message.flags == MCOMessageFlagSeen){
                    NSLog(@"your message is read");
                }else{
                    NSLog(@"your message is not read");
                }

                NSArray *attachmentlist = [message attachments];
                for (MCOAbstractPart *tempPart in attachmentlist) {
                    NSLog(@"%@",tempPart.mimeType);
                }
            }
        }];
    }];
}

It ends with the same error, which i got earlier for SMTP.

Below is the screenshot,

![Screenshot 2019-05-24 at 10 29 06 AM](https://user-images.githubusercontent.com/19487513/58303684-d03fe100-7e0e-11e9-9e7a-308f5eb70a84.png)

Kindly let me know , what was the issue i am committing..

Thanks,

**Comment by vymallesh** [comment]
@haithngn ,

Does Mailcore2 asks for OAuth implementation for Outlook,Yahoo etc.

**Comment by vymallesh** [comment]
In Mailcore documentation, you didn't mentioned such points regarding third party email apps.So we are getting issues , you (Mailcore) are supposed to provide the valid data.

It's my kind request to go through my issue.

**Comment by haithngn** [comment]
the solution already provided
