### ISSUE TITLE
Not able to receive emails in Outlook

### ISSUE THREAD

**Issue by vymallesh** [MailCore/mailcore2#1816]
Hello,

I am developing an email client application in iOS.

I can be able to login successfully through SMTP, where as i am not able to fetch emails from Outlook IMAP.

I am getting an error message says, "A stable connection to the server could not be established." UserInfo={NSLocalizedDescription=A stable connection to the server could not be established"

If i try to change any settings in IMAP session, i am getting an error message says, "Unable to authenticate with current session credentials"

Below are the configuration for SMTP and IMAP

//SMTP

    _outlookSession = [[MCOSMTPSession alloc] init];

    _outlookSession.username = @"dummy@outlook.com";

    _outlookSession.password = nil;

    _outlookSession.hostname = @"smtp-mail.outlook.com";

    _outlookSession.connectionType = MCOConnectionTypeStartTLS;

    _outlookSession.authType = MCOAuthTypeSASLLogin;

    _outlookSession.port = 587;

    _outlookSession.checkCertificateEnabled = false;

    _outlookSession.OAuth2Token = accessToken;

//IMAP

    session = [[MCOIMAPSession alloc]init];

    session.hostname = @"imap-mail.outlook.com";

    session.username = @"dummy@outlook.com";

    session.password = nil;

    session.port = 993;

    session.authType = MCOAuthTypeSASLLogin;

    NSLog(@"%@",accessToken);

    session.connectionType = MCOConnectionTypeStartTLS;

    session.checkCertificateEnabled = false;

I had tried with session.authType = MCOAuthTypeXOAuth2Outlook also, but no luck.

Any help would be appreciated.

Thanks,

**Comment by gnmmdk** [comment]
Hello, how did you solve it?
