### ISSUE TITLE
iOS 12: Non-public API Usage

### ISSUE THREAD

**Issue by dpanzer** [MailCore/mailcore2#1818]
I see there are various issues in the past similar to this, but here's a new one and I'm wondering if there is a workaround. We incorporate MailCore in our framework and then distribute that to clients. Here is the notice a client got today for the first time when TestFlight was processing a build: (Our framework is BlinkReceipt).

```
The app contains or inherits from non-public classes in Frameworks/BlinkReceipt.framework/BlinkReceipt: MCOIMAPIdentity, MCOIMAPSearchExpression, MCOIMAPSession, MCOIndexSet, MCOMessageParser . If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
```

Our clients have not had any problems in the past submitting apps with our framework.

**Comment by haithngn** [comment]
It seems something not clear we should contact Apple's support to get more information in detail I think.

**Comment by dpanzer** [comment]
I happened to be at WWDC today so I asked an Apple engineer and he instructed me to submit a case at https://feedbackassistant.apple.com, which I did, and he said he would follow up on that. But that was when I thought this was 100% a false positive on their side because I was focusing on the first sentence in the error message indicating that the `MCO*` classes conflict with private Apple classes, which I think is basically impossible.

Now, however, as I'm reading past issues in this repo and seeing that some _method_ names conflicted in the past, I'm paying more attention to the 2nd sentence in the error message that talks about _method_ names conflicting with "private APIs". So maybe the error message is just poorly worded and what's really going on is that some method names in those MCO* classes are suddenly conflicting with Apple's private methods, like it seems happened a few times with this library already...

**Comment by dpanzer** [comment]
I got to the bottom of this thanks to more helpful engineers from the App Review team. It turns out that those class names do, against all odds, match up exactly with internal Apple class names. But that is not the whole story. The problem arises from the fact that our framework weak-links a dynamic framework wrapper around MailCore, so that our clients can optionally include certain functionality or not.

When a client _does not_ pull in these additional dependencies such as MailCore, then the symbols remain weak linked and Apple's static analyzer cannot tell whether the app is using Apple's private version of these classes, or its own, and the build is rejected. But when a client _does_ pull in MailCore, then Apple has no problem realizing that everything is OK and the build succeeds. So we will factor our framework to avoid all this weak linking stuff.
