### ISSUE TITLE
MX Checks

### ISSUE THREAD

**Issue by CodaFi** [MailCore/mailcore2#182]
What do you think of this @dinhviethoa ?  Seems like it would be nice if check requests went on to ping a domain if a providers check failed.

**Comment by KieranMcGrady** [comment]
Sorry to reopen an old issue but I'm suddenly having a serious issue with ```VTMxRecordForHostname```. The ```res_search``` is failing and I'm unable to login to Gmail via OAuth in my live code. As I got it from here originally I'm not too familiar with it and having trouble debugging. Any ideas why it would suddenly stop working @mronge?

**Comment by KieranMcGrady** [comment]
Solved. Bad implementation on my part. Took some code from an issue here without fully understanding it and was passing the wrong hostname to the method. No idea why it worked and then suddenly stopped (it never should have worked) but solved now.
