### ISSUE TITLE
Getting error in Yahoo Login

### ISSUE THREAD

**Issue by David514** [MailCore/mailcore2#1821]
I am getting an error if i try to login with Yahoo account.Below are the SMTP and IMAP setup.

//SMTP

     smtpSession = [[MCOSMTPSession alloc] init];
     smtpSession.hostname = @"smtp.mail.yahoo.com ";
     smtpSession.username = @"test";
    smtpSession.password = @"testing";
    smtpSession.connectionType = MCOConnectionTypeStartTLS;
    smtpSession.authType = MCOAuthTypeSASLLogin;
    smtpSession.port = 587;

//IMAP

    session = [[MCOIMAPSession alloc]init];
    session.hostname = @"imap-mail.yahoo.com";
    session.username = @"test";
    session.password = @"testing";
    session.port = 993;
    smtpSession.connectionType = MCOConnectionTypeStartTLS;
    smtpSession.authType = MCOAuthTypeSASLLogin;
    

Error i am getting : Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo={NSLocalizedDescription=A stable connection to the server could not be established.

**Comment by haithngn** [comment]
@David514 ,
ref [IMAP server settings for Yahoo Mail](https://help.yahoo.com/kb/SLN4075.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS91cmw_c2E9dCZyY3Q9aiZxPSZlc3JjPXMmc291cmNlPXdlYiZjZD00JnZlZD0yYWhVS0V3aVhwUERWMl9EaUFoVUtrbkFLSGVFN0NKUVFGakFEZWdRSUFSQUImdXJsPWh0dHBzJTNBJTJGJTJGaGVscC55YWhvby5jb20lMkZrYiUyRlNMTjQwNzUuaHRtbCZ1c2c9QU92VmF3MF9HaGFydThEd3d4VTZIWnZWZWpZUA&guce_referrer_sig=AQAAAEyckkCmsKKQSdk33aPYxZKS1TOJaZ8xucxhPQob93vfEB5XvBxFm5QPmBJItA39BRosGoBwuG7fYJs5_jQWh12bfD01uw68DZmmAiA6eA00vc02DK_IENm-5dg26wTRhH8_9obiwo62LTOhr_UbBxLJA6lLn44ZqO-gP8BRBEDU)

**Comment by David514** [comment]
I would like to know connection type and auth type..

**Comment by haithngn** [comment]
@David514 , Mailcore can help you find-out host, port, ssl but you must try to others configuration's parameter.
ref https://github.com/MailCore/mailcore2/wiki/Providers-Syntax
