### ISSUE TITLE
你们都怎么做列表更新

### ISSUE THREAD

**Issue by wengxianxun** [MailCore/mailcore2#1822]
如题，假如邮件列表中间删除掉几封邮件都话，MCOIndexSet *uids = [MCOIndexSet indexSetWithRange:MCORangeMake(1,count)];设置的开始位置和数量会拉取不到正确的邮件列表，因为被删除的uid这个时候不会在列表里面导致数量不对等。

**Comment by haithngn** [comment]
English please mate :D
