### ISSUE TITLE
Airplane setup issue

### ISSUE THREAD

**Issue by biscuitgit** [MailCore/mailcore2#1828]
Hello,
I tried to setup Airplane (https://itunes.apple.com/gb/app/airplane-html-mail-sender/id1129404567) for sending HTML emails (Airplane uses MailCore).

With Apple Mail I had my Hostgator POP3 email accounts always configured 
using Port 465, TLS/SSL and "Password" as Authentication type.

I've tried some options in Airplane... 

<img width="328" alt="Screen Shot 2019-07-04 at 01 38 18" src="https://user-images.githubusercontent.com/11941428/60632245-7f9fa880-9dfc-11e9-8cee-74b210a29707.png">

... but always get the error message:

<img width="398" alt="Screen Shot 2019-06-29 at 17 37 55" src="https://user-images.githubusercontent.com/11941428/60632106-80840a80-9dfb-11e9-859e-70fa7a7ea378.png">

Can somebody help with the configuration? (the Airplane support can't)
Many thanks!

**Comment by biscuitgit** [comment]
The Airplane support mentioned that they use MailCore, and that I could probably get help in this forum. I really hope so.

**Comment by haithngn** [comment]
Airplane must support to solve this.
