### ISSUE TITLE
[macOS] Parser strips out HTML <audio> element

### ISSUE THREAD

**Issue by triton3** [MailCore/mailcore2#1830]
The html message body contains an embedded audio element using the `<audio>` tag. On macOS, the parser removes the `<audio>` tag when extracting the html rendering (interestingly, it retains it on iOS and Android). Is there a way to prevent it from removing this tag?

**Comment by haithngn** [comment]
could you please attach the html ?

**Comment by triton3** [comment]
I will add it as soon as I get a chance, but you can try any inline audio element with embedded data.
For the time being I overrode the `cleanHTMLForPart` method using custom `HTMLRendererDelegate` to bypass the default behavior, so that it does not strip out the <audio> tag:

````
class MyHTMLRenderingDelegate: NSObject, MCOHTMLRendererDelegate {
    #if os(OSX)
    /// Custom HTML cleaner - currently just passes the html string as is (because the default HTMLCleaner strips out <audio> tag)
    func abstractMessage(_ msg: MCOAbstractMessage!, cleanHTMLForPart html: String!) -> String! {
        return html
    }
    #endif
}

````

**Comment by haithngn** [comment]
@triton3 nice solved,
The default Template methods will not cover full tags so you should override for some specific cases. :)
