### ISSUE TITLE
error from server Optional(Error Domain=MCOErrorDomain Code=3 "Unable to parse response from server." UserInfo={NSLocalizedDescription=Unable to parse response from server.})

### ISSUE THREAD

**Issue by vk7063** [MailCore/mailcore2#1831]
I have generated app specific password too  but its coming same "Unable to parse response from server."
I installed mailcore through pod 
let imapsession = MCOIMAPSession()
        imapsession.hostname = "imap.mail.me.com"
        imapsession.port = 993
        imapsession.username = "xxxxxx@xxx.com"
          imapsession.password = "xxxx-xxxx-xxxx-xxxx"
     //   imapsession.oAuth2Token = token
       imapsession.authType = MCOAuthType.saslLogin
        imapsession.connectionType = MCOConnectionType.TLS
        let requestKind : MCOIMAPMessagesRequestKind =    MCOIMAPMessagesRequestKind.fullHeaders
        let folder : String = "INBOX"
        let uids : MCOIndexSet = MCOIndexSet(range: MCORangeMake(1, UINT64_MAX))
        
        let fetchOperation : MCOIMAPFetchMessagesOperation = imapsession.fetchMessagesOperation(withFolder: folder, requestKind: requestKind, uids: uids)
        
        fetchOperation.start { (err, msg, vanished) -> Void in
            print("error from server \(err)")
            print("fetched \(msg) messages")
        }

**Comment by haithngn** [comment]
I would like to see the domain name of your IMAP username.
And, could you please try?
 `imapsession.authType = .init(rawValue: 0)`
