### ISSUE TITLE
找不到头文件

### ISSUE THREAD

**Issue by feihuohua** [MailCore/mailcore2#1833]
iOS 使用pod导入，显示'MailCore/MailCore.h' file not found

**Comment by haithngn** [comment]
English please :D

**Comment by feihuohua** [comment]
that displays 'MailCore/MailCore.h' file not found ,when I pod this SDK by cocoa pod. but it is OK when one year ago.

**Comment by feihuohua** [comment]
> English please :D

that displays 'MailCore/MailCore.h' file not found ,when I pod this SDK by cocoa pod. but it is OK when one years ago.

**Comment by haithngn** [comment]
could you please try this:
`pod 'mailcore2-ios', :git => 'git@github.com:MailCore/mailcore2.git'`
