### ISSUE TITLE
how to use MCOAccountValidator?

### ISSUE THREAD

**Issue by borisyue** [MailCore/mailcore2#1835]
How to use MCOAccountValidator? I don't find the example in iOS/Mac demo.
When to produce the new release? I import the mailcore2 via the cocoapods. But I find it is old for 0.6.4. It not support the MCOAccountValidator. When I init the MCOAccountValidator, it is crash.

**Comment by haithngn** [comment]
@borisyue please try this:

`pod 'mailcore2-ios', :git => 'git@github.com:MailCore/mailcore2.git'`

The podspec files are now having a problem on the version number, we are considering to update   that files or release new MailCore2

**Comment by borisyue** [comment]
thanks. is there any example for MCOAccountValidator?

**Comment by borisyue** [comment]
@haithngn 
for your pod example, there is a error in below.

-> Pre-downloading: `mailcore2-ios` from `git@github.com:MailCore/mailcore2.git`
 > Git download
 > Git download
     $ /usr/bin/git clone git@github.com:MailCore/mailcore2.git
     /var/folders/s4/0s1s2fj517n5blcg1wr93bjh0000gn/T/d20190909-6187-2a9coi
     --template= --single-branch --depth 1
     Cloning into '/var/folders/s4/0s1s2fj517n5blcg1wr93bjh0000gn/T/d20190909-6187-2a9coi'...
     /Users/caibaocheng/.ssh/config line 4: garbage at end of line; "Enterprise"     
     fatal: Could not read from remote repository.
     
     Please make sure you have the correct access rights
     and the repository exists.

[!] Error installing mailcore2-ios
[!] Failed to download 'mailcore2-ios': [!] /usr/bin/git clone git@github.com:MailCore/mailcore2.git /var/folders/s4/0s1s2fj517n5blcg1wr93bjh0000gn/T/d20190909-6187-2a9coi --template= --single-branch --depth 1

Cloning into '/var/folders/s4/0s1s2fj517n5blcg1wr93bjh0000gn/T/d20190909-6187-2a9coi'...
/Users/caibaocheng/.ssh/config line 4: garbage at end of line; "Enterprise".
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by haithngn** [comment]
sorry @borisyue 
`pod 'mailcore2-ios', git: 'https://github.com/MailCore/mailcore2.git', branch: 'master'`

We do not have any example for MCOAccountValidator now, hope you try and make it happen :)
