### ISSUE TITLE
[iOS] Build fails using XCode 11.1 on macOS Catalina

### ISSUE THREAD

**Issue by triton3** [MailCore/mailcore2#1838]
Mailcore2 is linked as a static library for an iOS project, which worked fine for several years. I updated to macOS Catalina and now the project fails to build. Looks like it is searching for dependencies, and tries to re-download them, but fails to unzip.

Any suggestions on how to fix this? The final error it shows is `.../mailcore2/src/objc/utils/NSObject+MCO.mm:11:10: 'libetpan/libetpan.h' file not found`

Build logs below from XCode:

```
...
/bin/sh -c /Users/me/Library/Developer/Xcode/DerivedData/myproject-diiydhavkvwenodhngflzuofkhjh/Build/Intermediates.noindex/mailcore2.build/Debug-iphoneos/static\\\ mailcore2\\\ ios.build/Script-C6BA2B0A1705F4E6003F0E9E.sh

ctemplate-ios, installed: none, required:
Downloading ctemplate-ios-
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   322  100   322    0     0    715      0 --:--:-- --:--:-- --:--:--   713
[ctemplate-ios-.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ctemplate-ios-.zip or
        ctemplate-ios-.zip.zip, and cannot find ctemplate-ios-.zip.ZIP, period.
/Users/me/Documents/XcodeProjects/myProject-iOS/myProject-iOS/Submodules/third-party/mailcore2/scripts/include.sh/build-dep.sh: line 328: cd: ctemplate-ios-: No such file or directory
libetpan-ios, installed: none, required:
Downloading libetpan-ios-
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   320  100   320    0     0    651      0 --:--:-- --:--:-- --:--:--   650
[libetpan-ios-.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of libetpan-ios-.zip or
        libetpan-ios-.zip.zip, and cannot find libetpan-ios-.zip.ZIP, period.
/Users/me/Documents/XcodeProjects/myProject-iOS/myProject-iOS/Submodules/third-party/mailcore2/scripts/include.sh/build-dep.sh: line 328: cd: libetpan-ios-: No such file or directory
tidy-html5-ios, installed: none, required:
Downloading tidy-html5-ios-
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   324  100   324    0     0    702      0 --:--:-- --:--:-- --:--:--   702
[tidy-html5-ios-.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of tidy-html5-ios-.zip or
        tidy-html5-ios-.zip.zip, and cannot find tidy-html5-ios-.zip.ZIP, period.
/Users/me/Documents/XcodeProjects/myProject-iOS/myProject-iOS/Submodules/third-party/mailcore2/scripts/include.sh/build-dep.sh: line 328: cd: tidy-html5-ios-: No such file or directory
```

**Comment by triton3** [comment]
Could this be because of a change in `defaults read` behavior on macOS Catalina? I found this online:

```
WARNING: The defaults command will be changed in an upcoming
               major release to only operate on preferences domains. General
               plist manipulation utilities will be folded into a different
               command-line program.
```

**Comment by skillsfactory** [comment]
Same problem here with OS X Framework, have you solved it?
I’m seriously thinking to downgrade to 10.14.....

**Comment by skillsfactory** [comment]
I've "solved" with a workaround:
**1** - Picked up an old Externals folder and copied it outside mailcore2-master
**2** -Then added these headers path in **mailcore2 project**:
"$(SRCROOT)/../src/core/basetypes/icu-ucsdet/include"
"$(SRCROOT)/../src"

**3** -This headers path **into static mailcore2**:
"$(SRCROOT)/../../Externals/ctemplate-osx/include"
"$(SRCROOT)/../../Externals/libetpan-osx/include"
"$(SRCROOT)/../src"
"$(SRCROOT)/../src/core/basetypes/icu-ucsdet/include"

**4** -And these libraries path **into static mailcore2**: 
"$(SRCROOT)/../../Externals/ctemplate-osx/lib"
"$(SRCROOT)/../../Externals/libetpan-osx/lib"

Not so elegant, but it works...

**Comment by triton3** [comment]
Yes I had tried that but the run script in Xcode was overwriting them again and trying to rebuild dependencies. For the time being, I updated the build script as follows:

Script location: 
`mailcore2/scripts/include.sh/build-dep.sh`

Changes below:

Lines **16**, **171**, **318**:  Replace
```
version="`defaults read "$versions_path" "$name" 2>/dev/null`"
``` 
with
```
version="`/usr/libexec/PlistBuddy -c \"print :"$name"\" "$versions_path"  2>/dev/null`"
```

Lines **311**:  Replace
```
installed_version="`defaults read "$installed_versions_path" "$name" 2>/dev/null`"
``` 
with
```
installed_version="`/usr/libexec/PlistBuddy -c \"print :"$name"\" "$installed_versions_path"  2>/dev/null`"
```

**Comment by alamrezoanul** [comment]
@triton3 , thanks a lot! it worked for me

**Comment by rgbworld** [comment]
Just a note that I was able to resolve a **macOS** build failure by removing `-lcrypto -lssl` from "Other Linker Flags".

The solution is here #1511 thanks to @bgreenlee. The _incorrect_ instructions I followed were:

**Mac static library**
Set 'Other Linker Flags' under Build Settings: -lctemplate -letpan -lxml2 -lsasl2 -liconv -ltidy -lz -lc++ -stdlib=libc++ -ObjC -lcrypto -lssl -lresolv

Please update the ReadMe:
https://github.com/MailCore/mailcore2/blob/master/build-mac/README.md

**Comment by haithngn** [comment]
thanks @rgbworld

**Comment by karam28** [comment]
I am facing the same issue i.e.  .../mailcore2/src/objc/utils/NSObject+MCO.mm:11:10: 'libetpan/libetpan.h' file not found.
I am using macOS Sonoma 14.3 (23D56) , Xcode  15.2 and Objective C iOS project.

I download the code but there is no external folder in the code base. Please help me, I aim struggling with this from past 5 days.
