### ISSUE TITLE
mailcore2-android-4.aar not comptible with 64-bit version 

### ISSUE THREAD

**Issue by ShwetaChauhan18** [MailCore/mailcore2#1840]
mailcore2-android-4.aar not comptible with 64-bit version. However, we are not able to release app on playstore because of this issue. 
Can you help us for this problem ?

**Comment by mfussi** [comment]
We are facing the same issue. Is there a way to build the mailcore library manually with the additional x86_64 bit aebi?

**Comment by minhbui** [comment]
Same problem here. Had to disable 64-bit support on our app to be able to release it on Google Play. A fix would be highly appreciated.

**Comment by YueMuc** [comment]
I'm having the same issue.

**Comment by ShwetaChauhan18** [comment]
Yes, we had to disable 64- bit support on our app to release app on Play Store. It would be great, if you fix this issue.

**Comment by hhrowal** [comment]
I was able to get this working a couple years ago. Time constraints prevent me from trying again with the latest version of the code and NDK, but I remember rebuilding all the support libraries first:

ctemplate-android-3.zip
cyrus-sasl-android-4.zip
iconv-android-1.zip
icu4c-android-3.zip
libetpan-android-7.zip
libxml2-android-3.zip
openssl-android-3.zip
tidy-html5-android-3.zip

I updated all the build.sh files to add a x86_64 build step and I updated all the Android.mk files to add -fPIC to the LOCAL_CFLAGS (this took care of the relocation errors).

Once those were all built, I made the same changes to mailcore2 itself, making sure it linked all the newly built libraries. 

I hope this helps.

**Comment by minhbui** [comment]
Any updates on this? We're having trouble compiling openssl currently.
@ShwetaChauhan18 did you find any solution for this?

**Comment by vonox7** [comment]
Fyi: https://github.com/MailCore/mailcore2/pull/1912 explains the build pipeline on Android that works also in 2021, also with 64 bit ARM devices.

**Comment by haithngn** [comment]
https://github.com/MailCore/mailcore2/pull/1912 closed
