### ISSUE TITLE
MacOS 10.15 Catelina not found <libetpan/libetpan.h> 

### ISSUE THREAD

**Issue by chancelee** [MailCore/mailcore2#1843]
Beacause of MacOS 10.15 Catelina not found <libetpan/libetpan.h> , the mailcore2.project under the  "bulild-Mac"  directory  faild

**Comment by GarabaIgor** [comment]
Solution: #1838

**Comment by rgbworld** [comment]
I am experiencing compile/build errors related to External dependencies for `libetpan` and `lctemplate`. The "Externals" directory does not unzip the files as shown in #1842

macOS: 10.11
Xcode 12 beta
Target: static mailcore2 osx

I tried moving the Externals directory outside the mailcore directory as discussed here:
https://github.com/MailCore/mailcore2/issues/1838#issuecomment-540549712

That resolved the building of the **mac static library** (libMailcore.a).

Now when building my project, I receive the error:
`Library not found for -lctemplate`

`ld: warning: directory not found for option '-L/Users/ME/Documents/Development/mac_dev/Projects/MyApp/MyApp/MailCore2/build-mac/../Externals/ctemplate-osx/lib'`

So, apparently the build is not finding the modified location for Externals.
- Any suggestions on how to resolve the `Library not found` error?
- Has anyone been able to build with XCode 12 and macOS 11 yet?
- Please correct spelling of "Catelina" to "Catalina" in the issue title.

**Comment by haithngn** [comment]
fixed: https://github.com/MailCore/mailcore2/issues/1838
