### ISSUE TITLE
'init' is unavailable

### ISSUE THREAD

**Issue by chancelee** [MailCore/mailcore2#1844]
MCOAttachment *a = [[MCOAttachment alloc]init]; 

The Xcode compile error   'init' is unavailable

**Comment by chancelee** [comment]
Build Environment

MacOS 10.15 Catelina
Xcode 11.2.1
Build System is Legacy Build System


I have build mailcore2 success and import libMailCore-ios.a sucessfully!


MCOAttachment *a = [[MCOAttachment alloc]init];
---
@interface MCOAttachment : MCOAbstractPart

@implementation MCOAbstractPart {
    mailcore::AbstractPart * _part;
}

#define nativeType mailcore::AbstractPart

- (mailcore::Object *) mco_mcObject
{
    return _part;
}

**- (instancetype) init
{
    self = [self initWithMCPart:NULL];
    MCAssert(0);
    return nil;
}**
---- 
init realy exisit ,Why 'init' is unavailable

**Comment by haithngn** [comment]
@chancelee this constructor was hidden to make avoid creat new attachment without any content (NULL).
You should allocate new MCOAttachment by using their constructors.
