### ISSUE TITLE
issues connecting to icloud mail servers

### ISSUE THREAD

**Issue by dstocking** [MailCore/mailcore2#1845]
I use spark (uses Mailcore2) for my email. Recently, I started having problems with syncing my folders for my iCloud account and thought it might be specific to this app, but then I noticed the same exact issue with MailSpring (also using Mailcore2). This happens on multiple devices as well (iphone and mac). I think there might be an issue with mailcore connecting to iCloud right now. Both Apple Mail and Thunderbird work perfectly fine.

- I am using an app specific password with 2fa turned on.
- I do not see the issue with other mail providers.

Can anyone else confirm issues with connecting to iCloud accounts recently using a mailcore2 integrated app?

**Comment by dstocking** [comment]
- Mac (Catalina 10.15.1, 2.3.15.667, Mailspring 1.7.2)
- iOS (13.2.3, Spark 2.5.0.233)

**Comment by dstocking** [comment]
Can also confirm issue in Airmail 3 on Mac.... Also using MailCore...

**Comment by haithngn** [comment]
I think your network is having issue with iCloud, let check them, you might be blocked by iCloud security system.

**Comment by dstocking** [comment]
Nope - that was not the issue. Spark found out that the issue had to do with having emails with blank subjects lines.

**Comment by haithngn** [comment]
Could you share this icloud account with app password to me haithngn@gmail.com ?

**Comment by guidedways** [comment]
@dstocking so was the issue with MailCore?
