### ISSUE TITLE
Untitled attachment causes crash in Swift when attempting to implicitly unwrap filename

### ISSUE THREAD

**Issue by mattmaddux** [MailCore/mailcore2#1853]
When using Swift MCOAttachment's filename property (inherited from MCOAbstractPart, API doc[ here](http://libmailcore.com/api/objc/Classes/MCOAbstractPart.html#//api/name/filename)) is declared as an implicitly unwrapped optional. But I'm encountering an email where the attachments are unnamed, and attempting to access the property causes a crash with the message:

`Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`

Looking at the plain text rendering of the message it lists the attachments like this:

```
- Untitled, 492 bytes
- Untitled, 1.2 KB
```

How do I handle this without a crash?

**Comment by mattmaddux** [comment]
Okay, I realized you can just cast an implicitly unwrapped optional back to a regular optional, like below. That solves the crash. But maybe it would be better to return an optional since it is possible for the attachment to not have a name.

`let filename: String? = attachment.filename as String?`

**Comment by dinhviethoa** [comment]
@mattmaddux could you create a pull request to do that?
Thank you!

**Comment by haithngn** [comment]
fixed at  https://github.com/MailCore/mailcore2/commit/7ee423569e31b373702866c20a64e36156fa5a30
