### ISSUE TITLE
iOS - AppStore Rejection

### ISSUE THREAD

**Issue by hosy** [MailCore/mailcore2#1859]
Do you know about problems submitting an App with your Framework to Apple AppStore?

ITMS-90338: Non-public API usage - The app references non-public symbols in ****: _tidyBufAppend, _tidyBufFree, _tidyBufInit, _tidyCleanAndRepair, _tidyCreate, _tidyOptSetBool, _tidyOptSetInt, _tidyParseBuffer, _tidyRelease, _tidySaveBuffer, _tidySetCharEncoding, _tidySetErrorBuffer

**Comment by dinhviethoa** [comment]
Did you link against libtidy?
There's a convenient version of it here: https://github.com/dinhviethoa/tidy-html5

**Comment by hosy** [comment]
Thank you. Just found an answer for my question:
https://github.com/MailCore/mailcore2/issues/1037
