### ISSUE TITLE
Using MailCore to track only some email addresses

### ISSUE THREAD

**Issue by zulfishah** [MailCore/mailcore2#1868]
Hi,
I am looking into using the MailCore2 framework in my app to track incoming emails from a list of email addresses. A couple of things I'm not sure how to implement:
- how do you check for emails with a given date-range? Suppose I only want emails from the last year? Would I have to 
- how to check emails from a certain timestamp, or token? Suppose I downloaded all the emails already and save them somewhere on device. Next time I check, I would only want to see the difference between now and the last time I checked (can be saved as a timestamp or token). Is that possible? Having looked at the MCOIMAPSession header file, I can't say for sure. The only example I've seen is to download the last X number of emails, which wouldn't help in this case. How else would you parse through all the 'new' emails? Do you keep downloading ALL emails every time and then diffing the two sets? 

Would be great to learn more about this library, especially when I'm just starting out and don't want to go down rabbit holes. 
Thanks!

**Comment by zulfishah** [comment]
One more thing (if someone has the time to answer):
- for Gmail, I read somewhere that you need to enable a "less secure apps" setting for MailCore2 to work. Is that correct?

**Comment by dinhviethoa** [comment]
I think with the search API, you can query a date range.

If you don't go through the process of getting approved by Google, you get categorized as for "less secure apps", which means that the user needs to create a app-specific password.
I think using MailCore or any other framework will have the same problem.
