### ISSUE TITLE
Linker error: Undefined symbol: _OBJC_CLASS_$_MCOAddress etc...

### ISSUE THREAD

**Issue by tt556** [MailCore/mailcore2#1873]
I got these linker error.
![スクリーンショット 2020-05-04 16 50 54](https://user-images.githubusercontent.com/35441591/80945770-85548900-8e27-11ea-866d-bd109be7a815.jpg)
![スクリーンショット 2020-05-04 16 51 04](https://user-images.githubusercontent.com/35441591/80945773-87b6e300-8e27-11ea-957a-e83cbb5f4225.jpg)
I did "pod update", "clean build folder" but not work.
I put "-framework mailcore" on "Other Linker Flags" but Xcode showed "mailcore framework not found"
I don't know how to link...

**Comment by ForeverZhangXun** [comment]
You should add $(inherited) to "Other Linker Flags"

**Comment by ForeverZhangXun** [comment]
and -objc

**Comment by tt556** [comment]
I added, still not work...

**Comment by haithngn** [comment]
sorry for replying @tt556 let me know if you still facing this.

**Comment by iHTCboy** [comment]
I added, still not work...

**Comment by iHTCboy** [comment]
Apple's M1 Architecture no't Support，use build for Mac (Rosetta)
