### ISSUE TITLE
Fetching all mails

### ISSUE THREAD

**Issue by ninad458** [MailCore/mailcore2#1881]
Is there any way to download all the mails from the mailbox? The order of mails is about 30,000.
Getting around 600.

```
final IMAPFetchMessagesOperation messagesOperation = imapSession.fetchMessagesByUIDOperation(folder, requestKind,
                indexSet);

messagesOperation.start(new OperationCallback() {
           @Override
            public void succeeded() {
                 final List<IMAPMessage> messages = messagesOperation.messages();
            }
});

```

**Comment by haithngn** [comment]
@ninad458 ,
We have 3 methods to fetch the messages ref http://libmailcore.com/api/objc/Classes/MCOIMAPSession.html .
Hope you will compose the request to fetch all your messages.
