### ISSUE TITLE
[Bug] - 

### ISSUE THREAD

**Issue by zhaofeiyue** [MailCore/mailcore2#1882]
I use pod install，then，I find this error:  [!] 'mailcore2-ios' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.

**Comment by Poreis** [comment]
Yes its still happening , it says its fixed but it really isn't.

**Comment by haithngn** [comment]
You guys please try this
```
pod 'mailcore2-osx', :git => 'https://github.com/MailCore/mailcore2.git', :tag => '0.6.4'
```

We are now updating the spec to CocoaPods.

**Comment by anauk** [comment]
i have the same error after updating my xcode to 15v

**Comment by shukerullah** [comment]
I am also experiencing the same error. It was working fine until yesterday, but now I am facing this issue.

**Comment by anauk** [comment]
I’m still facing this issue and don’t know how fix it

**Comment by ju135** [comment]
I don't think this is the reason why you run into errors. The source of the pod is hosted via [etpan.org](https://etpan.org) which is currently down. (see the [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/4/c/a/mailcore2-ios/0.6.3/mailcore2-ios.podspec.json#L13C14-L13C82))

**Comment by anauk** [comment]
Ok, thanks for the clarification.
