### ISSUE TITLE
Crash in +[MCONNTPGroupInfo load]

### ISSUE THREAD

**Issue by srinadh-k** [MailCore/mailcore2#1884]
Hello all,

I got the following crash for iOS once in a while and got a log from firebase. Can anyone please help?

Crashed: Thread
0  libsystem_kernel.dylib         0x19b16edf0 __pthread_kill + 8
1  libsystem_pthread.dylib        0x19b08e930 pthread_kill + 228
2  libsystem_c.dylib              0x19b01cba4 abort + 104
3  XfinityConnect                 0x100951ea0 +[MCONNTPGroupInfo load] + 2217772
4  XfinityConnect                 0x100963818 mailcore::IMAPSession::setup() + 2289828
5  XfinityConnect                 0x100963a2c mailcore::IMAPSession::connect(mailcore::ErrorCode*) + 2290360
6  XfinityConnect                 0x1009643a0 mailcore::IMAPSession::loginIfNeeded(mailcore::ErrorCode*) + 2292780
7  XfinityConnect                 0x100965f5c mailcore::IMAPSession::fetchAllFoldersWithStatus(mailcore::ErrorCode*) + 2299880
8  XfinityConnect                 0x1009497b0 mailcore::IMAPFetchFoldersWithStatusOperation::main() + 2183228
9  XfinityConnect                 0x10095c4e0 mailcore::OperationQueue::runOperations() + 2260332
10 libsystem_pthread.dylib        0x19b08d8fc _pthread_start + 168
11 libsystem_pthread.dylib        0x19b0959d4 thread_start + 8

**Comment by haithngn** [comment]
@srinadh-k , unfortunately, we cannot do any investigation with your logs.

**Comment by srinadh-k** [comment]
@haithngn i have only this information from firebase crashlytics let me know what else you required
