### ISSUE TITLE
[Enhancement] - Replace backticks with quotes in LICENCE

### ISSUE THREAD

**Issue by eva-barczykowska** [MailCore/mailcore2#1892]
**In licence we have the phrase AS IS, which is surrounded by backticks on the left and quotes on the right**

```

**Actual outcome**
``AS IS''



**Expected outcome**
"AS IS"
In LICENCE we should have the phrase AS IS surrounded by quotes from both sides.


```

**Comment by haithngn** [comment]
update https://github.com/MailCore/mailcore2/commit/1434761709b4d9dd5acc5b7185a3b32aa4845ba8
