### ISSUE TITLE
Error: Showing All Messages https://github.com/MailCore/mailcore2 has no Package.swift manifest for version 0.6.4

### ISSUE THREAD

**Issue by sutefu23** [MailCore/mailcore2#1894]
Hi. Thank you for developing great package!

I follow this guidance using Swift Package Manager.
https://github.com/MailCore/mailcore2/blob/master/build-mac/README.md

> 1 . In Xcode click File -> Swift Packages -> Add Package Dependency...
> 2. Paste the following URL: https://github.com/MailCore/mailcore2

I can go to step 2 easily but when I click "next" button , the following error has been occurred every time.

> Showing All Messages https://github.com/MailCore/mailcore2 has no Package.swift manifest for version 0.6.4

I tried specify other version but same error was occurred.

Do you have any help?
Thank you.

Xcode 12.0
Swift 5.3.1
MacOS Big Sur

**Comment by mjbellantoni** [comment]
It looks like the manifest is only available on the master branch as of this writing.

**Comment by sutefu23** [comment]
Hi, Matthew.
Wow! I did it.
I really appreciate for you.

When I import Package, I've just select 'version' as by default.
I had to select 'Branch master'.

Thank you so much.

![ScreenShot2020-12-14 15 13 34](https://user-images.githubusercontent.com/16435468/102046716-33dd9500-3e1f-11eb-851e-e0c8d353591a.png)
