### ISSUE TITLE
[Bug] - Build fails with Carthage on Big Sur with Xcode 12.2 - fatal error: 'libetpan/libetpan.h' file not found

### ISSUE THREAD

**Issue by jraymonds86** [MailCore/mailcore2#1897]
This seems to have popped up in the past under different circumstances but currently the build is failing with Carthage using:

update --platform macosx

The error seems to be sourced back to this comment in the log...

fatal error: 'libetpan/libetpan.h' file not found

This still works fine on Mojave with Xcode 11.3.1 so it could be something creeping in due to Apple silicon support but that is just a guess.

**Comment by haithngn** [comment]
@jraymonds86 

Could you please try this and hope it will help you:

#### Cartfile
```
github "MailCore/mailcore2" "master"
```

#### Command 
```
carthage update --platform osx
```

if you still face with this " **fatal error: 'libetpan/libetpan.h' file not found** "

try to install libetpan using brew:
```
brew install libetpan
```

**Comment by jraymonds86** [comment]
I have since moved to SPM (instead of Carthage). Similar issue with the only fix using the "master" branch.

**Comment by haithngn** [comment]
@jraymonds86 thank you for updating, so could we close this issue?

**Comment by jraymonds86** [comment]
Close with a work around to use the master branch.
