### ISSUE TITLE
[Issue] - Not able to setup in my android project

### ISSUE THREAD

**Issue by PrantikMondal** [MailCore/mailcore2#1900]
**Summary**
Documentation of the android setup is not clear enough for me. Please help me with the setup.

**Platform(s)**
```
<Android>
```

**Happens on Mail Server**
```
<Gmail>
<iCloud>
```

**Piece of code**
```
$ export ANDROID_SDK=/path/to/android-sdk
$ export ANDROID_NDK=/path/to/android-ndk


where to add the above code?
and what to do next?
```

**Comment by haithngn** [comment]
please follow new instruction to make android lib, tks
