### ISSUE TITLE
[Bug] - Swift Package Manager to support minimum v9

### ISSUE THREAD

**Issue by jboisjo** [MailCore/mailcore2#1901]
**Summary**
I'm facing an issue with my CI using Swift Package Manager

The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'MailCore2' from project 'MailCore2')

**Platform(s)**
```
<iOS>
```

Can you update the Package.swift file to support minimum v9 (This will help others too since Xcode 12+ supports minimum v9+

Package.swift
let package = Package(
    name: "MailCore2",
    platforms: [
        .iOS(.**v9**), .macOS(.v10_10)
    ], ...

**Comment by jboisjo** [comment]
any help?????

**Comment by haithngn** [comment]
Close https://github.com/MailCore/mailcore2/commit/ddd21caf4297cc5568d9b1b84e5085637c2ee110
