### ISSUE TITLE
How to import a certificate file to authenticate with mail server

### ISSUE THREAD

**Issue by fatenumber25** [MailCore/mailcore2#1909]
Hello, Mr. Hai and Mr. Hoa.

I am making an iOS App to receive and send mail for my company. For security reasons, the company's mail server uses a firewall to block access from outside of the company. Can you tell me how to import the certificate file (this certificate is also used on the PC to authenticate with the server) into the app and set mailcore2 to use that certificate to access with the mail server?

Em chào anh Hải và anh Hòa, do trình độ tiếng anh của em không được tốt, không biết đoạn trên có truyền đạt được ý không nên em xin phép viết thêm tiếng Việt.

Em đang làm App IOS dùng để nhận và gửi mail cho công ty của em. Vì lý do bảo mật nên mail server của công ty dùng firewall để block truy cập từ ngoài công ty. 2 anh cho em hỏi có cách nào để chèn file chứng chỉ (Certificate, chứng chỉ này cũng dùng trên PC để xác thực với server) vào trong app và thiết lập để mailcore2 dùng chứng chỉ đó để truy cập với mail server không ạ?

**Comment by haithngn** [comment]
@fatenumber25 

Could you show me the way you are authorizing the mail server in MailCore2 and what is logs you received from MailCore's logger?

**Comment by fatenumber25** [comment]
@haithngn Thank you for quick replied. The problem is I don't know how to setting certificate file to use with mailcore. So ofcourse there is no error from mailcore. For now I just convert CRT file to DER file and import it to IOS project.

Please tell me if there is a way to setting certificate file with mailcore.

**Comment by haithngn** [comment]
@fatenumber25 Unfortunately, there is no implement for that.

**Comment by fatenumber25** [comment]
I see....so there is no way to do. Thank you for replied.
