### ISSUE TITLE
[Bug] - Plans for Apple's M1 Architecture Support?

### ISSUE THREAD

**Issue by vinhqn** [MailCore/mailcore2#1941]
Dear @dinhvh 

I have problem building mailcore2 on Apple's M1 Architecture, can mailcore2 update to support Apple's M1 Architecture?

ld: in /Users/vinhnguyen/whpmail/Pods/mailcore2-ios/lib/libMailCore-ios.a(MCONNTPFetchOverviewOperation.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/vinhnguyen/whpmail/Pods/mailcore2-ios/lib/libMailCore-ios.a' for architecture arm64

image : https://drive.google.com/file/d/1YzlMP01c4wvqagbd3y-SKmG-it24uW38/view?usp=sharing

**Comment by crasholo** [comment]
+1 for this. I had to turn off mailcore2 usage from my iOS projects (without Rosetta support). 
I hope to have news soon. 
Thanks

**Comment by pedrosakey** [comment]
🔝 hello same issue here, would it be possible to give an estimation about when it could be ready or should I try an alternative solution? 
Many thanks 🙏

**Comment by dinhvh** [comment]
I'll find some time to get the dependencies built.

The issue is that we need to build the dependencies for arm64.

**Comment by kyungkoo** [comment]
#1938

**Comment by dinhvh** [comment]
Could you try with the latest master?
The build should be fixed now.

**Comment by dan-ryan** [comment]
@dinhvh 
The Master branch doesn't work for me: https://ibb.co/Sy1Z62Z

**Comment by mpdifran** [comment]
Yeah `master` doesn't work for me either on macOS or simulator.

**Comment by TXB444** [comment]
Are there any plans of getting this working anytime soon?

**Comment by vikdenic** [comment]
Did anyone ever find a MailCore solution that builds for Arm64 / doesn't require Rosetta?
