### ISSUE TITLE
linked against modern SDK, VOIP socket will not wake error.

### ISSUE THREAD

**Issue by guidedways** [MailCore/mailcore2#1955]
When I run an iOS 16 app linked with MailCore, I see this:

```
libsp.dylib`spd_checkin_socket.cold.1:
    0x1f8628364 <+0>:  adrp   x8, 144849
    0x1f8628368 <+4>:  adrp   x9, 0
    0x1f862836c <+8>:  add    x9, x9, #0xa3f            ; "Linked against modern SDK, VOIP socket will not wake. Use Local Push Connectivity instead"
    0x1f8628370 <+12>: str    x9, [x8, #0x400]
->  0x1f8628374 <+16>: brk    #0x1
```

`Thread 20: EXC_BREAKPOINT (code=1, subcode=0x1f8628374`

This isn't happening on earlier iOS versions.

**Comment by guidedways** [comment]
It seems to be due to this line when `ConnectionTypeTLS` is set as the connection type (in MCIMAPSession.cpp):

```
        case ConnectionTypeTLS:
        r = mailimap_ssl_connect_voip(mImap, MCUTF8(mHostname), mPort, isVoIPEnabled());
```

**Comment by guidedways** [comment]
Seems like `mVoIPEnabled` is set to `true` by default, needs to be turned off when creating a new session on iOS 16.

**Comment by ruansunkel** [comment]
Hi, thank you for this, I got this error as well on iOS 16.
What worked for me was the following:
MCOIMAPSession *imapSession = [[MCOIMAPSession alloc] init];
imapSession.voIPEnabled = false;

**Comment by rokas-ambrazevicius** [comment]
``` 
var session = MCOIMAPSession()
session.isVoIPEnabled = false
```

Works on Xcode 14 and iOS 16 👍
