### ISSUE TITLE
[Bug] - Crash when running to iOS16 with Xcode14

### ISSUE THREAD

**Issue by MuXingX** [MailCore/mailcore2#1959]
when i start use 

    [fetchOperation start:^(NSError * error, NSArray * fetchedMessages, MCOIndexSet * vanishedMessages) {
        if(error) {
            NSLog(@"Error downloading message headers:%@", error);
        }
    }];

it crash。
my Xcode version is Xcode14，iOS version is iOS16。
if i running to iOS16 with Xcode13 or running to iOS15 with Xcode14, it worked.

**Comment by guidedways** [comment]
@MuXingX see this: https://github.com/MailCore/mailcore2/issues/1955

**Comment by MuXingX** [comment]
Thank you very much

**Comment by haithngn** [comment]
Closed by [Workaround](https://github.com/MailCore/mailcore2/issues/1955)
