### ISSUE TITLE
[Bug] - Fails to install with SPM

### ISSUE THREAD

**Issue by Mrteller** [MailCore/mailcore2#1961]
**On attempt to add package to Xcode project fails with error:**
failed downloading 'https://downloads.maddux.cloud/mailcore2-apple-xcframework/MailCore...'
**Platform(s)**
```
<iOS>
```

**Comment by haithngn** [comment]
fixed: https://github.com/MailCore/mailcore2/pull/1949

@Mrteller plz check

**Comment by Mrteller** [comment]
Thank for such a quick response.
I’ll check as soon as I can.
