### ISSUE TITLE
[Bug] - iOS app crash with Xcode 14 and iOS 16 because of deprecated api - kCFStreamNetworkServiceTypeVoIP

### ISSUE THREAD

**Issue by rjvishnu87** [MailCore/mailcore2#1964]
**Summary**
My iOS app is getting crashed when I build it from Xcode 14 & iOS 16. 
This is because of the deprecated api usage "kCFStreamNetworkServiceTypeVoIP"
This should not be used with the new Xcode 14. 

**Platform(s)**
```
< iOS >
```

**Happens on Mail Server**
```
<All>

```

**Piece of code**
```
kCFStreamNetworkServiceTypeVoIP
```

**Actual outcome**
app is getting crashed. 

Application Specific Information:
Linked against modern SDK, VOIP socket will not wake. Use Local Push Connectivity instead

**Connection Logs**
```
Linked against modern SDK, VOIP socket will not wake. Use Local Push Connectivity instead

```

**Expected outcome**
app should not get crashed. 

**Link to sample code on GitHub reproducing the issue (a full Xcode project):**
```
```

**Comment by zhangcx627** [comment]
`session.isVoIPEnabled = false` worked for me.
[[#1955](https://github.com/MailCore/mailcore2/issues/1955)]

**Comment by rjvishnu87** [comment]
yes, for me also worked, thanks.

**Comment by rajulonka123** [comment]
is there any other solution for "Linked against modern SDK, VOIP socket will not wake. Use Local Push Connectivity instead".
Thanks in advance.
