### ISSUE TITLE
Implement validation of email account

### ISSUE THREAD

**Issue by dinhviethoa** [MailCore/mailcore2#236]
**input**

- email / password

or

- email / password
- list of imap (or pop) account
- list of smtp accounts

**output**

- imap server (or pop server)
- login
- password

- smtp server
- login password

**Comment by DrChrispoper** [comment]
Hi, I would like to help with this are there any specifications on how to go with it?
rlaferia was suggesting adding to MCOIMAPSession but if it is to test SMTP too it might not be the best way.
I was thinking of going with something new like MCOAccountValidator and having MCOMailProvider, MCOIMAPSession and MCOSMTPSession as properties of that class. 
Then using like this:

```
self.accountVal = [[MCOAccountValidator alloc]init];
self.accountVal.email = username;
self.accountVal.password = password;
    
[self.accountVal imapStart:^(NSError *error) {
    if (error == nil) {
        //IMAP is ok
    } 
}];

[self.accountVal smtpStart:^(NSError *error) {
    if (error == nil) {
        //SMTP is ok
    }
}];
 ```
With imapStart and smtpStart using checkOperations from MCOIMAP/SMTPOperation.

**Comment by dinhviethoa** [comment]
```
@interface  MCOAccountValidator

@property (nonatomic, copy) NSString * email; /* for SMTP */
@property (nonatomic, copy) NSString * username;
@property (nonatomic, copy) NSString * password;
@property (nonatomic, copy) NSString * OAuth2Token;

@property (nonatomic, retain) NSArray * /* MCONetService */ imapServers;
@property (nonatomic, retain) NSArray * /* MCONetService */ popServers;
@property (nonatomic, retain) NSArray * /* MCONetService */ smtpServers;

// result
@property (nonatomic, retain, readonly) MCONetService * imapServer;
@property (nonatomic, retain, readonly) MCONetService * popServer;
@property (nonatomic, retain, readonly) MCONetService * smtpServer;
@property (nonatomic, retain, readonly) NSError * imapError;
@property (nonatomic, retain, readonly) NSError * popError;
@property (nonatomic, retain, readonly) NSError * smtpError;

- (void) start:(void (^)(void))completionBlock;

@end
```

This class will create the session it needs.
the input array might be nil if it doesn't need to be checked.
The MCOAccountValidator will test everything given as input.

**Comment by DrChrispoper** [comment]
I have a question
There can be different MX records for one hostname but could there be different providers for those MX records?
Logical answer would be no but someone might know of an exception. In which case it should be handled.

**Comment by dinhviethoa** [comment]
Just use - (MCOMailProvider *) providerForMX:(NSString *)hostname and use the first provider that's not nil. We shouldn't take care of weird cases for now.

**Comment by DrChrispoper** [comment]
Other question :)
Should/Can I be using an underlying C++ class like the other classes?
I've managed to wrapped my mind about how but I'm using sessions to test the settings and it looks like I would need to handle the completion callbacks of the check operations myself to not have to use the MCO classes? 
Or is there something I am failing to see?

**Comment by dinhviethoa** [comment]
Sure. You should use an underlying C++ class. I'm not sure what you mean but at C++ level, the operation callbacks is an interface that needs to be implemented.
AccountValidator will probably implement the operation callbacks.

**Comment by DrChrispoper** [comment]
Can we add an ErrorCode that we can use when no info was found (for IMAP or POP or SMTP) to avoid having to NSError as NULL and then MCONetService NULL too?

The validator is working, should I just do a pull request and you can give feedback there?

**Comment by dinhviethoa** [comment]
Sure. Please add ErrorNoValidServerFound.
You can send the pull request and we'll take it from here.
Thanks!

**Comment by bu2zhouzhu** [comment]
How should I validate email account in Android?
