### ISSUE TITLE
Error sending email:Error Domain=MCOErrorDomain Code=1 "The operation couldn’t be completed. (MCOErrorDomain error 1.)

### ISSUE THREAD

**Issue by neowinston** [MailCore/mailcore2#240]
I'm getting this error message:

Error sending email:Error Domain=MCOErrorDomain Code=1 "The operation couldn’t be completed. (MCOErrorDomain error 1.)

Only using an iPad 1, with iOS 5.1.1.

With above systems all is well. Thanks for looking into this problem.

**Comment by jagdish24** [comment]
Add this line and done. 

    smtpSession.checkCertificateEnabled = NO;

**Comment by mengxianzhi1989** [comment]
Hello Will you solve the problem? (Error Domain = MCOErrorDomain Code = 1) I send a message also appeared this problem! This and outgoing server address (POP or SMTP) the relationship between you? 163 126 qq mailbox no problem, but our mail server address recipient pop smtp outgoing mail server address is it! And you use the same method as you want reply

**Comment by neowinston** [comment]
Sorry, I have not solved this problem because we dropped support for iOS 5 a while back and we're OK with no problems using iOS 7 and 8.

**Comment by SazzadIproliya** [comment]
Hello friend,
I got a solution. if you are using Gmail address for username and password so please Disable
"unlock captcha and enable less secure apps" it.

After that, try this code. it is working. it was google security issue.  

Hope you like it.

**Comment by neowinston** [comment]
Thanks for posting a new solution!

**Comment by lwllucas** [comment]
Hi I am having the same MCOErrorDomainCode = 1 Error when trying it out in swift5. Am currently using outlook smtp server to send mail

**Comment by mehulparmar4ever** [comment]
Swift 5, iOS 13 **Same error again**

Tried every solution from above comment & research on net. Unable to find proper solution. Need help.

Error sending email: Optional(Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo={NSLocalizedDescription=A stable connection to the server could not be established.})

**Comment by mehulparmar4ever** [comment]
### Just for information,
Library is working perfect, All is working fine. 

[I find solution. Finally. Take look into this,](https://stackoverflow.com/questions/34538647/mailcore2-via-smtp-outlook-com-gives-error-domain-mcoerrordomain-code-1-a-stabl/60548872#60548872)  

**Swift 5, iOS 13, Xcode Version 11.3.1 (11C504)**

    Also Need to Disable Captcha :  [https://accounts.google.com/DisplayUnlockCaptcha][1]

> Response: Successfully sent email!

Here is the perfect solution: 

        @IBAction func btnSendMailClicked(_ sender: UIButton) {

        print(#function)
        let smtpSession = MCOSMTPSession()
        smtpSession.hostname = "smtp.gmail.com"
        smtpSession.username = "emailaddress@gmail.com"
        smtpSession.password = "password" //You can create [App Password from gmail setting][1] 

        smtpSession.port = 587 //25
        smtpSession.authType = MCOAuthType.saslPlain
        smtpSession.connectionType = MCOConnectionType.startTLS
        smtpSession.isCheckCertificateEnabled = false

        smtpSession.connectionLogger = {(connectionID, type, data) in
            if data != nil {
                if let string = NSString(data: data!, encoding: String.Encoding.utf8.rawValue){
                    NSLog("Connectionlogger: \(string)")
                }
            }
        }

        let builder = MCOMessageBuilder()
        builder.header.to = [MCOAddress(displayName: "Swifty Developers", mailbox: "swiftydevelopers@gmail.com")!]
        builder.header.from = MCOAddress(displayName: "Mehul Parmar", mailbox: "mehulasjack@gmail.com")
        builder.header.subject = "My message"
        builder.htmlBody = "Yo Rool, this is a test message!"
        
        let rfc822Data = builder.data()
        let sendOperation = smtpSession.sendOperation(with: rfc822Data)
        sendOperation?.start { (error) -> Void in
            if (error != nil) {
                NSLog("Error sending email: \(String(describing: error))")
            } else {
                NSLog("Successfully sent email!")
            }
        }
    }


  [1]: https://accounts.google.com/DisplayUnlockCaptcha
