### ISSUE TITLE
How to delete a message in Mailcore 2?

### ISSUE THREAD

**Issue by bhushan12** [MailCore/mailcore2#286]
Hi ,
I am using mailcore2. I have fetched folders and I am able to show messages.
Now I am trying to delete a message. I am not sure which class and which methods to  use in mailcore2.

**Comment by cdf1982** [comment]
Hi, I have the same issue, but with POP: I'm not getting how can I delete an email message on a POP server after I downloaded it. Any suggestions?

**Comment by dinhviethoa** [comment]
Please use `-[MCOPOPSession deleteMessagesOperationWithIndexes]`.

**Comment by cdf1982** [comment]
Thanks!
