### ISSUE TITLE
Mailcore 2 can not access gmail messages except Inbox folder

### ISSUE THREAD

**Issue by bhushan12** [MailCore/mailcore2#303]
With Mailcore 2 I am able to access Yahoo's almost all folders but when try for gmail , it can only access Inbox folder. Please anyone know whats going wrong.

**Comment by VishnuPrem55** [comment]
I have fetched all mailcore folder names. please check the given link,

[https://github.com/MailCore/mailcore2/issues/912#issuecomment-1323276900](url)
