### ISSUE TITLE
how to set up sub-folder

### ISSUE THREAD

**Issue by sxy707** [MailCore/mailcore2#321]
excuse me,how to set up sub-folders by createFolderOperation?
For example, there is a folder named "MailCore2FolderOpTest", I want to set up one subfolder named "subfolder1" in it, how can I achieve it?
I use the codes as following.

``` objective-c
MCOIMAPOperation *op = [imapSession createFolderOperation:@"MailCore2FolderOpTest\\subfolder1"]
[op start:^(NSError *error) {
    NSLog(@"error info:%@", error);
}];
```

but there is no callback message. That is to say, "NSLog(@"error info:%@", error)" can not be executed.

**Comment by lyluoyuan** [comment]
> Try those:
> 
> ```
> NSString * path = [[session defaultNamespace] pathForComponents:@["MailCore2FolderOpTest", "subfolder1"]];
> MCOIMAPOperation *op = [imapSession createFolderOperation:path]
> [op start:^(NSError *error) {
> NSLog(@"error info:%@", error);
> }];
> ```
> 
> ```
> NSString * path = [[session defaultNamespace] pathForComponents:@["测试中文"]];
> MCOIMAPOperation *op = [imapSession createFolderOperation:path]
> [op start:^(NSError *error) {
> NSLog(@"error info:%@", error);
> }];
> ```

It dosn't work. And return error: "NO Invalid top folder name". Maybe character '/' or '\' is not allowed.
