### ISSUE TITLE
How to get localize folder path

### ISSUE THREAD

**Issue by oRandeniKasun** [MailCore/mailcore2#330]
Want to get the [Gmail]/All mail folder, but in japanese localization it return "[Gmail]",
    "\U3059\U3079\U3066\U306e\U30e1\U30fc\U30eb"

**Comment by xingheng** [comment]
@oRandeniKasun , how did you solve your error "The requested folder does not exist. Folder selection failed"?

**Comment by Dimajp** [comment]
Sorry - I played with this library a year ago - so can not help you right now.
Can only suggest to request your mail server with console commands - it is a bit faster than rebuild project and test it again and again.
+ If you do see a folder in a list of folders - than you definitely have some problems in folder name when you request its content.
For ex - if you using Gmail account and it is set up to some non english language - some folders will be still in english(main ones) - another ones - not.

17.09.2015, 10:17, "Will Han" <notifications@github.com>:

**Comment by xingheng** [comment]
@Dimajp  Thanks all the same, I'll try.
