### ISSUE TITLE
Issues sending emails using open relay exchange on an iPad

### ISSUE THREAD

**Issue by ghost** [MailCore/mailcore2#343]
I'm try to use the mailcore2 library with an iPad app. When I try to send an email I get the "Unable to authenticate with the current session's credentials" error.

We use an open replay for our exchange server. Is there a way to prevent it sending a username and password as I think this maybe the issue?

**Comment by mishug** [comment]
MailCore is not working. 

Error sending email: Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo={NSLocalizedDescription=A stable connection to the server could not be established.}

**Comment by dinhviethoa** [comment]
Please create an other issue and give more details. Show your code sample.
