### ISSUE TITLE
How to handle: (Best Practices) "Too many simultaneous connections were made to this Gmail account"

### ISSUE THREAD

**Issue by palaniraja** [MailCore/mailcore2#382]
At the moment, I just call folderstatus operation & imap/pop message fetch operation inside a for loop.

dispatch_async(GQ_DEF_PRIORITY, ^{
    //BG queue
});

Works most of the time, but frequently i get "Too many simultaneous connection..." error if I go back and forth from account selection and folderlisting view. (I call the folderstatus update in viewdidload).

It would be really helpful to share some best practice or resource links on fixing this issue. 

Thank you.

**Comment by vu0tran** [comment]
@dinhviethoa One problem I encountered is if the user manually terminates the app from the background process, relaunches a fresh instance of the app and continues to do this several times, it will open up multiple imap sessions with Google which causes the "too many simultaneous connection" error. 

What do you recommend to the solution here to be? I can call "disconnect" explicitly when the app moves to the background, but I would still like to keep a open connection for background fetch...

**Comment by dinhviethoa** [comment]
Can you post to stackoverflow? It's easier to discuss here rather than a on a closed github issue.

**Comment by vu0tran** [comment]
Here it is for future reference:

http://stackoverflow.com/questions/29981039/what-are-the-best-practices-to-handling-app-suspensions-and-too-many-simultaneo
