### ISSUE TITLE
Problem of MCOIMAPSearchOperation with searchString is chinese char

### ISSUE THREAD

**Issue by zhangxn** [MailCore/mailcore2#421]
there is a error when searchString contains chinese char, such as "中文"

Error Domain=MCOErrorDomain Code=19 "An error occured while fetching messages in the requested folder.

my code is:

MCOIMAPSearchOperation *searchOperation = [session searchOperationWithFolder:folderName kind:requestKind searchString:@"中文"];

 [searchOperation start:^(NSError *error, MCOIndexSet *searchResult) {
        if (error != nil) // log
｝

**Comment by bineshpavithran** [comment]
This issue still exist in outlook and office365 servers . Is there any solution for this issue?

**Comment by jstedfast** [comment]
What charset value are you sending to the server? And does the server support that charset?
