### ISSUE TITLE
Include static lib only

### ISSUE THREAD

**Issue by skela** [MailCore/mailcore2#427]
Is there a way I can build and then include the static library alone (Without having to include the whole mailcore xcode project).
I'm having a lot of weird issues when it comes to the default setup of adding the xcode project to my project, and linking it that way.
Sometimes it builds and works, other times it will suddenly stop working, forcing me to delete the mailcore2/Externals folder and do a full rebuild.
![screen shot 2013-10-22 at 16 47 46](https://f.cloud.github.com/assets/58268/1379724/af245674-3af6-11e3-94a9-dd7d047b7d73.png)

**Comment by Sarosh-Madara** [comment]
Hey guyz I am getting the same error I am trying to add MailCore2 to my iOS project and  I have followed all the steps provided by the github   github.com/MailCore/mailcore2/blob/master/build-mac/README.md   and when I tried to add libmailcore-ios.a through Link Binary With Libraries It gets red.. It seems that the mailcore2 isn't build correctly and I am getting 3 warnings also.. 
If anyone could help me will be great apprecited.

![screen shot 2015-04-13 at 8 36 52 pm](https://cloud.githubusercontent.com/assets/8752879/7119076/ff0fcaa0-e235-11e4-8c7f-c02e1e08dff4.png)

**Comment by dinhviethoa** [comment]
Please post on stackoverflow.
