### ISSUE TITLE
How can I save draft

### ISSUE THREAD

**Issue by hao2596** [MailCore/mailcore2#434]
I want to save draft,but there is no example.Would someone show me how to do it.

**Comment by cuongproit** [comment]
In Yahoo mail, outlook mail.. saving email to Darft folder is worked. But, I can't save email to Draft folder in only GMAIL. The error description is: "The requested folder does not exist.  Folder selection failed". See my code below:

MCOIMAPAppendMessageOperation *op = [self.currentAccount.imapSession appendMessageOperationWithFolder:self.currentAccount.draftFolder/*@"[Gmail]/Drafts"*/ messageData:data flags:MCOMessageFlagDraft];
[op start:^(NSError *error, uint32_t createdUID) {

}];

I logged draftFolder in this case is "[Gmail]/Drafts".

Please help me!

**Comment by houssem-yahiaoui** [comment]
Regadringthe appendOperation, i've an issue with the Data field @dinhviethoa  what is the value of that object if i'm using mailcore in swift and i have the msg object?
