### ISSUE TITLE
MCOMessageParser  header

### ISSUE THREAD

**Issue by cheshuangchun** [MailCore/mailcore2#454]
this is the header i got from .eml

Date: Tue, 05 Nov 2013 10:36:57 +0800
MIME-Version: 1.0
X-IBC-SecMail: encrypted,signed
X-IBC-Domain-Version: cwindow,1
From: byang byang@cmailvip.net
To: shizhong.yang@sic-ca.com, jinqiao.chang@sic-ca.com,
ming.xiang@sic-ca.com, liwei.wang@sic-ca.com, hao.sun@sic-ca.com,
helei.wang@sic-ca.com, shuangchun.che@sic-ca.com
Content-Type: multipart/mixed; boundary="__=_Part_Boundary_007_1195965775.2834191348"
Message-Id: E1VdWdP-0006yl-At@mail.cwindow.net

i can not get      X-IBC-SecMail: encrypted,signed
                         X-IBC-Domain-Version: cwindow,1 

please tell me how can i get that ,thank you very much !

MCOIMAPFetchContentOperation \* op = [[[AuthManager sharedManager] getImapSession] fetchMessageByUIDOperationWithFolder:folder uid:[msg uid] urgent:NO];
[op start:^(NSError \* error, NSData \* messageData) {
MCOMessageParser \* parser = [MCOMessageParser messageParserWithData:messageData];

```
NSLog(@"hyhyhy====.>>%@",[parser header]);  
```

}]; this is the code

you reply to me that "I think they will show in extraHeaders of the header structure if you parse the resulting .eml using MCOMessageParser."  But,i can not find extraHeaders in [parser header].

**Comment by BoydYang** [comment]
Please obfuscate the email addresses in the question.
They are real emails which are used by abusers for sending spams.
