### ISSUE TITLE
Set priority of MCOOperation

### ISSUE THREAD

**Issue by martinc** [MailCore/mailcore2#458]
Great work! Would like it if there was a way to set priority for an operation, like setting queuePriority on an NSOperation. Say there are alot of messages to download in the queue, but the user opens one that's not yet downloaded, you want to download that one first with a higher priority that jumps to the front of the queue.

**Comment by xmkevin** [comment]
okay, I can I manage operation priory in the app level ? I also need to load the email content quickly
