### ISSUE TITLE
Call back in current thread vs main thread

### ISSUE THREAD

**Issue by Tensho** [MailCore/mailcore2#501]
AFAIK, callback of every operation works in Main Thread. So, if I start operation in background thread the callback will be processed whatever in Main Thread. Can I coerce to work callback in current thread?

``` objective-c
// Background Thread
MCOIMAPFetchContentOperation * op = [session fetchMessageByUIDOperationWithFolder:_folder uid:[_message uid]];
[op start:^(NSError * error, NSData * data) {
    // Main Thread, but will be cool to have the same Background Thread
}
```

As I can see in [this pull](https://github.com/MailCore/mailcore2/pull/431/files) current thread was regressed.

**Comment by lyahdav** [comment]
So is there a solution to this problem without using the deprecated dispatch_get_current_queue method?

**Comment by dinhviethoa** [comment]
You can use the property dispatchQueue of MCOIMAPSession.
You you have a specific question, please ask on stackoverflow.
Thanks.
