### ISSUE TITLE
can i fetch the attachments from pop.server.com ?

### ISSUE THREAD

**Issue by loveNoodles** [MailCore/mailcore2#516]
l want to get all the attachnents from pop.server.com, but how ?

**Comment by pradnyaGaikwad** [comment]
Hi,

I am trying to get attachments data for pop server, but the data property of MCOAttachment class is giving this result <NSData: 0x17447d400 length 134144>. How can i get the metadata of attachment?
Am i doing anything wrong. Below is the code i have used to fetch attachment data and filename.

MCOPOPFetchMessagesOperation *fetchOp = [session fetchMessagesOperation];
    [fetchOp start:^(NSError *err, NSArray *msgs) {
        //NSLog(@"All Mesages = %@.",msgs);
        if (err == nil) {
            for (int i=0; i<[msgs count]; i++) {
                //MCOPOPMessageInfo *msg = [msgs objectAtIndex:i];
                //NSLog(@"Message:%@",msg);
                
                MCOPOPFetchHeaderOperation *headerOp  = [session fetchHeaderOperationWithIndex:i];
                [headerOp start:^(NSError * __nullable error, MCOMessageHeader * headerMsg) {
                    
                    // Get subject for each mail
                    NSLog(@"String:%@",headerMsg.subject);
                }];
                MCOPOPFetchMessageOperation * op = [session fetchMessageOperationWithIndex:i];
                [op start:^(NSError * __nullable error, NSData * messageData) {
                    NSLog(@"Session:%@",session);
                    // messageData is the RFC 822 formatted message data.
                    MCOMessageParser *parser = [[MCOMessageParser alloc] initWithData:messageData];
                    NSArray *arr = parser.attachments;
                    //NSLog(@"Attachments: %@",arr);
                    for ( NSInteger j = 0; j <[arr count]; j++ )
                    {
                        MCOAttachment *attachment = [arr objectAtIndex:j];
                        NSLog(@"Attachments file name: %@",attachment.filename);
                        
                        NSData *data = attachment.data;
                        NSLog(@"Attachments file data: %@",data);
                    }
                }];
            }
        }
    }];

Thanks

**Comment by dinhviethoa** [comment]
MCOAttachment is a subclass of MCOAbstractPart. Please take a look at the properties of MCOAbstractPart. Also, create a different issue if you still have problems.
