### ISSUE TITLE
Why  the folders path .Chinese is garbled.

### ISSUE THREAD

**Issue by yangbor** [MailCore/mailcore2#570]
i use the imap to get the mail folders and messages. messages are correct, but folders in Chinese is garbled. what should i do ?

**Comment by youzhenyu** [comment]
@dinhviethoa  
for (MCOIMAPFolder *folder in folders) {
                NSString *folderPath1=[[self.imapSession defaultNamespace] componentsFromPath:folder.path][0];
                NSString *folderPath2=[self.imapSession.defaultNamespace pathForComponents:@[folder.path]];
                NSLog(@"%@ === %@", folderPath1,folderPath2);
            }
I go to request with this two value. Returns the error : The requested folder does not exist.  Folder selection failed.
Where is my problem?
