### ISSUE TITLE
How to archive message instead of deleting

### ISSUE THREAD

**Issue by galblank** [MailCore/mailcore2#574]
Hi,
I know how to flag message as deleted using MCOMessageFlagDeleted but I can't find a flag for mark them as archived.
Any suggestions?
thanks

Gal Blank

**Comment by guidedways** [comment]
Sorry bringing this up again - the rule surely won't apply to all email accounts? Setting the Deleted flag on a non-gmail account deletes it (and does not even show under Trash). Any globally acceptable way of archiving emails?
