### ISSUE TITLE
Problem connecting to IMAP server and performing search

### ISSUE THREAD

**Issue by truppelito** [MailCore/mailcore2#576]
I am having a problem when connecting to a Gmail IMAP server to perform a search. Here is the relevant code:

```
NSString* folder = @"INBOX";

MCOIMAPSearchExpression* exprFrom = [MCOIMAPSearchExpression searchFrom: @"..."];
MCOIMAPSearchExpression* exprSubject = [MCOIMAPSearchExpression searchSubject: @"..."];
MCOIMAPSearchExpression* expr = [MCOIMAPSearchExpression searchAnd: exprFrom other: exprSubject];

MCOIMAPSearchOperation* searchOperation = [[self IMAPSession] searchExpressionOperationWithFolder: folder expression: expr];
[searchOperation start: ^(NSError* error, MCOIndexSet* searchResult) {
    if (error) {
        NSLog(@"Error downloading message headers: %@", error);
    }

    [searchResult enumerateIndexes: ^(uint64_t uuID) {
        MCOIMAPFetchContentOperation* op = [[self IMAPSession] fetchMessageByUIDOperationWithFolder: folder uid: (uint32_t)uuID];

        [op start: ^(NSError* error, NSData* messageData) {
            MCOMessageParser* parser = [MCOMessageParser messageParserWithData: messageData];
            NSString* message = [parser plainTextRendering];

            for (NSString* line in [message componentsSeparatedByCharactersInSet: [NSCharacterSet newlineCharacterSet]]) {
                NSLog(@"%@", line);
            }
        }];
    }];
}];
```

and:

```
- (MCOIMAPSession*)IMAPSession
{
    MCOIMAPSession* IMAPSession = [MCOIMAPSession new];
    IMAPSession.hostname = @"imap.gmail.com";
    IMAPSession.port = 993;
    IMAPSession.username = @"...";
    IMAPSession.password = @"...";
    IMAPSession.connectionType = MCOConnectionTypeStartTLS;
    IMAPSession.authType = MCOAuthTypeSASLCRAMMD5;

    // Just for testing purposes
    [IMAPSession setConnectionLogger:^(void * connectionID, MCOConnectionLogType type, NSData * data){
        NSLog(@"MCOIMAPSession: [%i] %@", type, [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
    }];

    return IMAPSession;
}
```

This consistently doesn't work, and I get the following:

```
2014-02-01 21:49:34.205 MyApp[64891:9b3b] MCOIMAPSession: [4] 
2014-02-01 21:49:34.206 MyApp[64891:303] Error downloading message headers: Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo=0x1020018f0 {NSLocalizedDescription=A stable connection to the server could not be established.}
```

I am at a complete loss. I think I'm doing everything correctly, but it sure isn't working as it should...

If it helps, I noticed that quite a bit of time (say, 20-30 secs) passes between the call to `[searchOperation start: ^(NSError* error, MCOIndexSet* searchResult) {` and the actual block being run. Any ideas are greatly appreciated!

**Comment by puneetarora10** [comment]
Error downloading message headers:Error Domain=MCOErrorDomain Code=1 "A stable connection to the server could not be established." UserInfo={NSLocalizedDescription=A stable connection to the server could not be established.}


Testing on a simulator (iphone 6).

Code ---->

MCOIMAPSession *session = [[MCOIMAPSession alloc] init];
    [session setHostname:@"imap.gmail.com"];
    [session setPort:993];
    [session setUsername:@"@gmail.com"];
    [session setPassword:@""];
    [session setConnectionType:MCOConnectionTypeTLS];
    [session setAuthType:MCOAuthTypeSASLCRAMMD5];
    //[session setCheckCertificateEnabled:NO];
    
    MCOIMAPMessagesRequestKind requestKind = MCOIMAPMessagesRequestKindHeaders;
    NSString *folder = @"INBOX";
    MCOIndexSet *uids = [MCOIndexSet indexSetWithRange:MCORangeMake(1, UINT64_MAX)];
    
    MCOIMAPFetchMessagesOperation *fetchOperation = [session fetchMessagesByUIDOperationWithFolder:folder requestKind:requestKind uids:uids];
    
    [fetchOperation start:^(NSError * error, NSArray * fetchedMessages, MCOIndexSet * vanishedMessages) {        
        if(error) {
            NSLog(@"Error downloading message headers:%@", error);
        }
        
        NSLog(@"The post man delivereth:%@", fetchedMessages);
    }];

**Comment by puneetarora10** [comment]
Dont worry, works on the device!
