### ISSUE TITLE
Download only mail body...

### ISSUE THREAD

**Issue by venkatesh81290** [MailCore/mailcore2#581]
Hi,

I'm using the below code to download message data using UID. But the message data contains mail body + attachments data too. 

MCOIMAPFetchContentOperation *operation = [imapSession fetchMessageByUIDOperationWithFolder:mailFolder.path uid:mailMessage.uid];

```
[operation start:^(NSError *error, NSData *data) {
    NMail_ContentView *mailContentObj = [NMail_ContentView getInstance];
           //functionality to render mail body using data...
}];
```

I need only mail body to be fetched without downloading attachments... Is it possible?

I used
MCOIMAPMessagesRequestKindHeaders | MCOIMAPMessagesRequestKindFlags | MCOIMAPMessagesRequestKindStructure
 request kinds to get message headers. So i got the list of attachements.

**Comment by kapil0408** [comment]
Hello venkatesh81290, 

I am using below this code only for download message body.

MCOIMAPFetchContentOperation * op = [[[CMSessionController sharedInstance] globalSession] fetchMessageByUIDOperationWithFolder:@"INBOX" uid:81710053];
    [op start:^(NSError * __nullable error, NSData * messageData) {
        MCOMessageParser * parser = [MCOMessageParser messageParserWithData:messageData];
        NSString *str= [parser plainTextRendering];
        NSLog(@"str=%@",str);
    }];

But In response I am only getting
str=
To: Undisclosed recipient
Subject: No Subject
Date: June 5, 2018 at 5:38:08 PM GMT+5:30

please help 
Thanks

**Comment by lksnmnn** [comment]
This is somewhat unrelated to my former issue, but I think the messageData only contains the email header at this point.
There should be another function to download and parse the emails content.

Please check the examples or the questions/answers on StackOverflow.

Cheers,
Lukas

**Comment by kapil0408** [comment]
Thank you so much. i see examples and also on StackOverflow.
