### ISSUE TITLE
Error sending email:Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo=0x209f5e90 {NSLocalizedDescription=Unable to authenticate with the current session's credentials.}

### ISSUE THREAD

**Issue by cheshuangchun** [MailCore/mailcore2#588]
when i send email with the follow method

MCOSMTPSession *smtpSession = [[AuthManager sharedManager] getSmtpSession];
MCOSMTPSendOperation *sendOperation;
sendOperation = [smtpSession sendOperationWithData:rfc822Data];
        [sendOperation start:^(NSError *error) {
            if(error) {

i got the error
Error sending email:Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo=0x209f5e90 {NSLocalizedDescription=Unable to authenticate with the current session's credentials.}

**Comment by EMart002** [comment]
Hi dinhviethoa,

could you please provide a resetSessionCredentials method or so. It would be really cool! I will never evern need to create a new E-Mail Account, whenever this error occures. 

Thanks,
best regards!

**Comment by camillezlh** [comment]
Hi all
Didn't know what to do upstairs problems are not solved, I also encountered the same problem now, log is problem
Error loading account: error Domain = MCOErrorDomain Code = 5 "Unable to authenticate with the current session 's credentials." the UserInfo = 0 x16dbb1b0 {NSLocalizedDescription = Unable to authenticate with the current session' s credentials
Ask for help, thank you

**Comment by camillezlh** [comment]
My error log and amritsahay is the same, if you have already solved, still hope generous help, thank you

**Comment by dinhviethoa** [comment]
Please stop commenting on closed issue. I'm locking this issue.
The solution is already provided.
