### ISSUE TITLE
Large mail messages in iOS

### ISSUE THREAD

**Issue by iWeaverMan** [MailCore/mailcore2#640]
We constantly get memory  issues when attempting to load large (50-100 Mb) mail messages. Is it possible to use file streams instead of NSData objects in following classes? 
MCOMessageParser, MCOPOPFetchMessageOperation, MCOIMAPFetchContentOperation

**Comment by dinhviethoa** [comment]
It's fixed now. There's the ability to download an attachment or a message to a file.
