### ISSUE TITLE
Mailcore 2 for iOS as a Framework

### ISSUE THREAD

**Issue by TroyJ** [MailCore/mailcore2#664]
When are you guys going to just release this as a framework for iOS? Is there some technical limitation stopping you?

The need for me comes from a lot of trouble getting mailcore2 integrated into my project. Following the directions I found didn't work. With a lot of tweaking it's in there, but unfortunately it's not in as a separate library - it builds every time and runs those scripts.

**Comment by jonasman** [comment]
I can confirm that the static lib for ios  works fine!
