### ISSUE TITLE
Can I download a message without downloading attachments?

### ISSUE THREAD

**Issue by John1843** [MailCore/mailcore2#681]
I would like to display an HTML email but it takes long to download the message since all attachments are also downloaded. Is it possible to avoid downloading the attachments?

(This issue was already discussed but I would like to ask if there is now a solution, 
https://github.com/MailCore/mailcore2/issues/305)

This is my code:

``` Objective-C
- (void) showEmail
{
    MCOIMAPSession *session = [_email getSession];
    MCOIMAPFetchContentOperation *operation = [session fetchMessageByUIDOperationWithFolder:[_email getFolder] uid:[_email getIMAPMessage].uid];

    [operation start:^(NSError *error, NSData *data) {
        MCOMessageParser *messageParser = [[MCOMessageParser alloc] initWithData:data];

        NSString *msgHTMLBody = [messageParser htmlRenderingWithDelegate:nil];

        [_webView loadHTMLString:msgHTMLBody baseURL:nil];

    }];
}
```

**Comment by fans3210** [comment]
I didn't use fetchcontentoperation for now since it fetches all including attachments. I use MCOIMAPMessageRenderingOperation for loading htmls only.
