### ISSUE TITLE
IMAP AUTHENTICATE DIGEST-MD5 issue

### ISSUE THREAD

**Issue by withshe** [MailCore/mailcore2#688]
How to config mailcore2 to accomplish the following interaction? Thanks!
- OK Sendmail Mail Store IMAP4rev1 ready
  A0 CAPABILITY
- CAPABILITY IMAP4rev1 CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT AUTH=DIGEST-MD5 QUOTA
  A0 OK CAPABILITY completed
  A1 AUTHENTICATE DIGEST-MD5
  +cmVhbG09Im8yLmNvbSIsbm9uY2U9Ik1qQXhOREF6TVRnd05qUTVOVEEwTlRRMk5EQWciLHFvcD0iYXV0aCIsYWxnb3JpdGhtPW1kNS1zZXNz
  dXNlcm5hbWU9IjE4Mzc1NjYxODgxIixyZWFsbT0ibzIuY29tIixxb3A9YXV0aCxuYz0wMDAwMDA+ cnNwYXV0aD1jMGY0ZmNiNGFhM2FiNmZkZGRmYWJjYzgxZDM3NDBiOA==

**Comment by libec** [comment]
What is the reason for not supporting DIGEST-MD5? What can we do to add support?
