### ISSUE TITLE
How can I really cancel download large attachment？

### ISSUE THREAD

**Issue by zhangjiangshan** [MailCore/mailcore2#698]
Hello. I know that mailcore2 won't really stop download when calling cancel method.But we don't want to cost bandwidth when user cancel download attachment.Is there any way to solve this problem. 
Becides,I download the attachment like this:
MCOIMAPFetchContentOperation \* op =[session fetchMessageAttachmentByUIDOperationWithFolder:[folder path] uid:[self.mail.uid intValue] partID:self.partID encoding:MCOEncodingBase64 urgent:YES];
and the attachment is a jpg image larger than 2.5M

**Comment by wwwang89** [comment]
is there any API for suspend or resume  when download a large attachment?  thanks~
