### ISSUE TITLE
MCOSMTPSendOperation only works on iOS Simulator, not on device.

### ISSUE THREAD

**Issue by f2m2rd** [MailCore/mailcore2#72]
The code from the wiki (see below), with a valid email account and SMTP connection info, **will send** from the **iOS Simulator**, but will **not send** on the **iPhone device**.  

The device returns an error: 
_Domain=MCOErrorDomain Code=5 "The operation couldn’t be completed. (MCOErrorDomain error 5.)_ 

**Is anyone else having this issue?**

``` objective-c

MCOSMTPSession *smtpSession = [[MCOSMTPSession alloc] init];
smtpSession.hostname = @"smtp.gmail.com";
smtpSession.port = 465;
smtpSession.username = USERNAME;
smtpSession.password = PASSWORD;
smtpSession.authType = (MCOAuthTypeSASLPlain | MCOAuthTypeSASLLogin);
smtpSession.connectionType = MCOConnectionTypeTLS;

MCOMessageBuilder * builder = [[MCOMessageBuilder alloc] init];
[[builder header] setFrom:[MCOAddress addressWithDisplayName:nil mailbox:USERNAME]];
NSMutableArray *to = [[NSMutableArray alloc] init];
for(NSString *toAddress in RECIPIENTS) {
    MCOAddress *newAddress = [MCOAddress addressWithMailbox:toAddress];
    [to addObject:newAddress];
}
[[builder header] setTo:to];
NSMutableArray *cc = [[NSMutableArray alloc] init];
for(NSString *ccAddress in CC) {
    MCOAddress *newAddress = [MCOAddress addressWithMailbox:ccAddress];
    [cc addObject:newAddress];
}
[[builder header] setCc:cc];
NSMutableArray *bcc = [[NSMutableArray alloc] init];
for(NSString *bccAddress in BCC) {
    MCOAddress *newAddress = [MCOAddress addressWithMailbox:bccAddress];
    [bcc addObject:newAddress];
}
[[builder header] setBcc:bcc];
[[builder header] setSubject:SUBJECT];
[builder setHTMLBody:BODY];
NSData * rfc822Data = [builder data];

MCOSMTPSendOperation *sendOperation = [smtpSession sendOperationWithData:rfc822Data];
[sendOperation start:^(NSError *error) {
    if(error) {
        NSLog(@"%@ Error sending email:%@", USERNAME, error);
    } else {
        NSLog(@"%@ Successfully sent email!", USERNAME);
    }
}];

```

**Comment by camillezlh** [comment]
@younghwanglocalspace  
Hello, I want to ask, I use an error on the equipment of xcode6.1 iOS8.1 imap, I posted code and error message, please correct me or please let us know where to find the solutions of the related content, thank you
self.imapSession = [[MCOIMAPSession alloc] init];
	self.imapSession.hostname = hostname;
	self.imapSession.port = 993;
	self.imapSession.username = username;
	self.imapSession.password = password;
    self.imapSession.authType= MCOAuthTypeSASLLogin;
    if (oauth2Token != nil) {
        self.imapSession.OAuth2Token = oauth2Token;
        self.imapSession.authType = MCOAuthTypeXOAuth2;
    }
	self.imapSession.connectionType = MCOConnectionTypeTLS;
    MasterViewController * __weak weakSelf = self;
	self.imapSession.connectionLogger = ^(void * connectionID, MCOConnectionLogType type, NSData * data) {
        @synchronized(weakSelf) {
            if (type != MCOConnectionLogTypeSentPrivate) {
                NSLog(@"event logged:%p %i withData: %@", connectionID, type, [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
            }
        }
    };
	
	// Reset the inbox
	self.messages = nil;
	self.totalNumberOfInboxMessages = -1;
	self.isLoading = NO;
	self.messagePreviews = [NSMutableDictionary dictionary];
	[self.tableView reloadData];
    
	NSLog(@"checking account");
	self.imapCheckOp = [self.imapSession checkAccountOperation];
	[self.imapCheckOp start:^(NSError *error) {
		MasterViewController *strongSelf = weakSelf;
		NSLog(@"finished checking account.");
		if (error == nil) {
			[strongSelf loadLastNMessages:NUMBER_OF_MESSAGES_TO_LOAD];
		} else {
			NSLog(@"error loading account: %@", error);
		}
		
		strongSelf.imapCheckOp = nil;
	}];

Error message is：
event logged:0x14db6ae0 0 withData: * OK [CAPABILITY IMAP4 IMAP4rev1 IDLE XAPPLEPUSHSERVICE ID UIDPLUS AUTH=LOGIN NAMESPACE] QQMail IMAP4Server ready

2015-02-12 11:20:53.059 MailCoreTest[6472:2620896] event logged:0x14db6ae0 0 withData: + VXNlciBOYW1lAA==

2015-02-12 11:21:07.264 MailCoreTest[6472:2620896] event logged:0x14db6ae0 0 withData: + UGFzc3dvcmQA

2015-02-12 11:21:07.370 MailCoreTest[6472:2620896] event logged:0x14db6ae0 0 withData: (null)
2015-02-12 11:21:07.373 MailCoreTest[6472:2620864] finished checking account.
2015-02-12 11:21:07.374 MailCoreTest[6472:2620864] error loading account: Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo=0x14db9c40 {NSLocalizedDescription=Unable to authenticate with the current session's credentials.
