### ISSUE TITLE
When to Expunge Folder?

### ISSUE THREAD

**Issue by mguillen** [MailCore/mailcore2#762]
Do I need to expunge a folder after I flag a message as Deleted?

For example: I flagged a message (from draft folder) as deleted.

Without expunging the "draft" folder will the flagged message be removed from the "draft" folder?

Note: What I want to achieve is remove a draft message permanently.

@dinhviethoa Could you help me with this sir?

**Comment by blindknight47** [comment]
@mguillen Can you help me to remove a draft message permanently? please.
