### ISSUE TITLE
.eml attachment file problem

### ISSUE THREAD

**Issue by lhshin** [MailCore/mailcore2#767]

**Comment by lksnmnn** [comment]
Sorry for brewing up this old topic, but I just came across a similar problem:

We are downloading the full header and the structure of the message, but there are no attachments in either ```message.attachments```nor ```message.htmlInlineAttachments``` of the fetched ```MCOIMAPMessage```.

How should we detect the *.eml* attachments?

**Comment by dsanghan** [comment]
@lksnmnn I'm seeing the same thing. Its getting automatically parsed as being part of the body. Did you find out how to separate it?

**Comment by lksnmnn** [comment]
Nah, we couldn't find the time to address this issue just yet. But maybe this could be solved within MailCore (@dinviethoa)? However, I hope we can tackle this topic within the next few weeks.

**Comment by dinhviethoa** [comment]
You can probably iterator over -mainPart. Also, if you have a patch to help the message part (with filename .eml) make its way to message.attachments, it would be a good contribution.
