### ISSUE TITLE
Setting custom MIME part headers?

### ISSUE THREAD

**Issue by shafferj** [MailCore/mailcore2#776]
Hi, 

I've had what I think is a good look around, so thought i'd ask. There doesn't appear to be an interface available that allows the setting of custom MIME Part headers? The MIME spec suggests this should be possible, but i didn't see a way to do it here. Custom message headers are working just fine, but I want to do provide some additional metadata in the MIME header that relates to a part of an attachment. 

Thanks,

Justin

**Comment by jafework** [comment]
@dinhviethoa @shafferj 
I am interested in getting this request reopened.

Gmail IMAP accounts for example will prefix a custom header for the gmail attachment id on the mime part node:

Ex:
```
Content-Type: image/png
Content-Transfer-Encoding: base64
Content-ID: <chart_01Z30000000iupw_1436421722000_0.png>
Content-Location: chart_01Z30000000iupw_1436421722000_0.png
X-Attachment-ID: Some_Gmail_Attachment_ID
```

I have a different usecase where I would also like to add additional headers in the mime part header as metadata, but I too believe it should be allowed. 

Note: In gmails case, the attachmentID tends to line up with the content-id, but I will be marking custom metadata.

**Comment by dinhviethoa** [comment]
I'd advise you to use the main header of the message for that. You can easily create a header such as:

```X-Attachment-Metadata: encoded{partID1: info1, partID2: info2...}```

`Content-Type` parameters could also work.
