### ISSUE TITLE
fetchMessagesByUIDOperationWithFolder / MCOErrorDomain Code=19

### ISSUE THREAD

**Issue by rlaferla** [MailCore/mailcore2#821]
When fetching messages using "fetchMessagesByUIDOperationWithFolder" (MCOIMAPFetchMessagesOperation) from a Yahoo IMAP server, I am getting the following error:

Error Domain=MCOErrorDomain Code=19 "An error occured while fetching messages in the requested folder."

**Comment by Sarosh-Madara** [comment]
Hey its urgent help me what to do now I got stuck.. 
when I tried to run the code provided below give the error..
+ (void)abc{
    MCOIMAPSession *session = [[MCOIMAPSession alloc]init];
    [session setHostname:@"imap.gmail.com"];
    [session setPort:993];
    [session setUsername:@"*************@gmail.com"];
    [session setPassword:@"************************"];
    [session setConnectionType:MCOConnectionTypeTLS];
    
    
    MCOIMAPMessagesRequestKind req_kind = MCOIMAPMessagesRequestKindHeaders;
    NSString* folder = @"INBOX";
    MCOIndexSet *uids = [MCOIndexSet indexSetWithRange:MCORangeMake(1,UINT64_MAX)];
    MCOIMAPFetchMessagesOperation *fetchOperation = [session fetchMessagesByUIDOperationWithFolder:folder requestKind:req_kind uids:uids];
    
    [fetchOperation start:^(NSError* error,NSArray* fetchMessages,MCOIndexSet *vanishedMessages){
        
        if(error){
            NSLog(@"Error downloading message headers:%@", error);
        }
        NSLog(@"The post man delivereth:%@", fetchMessages);
    }];   
}


the er
![screen shot 2015-04-13 at 9 25 31 pm](https://cloud.githubusercontent.com/assets/8752879/7120036/c94758d2-e23c-11e4-950e-04df24213ee9.png)
ror is here also ww

2015-04-13 21:10:02.912 MailCoreForMobile[1814:11303] Error downloading message headers:Error Domain=MCOErrorDomain Code=5 "Unable to authenticate with the current session's credentials." UserInfo=0x8157280 {NSLocalizedDescription=Unable to authenticate with the current session's credentials.}
2015-04-13 21:10:02.915 MailCoreForMobile[1814:11303] The post man delivereth:(null)

**Comment by dinhviethoa** [comment]
Please contact AstroPad HQ (http://astro-hq.com/) for urgent matter.
Thanks.
