### ISSUE TITLE
Fetch operation progress not being called

### ISSUE THREAD

**Issue by davetroy** [MailCore/mailcore2#851]
As a test, I'm doing the following:

```
        let fetchOp = session.fetchMessagesByUIDOperationWithFolder(folder, requestKind: requestFlags, uids: uids)

        fetchOp.progress = { (current: UInt32) in
            println("\(current)")
        }

        fetchOp.start { (error: NSError!, fetchedMessages: [AnyObject]!, vanished: MCOIndexSet!) -> Void in
etc...
```

The progress block is not being called, even though the fetchOp is running successfully and returning hundreds of messages. What could be the trouble? Swift issue?

**Comment by MIOSY** [comment]
Hi, 
I'm copying/moving messages uid from INBOX folder to Trash folder using copyMessageOperation/moveMessageOperation and it was successful. Here I need progress of the operation same as I'm able to got progress for fetching. Can someone help me to get the progress of the operation. here is y swift code below.

	let localCopyMessageOperation = sessionForOperation.copyMessagesOperation(withFolder: "INBOX", uids: indexSet, destFolder: account.trashFolderPath)
            DispatchQueue.main.async { [weak self] in
                localCopyMessageOperation?.progress = {
                    progress in
                    var progressPercentage = Float(progress) / Float(self.totalDeletedMailscount)
                    print("Progress percentage is \(progressPercentage)")
                    self.pendingRing!.setProgress(CGFloat(progressPercentage), animated: false)
                }
            }

**Comment by schmidt9** [comment]
> OK, I finally figured out what's going on here and it's weird but easy to trigger. If you call the fetch operation with FullHeaders vs. Headers flag set, the progress operation is not called.
> 
> ```
> // doesn't work
> MCOIMAPMessagesRequestKind flags = MCOIMAPMessagesRequestKindFullHeaders | MCOIMAPMessagesRequestKindExtraHeaders;
> 
> // works
> MCOIMAPMessagesRequestKind flags = MCOIMAPMessagesRequestKindHeaders | MCOIMAPMessagesRequestKindExtraHeaders;
> ```
> 
> I don't know why this is yet but I can reproduce it consistently.

Confirmed, still existing in v0.6.4
