### ISSUE TITLE
Easy way to get the the body and html body for the messages

### ISSUE THREAD

**Issue by pushkarsingh** [MailCore/mailcore2#86]
Similar to body and htmlBody messages on CTMessage class in MailCore1
- (NSString *)body {
  if (myFields == NULL || myParsedMIME == nil) {
      [self fetchBodyStructure];
  }
  NSMutableString *result = [NSMutableString string];
  BOOL success = [self _buildUpBodyText:myParsedMIME result:result];
  if (!success) {
      return nil;
  }
  return result;
  }

AND
- (NSString *)htmlBody {
  if (myFields == NULL || myParsedMIME == nil) {
      [self fetchBodyStructure];
  }
  NSMutableString *result = [NSMutableString string];
  BOOL success = [self _buildUpHtmlBodyText:myParsedMIME result:result];
  if (!success) {
      return nil;
  }
  return result;
  }

**Comment by bootsie123** [comment]
@dinhviethoa I'm new to programming in objective-c. So how would I implement that delegate method because I'm having the same problem as @ProjectDent.
