### ISSUE TITLE
Users/../MailCore.h:13:10: 'MailCore/MCCore.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by xiaoer371** [MailCore/mailcore2#865]
at first , thank you that your core。 (my English is bad )
but now  i am in trouble  that title's problem .
problem：
 compile is succeed，but import <MailCore.h>  in my class   when i want to use your core ， that  error  will appear。
help me ，if you have some time。 thank you 。

i use cocoapods

**Comment by JingLiangWen** [comment]
@xiaoer371 您能说说你解决方法吗？我这边也遇到相同情况。pod与mailcore2 “冲突”

**Comment by xiaoer371** [comment]
@JingLiangWen   现在的工程没有用pod 来引入mailcore2（对源码有些改动）， 直接按照作者的描述的使用方法 ：拖进去，再配置使用的。    用pod 引入，会自动配置应该更简单吧，    具体的我也不太清楚了。
