### ISSUE TITLE
.TXT attachment content inside message body

### ISSUE THREAD

**Issue by xdoug** [MailCore/mailcore2#874]
Hello, 

I'm trying to fetch a message body using `- plainTextBodyRenderingOperationWithMessage` and this message has a .txt file as attachment (that is not inline) but the .txt content is coming inside the message text body and also on HTML body.

How can I remove the .txt content from the message body?

Thanks!

**Comment by KieranMcGrady** [comment]
I actually came across this problem too recently. I received an email with a .txt file attachment and the content of the file rendered as body content. It doesn't happen with all .txt files. I created a few in TextEdit (plain text and rich text) and they worked fine. It seemed like the issue was with a couple of specific text files.

**Comment by dinhviethoa** [comment]
I think it happens when the .txt file is the first MIME part of the message.

**Comment by KieranMcGrady** [comment]
Hmm. So I've been trying to replicate it and this is what I've found.

1. I create a message in Gmail (web interface) with no subject and no body and drag a text file into the window.
2. When I receive it in my app the text file is treated correctly (as an attachment).
3. If I do the same in the Mac Mail app (drag the text file onto the message again) my app displays the text file content as the message body.

In other words the problem appears to be with the sender. Here is a gist of each message received so you can see the difference between how Gmail builds the message and how Mail.app builds the message.

https://gist.github.com/KieranMcGrady/a76a46cf4c4ebe9aff4d

https://gist.github.com/KieranMcGrady/120c072ae9989ee6ed3a

NB: I replaced some info in the messages for privacy but I tested sending a message from my Gmail account to the same Gmail account in both Gmails web app and Mail.app. I also tested sending to my Gmail account from a Host Gator account via Mail.app. Mail.app had the problem with both senders so it seems consistent and a problem with how the client builds the message.

**Comment by dinhviethoa** [comment]
Could you let me know if it fixes the issue for you?

**Comment by KieranMcGrady** [comment]
I'm using Cocoapods but it's downloading the 0.5.0 release. Am I able to force it download the latest commits?

**Comment by dinhviethoa** [comment]
@KieranMcGrady Can you try with the test app by checking out the repository?

**Comment by KieranMcGrady** [comment]
Sorry for the late reply, I was on vacation. I wasn't able to test on the iOS example app as I was getting a linker error when building: 

```ld: library not found for -luchardet-ios ```
```clang: error: linker command failed with exit code 1```

I tested it using the Mac example app instead and the fix worked.

**Comment by KieranMcGrady** [comment]
Tested on iOS using the latest MailCore release via Cocoapods and the fix is working.
