### ISSUE TITLE
Gmail rejects mailcore apps for certain accounts during checkAccountOperation...

### ISSUE THREAD

**Issue by rlaferla** [MailCore/mailcore2#876]
I have a Gmail user who gets this error in the logs for a "checkAccountOperation" on an IMAP session. 

Data String :: \* NO [WEBALERT https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=abcdefghijklmnopqrstuvqxyz-some-secret-token] Web login required.
2 NO [ALERT] Please log in via your web browser: http://support.google.com/mail/accounts/bin/answer.py?answer=78754 (Failure)

Thoughts on how to handle this?  Reading the Google web page, they may be rejecting apps with less security.  Perhaps non-oAuth logins?  Any idea why and what to do?

**Comment by vishundayal** [comment]
Hi, 
I am also getting the same error. 
Can you please suggest any workaround with gmail? 
Google suggests to turn on "Access for less secure apps". I dont understand why google thinks that my app is less secure? 
I am using the exactly the sample code from [Basic SMTP Usage]( https://github.com/MailCore/mailcore2/wiki/SMTP-Examples#basic-smtp-usage)

**Comment by dinhviethoa** [comment]
Please use OAuth2 authentication. to solve it.
