### ISSUE TITLE
Changing mailcore2 operations order

### ISSUE THREAD

**Issue by andreynagovitsyn** [MailCore/mailcore2#877]
How should I do in the following scenario:

I got list of messages for folder, for each message in the list I enqueue download message body operation into background thread like this:

void (^fetchMessages)(void) = ^{ // block to pass to global thread queue
for(MCOIMAPMessage *msg in msgs)
    {
        MCOIMAPMessageRenderingOperation *op = [[[AuthManager sharedManager] getImapSession] htmlBodyRenderingOperationWithMessage:msg folder:folderPath];
        [op start:^(NSString \* htmlText, NSError \* error){
            if(error != nil)
                return;

```
        [gs db_SetMessageBody:htmlText forUid:msg.uid];
    }];
}
```

};

// .....
 NSBlockOperation *bo = [NSBlockOperation blockOperationWithBlock:fetchMessages];
 [[[NSOperationQueue alloc] init] addOperation:bo];

While the background thread is working, user scrolls down the message list to message No 30. When user tap on message No30 I start operation to download the body of the message again. Result: the body of the tapped message No 30 is not downloaded until background thread did end downloading all the previous 29 enqueued messages.

How can I download the body of message No 30 without waiting previous enqueued background operations to complete?

**Comment by xmkevin** [comment]
How to manage my own queue ?  Which api should I use ?
