### ISSUE TITLE
Background app refresh

### ISSUE THREAD

**Issue by juddernaught** [MailCore/mailcore2#882]
I'm looking to perform a background fetch/app refresh and know that we need to use apple's special methods for fetching data when doing a background fetch. Does mailcore support this functionality and how can I go about implementing this in iOS 8?

**Comment by gsantome** [comment]
Hi @dinhviethoa do you have an idea on how we could implement real time push notifications? because Im using oauth2 so its not right to use the credentials in my server... 

Thanks

**Comment by dinhviethoa** [comment]
Why do you think it's not right to use the credentials in your server? Lots of apps do that.

**Comment by gsantome** [comment]
Really I don't know... its not correct for me... but i will take a look... 

Thanks
