### ISSUE TITLE
"CFNetwork SSLHandshake failed (-9824)" when connecting to iCloud

### ISSUE THREAD

**Issue by ghost** [MailCore/mailcore2#896]
My app uses Mailcore2 to connect to a range of mail server types. I have started getting an error "A stable connection to the server could not be established" when connecting to any iCloud accounts. This is even on the production version of the app in the iOS App Store. If I run the development version in Xcode, I get an additional error in the console: "CFNetwork SSLHandshake failed (-9824)". This happens on several different devices, and the simulator. I have tested with two different iCloud accounts over two different connections (WiFi and 3G).

**Comment by hanming223** [comment]
What do you mean by the fix will be on libetpan?
