### ISSUE TITLE
How to fetch Sent Mail , Draft and Starred Emails from Gmail server using Mailcore2 Api?

### ISSUE THREAD

**Issue by ritugarodia** [MailCore/mailcore2#912]
Hello Sir, I am using Mailcore2 Api in my project to fetch inbox emails from Gmail server. I am Successfull in it.But my question is How to fetch the Sent Mail,Drafts and Starred emails from gmail server.
Any help will be appreciated.

**Comment by VishnuPrem55** [comment]
```
let fetchOp = self.session.fetchSubscribedFoldersOperation()
                fetchOp?.start({ error, folders in

                    print("\(folders)")
                })
```

All Folder names...
`[<mailcore::IMAPFolder:0x280c69280 INBOX>, <mailcore::IMAPFolder:0x280c69ce0 [Gmail]>, <mailcore::IMAPFolder:0x280c69d80 [Gmail]/All Mail>, <mailcore::IMAPFolder:0x280c69c80 [Gmail]/Drafts>, <mailcore::IMAPFolder:0x280c6a1e0 [Gmail]/Important>, <mailcore::IMAPFolder:0x280c695e0 [Gmail]/Sent Mail>, <mailcore::IMAPFolder:0x280c6a620 [Gmail]/Spam>, <mailcore::IMAPFolder:0x280c6a7c0 [Gmail]/Starred>, <mailcore::IMAPFolder:0x280c6a9e0 [Gmail]/Trash>]`
