### ISSUE TITLE
MessageParser html rendering does not fetch image attachments

### ISSUE THREAD

**Issue by mrosales** [MailCore/mailcore2#93]
Sorry to keep peppering this thread with questions, but I have been looking through all of the sample code and have run into a problem with rendering an html version of a message. In your iOS sample program, you have the <code>FetchFullMessageEnabled</code> user default to determine whether or not the <code>MCOMessageView</code> will fetch all content in a message. The alternative is to initialize the message view with a <code>MCOMessageParser</code> object initialized from the NSData returned from <code>fetchMessageByUIDOperationWithFolder:uid:</code>. I have cached the NSData in a local store for the most recent messages and want to initialize the <code>MCOMessageView</code> with a <code>MCOMessageParser</code>, but the problem is, it won't fetch the inline image attachments for me. I am assuming that this is because of a difference in the html rendering methods (<code>htmlRenderingWithDelegate:</code> vs. <code>htmlRenderingWithFolder:delegate:</code>), but I would like to have a way to fetch the images when initializing the view with a <code>MCOMessageParser</code>.

Do you have any ideas for how to accomplish this?

**Comment by malavsoni** [comment]
Hello
Can anyone tell me how I need to use the script as I am new for JS things?

**Comment by dinhviethoa** [comment]
Please ask a specific question rather on stackoverflow. I'm locking this issue now.
