### ISSUE TITLE
XCode 6.1 Failed to build (ld: library not found for -luchardet-ios clang: error: linker command failed with exit code 1 (use -v to see invocation))

### ISSUE THREAD

**Issue by buddy398** [MailCore/mailcore2#941]
build : Xcode 6.1 

ld: library not found for -luchardet-ios
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can anyone help me?

**Comment by KennyVB** [comment]
Hey there, can't compile the example for iOS it says 
ld: library not found for -luchardet-ios
clang: error: linker command failed with exit code 1 (use -v to see invocation)

when trying to build it... using latest xcode and mac os x yosemite

**Comment by bbsan2k** [comment]
Experiencing the same issue. Installed through mailcore-ios 0.5.1 cocoapod

**Comment by dinhviethoa** [comment]
Could you remove the linker flags -luchardet-ios?
It's not required any more.

**Comment by bbsan2k** [comment]
Damn. Ok figured it out myself. Problem was my Old Build Config with a newer Cocoapod. After Resetting it, the issue was gone.
