### ISSUE TITLE
How get Display name?

### ISSUE THREAD

**Issue by xiaoer371** [MailCore/mailcore2#976]
hi  
In MCOIMAPSession.h 
/*\* Display name of the Gmail user. It will be nil if it's not a Gmail server. */
@property (nonatomic, copy, readonly) NSString \* gmailUserDisplayName;

How get Display name of the other server user ?  
can I get the  Display name ? 
 help me !

**Comment by slrudani** [comment]
Hi , 

Is there anyway I can get profile image set for the email account. Can I get such information from message header or from the message object. 

Thanks,
Sandip.

**Comment by KieranMcGrady** [comment]
@slrudani I'm not sure if this is built-in to Mailcore but you could [use the Google+ API](https://developers.google.com/+/api/latest/people#image) for that. You could also try to get images from the users local address book on their device.
